### ISSUE TITLE
Spreadsheet loader: note with no attribute

### ISSUE THREAD

**Issue by sarahjeansweeney** [NEU-Libraries/cerberus#1000]
A spreadsheet that I uploaded for Archives contains a `Note 1` column and `Note 1 Attribute` field, which is empty. By leaving the attribute empty, the cataloger intended for the note to be a plain note field with no attribute. When the record processed, a note field with an empty attribute was created:

`<mods:note type="">`

The loaded record displays in the DRS as:

> :
> "Holocaust Awareness Committee : A Time To Bear Witness"

See example: https://repository.library.northeastern.edu/files/neu:cj82m289h

Can the loader be updated to not create an empty attribute when no attribute is supplied in the spreadsheet?

**Comment by elizoller** [comment]
This should be a quick fix. Does mods display do the right thing if there is no type attribute at all?

**Comment by sarahjeansweeney** [comment]
It just displays it with a plain "Note" label: https://repository.library.northeastern.edu/files/neu:cj82n385s
