### ISSUE TITLE
Spreadsheet loader error: "400 Bad Request"

### ISSUE THREAD

**Issue by sarahjeansweeney** [NEU-Libraries/cerberus#1004]
Of the 2588 successful records processed for the Boston Deseg collection (https://repository.library.northeastern.edu/loaders/spreadsheet/report/906), 1 record couldn't be updated because of this error:

> 400 Bad Request

Target record:
https://repository.library.northeastern.edu/files/neu:cj82kf405

![2016-08-05_0830](https://cloud.githubusercontent.com/assets/4663073/17437664/f723b2ee-5aec-11e6-9d49-6a5192e6159f.png)

**Comment by elizoller** [comment]
The pid column in this case start with `/neu:...`. Going to put in validation to check that the pid column starts with `neu:` before proceeding.
