### ISSUE TITLE
XML loader: A/V file support

### ISSUE THREAD

**Issue by sarahjeansweeney** [NEU-Libraries/cerberus#1013]
I tried uploading a few different file types using the XML loader. Most worked fine, but I received errors when trying to upload A/V files (http://cerberus.library.northeastern.edu/loaders/xml/report/215):

> Error - Audio or Video File must have poster file

Can the loader/manifest be updated to support A/V files and their posters?

**Comment by dgcliff** [comment]
Sure - is there any reason to expect people will have fully formed XML for Video, instead of using the spreadsheet loader?

**Comment by sarahjeansweeney** [comment]
Absolutely. I think it's reasonable to expect that if we support the file type in the DRS, we'll need to support it in our batch uploaders.

**Comment by dgcliff** [comment]
I guess I was under the impression that only RADS/Yourself would be using the XML loader much. Don't get me wrong, I wish we never had to build the Spreadsheet Loader in the first place, but I just wanted to make sure we weren't being duplicitous for the sake of it.

**Comment by sarahjeansweeney** [comment]
RADS and I will definitely be the primary (maybe only) users of the XML loader, but we'll probably use the tool often to load on behalf of others. Most user-submitted metadata will be through a spreadsheet, but some will be in formats that we will transform into MODS and use the XML loader to ingest. Also, it seems natural to me that the loaders would support the exact same file formats.

**Comment by elizoller** [comment]
Column header is `File Name - Poster` like for Spreadsheet Loader

**Comment by sarahjeansweeney** [comment]
Almost there. The load I tried had two files, one without an embargo and one with (http://cerberus.library.northeastern.edu/loaders/xml/report/224). The file with the embargo uploaded with the poster, the one without the embargo didn't upload because it claimed not to have a poster. Clicking "View MODS" in the load report, the poster filename shows up in the embargo date field: 

![2016-08-15_1201](https://cloud.githubusercontent.com/assets/4663073/17670474/21eb4fe6-62e0-11e6-906d-a5ab262d72cc.png)

I'll share the spreadsheet over Slack.

**Comment by elizoller** [comment]
Indeed. Looking into it.
