### ISSUE TITLE
XML loader: missing MODS XML

### ISSUE THREAD

**Issue by sarahjeansweeney** [NEU-Libraries/cerberus#1015]
The MODS records for two of the files I was using to test this morning was removed: http://cerberus.library.northeastern.edu/collections/neu:dr26z189d

I can't say for sure what I did to trigger the erasure, but here's what I was doing:

1. Tried to replace records with XML missing handles
2. Tried to replace records with XML missing keywords
3. Tried to replace records with XML missing title
4. Tried to replace records with XML that was not valid MODS (a bad value for typeOfResource, an extra non-MODS element)
5. Tried uploading a zip with XML files not listed in the manifest
6. Tried uploading a zip with missing XML files that were listed in the manifest

Numbers 1 - 4 didn't make it past preview
Numbers 5 - 6 did make it past preview, but both had errors that I didn't expect:
http://cerberus.library.northeastern.edu/loaders/xml/report/250
http://cerberus.library.northeastern.edu/loaders/xml/report/251

**Comment by elizoller** [comment]
Closed with de74906
