### ISSUE TITLE
XML Loader: error text

### ISSUE THREAD

**Issue by sarahjeansweeney** [NEU-Libraries/cerberus#1016]
There are only two regular error messages that need to be updated:

**Zip missing XML/MODS XML cell blank/MODS XML column missing**
Currently: XML Files does not exist at the path specified.
Change to: Your upload could not be processed because the XML files could not be found.

**Blank first row/file name column missing/file name empty/empty spreadsheet**
Currently: Your upload could not be processed because the spreadsheet is missing file names or PIDs. Please update the spreadsheet and try again
Change to: Just add a period at the end.

There are also various XML related errors which probably need to be handled differently:

> `Exceptions::MissingMetadata: No valid keywords in xml;`

> `Exceptions::MissingMetadata: No valid title in xml;`

> `Nokogiri::XML::SyntaxError: Element '{http://www.loc.gov/mods/v3}typeOfResource': [facet 'enumeration'] The value 'books?' is not an element of the set {'text', 'cartographic', 'notated music', 'sound recording-musical', 'sound recording-nonmusical', 'sound recording', 'still image', 'moving image', 'three dimensional object', 'software, multimedia', 'mixed material', ''}.;Nokogiri::XML::SyntaxError: Element '{http://www.loc.gov/mods/v3}typeOfResource': 'books?' is not a valid value of the atomic type '{http://www.loc.gov/mods/v3}resourceTypeDefinition'.;`

> `Nokogiri::XML::SyntaxError: Element '{http://www.loc.gov/mods/v3}sports': This element is not expected. Expected is one of ( {http://www.loc.gov/mods/v3}topic, {http://www.loc.gov/mods/v3}geographic, {http://www.loc.gov/mods/v3}temporal, {http://www.loc.gov/mods/v3}titleInfo, {http://www.loc.gov/mods/v3}name, {http://www.loc.gov/mods/v3}geographicCode, {http://www.loc.gov/mods/v3}hierarchicalGeographic, {http://www.loc.gov/mods/v3}cartographics, {http://www.loc.gov/mods/v3}occupation, {http://www.loc.gov/mods/v3}genre ).;`

> `Nokogiri::XML::SyntaxError: Element '{http://www.loc.gov/mods/v3}sports': This element is not expected.;`

Since these are all related to invalid MODS or poorly formatted XML, can we just use one statement instead? Something like, "Your upload could not be processed because one or more XML files could not be validated."

**Comment by dgcliff** [comment]
Would it worth it to be more specific? The latter XML related errors are all due to the attempt at preview, so we could point out that at least these things pertain to row 1

i.e.

"There was an error in displaying the Preview screen. The first file in the spreadsheet failed with this error (dump out error to screen)"

**Comment by elizoller** [comment]
If the first record passes, the XML errors can also be encountered throughout processing and are saved and displayed in the load reports.

**Comment by sarahjeansweeney** [comment]
More specific is always better, but knowing all the things that can go wrong with XML I don't really want to write a lot of messages (too lazy!).

**Comment by dgcliff** [comment]
Just more specific about the timing of the error, we can do the raw dump of the specific XML problem.

The timing helps them find and fix the issue

**Comment by sarahjeansweeney** [comment]
That makes sense, so when the first record fails before the preview screen, we can use the message you wrote above, @dgcliff.

**Comment by elizoller** [comment]
And if the error occurs in a file not the preview file?

**Comment by dgcliff** [comment]
Then it goes into the load report as it currently does

**Comment by elizoller** [comment]
Ok. So just adding "There was an error in displaying the Preview screen. The first file in the spreadsheet failed with this error "... prior to current error messages from XML validation

**Comment by sarahjeansweeney** [comment]
Yup!

**Comment by elizoller** [comment]
Proposed solution for XML Validation errors in XML Loader:
When a preview file encounters an XML validation error, the flash message will display a generic message informing the user that the load has failed. It will provide a link to the item report for the preview file (an item report with preview flag). The item report will give the user details about how the MODS failed validation (just like when an item report within a load that passed preview works).
If the load passes the preview stage, no item report will be created for the preview file.
(Feel free to fill in/correct me)

**Comment by sarahjeansweeney** [comment]
All of the XML messages and the load reports work really well. I tried a few other things and I got three other messages that I didn't expect when using the metadata + file XML loader option, which I didn't get before:

Zip is missing the XML:
> Is a directory - /home/drs/cerberus/releases/20160819175250/tmp/1471631745-7041497-df/

(Was _XML Files does not exist at the path specified._)


Manifest file had a blank first row:
> Is a directory - /home/drs/cerberus/releases/20160819175250/tmp/1471631745-7041497-df/

(Was _Your upload could not be processed because the spreadsheet is missing file names or PIDs. Please update the spreadsheet and try again_)

XML file has no prolog:

> Exceptions::XmlEncodingError: This object requires a prolog with UTF-8 encoding.;

(Same as before - I don't think I included it in the original ticket)

**Comment by elizoller** [comment]
This should be all set with c41a6a54f066ad7bcafd5d700389a3e42bdf1a2d
