### ISSUE TITLE
XML Loader: date validation (new file and replace metadata)

### ISSUE THREAD

**Issue by sarahjeansweeney** [NEU-Libraries/cerberus#1017]
In addition to the other bits we validate at upload (title, keyword, etc), can the date format also be validated? I uploaded and replaced metadata for a handful of files focusing on the date and I was able to insert these dates:

01-01-1934: http://cerberus.library.northeastern.edu/files/neu:dr26z300d

08101934: http://cerberus.library.northeastern.edu/files/neu:dr26z310n

potato: http://cerberus.library.northeastern.edu/files/neu:dr26z2847

**Comment by dgcliff** [comment]
:sweet_potato:

**Comment by elizoller** [comment]
Is this for embargo date?

**Comment by dgcliff** [comment]
Potato is at least date created

**Comment by sarahjeansweeney** [comment]
Just date created. All the embargo tests had the right message ("Error - Embargo date must follow format YYYY-MM-DD").

**Comment by dgcliff** [comment]
@elizoller I think we can probably steal the date validation from whatever the edit form allows

**Comment by dgcliff** [comment]
YYYY OR YYYY-MM OR YYYY-MM-DD (for posterity)

**Comment by elizoller** [comment]
Would this apply to XML editor, XML Loader, and Spreadsheet Loader?

**Comment by dgcliff** [comment]
Yarp. So gratefully I think theres a convenient code sharing place for it

**Comment by elizoller** [comment]
<img width="1253" alt="screen shot 2016-08-31 at 2 26 38 pm" src="https://cloud.githubusercontent.com/assets/5439169/18141305/035a10e0-6f87-11e6-95e6-6e19f67c9810.png">
preferences for language?

**Comment by dgcliff** [comment]
Looks good to me. Don't forget we throw out lots of Nokogiri errors that are less than clear, so that's one of the more lucid ones 👍

**Comment by sarahjeansweeney** [comment]
yeah, that message looks good to me!
