### ISSUE TITLE
XML Loader: Export email

### ISSUE THREAD

**Issue by sarahjeansweeney** [NEU-Libraries/cerberus#1018]
I'd like to add just a tiny bit more info to the body of the export email:

> **MODS XML Export Alert**
> 
> The MODS export you requested is now available for download:
> 
> [url]
> 
> The export file will be deleted after [insert whatever the window is here - 12 maybe?] hours.

If customization is possible:

> **MODS XML Export Alert**
> 
> The MODS export you requested for [collection name] is now available for download:
> 
> [url]
> 
> The export file will be deleted [date] at [time calculated based on when zip finished generating].

**Comment by dgcliff** [comment]
h'ok, can do

**Comment by elizoller** [comment]
![screen shot 2016-08-30 at 3 59 54 pm](https://cloud.githubusercontent.com/assets/5439169/18104817/d8410146-6eca-11e6-994e-7adc37bd01a9.png)

**Comment by sarahjeansweeney** [comment]
Looks good!
