### ISSUE TITLE
New IPTC Loader: AAI Archives

### ISSUE THREAD

**Issue by sarahjeansweeney** [NEU-Libraries/cerberus#1019]
The African American Institute Archives needs a IPTC loader. Here are the basic details you'll need to create their loader:

*Collection PID: https://repository.library.northeastern.edu/collections/neu:cj82n322h

*Access rights:
```
<rightsMetadata xmlns="http://hydra-collab.stanford.edu/schemas/rightsMetadata/v1" version="0.1">
<copyright>
<human type="title"/>
<human type="description"/>
<machine type="uri"/>
</copyright>
<access type="discover">
<human/>
<machine/>
</access>
<access type="read">
<human/>
<machine>
<group>public</group>
</machine>
</access>
<access type="edit">
<human/>
<machine>
<person>001900082</person>
<group>northeastern:drs:repository:staff</group>
<group>northeastern:drs:jdoaai:archive_staff</group>
</machine>
</access>
<embargo>
<human/>
<machine/>
</embargo>
</rightsMetadata>
```
*Loader group:
`northeastern:drs:repository:loaders:aai_archives`

*Derivative sizes:
No derivatives.

*Standard statement for mods/accessCondition:
```
<mods:accessCondition type="use and reproduction">Copyright Not Evaluated: This Rights Statement should be used for Items for which the copyright status is unknown and for which the data provider has not undertaken an effort to determine the copyright status of the work. (http://rightsstatements.org/page/CNE/1.0/?language=en)</mods:accessCondition>
```

**Comment by elizoller** [comment]
i dont think we’ve ever explicitly given edit access to an individual in the iptc loaders -  is that the right permissions? also since you didn’t mention it, can i assume these permissions are propagated to all of the content objects?

**Comment by dgcliff** [comment]
@sarahjeansweeney do we want 001900082 instead of 000000000 as the depositor for aai?

**Comment by sarahjeansweeney** [comment]
Sorry, that must have been bad copy and paste. I took that from an active record and updated it, but I neglected to remove the NUID! Ooops. It should be the 9 zeros number.

**Comment by elizoller** [comment]
👍
