### ISSUE TITLE
Spreadsheet loader error: "undefined method `sheets' for nil:NilClass"

### ISSUE THREAD

**Issue by sarahjeansweeney** [NEU-Libraries/cerberus#1024]
I'm setting up a new spreadsheet for ECDA to load their materials into the DRS, but my sample spreadsheet triggered this error:

> undefined method `sheets' for nil:NilClass

It's possible there's something wrong with the spreadsheet, but it's hard to tell from the error. I'll share the files over Slack.

**Comment by dgcliff** [comment]
For posterity - filename issue, specifically spaces I believe. Will patch with same tmp space workaround we did for individual files.
