### ISSUE TITLE
D'Amore Mckim IPTC Loader making files private

### ISSUE THREAD

**Issue by sarahjeansweeney** [NEU-Libraries/cerberus#1026]
The D'Amore Mckim IPTC loader is uploading all files as private when it should be setting permissions according to the collection permissions.

Their collections are a mix of public and private collections and files, but this collection is public and the files loaded to it should be public: https://repository.library.northeastern.edu/collections/neu:cj82nd73v

**Comment by elizoller** [comment]
@dgcliff ran loop to remove "person" public and add "group" public
