### ISSUE TITLE
Download buttons displaying for files made private using a Set Sentinel 

### ISSUE THREAD

**Issue by sarahjeansweeney** [NEU-Libraries/cerberus#1029]
I just made a Sentinel to test a bunch of files in this Set: http://cerberus.library.northeastern.edu/sets/neu:dr26z561j

![screencapture-cerberus-library-northeastern-edu-sentinels-new-1472821044091](https://cloud.githubusercontent.com/assets/4663073/18204741/4c21e882-70ec-11e6-816b-008cce0860d3.png)

If I did it correctly (always I chance I didn't), the core file should be public and all the content objects should be private. When I look at the Set incognito, I can see the download buttons for all the files, though clicking on them gives me this error:

![2016-09-02_0909](https://cloud.githubusercontent.com/assets/4663073/18204855/f73e901c-70ec-11e6-961d-c48eaa8e4eca.png)

The rights records look correct, like this one for zip files:

```
<rightsMetadata xmlns="http://hydra-collab.stanford.edu/schemas/rightsMetadata/v1" version="0.1">
<copyright>
<human type="title"/>
<human type="description"/>
<machine type="uri"/>
</copyright>
<access type="discover">
<human/>
<machine/>
</access>
<access type="read">
<human/>
<machine>
<group>northeastern:drs:staff</group>
</machine>
</access>
<access type="edit">
<human/>
<machine>
<person>001126975</person>
<group>northeastern:drs:repository:staff</group>
<person>000000000</person>
</machine>
</access>
<embargo>
<human/>
<machine/>
</embargo>
</rightsMetadata>
```

Possibly related: The multipage file (last in the list) displays with a broken thumbnail:

![2016-09-02_0910](https://cloud.githubusercontent.com/assets/4663073/18204885/2d57b6ba-70ed-11e6-8f61-ac9e509566a6.png)

Signing in reveals the thumbnail.

**Comment by dgcliff** [comment]
So at first glance, looking at the small image of bonfires, I see the button, but I can't get to it unless I'm logged in - http://cerberus.library.northeastern.edu/downloads/neu:dr26z557z?datastream_id=content

So that appears to be a ux issue. Looking into it.

**Comment by dgcliff** [comment]
Appears to have been a staging caching issue
