### ISSUE TITLE
Loading spreadsheet files

### ISSUE THREAD

**Issue by sarahjeansweeney** [NEU-Libraries/cerberus#1030]
Neither the XML loader nor the spreadsheet loader will process excel files because the the loader only expects one spreadsheet, the manifest. To allow more than one spreadsheet, we should require the manifest be strictly named: manifest.xlsx (or manifest.xls, or manifest.[whatever we require for extensions, I guess]).

**Comment by elizoller** [comment]
We only allow .xlsx
