### ISSUE TITLE
Sentinel: PDF generated from Word file missing permissions

### ISSUE THREAD

**Issue by sarahjeansweeney** [NEU-Libraries/cerberus#1032]
I uploaded a Word file using the spreadsheet loader after setting a new sentinel for a collection: http://cerberus.library.northeastern.edu/files/neu:dr26z584v
The Word file uploaded with the expected permissions (`northeastern:drs:repository:loaders:cps`), but the PDF generated from the word file didn't get the sentinel permissions or the collection permissions, it was just set to public:

```
<rightsMetadata xmlns="http://hydra-collab.stanford.edu/schemas/rightsMetadata/v1" version="0.1">
<copyright>
<human type="title"/>
<human type="description"/>
<machine type="uri"/>
</copyright>
<access type="discover">
<human/>
<machine/>
</access>
<access type="read">
<human/>
<machine>
<group>public</group>
</machine>
</access>
<access type="edit">
<human/>
<machine>
<person>000000000</person>
</machine>
</access>
<embargo>
<human/>
<machine/>
</embargo>
</rightsMetadata>
```

I loaded the file again without the sentinel set for the collection, and the collection permissions were assigned to both the Word file and generated PDF: http://cerberus.library.northeastern.edu/collections/neu:dr26z5900

**Comment by dgcliff** [comment]
Ah - must be because it's a derivative of a content object - nice catch. Will make a patch.
