### ISSUE TITLE
Permissions for multipage loads

### ISSUE THREAD

**Issue by sarahjeansweeney** [NEU-Libraries/cerberus#1033]
I tried a multipage load after setting a sentinel on a collection, but the permissions weren't applied: http://cerberus.library.northeastern.edu/collections/neu:dr26z5790

![multipage 0902](https://cloud.githubusercontent.com/assets/4663073/18207127/cda54ad8-70f7-11e6-9c89-60850a5c5e19.png)

```
<rightsMetadata xmlns="http://hydra-collab.stanford.edu/schemas/rightsMetadata/v1" version="0.1">
<copyright>
<human type="title"/>
<human type="description"/>
<machine type="uri"/>
</copyright>
<access type="discover">
<human/>
<machine/>
</access>
<access type="read">
<human/>
<machine>
<group>public</group>
</machine>
</access>
<access type="edit">
<human/>
<machine>
<person>001126975</person>
<group>northeastern:drs:repository:staff</group>
</machine>
</access>
<embargo>
<human/>
<machine/>
</embargo>
</rightsMetadata>
```

I tried another multipage load into a collection without a sentinel, and the collection permissions weren't applied, either: http://cerberus.library.northeastern.edu/collections/neu:dr26z5900

![2016-09-02_1025](https://cloud.githubusercontent.com/assets/4663073/18207153/e58b2b72-70f7-11e6-8841-c345245a5ac4.png)

```
<rightsMetadata xmlns="http://hydra-collab.stanford.edu/schemas/rightsMetadata/v1" version="0.1">
<copyright>
<human type="title"/>
<human type="description"/>
<machine type="uri"/>
</copyright>
<access type="discover">
<human/>
<machine/>
</access>
<access type="read">
<human/>
<machine>
<group>public</group>
</machine>
</access>
<access type="edit">
<human/>
<machine>
<person>001126975</person>
<group>northeastern:drs:repository:staff</group>
</machine>
</access>
<embargo>
<human/>
<machine/>
</embargo>
</rightsMetadata>
```

**Comment by dgcliff** [comment]
I think this is as simple as I totally forgot about the Multipage loader. Will amend it.

**Comment by dgcliff** [comment]
Multipage just shouldn't be in the list. Their content model type is zip. This is in conjunction with the loader not applying the permissions I believe.

**Comment by dgcliff** [comment]
Multipage is currently structured like IPTC, with hardcoded permissions being passed to it. I've removed the Multipage content model from the form, and sentinels will apply to Multipage in when the IPTC refactor branch is finished.

In the meantime, the Zip model will suffice for Set application.
