### ISSUE TITLE
Sentinel: dropdown menus

### ISSUE THREAD

**Issue by sarahjeansweeney** [NEU-Libraries/cerberus#1034]
Two small things with the sentinel content object dropdown menus

**1** I'm able to add the same group twice. No idea if this matters, just thought I'd point it out in case it does.

![2016-09-01_0826](https://cloud.githubusercontent.com/assets/4663073/18207530/81920774-70f9-11e6-8895-7053aaa6f81b.png)

**2** When there are multiple group selections for a content object, the first dropdown box is styled differently than the other dropdowns.

 - Style for first available "Select Group" dropdown:

![2016-09-02_1037](https://cloud.githubusercontent.com/assets/4663073/18207513/75e9a35a-70f9-11e6-81e0-e5d64fd7de05.png)

 - Style for second available "Select Group" dropdown:

![2016-09-02_1037-1](https://cloud.githubusercontent.com/assets/4663073/18207514/79ee38b2-70f9-11e6-8305-3b6047d94546.png)

**Comment by dgcliff** [comment]
Just out of curiosity, as a user, what would you expect to have happen if you chose the same group twice?

**Comment by sarahjeansweeney** [comment]
Nothing - I think it would probably be a mistake.

**Comment by dgcliff** [comment]
As in, don't apply the permissions for either choice of the same grouper group?

**Comment by sarahjeansweeney** [comment]
For the example above, the CPS loader group should still be given the assigned permissions, but only once, not twice.

**Comment by dgcliff** [comment]
Ok - given that it's read for both, that makes sense. I think this is the case of what happens, but I'll double check.
