### ISSUE TITLE
Error editing thumbnail

### ISSUE THREAD

**Issue by sarahjeansweeney** [NEU-Libraries/cerberus#1039]
I encountered an error updating a thumbnail this morning for this file: https://repository.library.northeastern.edu/files/neu:cj82ng31r

I did the normal thing, clicked manage tab, added the new thumbnail, clicked Submit. That's when I encountered a system error, though the "...was updated successfully." message was displayed as well:

![2016-09-08_0843](https://cloud.githubusercontent.com/assets/4663073/18350053/096790fe-75a2-11e6-93e4-3759f3721ded.png)

The thumbnail was replaced, but now I can't edit the file even though I'm logged in:

<img width="1225" alt="2016-09-08_0856" src="https://cloud.githubusercontent.com/assets/4663073/18350092/3ecb0b36-75a2-11e6-8882-2c3d1e8c2a09.png">

I tried a hard refresh, incognito, and a different browser.

**Comment by dgcliff** [comment]
My mistake, simply a mis-typed line. Will post a patch

**Comment by dgcliff** [comment]
Fixed with f8b74a674d72069ef1a9bd29971dc8cdbca1ef4c

**Comment by sarahjeansweeney** [comment]
I'm not sure if it's related to this ticket or something else, but two files I uploaded yesterday using the spreadsheet loader also can't be edited: 

https://repository.library.northeastern.edu/files/neu:m040g955w
https://repository.library.northeastern.edu/files/neu:m040g957f

**Comment by dgcliff** [comment]
ok will look into it

**Comment by dgcliff** [comment]
Is there any kind of error or screen when you try? I can save the file in console fine

**Comment by sarahjeansweeney** [comment]
There's no tab to try, but when I add /edit to the end of the URL I get this message: 
"Sorry, you don't have permission to access this page."

**Comment by sarahjeansweeney** [comment]
Looking at the rights record, somehow DRS staff got added to 'read' not 'edit'

```
rightsMetadata xmlns="http://hydra-collab.stanford.edu/schemas/rightsMetadata/v1" version="0.1">
<copyright>
<human type="title"/>
<human type="description"/>
<machine type="uri"/>
</copyright>
<access type="discover">
<human/>
<machine/>
</access>
<access type="read">
<human/>
<machine>
<group>public</group>
<group>northeastern:drs:repository:staff</group>
<group>
northeastern:drs:college_of_social_sciences_humanities:early_caribbean_digital_archive
</group>
</machine>
</access>
<access type="edit">
<human/>
<machine>
<person>000351560</person>
<person>000000000</person>
</machine>
</access>
<embargo>
<human/>
<machine/>
</embargo>
</rightsMetadata>
```
