### ISSUE TITLE
Multipage Failed Load

### ISSUE THREAD

**Issue by sarahjeansweeney** [NEU-Libraries/cerberus#1040]
I tried uploading a few files this morning using the multipage loader. I made it past the preview page to the load report page, which took longer to process than I expected. I looked in resque and sure enough the load had failed. Resque displays a helpful error message:

> Your upload could not be processed because the submitted .zip file does not contain a spreadsheet named manifest.xlsx.

![2016-09-09_1136-1](https://cloud.githubusercontent.com/assets/4663073/18393207/8b1ef53e-7682-11e6-8a45-64cb569e6d77.png)

But the load report page continues to churn as if the files are being processed, with no message or indication that the load has failed:

![2016-09-09_1136](https://cloud.githubusercontent.com/assets/4663073/18393258/b0f5ab72-7682-11e6-8cf0-ee5edc5028da.png)

**Comment by dgcliff** [comment]
Will be fixed with #1009
