### ISSUE TITLE
Using quotations around search terms in featured content

### ISSUE THREAD

**Issue by sarahjeansweeney** [NEU-Libraries/cerberus#1041]
I noticed today that when I try to do an exact search by putting quotation marks around my search terms in one of the featured content areas (ETDs, Research, etc), the quotation marks are ignored. Both searches for "design studies" and design studies in ETDs brings up 1884 results, and it should be much less. In the case of "design studies", the quotation marks appear escaped when the results are returned:

![2016-09-16_1322](https://cloud.githubusercontent.com/assets/4663073/18595163/8a99d7a2-7c11-11e6-83ed-c0406f5f25c8.png)

I don't see this happening with general search or scoped searches in communities or collections. Is this by design with the featured content stuff? It would be preferable if all search boxes behaved similarly.

**Comment by dgcliff** [comment]
Pat requested strict AND searches. All searches are exact searches, quotes aren't required.

**Comment by dgcliff** [comment]
Unless I'm misunderstanding the premise?

**Comment by dgcliff** [comment]
Mm...Ok, I think I understand now. But implementing quotes in that way would mean that a search for 

`"A plague 'o both your houses" : Shakespeare and early modern plague writing.`

would not return that particular item. A decision was made to allow for any copy pasted search of any items title should return that item.

**Comment by sarahjeansweeney** [comment]
Quotes may not be required, but using quotes does return more exact results even with the AND (try design studies and "design studies" in the Marcom collection - "design studies" returns nothing, design studies 93).

I guess this ticket is more about why searches with quotes in ETDs and Research Pubs are treated differently than every other search box on the site.

**Comment by dgcliff** [comment]
It appears logic that is in the Catalog Controller is not in the Communities and Collections controllers. I'll make a patch.

**Comment by dgcliff** [comment]
Fixed with 6af8b044dbec5d4a9997de7e94bb463c51f8aae7
