### ISSUE TITLE
Marcom loader: dialog box preventing upload

### ISSUE THREAD

**Issue by sarahjeansweeney** [NEU-Libraries/cerberus#1042]
Matt just reported to me that he can't upload using the Marcom IPTC loader because he's encountering this error message when he clicks the "Terms of Service" button:

> Parent id has not been set. This may be caused by copying and pasting urls, pressing the back button, disabled javascript or other processes. Please refresh this page to continue.

![2016-09-16_1506](https://cloud.githubusercontent.com/assets/4663073/18598077/239aaf96-7c1f-11e6-9471-3a9775030db8.png)

I was able to replicate this in the Marcom loader, as well as the spreadsheet and XML loaders.

**Comment by dgcliff** [comment]
Fixed with 6af8b044dbec5d4a9997de7e94bb463c51f8aae7

**Comment by sarahjeansweeney** [comment]
NBD, but I'm still seeing this on staging.

**Comment by dgcliff** [comment]
Thats just because my feature branch hasn't been updated with master code
