### ISSUE TITLE
Download Queue File List

### ISSUE THREAD

**Issue by sarahjeansweeney** [NEU-Libraries/cerberus#1043]
It looks like the Download Queue page only shows 10 items, rather than every file in the queue:

![2016-09-19_1319](https://cloud.githubusercontent.com/assets/4663073/18641754/fe7bb1f2-7e6b-11e6-9b7c-8db36e9fe4c2.png)

The Download Queue button count at the top of the page is correct, though the number on the page itself is only "10".

When I download the zip it contains all 20 files, though when I add it to a Set using "Save for later", it only asks me if I want to add 10 files:

![2016-09-19_1325](https://cloud.githubusercontent.com/assets/4663073/18641931/b60e30ec-7e6c-11e6-95a8-806e95130e7a.png)

When I confirm "Yes", only 5 files are added to the Set:

![2016-09-19_1326](https://cloud.githubusercontent.com/assets/4663073/18641939/bd1188e4-7e6c-11e6-8149-9e1f5814c76f.png)

**Comment by dgcliff** [comment]
This is a solr query row limit, the defaults 10. Easy fix
