### ISSUE TITLE
DRS down: "This website is under heavy load (queue full)"

### ISSUE THREAD

**Issue by sarahjeansweeney** [NEU-Libraries/cerberus#1046]
Users are encountering this error when visiting the DRS:

<img width="829" alt="2016-09-22_1152" src="https://cloud.githubusercontent.com/assets/4663073/18755971/137fa6b0-80bc-11e6-86b6-70780fcbcb11.png">

Can't say how long this has been the case. It was working 9am/10am-ish, at the least.

**Comment by dgcliff** [comment]
Seems to have been a memory leak, that was triggered when the toolkit accessed an empty compilation. Hopefully fixed with aab1ce46f7896195fdd898f5a89f5a20b0980b23
