### ISSUE TITLE
System error at preview page for spreadsheet metadata-only load

### ISSUE THREAD

**Issue by sarahjeansweeney** [NEU-Libraries/cerberus#1050]
Not sure what happened, but I ran into a system error when I tried to upload a spreadsheet using the metadata-only option. I got this error in between the file submission page and the preview pane:

![2016-09-26_1614](https://cloud.githubusercontent.com/assets/4663073/18850197/7614c85a-8404-11e6-8bbf-9def806c4ab3.png)

I successfully uploaded another version of the same spreadsheet this afternoon: https://repository.library.northeastern.edu/loaders/spreadsheet/report/1119

That load was for all 500+ files. The upload that failed was for just one file that had failed the initial load because it had the wrong PID. I replaced the incorrect PID with the correct one, removed all the unnecessary rows and uploaded the revised spreadsheet, then error.

**Comment by dgcliff** [comment]
User/depositor was deleted in the neu/northeastern fracas - remedied
