### ISSUE TITLE
Single file upload error on staging

### ISSUE THREAD

**Issue by sarahjeansweeney** [NEU-Libraries/cerberus#1051]
I encountered this error when I tried to upload an image file using the regular interface upload tool to add a file to my research publications smart collection:

![2016-09-28_1656](https://cloud.githubusercontent.com/assets/4663073/18932030/bda44a1c-859c-11e6-976d-43da97cbc724.png)

**Comment by sarahjeansweeney** [comment]
If it helps, this is the URL: http://cerberus.library.northeastern.edu/files/undefined

**Comment by dgcliff** [comment]
Related to my branch, working on it now

**Comment by dgcliff** [comment]
This appears to have just been a missing tmp directory on staging, happens from time to time for a hard to determine reason
