### ISSUE TITLE
End date in MODS display

### ISSUE THREAD

**Issue by sarahjeansweeney** [NEU-Libraries/cerberus#1052]
Dan pointed out that this record is handling the MODS end date differently than other records:
https://repository.library.northeastern.edu/files/neu:m040jq20m

Instead of taking the YYYY-MM-DD end date value and turning it into Month Day, Year, it's keeping the YYYY-MM-DD value:

![2016-09-29_1014](https://cloud.githubusercontent.com/assets/4663073/18957574/9898847c-862d-11e6-8c6a-37dd8056c656.png)

The start date is being transformed as expected, though. Neither of us see anything out of the ordinary with the original spreadsheet date or the XML. 

Here's an example of a correctly formatted start and end date https://repository.library.northeastern.edu/files/neu:m040jq293

![2016-09-29_1016](https://cloud.githubusercontent.com/assets/4663073/18957610/bd667958-862d-11e6-9b1b-11d5026c339d.png)

**Comment by dgcliff** [comment]
I might be wrong, but aren't there only 30 days in June?

**Comment by sarahjeansweeney** [comment]
You're definitely right. Changing it to 30 fixed it...
