### ISSUE TITLE
Sentinel Refactor: private collections and depositor IDs

### ISSUE THREAD

**Issue by sarahjeansweeney** [NEU-Libraries/cerberus#1054]
Staging loaders are working mostly as expected. I noticed two things while testing:

1) When uploading files to a private collection, the core files will remain private even if the sentinel is set to make the core file public. This makes sense since we don't allow public files in private collections. Just to make it a bit clearer to the user (me!), can the public/private Sentinel options for core files in a private collection behave like permissions for files or collections contained within a private collection? In other words, if a collection is private, the collection's Sentinel should not allow me to try to make new files "public".

2) The depositor ID isn't being added to the rights records for some derivative files. I tested a few different files using the Marcom loader: http://cerberus.library.northeastern.edu/collections/neu:6241

I tested Sentinel derivative options using these two files:
http://cerberus.library.northeastern.edu/files/neu:dr26zb235
http://cerberus.library.northeastern.edu/files/neu:dr26zb24f

These are the Sentinel settings:

- The core files are public with edit privileges for Marketing.
- The master files are private with read privileges for Marketing.
- The large derivative files are public with read privileges for College of Engineering.

The loader applied these permissions, but the large derivative files are missing the depositor ID:

```
<rightsMetadata xmlns="http://hydra-collab.stanford.edu/schemas/rightsMetadata/v1" version="0.1">
<copyright>
<human type="title"/>
<human type="description"/>
<machine type="uri"/>
</copyright>
<access type="discover">
<human/>
<machine/>
</access>
<access type="read">
<human/>
<machine>
<group>northeastern:drs:repository:loaders:coe</group>
<group>public</group>
</machine>
</access>
<access type="edit">
<human/>
<machine>
<group>northeastern:drs:repository:staff</group>
</machine>
</access>
<embargo>
<human/>
<machine/>
</embargo>
</rightsMetadata>
```

I uploaded these two files in an earlier load to test uploading with just collection permission: 

- http://cerberus.library.northeastern.edu/files/neu:dr26z900n
- http://cerberus.library.northeastern.edu/files/neu:dr26z8993

For these files, the large derivative files do have the depositor ID under "edit".

**Comment by dgcliff** [comment]
Both issues should be fixed on staging
