### ISSUE TITLE
Missing northeastern:drs:repository:staff group

### ISSUE THREAD

**Issue by sarahjeansweeney** [NEU-Libraries/cerberus#1057]
Marcom asked me to delete a few files this afternoon, which lead me to discover that I couldn't edit  any of Marcom's files.

It looks like my user is missing both the northeastern:drs:repository:staff and the northeastern:drs:marketing_and_communications:staff groups. I'm still a member of these groups in Grouper.

(I needed to delete the files quickly, so I impersonated @elizoller to add a group I belong to to the permissions list. Thanks, Eli!)

**Comment by dgcliff** [comment]
Well, not sure what the issue would be, but I don't understand this bit - "to add a group I belong to to the permissions list" which permissions list for what?

**Comment by sarahjeansweeney** [comment]
I needed to tombstone the files, but my user doesn't belong to any of the groups that have access to manage them (drs staff or marcom), so I impersonated someone with those permissions (Eli) and edited the permissions list to include a group I still belonged to (dsg staff). 

Regardless of the example, I think it's clear that my user should belong to the drs:staff group.

**Comment by dgcliff** [comment]
Ahhh ok, I gotcha. Yes, you should. I deployed last night. If you still don't have them this morning, we can delete your user, have you sign out then back in. If you *still* don't then, then I think there will be a grouper problem, and I'll get you to private slack message me the contents of /secure
