### ISSUE TITLE
Spreadsheet loader "File specified does not exist" error

### ISSUE THREAD

**Issue by sarahjeansweeney** [NEU-Libraries/cerberus#1058]
I've used the spreadsheet loader for new files twice today, each for zipped files that are slightly less than 10gb. About half of the files in each load failed with an "Error - File specified does not exist" error:
https://repository.library.northeastern.edu/loaders/spreadsheet/report/1248
https://repository.library.northeastern.edu/loaders/spreadsheet/report/1249

The manifests and the file lists do match, so the files do indeed exist. Since I couldn't see anything immediately wrong, I just edited the manifest to remove the successful files and zipped it with the files that weren't processed the first time, then reloaded the files. That load is processing normally right now: https://repository.library.northeastern.edu/loaders/spreadsheet/report/1250

I'm not sure this is an issue, really, since we only speculated the reasonable limit for loads was ~10gb. Since each of those loads started to get errors around 5gb, maybe the reasonable limit is about 5gb?

**Comment by dgcliff** [comment]
5gb is safer simply because theres less time for something to go wrong. Can't find any fault with the files/zip - my best guess is an ITS hiccup.
