### ISSUE TITLE
System Error on Administer Sets page

### ISSUE THREAD

**Issue by sarahjeansweeney** [NEU-Libraries/cerberus#1066]
I just encountered a system error on the Administer Sets page when trying to advance through the pages:

![2016-11-28_1134](https://cloud.githubusercontent.com/assets/4663073/20676734/ca70ad7a-b55e-11e6-8802-9bd5b8073889.png)

To replicate:
Navigate to the Administer Sets page: https://repository.library.northeastern.edu/admin/sets
Click "Next" in the pagination or any of the page numbers

**Comment by dgcliff** [comment]
```A NoMethodError occurred in compilations#index:

  undefined method `name' for nil:NilClass
  app/views/admin/compilations/index.html.haml:26:in `block in _app_views_admin_compilations_index_html_haml___1697797166030196971_66146460'```

**Comment by elizoller** [comment]
Ok, I'll look into it
