### ISSUE TITLE
Smart and User Created Collections missing from My DRS user pages

### ISSUE THREAD

**Issue by sarahjeansweeney** [NEU-Libraries/cerberus#1067]
I noticed today that my smart and user created collections are missing from my My DRS page:
![2016-11-28_1403](https://cloud.githubusercontent.com/assets/4663073/20681850/688d3672-b573-11e6-9512-4cacbb2b5937.png)

I should be able to see all of my smart collections, even the empty ones. I should also see at least two personal collections.

This seems to be true for all users' collections. Hillary should have at least two smart collections (presentations and research publications):

![2016-11-28_1400-1](https://cloud.githubusercontent.com/assets/4663073/20681938/c83bd952-b573-11e6-89c0-aeaccffcc6dc.png)

The files stored in smart collections are still showing up in the aggregated featured content area, so I imagine I can't see these because of permissions changes?

**Comment by dgcliff** [comment]
Looking into it

**Comment by dgcliff** [comment]
This seems odd at first blush - Hilary's Research Publications collection is public - https://repository.library.northeastern.edu/collections/neu:29680

This must be related to the my_drs changes, and code logic, not permissions. Looking to pin down the cause.
