### ISSUE TITLE
Disappearing posters

### ISSUE THREAD

**Issue by sarahjeansweeney** [NEU-Libraries/cerberus#1072]
The poster image for audio files displays on the core file page until the user clicks to stream the file. Once the file starts streaming, the poster image disappears:

![2017-01-10_1018](https://cloud.githubusercontent.com/assets/4663073/21811606/475a0030-d71e-11e6-963d-6d0595c34d4d.png)

This seems to be true in Chrome and Firefox. Safari displays the poster image as expected:

![2017-01-10_1019](https://cloud.githubusercontent.com/assets/4663073/21811621/5ad3a044-d71e-11e6-949d-5b8e2372c120.png)

I tried with a few files, but this is the file I used for the examples: https://repository.library.northeastern.edu/files/neu:m0410x99d

**Comment by elizoller** [comment]
For JWPlayer6 I implemented a bit of javascript which on playing an audio file when the poster can be displayed, it would minimize the height of the player and show the thumbnail above it not actually in the player. 
This should be achievable in JWPlayer7 as well but may require a little rewiring. I'll look into it.

**Comment by elizoller** [comment]
The newer version of jwplayer (7.8.7) handles posters fine on audio only files for chrome and firefox but now has an issue in safari. So I've removed the patch that applied to jwplayer 6 and added a new one for safari on 7.
