### ISSUE TITLE
Play button for streaming a/v not working in Chrome

### ISSUE THREAD

**Issue by sarahjeansweeney** [NEU-Libraries/cerberus#1073]
Clicking the big play button in the middle of the a/v player in Chrome doesn't start the file stream: 
(Let me know if you need a video screencapture of this, rather than just static images)

![2017-01-10_1053](https://cloud.githubusercontent.com/assets/4663073/21813096/1b22d74e-d723-11e6-9261-041f9170604d.png)

The button changes color when you hover over or click, but nothing else. Clicking anywhere else on the poster will stop and start the stream.

This only appears to be true n Chrome. Clicking the button in Firefox and Safari triggers the stream.

**Comment by dgcliff** [comment]
Eli's on it 👍  If you click around the button, it'll play

**Comment by elizoller** [comment]
Should have fixes for this and #1072 up later today - hopefully just some tweaks to handle newer version of JWPlayer

**Comment by elizoller** [comment]
I think this was a bug in a specific version of JWPlayer - updated by several minor points (still in 7) and this resolved itself

**Comment by elizoller** [comment]
was 7.3.4 now 7.8.7
