### ISSUE TITLE
Truncated Sets List

### ISSUE THREAD

**Issue by sarahjeansweeney** [NEU-Libraries/cerberus#1075]
The "Add to a Set." modal only displays 10 Sets:

![2017-01-18_1612](https://cloud.githubusercontent.com/assets/4663073/22083227/1613c7f0-dd99-11e6-9445-19cf2a158a49.png)

This modal used to display all Sets, but if that's no longer possible the modal should be paginated so users can access all their Sets.

**Comment by elizoller** [comment]
I'll look into it in the morning.
