### ISSUE TITLE
Spreadsheet loader for A/V files: varied success

### ISSUE THREAD

**Issue by sarahjeansweeney** [NEU-Libraries/cerberus#1076]
This morning I reloaded the A/V files that failed last week using the spreadsheet loader, with varied success: https://repository.library.northeastern.edu/loaders/spreadsheet/report/1495
![2017-01-23_0927](https://cloud.githubusercontent.com/assets/4663073/22207719/3146cd48-e14e-11e6-9926-c15fea514cf9.png)

The load report lists two successful files and one failed file:

- The first file listed in the report did indeed load successfully: https://repository.library.northeastern.edu/files/neu:m0411m380
- The second file listed in the report is stuck in processing, but I'm not sure why (nothing in Resque that I can see): https://repository.library.northeastern.edu/files/neu:m0411m42k
- The third file failed with this error: "Error - File specified does not exist". Both the file and the poster do exist in the packaged zip file.

**Comment by sarahjeansweeney** [comment]
I should also probably mention that the zip file is 9.95GB.

**Comment by dgcliff** [comment]
Tested with same structure, smaller files, worked fine. Large zip issue still exists, I'm afraid. Happy to implement TAR unpacking to deal with the batching burden.
