### ISSUE TITLE
Support for loading new files with handles?

### ISSUE THREAD

**Issue by sarahjeansweeney** [NEU-Libraries/cerberus#1079]
I have two questions about ingesting files with handles:

1. I have a batch of IRis files that need to be uploaded to the DRS. Since these are IRis files, they already have handles generated and maintained by the library. I'd like to use the new file XML loader to ingest the 455 files, but doing so would create another new handle (I assume?). Rather than create extra handles, I'd like to load these without creating a new handle. 

2. All of the handles in question direct to https://repository.library.northeastern.edu/iris . If it's possible to ingest these files and keep the original handle, how can I update the handles so they redirect to the new DRS URLs?

**Comment by dgcliff** [comment]
Manually loaded through the console
