### ISSUE TITLE
Sets modal pagination

### ISSUE THREAD

**Issue by sarahjeansweeney** [NEU-Libraries/cerberus#1080]
Michelle reported to me late last week that she couldn't advance past the first page in the "Add to a Set." modal when trying to add something to a Set.
To replicate, click "Save for later" to add a file to a Set. In the "Add to a Set." modal, advance to the next page or pick a deeper page to navigate to.

Instead of advancing through the pages, a blank pages opens in the active browser window:
![2017-02-13_0838](https://cloud.githubusercontent.com/assets/4663073/22886150/9eeb4dba-f1ca-11e6-885e-2386ed599b2b.png)

She was using Firefox and Chrome, and experienced the same issue in both. I can replicate her issue in Firefox and Safari, but not Chrome.

**Comment by elizoller** [comment]
in firefox and safari can you try a hard refresh? i can't replicate this is any browser

**Comment by sarahjeansweeney** [comment]
Hard refresh worked for me in Firefox, but not Safari.

**Comment by sarahjeansweeney** [comment]
Clearing cache in Safari worked, too.
