### ISSUE TITLE
Handle URL Replacement

### ISSUE THREAD

**Issue by sarahjeansweeney** [NEU-Libraries/cerberus#1081]
I need two handle URLs changed:

This handle: http://hdl.handle.net/2047/D20237099
Needs to be changed to: https://repository.library.northeastern.edu/files/neu:336460

This handle: http://hdl.handle.net/2047/D20237100
Needs to be changed to: https://repository.library.northeastern.edu/files/neu:1197

**Comment by dgcliff** [comment]
Fixed

**Comment by sarahjeansweeney** [comment]
Thanks!
