### ISSUE TITLE
Downloaded .zip file missing extension

### ISSUE THREAD

**Issue by sarahjeansweeney** [NEU-Libraries/cerberus#1082]
A user just reported this to me: 

> There appears to be an issue with a file I uploaded last year. I'm sure I checked it when I uploaded it originally, but now it downloads and unzips as a unix executable, instead of a set of files (powerpoint and word documents as well as windows/mac executables).

This is the file she's referring to: https://repository.library.northeastern.edu/files/neu:rx9184970

It looks like the original filename was either "1449417095-6425257.zip" or "grace-summer15-pilot-materials.zip", so I think it was uploaded as a .zip and not an extension-less file. Is it possible the file extension was stripped from the original file when it was uploaded way back in December 2015?

**Comment by dgcliff** [comment]
Looks like at some point in the past we zipped zips and removed their extension. Re-uploaded the content object, and should be working now.

**Comment by sarahjeansweeney** [comment]
Found another one: https://repository.library.northeastern.edu/files/neu:rx918190f
I uploaded this, so I know it was a zip when it was uploaded.

Is there any way to find all of the affected files?

**Comment by dgcliff** [comment]
I'll see if there might be a solr query

**Comment by dgcliff** [comment]
Querying for core files with canonical class of zip file, but not including multipage or supplemental, gives 14 files (that are listed in this set)

https://repository.library.northeastern.edu/sets/neu:cj82pp846

**Comment by dgcliff** [comment]
Thats not to say they're all broken, but they potentially could be. As far as I know, theres no outward solr document or core file value that indicates this particular error state.

**Comment by sarahjeansweeney** [comment]
14 is easy enough to look through. Thanks!
