### ISSUE TITLE
File upload size limit error

### ISSUE THREAD

**Issue by sarahjeansweeney** [NEU-Libraries/cerberus#1083]
Kristin reported to me that she encountered this error after she tried to upload a file that's slightly over 1GB:

> The file you chose is larger than 1000MB. Please contact DRS staff for help uploading files larger than 1000MB.

![flachsbart_errormessage](https://cloud.githubusercontent.com/assets/4663073/23625051/cc82ea4c-0275-11e7-8bd8-82f20947cbb7.JPG)

Kristin part of the DRS staff group, which can upload files up to 10GB, so she should be able to upload this file. The upload page text is correct ("Please contact the DRS staff for help uploading files larger than **10,000MB.**"), but uploading the file triggers the error.

**Comment by dgcliff** [comment]
This seems odd.

https://github.com/NEU-Libraries/cerberus/blob/master/app/views/core_files/_single_upload.haml#L92

She should've fallen into the second bucket of this if elsif statement.

Going to have to do some testing.

**Comment by dgcliff** [comment]
I can't replicate this. Either by making my groups like hers, or impersonating her user (which will be exactly what she experiences)

<img width="852" alt="screenshot 2017-03-08 10 12 55" src="https://cloud.githubusercontent.com/assets/459084/23717248/e7bdf7ca-03e7-11e7-856b-7780be88c56a.png">

I hesitate to suggest it, but perhaps a hard refresh, or checking whether she's using the correct of her two accounts might solve the issue.

**Comment by sarahjeansweeney** [comment]
To make things easier, her Husky and staff accounts have the same permissions, so it shouldn't matter which account she uses. I'll ask her to do a hard refresh and try again.

**Comment by sarahjeansweeney** [comment]
From Kristin: 

> I got the same message that I can’t upload over 1000MB.  I did hard refreshes.  I was using Chrome...I just tried it on Firefox- same message.

I've asked Dan, who has the same permissions, to try to replicate it.

**Comment by dgcliff** [comment]
Short of her logging into your laptop (or mine) I'm not sure this is reproducible. There doesn't seem to be anything in the logs, code, or her accounts to suggest what the issue may be.

**Comment by dgcliff** [comment]
This may not be relevant, but I also see in your screenshot that no file has actually been chosen?

**Comment by sarahjeansweeney** [comment]
Interesting. I can replicate by impersonating her (both Husky and staff). Each time I selected the file, submitted, then was kicked back to the "Upload new files" page, where the file was no longer selected:

![2017-03-08_1546](https://cloud.githubusercontent.com/assets/4663073/23723325/c0bfce08-0416-11e7-8093-a56ccf39681a.png)

**Comment by dgcliff** [comment]
that result indicates theres a controller issue. But the code is the same there, as well.

https://github.com/NEU-Libraries/cerberus/blob/master/app/controllers/core_files_controller.rb#L336

**Comment by dgcliff** [comment]
Eli and I think we might have a fix
