### ISSUE TITLE
Admin panel delete

### ISSUE THREAD

**Issue by sarahjeansweeney** [NEU-Libraries/cerberus#1084]
On several of the Admin panel pages the "Delete" confirmation message asks if I want to delete the first object in the list, rather than the object I selected to delete.

I first noticed this on the Sets Admin page. I tried to delete the "Irvine Wei publications" set, but the confirmation message asked if I want to delete the "Holocaust Awareness Archives" set:

![2017-03-06_1517](https://cloud.githubusercontent.com/assets/4663073/23627994/d6fac0f2-0280-11e7-8f8b-3f8bb4055b85.png)

I encountered this on the Collections, Communities, Employees, and Sets admin pages. The Manage Files" behaves as expected.

**Comment by elizoller** [comment]
OK, I'll look into it.
