### ISSUE TITLE
Error message when exporting Set metadata

### ISSUE THREAD

**Issue by sarahjeansweeney** [NEU-Libraries/cerberus#1086]
I just triggered a MODS export for two Sets:

https://repository.library.northeastern.edu/sets/neu:rx917d214
https://repository.library.northeastern.edu/sets/neu:cj82pp77s

I clicked the Export button and encountered a regular DRS error:

![2017-03-13_1012](https://cloud.githubusercontent.com/assets/4663073/23858149/e85bb6a8-07d5-11e7-8549-525e3bb4871e.png)

The error page URL is for a collection, not the Set where I triggered the export.

**Comment by dgcliff** [comment]
Seems to be pathing related, looking into it

**Comment by sarahjeansweeney** [comment]
FYI: the export was successful

**Comment by dgcliff** [comment]
Excellent - a successful failure 👍 

![image](https://media.giphy.com/media/67kThO9PPAF1K/giphy.gif)
