### ISSUE TITLE
Newly associated files not displaying on core file

### ISSUE THREAD

**Issue by sarahjeansweeney** [NEU-Libraries/cerberus#1087]
I just associated this file: https://repository.library.northeastern.edu/files/neu:rx918356j
with this one: https://repository.library.northeastern.edu/files/neu:rx918695v

The association displays in the "Associate" tab in the manage area:
<img width="1182" alt="2017-03-15_1106" src="https://cloud.githubusercontent.com/assets/4663073/23960561/b7228cce-097e-11e7-9fce-63ec703a9e14.png">

But it does not display on its core file page, or the associated file's core file page
<img width="1164" alt="2017-03-15_1106-1" src="https://cloud.githubusercontent.com/assets/4663073/23960568/bba7c340-097e-11e7-8ad1-b160396601ed.png">

This is an older associated file, which displays as expected: https://repository.library.northeastern.edu/files/neu:rx9181610

**Comment by elizoller** [comment]
The interface isn't set up correctly for displaying the transcript of relationship. I'll fix it

**Comment by elizoller** [comment]
The interface specifically shows supplemental and instructional relationships and does not show codebook, dataset, figure, and transcript. We started with just supplemental since the other relationships weren't being used much then added instructional later on.

**Comment by sarahjeansweeney** [comment]
Can transcript be added?

**Comment by elizoller** [comment]
Yeah, no problem
