### ISSUE TITLE
Error when trying to associate two files

### ISSUE THREAD

**Issue by sarahjeansweeney** [NEU-Libraries/cerberus#1088]
I just encountered an error while trying to associate a [video](https://repository.library.northeastern.edu/files/neu:m0413h012) to its [transcript](https://repository.library.northeastern.edu/files/neu:rx918356j) file:

> There was an error processing your request. The error received was "undefined method `each' for nil:NilClass". Please try again or contact DRS Staff for help.

![2017-03-21_1623](https://cloud.githubusercontent.com/assets/4663073/24169102/ec03f832-0e52-11e7-99eb-67d09ad50d37.png)

I entered the transcript's URL in the "Associate files" box on the Associate tab and selected "Is Transcription Of" from the dropdown box. Clicking "Associate" triggered the error.

I tried again using the supplemental association and did not encounter an error. The file was associated, and both the supplemental and transcription associations display:

![2017-03-21_1628](https://cloud.githubusercontent.com/assets/4663073/24169289/84eb8f6a-0e53-11e7-8e59-a8b0676ead8b.png)

So it seems it was successful, just not sure why I got the error.

**Comment by elizoller** [comment]
It might require a hard refresh. If that doesn't resolve it, I'll take a deeper look first thing tomorrow

**Comment by sarahjeansweeney** [comment]
I still encountered the error after a hard refresh.

**Comment by elizoller** [comment]
Ah. Making some headway to debugging this issue.
This transcript was related to a file which got tombstoned but the tombstoned file pid is still in the rels-ext and the solr doc, which is what is causing this error. 
If we remove the associated relationships when a file is tombstoned then if the file is revived, they will not have the relationships anymore.
The other option would be to leave the pid in place but do some kind of filtering out tombstoned (or deleted items). 
We maintain the parent relationship for a tombstoned file so it can be placed back in its correct place if it is revived.

**Comment by dgcliff** [comment]
I think removing the association on tombstoning makes sense

**Comment by elizoller** [comment]
That is what I was thinking also. I'll work on a patch.
