### ISSUE TITLE
MODS stripped from records after XML metadata replacement errors

### ISSUE THREAD

**Issue by sarahjeansweeney** [NEU-Libraries/cerberus#1089]
Michelle just reported to me that the following records are missing their metadata:
http://hdl.handle.net/2047/D20197773
http://hdl.handle.net/2047/D20197788
http://hdl.handle.net/2047/D20197792
http://hdl.handle.net/2047/D20197777
http://hdl.handle.net/2047/D20197770
http://hdl.handle.net/2047/D20197781
http://hdl.handle.net/2047/D20197783
http://hdl.handle.net/2047/D20197772
http://hdl.handle.net/2047/D20197795
http://hdl.handle.net/2047/D20197780
http://hdl.handle.net/2047/D20197767
http://hdl.handle.net/2047/D20197769
http://hdl.handle.net/2047/D20197774
http://hdl.handle.net/2047/D20197778
http://hdl.handle.net/2047/D20197787
http://hdl.handle.net/2047/D20197768
http://hdl.handle.net/2047/D20197790
http://hdl.handle.net/2047/D20197776
http://hdl.handle.net/2047/D20197782
http://hdl.handle.net/2047/D20197224
http://hdl.handle.net/2047/D20196307

![2017-03-22_1538](https://cloud.githubusercontent.com/assets/4663073/24217271/b35e89fc-0f15-11e7-959f-af50bdf6c726.png)

It looks like each record was part of a XML replacement load on March 8: https://repository.library.northeastern.edu/loaders/xml/report/1606

Each of the records above triggered an error. 20 of the 21 records had this error:

> Error - Nokogiri::XML::SyntaxError: Element '{http://www.loc.gov/mods/v3}keyword': This element is not expected. Expected is one of ( {http://www.loc.gov/mods/v3}topic, {http://www.loc.gov/mods/v3}geographic, {http://www.loc.gov/mods/v3}temporal, {http://www.loc.gov/mods/v3}titleInfo, {http://www.loc.gov/mods/v3}name, {http://www.loc.gov/mods/v3}geographicCode, {http://www.loc.gov/mods/v3}hierarchicalGeographic, {http://www.loc.gov/mods/v3}cartographics, {http://www.loc.gov/mods/v3}occupation, {http://www.loc.gov/mods/v3}genre ).;

The other had this error:

> Error - Must have a handle

I can revert the metadata back, but the XML loader shouldn't be stripping metadata from records that can't be loaded.

**Comment by elizoller** [comment]
I'll look into this. If it encounters an error, it is supposed to revert back to the MODS content from before the load.
