### ISSUE TITLE
Public Sets are displaying in most/all users' Collaborative Sets list 

### ISSUE THREAD

**Issue by sarahjeansweeney** [NEU-Libraries/cerberus#1090]
Abbie reported to me yesterday that she has access to many Sets in her Collaborative Sets list that she didn't think she should, which appears to be true. For example, in her list of 91 collaborative sets she has access to the "Abod" and "Associated Files" Sets:

![2017-03-24_0846](https://cloud.githubusercontent.com/assets/4663073/24295079/8cbe7112-106f-11e7-8e41-c9ee333ba8aa.png)

"Abod" was created by Michelle, is public, and has edit permissions for Archives staff (a group Abbie does not belong to):
![2017-03-24_0847](https://cloud.githubusercontent.com/assets/4663073/24295247/31e251ea-1070-11e7-8678-123779143726.png)

"Associated Files" was created by me, is public, and has no other permissions.

![2017-03-24_0846-1](https://cloud.githubusercontent.com/assets/4663073/24295141/cdce3944-106f-11e7-8ec8-546134723786.png)

I checked a few other random users, and they can see these sets, too. There are plenty of private sets that do not show up in these random users' collaborative sets, so it seems only public Sets are affected. The read permissions should determine that a user can access a set in the collaborative sets list, not the public/private permission.

**Comment by dgcliff** [comment]
Read permissions are public/private permission. Do you mean edit?

**Comment by sarahjeansweeney** [comment]
I mean the read/edit Grouper permissions, not the public/private Mass Permissions.

**Comment by dgcliff** [comment]
An item set to public with no more specificity in grouper permissions is by default readable by anyone.

**Comment by sarahjeansweeney** [comment]
Yes, readable, but readable should not equal collaborative. Collaborative should be specifically set by Grouper group membership.

**Comment by dgcliff** [comment]
Blacklight doesn't disambiguate read ability from public no specificity, to explicitly with groups. I can put in that extra filtering, but it'll slow down that page.

**Comment by sarahjeansweeney** [comment]
As users add more and more public sets, the page will slow anyway, so that seems like a reasonable solution. I think it's more important for users to only be able to access sets in the collaborative area that have been purposefully shared with them.

**Comment by dgcliff** [comment]
The way blacklight is constructed, pagination ensures that count is irrelevant for page speed. Processing is different. I'll put in the patch.
