### ISSUE TITLE
System error when accessing files

### ISSUE THREAD

**Issue by sarahjeansweeney** [NEU-Libraries/cerberus#1091]
I just encountered system errors when trying to access DRS files. The first came from a search result page:

https://repository.library.northeastern.edu/catalog?utf8=%E2%9C%93&q=lower+roxbury

I tried to access the first and second result, both triggered a system error.

I also tried to access one of the newly uploaded Marcom files on the home page, same system error:

![2017-04-03_1628](https://cloud.githubusercontent.com/assets/4663073/24630420/a7bc4034-188a-11e7-869d-1a0d7e30b59b.png)

**Comment by dgcliff** [comment]
Yeah, I'm getting a lot of errors. Not sure if it's network related or not. Restarting some things to try and fix it.

**Comment by sarahjeansweeney** [comment]
👍
