### ISSUE TITLE
Large file (1GB+) uploads stall on the submit page

### ISSUE THREAD

**Issue by sarahjeansweeney** [NEU-Libraries/cerberus#1092]
Kristen just reported this to me after trying to load a single file, and I just experienced this myself with the spreadsheet loader.

Kristin tried a few times to upload a 1.26GB file using the single file uploader (both on wireless and wired), and each time the file stalled on the submit page (the progress bar stops advancing and spinning, so it appears not to be making progress):

![2017-04-05_0830](https://cloud.githubusercontent.com/assets/4663073/24705882/b4f7f78c-19db-11e7-93eb-a98719a779da.png)

I also tried to submit a few large files using the spreadsheet loader and experienced the same thing. First I tried to submit a 6GB spreadsheet load, and when that stalled I repackaged it in to two ~3GB packages, and those stalled on the submit page, too:

![2017-04-05_0831](https://cloud.githubusercontent.com/assets/4663073/24705939/e7728024-19db-11e7-81f0-630d5b6459aa.png)

Kristin says she waited hours before closing the tab, so it's not a matter of patience. Let me know if you want me to share the files.

**Comment by dgcliff** [comment]
Appears to be fixed.
