### ISSUE TITLE
New IPTC loader: Library Communications

### ISSUE THREAD

**Issue by sarahjeansweeney** [NEU-Libraries/cerberus#1095]
The Library Communications group would like a photo loader for their media collection. They're still working on organizing their files, so no rush.

Here are the basic details you'll need to create their loader:

Collection PID: https://repository.library.northeastern.edu/collections/neu:cj82px01w

Derivative sizes: No derivatives.

Standard statement for mods/accessCondition:

<mods:accessCondition type="use and reproduction">In Copyright - Non-Commercial Use Permitted: This Item is protected by copyright and/or related rights. You are free to use this Item in any way that is permitted by the copyright and related rights legislation that applies to your use. In addition, no permission is required from the rights-holder(s) for non-commercial uses. For other uses you need to obtain permission from the rights-holder(s). http://rightsstatements.org/page/InC-NC/1.0/?language=en</mods:accessCondition>

Access rights: 
I think this is handled by the sentinel now? If not:

Read: public
Edit: northeastern:drs:library:communications

**Comment by dgcliff** [comment]
Should be done with 3943a5d3886f4b227291ec69a1f02ee06623c452

Will review with @sarahjeansweeney when she returns from Aus

**Comment by sarahjeansweeney** [comment]
Discussed with Communications group - looks good to us!

**Comment by dgcliff** [comment]
Ok, will deploy either tonight or tomorrow night

**Comment by sarahjeansweeney** [comment]
Is there a base collection set for this loader? None display in the "Choose Collection" dropdown menu:

![2017-07-24_0931](https://user-images.githubusercontent.com/4663073/28525663-fb48cc7a-7052-11e7-9b5f-251baa2b7242.png)
