### ISSUE TITLE
DRS Files Unavailable

### ISSUE THREAD

**Issue by sarahjeansweeney** [NEU-Libraries/cerberus#1096]
DRS files are unavailable:
![2017-06-05_0951](https://cloud.githubusercontent.com/assets/4663073/26786431/9ec18180-49d4-11e7-83b8-6fe63f3f1c01.png)

Thumbnails are displaying as broken images and clicking on files brings up a system error:
![2017-06-05_0952](https://cloud.githubusercontent.com/assets/4663073/26786464/c32ae8fe-49d4-11e7-8924-02d0a1a3232e.png)

**Comment by dgcliff** [comment]
Can this be closed now?

**Comment by elizoller** [comment]
Fedora would not start. Ernesto was able to restore service by deleting a stale activemq lock file.
