### ISSUE TITLE
Collection URL validation in move requests

### ISSUE THREAD

**Issue by sarahjeansweeney** [NEU-Libraries/cerberus#1098]
A user just submitted a move request with the following details:

> Collection Move Alert
> 
> A user has requested that a Collection be moved:
> 
> Title: Lent Shaw
> PID: neu:cj82nf928
> _New Collection URL: Georgia_
> User: [name removed]
> User Email: [email removed]
> A link to the Collection can be found here
> 
> Lent Shaw should be moved to Georgia [link: applewebdata://FD8CA855-39D4-4DC2-B2A3-D0122A5EF199/Georgia]
> 
> The reason for moving is: Categorized by state

She submitted the request by entering the collection name in the URL field ("Georgia") rather than the collection URL (https://repository.library.northeastern.edu/collections/neu:cj82q142x).

Can the move request form include validation for the new collection field ("Please enter the URL for the destination community or collection") to make sure the user submits a valid URL rather than free text?

**Comment by dgcliff** [comment]
Sure, should be doable
