### ISSUE TITLE
Restricted files in the Associated Files tab

### ISSUE THREAD

**Issue by sarahjeansweeney** [NEU-Libraries/cerberus#1099]
It looks like the Associated Files tab displays all associated files, regardless of whether the user is able to view the associated files. 

For example, this core file is public and has one associated file: https://repository.library.northeastern.edu/files/neu:cj82n4604

The associated file (https://repository.library.northeastern.edu/files/neu:cj82n4647) is a master file that Archives has chosen to restrict to only two groups. 

I viewed the file before I signed in and noticed that the restricted file shows up in the Associated Files tab:

![2017-05-30_1007](https://user-images.githubusercontent.com/4663073/28422584-751af11a-6d36-11e7-8101-55cca967cfe8.png)

Clicking on it opens up the Shib login page. This is fine for now, but we should continue the practice of not showing users things they can't access. If possible, the user should be presented with the Associated Files tab only if s/he can access the associated file(s).

**Comment by dgcliff** [comment]
Have a patch for this, just running it through some tests.
