### ISSUE TITLE
Public files in private collections

### ISSUE THREAD

**Issue by sarahjeansweeney** [NEU-Libraries/cerberus#1101]
Generally, we do no allow public files in a private collection, but when a public collection is switched to private by the user the public files contained within remain public and the edit form displays to the user that the file is private (even though the file is still public in the Fedora rights record). 

Instead, when a user changes a collection to private all the collections and files contained within, including nested collections and files, should be switched from public to private. 

The user will be presented with a modal message asking them to confirm this action:

> Making this collection "Private" will change everything in it to "Private". Do you want to proceed?

**Comment by dgcliff** [comment]
I think we could add the count of files that'll be modified, to help impart the severity of the change (especially for nested collections)

**Comment by sarahjeansweeney** [comment]
That would be good! So:

> Making this collection "Private" will change [x] collections and [x] files to "Private". Do you want to proceed?

**Comment by dgcliff** [comment]
Fixed with d3349ea89d53de2f727e01794aaacd1a06c62cfe
