### ISSUE TITLE
DRS System Error downloading embargoed files

### ISSUE THREAD

**Issue by sarahjeansweeney** [NEU-Libraries/cerberus#1141]
Kristin reported to me that she cannot download embargoed files. As a member of the DRS Repository Staff group, she is able to view and download anything, including embargoed files. I'm an admin user and I was able to replicate her experience for downloading embargoed files from the full item page (downloads from the browse lists were successful). 

To replicate:
- Click on any embargoed file to go to the full metadata page (ie, https://repository.library.northeastern.edu/files/neu:cj82ng39z)
- Click the PDF download button, which will trigger a "Sorry, you don't have permission to access this page" system error

![2017-08-29_0920](https://user-images.githubusercontent.com/4663073/29823243-1f84ea50-8c9c-11e7-9e44-274b3c725106.png)

Interestingly, the download option works for embargoed files when clicking the download button in a search or browse list:
https://repository.library.northeastern.edu/collections/neu:rx915f449

![2017-08-29_0928](https://user-images.githubusercontent.com/4663073/29823379-793aceb6-8c9c-11e7-960d-b3e3ef174e51.png)

**Comment by dgcliff** [comment]
Fix deployed, should be all sorted.

**Comment by sarahjeansweeney** [comment]
👍
