### ISSUE TITLE
File download support for iTunes

### ISSUE THREAD

**Issue by sarahjeansweeney** [NEU-Libraries/cerberus#1142]
The first episode of the dean's new [podcast](http://whatsnewpodcast.org/) is ready to be distributed via iTunes, but unfortunately the WordPress RSS feed failed iTunes validation. 

![itunes connect screenshot 2](https://user-images.githubusercontent.com/4663073/30445579-6f5e22a2-9954-11e7-8fb8-f06534294b0d.png)

It turns out that in addition to requiring direct download URLs for episodes (#1100), iTunes requires episodes to be stored on a server that supports byte-range requests:

> Confirm that the server where you post your RSS feed uses a publicly addressable URL (for example, the URL must not be behind a firewall) and supports byte-range requests. Support for byte-range requests allows users to stream your episodes.

Will discuss when @dgcliff when he returns.

**Comment by dgcliff** [comment]
Fixed on DRS end. Still issues with Wordpress feed.

**Comment by sarahjeansweeney** [comment]
Fixed the WordPress issues, but I'm still getting the byte-range request error:

![2017-11-02_1054](https://user-images.githubusercontent.com/4663073/32332620-561da2c0-bfbc-11e7-8ee4-04e8163f024e.png)
