### ISSUE TITLE
MODS corporate names being unexpectedly altered when using the edit form

### ISSUE THREAD

**Issue by sarahjeansweeney** [NEU-Libraries/cerberus#1145]
When a record contains a full corporate MODS creator, i.e.:
```
    <mods:name type="corporate" authorityURI="http://id.loc.gov/authorities/names" valueURI="http://id.loc.gov/authorities/names/n84066203">
        <mods:namePart>Northeastern University (Boston, Mass.) Libraries</mods:namePart>
        <mods:role>
            <mods:roleTerm authority="marcrelator" authorityURI="http://id.loc.gov/vocabulary/relators" valueURI="http://id.loc.gov/vocabulary/relators/cre" type="text">Creator</mods:roleTerm>
        </mods:role>
    </mods:name>
```
each save from the edit form adds "Creator" to the end of the namePart value:

![2017-10-05_1030](https://user-images.githubusercontent.com/4663073/31232579-4b19b982-a9b8-11e7-8861-6dae71c50dac.png)

```
    <mods:name type="corporate" authorityURI="http://id.loc.gov/authorities/names" valueURI="http://id.loc.gov/authorities/names/n84066203">
        <mods:namePart>Northeastern University (Boston, Mass.) Libraries Creator Creator Creator Creator Creator Creator</mods:namePart>
        <mods:role>
            <mods:roleTerm authority="marcrelator" authorityURI="http://id.loc.gov/vocabulary/relators" valueURI="http://id.loc.gov/vocabulary/relators/cre" type="text">Creator</mods:roleTerm>
        </mods:role>
    </mods:name>
```

Dan J. first noticed it on this record: https://repository.library.northeastern.edu/files/neu:cj82qf55g
And I was able to replicate it on this record: https://repository.library.northeastern.edu/files/neu:m041gv143 (private, you'll need to be signed in to see it)

I suspect this is because the corporate role value is being pulled into the name value in the edit form:

![2017-10-05_1041](https://user-images.githubusercontent.com/4663073/31233102-ce1b40c0-a9b9-11e7-8ae4-351df0aede94.png)

**Comment by dgcliff** [comment]
How odd. Looking into it.

**Comment by dgcliff** [comment]
Appears to be a specificity issue

```2.0.0 :003 > x.mods.corporate_name
 => ["\n        \n        Northeastern University (Boston, Mass.) Libraries Creator\n        \n            Creator\n        \n    "]
2.0.0 :004 > x.mods.corporate_name.name_part
 => ["Northeastern University (Boston, Mass.) Libraries Creator"]
2.0.0 :005 >```

I think it hadn't popped up before, as we hadn't been testing with quite such detailed data.

Making a patch.

**Comment by dgcliff** [comment]
Yeah, thats Will code from 4 years ago, before we knew better about OM's underlying behaviors. It reaches below the request and hoovers everything up.
