### ISSUE TITLE
Spreadsheet loader not processing/semi-processing name subject headings

### ISSUE THREAD

**Issue by sarahjeansweeney** [NEU-Libraries/cerberus#1146]
Dan just reported to me that the name subjects in this spreadsheet load were processed differently than he expected: https://repository.library.northeastern.edu/loaders/spreadsheet/report/2261

There are two issues with name subjects in this load:

1. Most of the records in the spreadsheet had an entry for 
`Snowden | Muriel S. (Muriel Sutherland) | | 1916- |http://id.loc.gov/authorities/names/no90025075` (one example: https://repository.library.northeastern.edu/files/neu:m041z9766). This name subject displays as the last "Subjects and keywords" value, but each of its MODS element values is displayed, even the authority and authority URI:

![2017-10-06_1133](https://user-images.githubusercontent.com/4663073/31285813-5b2238b8-aa8a-11e7-943e-f70e6ce951d8.png)

2. The other name subjects in the spreadsheet were not processed. Another record (https://repository.library.northeastern.edu/files/neu:m041z9791) had a few other name subject heading values (Pan African Movement, Pan African Congress) that weren't included in the generated MODS record.

The spreadsheet columns appear to be formatted correctly and the topical subjects don't seem to have the same issue.

I'll share the spreadsheet used in the load over Slack.

**Comment by dgcliff** [comment]
Hm, ok, looking into it

**Comment by dgcliff** [comment]
Eli wrote a lot of this parsing code. Could you attach an example of what you'd expect the loader to produce given the spreadsheet data?

**Comment by dgcliff** [comment]
I can say looking at the loader code, that name subjects and topical subjects are treated distinctly, and differently. Giving the same data to both will not produce the same output.

**Comment by sarahjeansweeney** [comment]
Sure, here's an example for the first part of the issue (the second part should be processed the same way. I'm not sure why only the Snowden values got processed).

The submitted values:
_Name Subject Heading 1_: Snowden | Muriel S. (Muriel Sutherland) | | 1916- | http://id.loc.gov/authorities/names/no90025075 
_Name Subject Heading Authority 1_: lcnaf | http://id.loc.gov/authorities/names/

should have been processed into the following MODS:

```
<mods:subject>
   <mods:name type="personal" authority="lcnaf" authorityURI="http://id.loc.gov/authorities/names/" valueURI="http://id.loc.gov/authorities/names/no90025075">
     <mods:namePart type="given">Muriel S. (Muriel Sutherland)</mods:namePart>
     <mods:namePart type="family">Snowden</mods:namePart>
     <mods:namePart type="date">1916-</mods:namePart>
     <mods:namePart/>
   </mods:name>
</mods:subject>
```
rather than

```
  <mods:subject>
    <mods:name type="personal">
      <mods:namePart>Snowden | Muriel S. (Muriel Sutherland) | | 1916- | http://id.loc.gov/authorities/names/no90025075</mods:namePart>
    </mods:name>
  </mods:subject>
```

**Comment by dgcliff** [comment]
Ah, ok, thanks.

Looks like the pipes are being ignored for some reason. Has this style of input previously worked for personal subject names? (trying to narrow down if it's code or spreadsheet where the bug might be)

**Comment by dgcliff** [comment]
Looks like this was due to extra whitespace in column header. Closing, but will re-open if further issues arise.
