### ISSUE TITLE
Export PIDs/original file names to spreadsheet to support metadata overwrite workflow

### ISSUE THREAD

**Issue by sarahjeansweeney** [NEU-Libraries/cerberus#1147]
A simple process for exporting, editing, and overwriting MODS XML exists and works very well, but project teams that do not work with XML also need the ability to overwrite DRS metadata. Project teams that create spreadsheets to upload their files to their DRS tend to continue to use the upload spreadsheet to make edits to the metadata over time. This spreadsheet cannot be used to overwrite the DRS metadata because the project team would need to add a new column for the DRS file PIDs, which are required for spreadsheet overwrite. It isn't too difficult to add this column by hand for spreadsheets with 20 or fewer rows, but some spreadsheets can have hundreds of rows.

Rather, it would be useful if the DRS could generate a list of PIDs and original filenames for a collection or Set of DRS files. The project teams' spreadsheets have the original upload file name, which can be used to match the PIDs to rows and merge the spreadsheets, or simply copy and paste if the rows are sorted similarly.

Similar to MODS XML export, this feature would be limited DRS staff, as it will require staff assistance to combine the spreadsheets and make sure the metadata is being overwritten correctly.

**Comment by dgcliff** [comment]
Moving this to v1 - should be an easy feature, and helps prolong the usefulness of v1 by making it's core competency (data ingest) last longer, while we build v2.
