### ISSUE TITLE
Collections/load reports that need new derivatives created

### ISSUE THREAD

**Issue by sarahjeansweeney** [NEU-Libraries/cerberus#1148]
The following collections need derivatives created:

- [x] https://repository.library.northeastern.edu/collections/neu:cj82qf96q
- [x] https://repository.library.northeastern.edu/collections/neu:cj82qf988
- [x] https://repository.library.northeastern.edu/collections/neu:cj82qf546
- [x] https://repository.library.northeastern.edu/collections/neu:cj82qf59k
- [x] https://repository.library.northeastern.edu/collections/neu:cj82qf61m
- [x] https://repository.library.northeastern.edu/collections/neu:cj82qf571
- [x] https://repository.library.northeastern.edu/collections/neu:cj82pv86s
- [x] https://repository.library.northeastern.edu/collections/neu:rx918725c
- [x] https://repository.library.northeastern.edu/collections/neu:cj82nq94g

Also, these load reports:

- [x] https://repository.library.northeastern.edu/loaders/spreadsheet/report/1927
- [x] https://repository.library.northeastern.edu/loaders/spreadsheet/report/1952

Each file needs small (~600px) and large (~1200) versions.
Each collection has a sentinel set up with the correct permissions.

**Comment by dgcliff** [comment]
All done

**Comment by sarahjeansweeney** [comment]
Here's another batch that need derivatives (small and large; all have collection sentinels and the core files have been updated): 

- [ ] https://repository.library.northeastern.edu/collections/neu:cj82qm768
- [ ] https://repository.library.northeastern.edu/collections/neu:cj82qm74q
- [ ] https://repository.library.northeastern.edu/collections/neu:cj82qm30n
- [ ] https://repository.library.northeastern.edu/collections/neu:cj82qm29w
- [ ] https://repository.library.northeastern.edu/collections/neu:cj82qm20d
- [ ] https://repository.library.northeastern.edu/collections/neu:cj82qk894
- [ ] https://repository.library.northeastern.edu/collections/neu:cj82qk869
- [ ] https://repository.library.northeastern.edu/collections/neu:cj82qk84r
- [ ] https://repository.library.northeastern.edu/collections/neu:cj82qk37c
- [ ] https://repository.library.northeastern.edu/collections/neu:cj82qk34j
- [ ] https://repository.library.northeastern.edu/collections/neu:cj82qk320
- [ ] https://repository.library.northeastern.edu/collections/neu:cj82qj17p
- [ ] https://repository.library.northeastern.edu/collections/neu:cj82qj129
- [ ] https://repository.library.northeastern.edu/collections/neu:cj82qj10r
- [ ] https://repository.library.northeastern.edu/collections/neu:cj82px38j
- [ ] https://repository.library.northeastern.edu/collections/neu:cj82qh68z

**Comment by dgcliff** [comment]
All sorted
