### ISSUE TITLE
Load report file name ordering

### ISSUE THREAD

**Issue by sarahjeansweeney** [NEU-Libraries/cerberus#1150]
Currently, the IPTC and other loader reports display the filenames in the order they were processed by the loader (I think), which is not necessarily in the filename sequence order.

For example, [this](https://repository.library.northeastern.edu/loaders/marcom/report/2277) IPTC load report lists the files out of order:
![2017-10-11_1008](https://user-images.githubusercontent.com/4663073/31445495-28a260bc-ae6c-11e7-8d59-3e184f164a2f.png)

Though some load reports do display the files in order: https://repository.library.northeastern.edu/loaders/spreadsheet/report/2275

![2017-10-11_1009](https://user-images.githubusercontent.com/4663073/31445598-5867d41c-ae6c-11e7-940e-d632f3ba49d9.png)

Marcom requested that the load report be sorted by the filename, which seems reasonable. I can see two options to support this: process the files in filename order or allow the load report table to be sorted by file name, core file title, or status - or both. Being able to sort by status would be useful when someone is troubleshooting a load with errors.

**Comment by dgcliff** [comment]
Sorting by column shouldn't be too bad, will make a patch.
