### ISSUE TITLE
Clicking the terms of use link on the submission page doesn't open the terms

### ISSUE THREAD

**Issue by sarahjeansweeney** [NEU-Libraries/cerberus#1151]
Clicking the DRS terms of use link on the file upload page doesn't open the terms page:

![2017-10-19_1513](https://user-images.githubusercontent.com/4663073/31789659-d797f698-b4e0-11e7-8afe-dbfd5cee692a.png)

Opening the link in a new page works. Copying the URL also copies the correct URL.

Tried in Firefox and Chrome with the same result.

**Comment by dgcliff** [comment]
I think you found a 4 year old bug. Steven made it `%a{href: "/terms" , data: { remote: true} }`

Easy fix, will put in a patch
