### ISSUE TITLE
Creator name not sorting as expected

### ISSUE THREAD

**Issue by sarahjeansweeney** [NEU-Libraries/cerberus#1154]
Hillary submitted this to library help:

When sorted by Creator A-Z, the last item listed in the [Information Design and Visualization Master's Theses](https://repository.library.northeastern.edu/collections/neu:cj82mf17j?utf8=%E2%9C%93&sort=creator_ssi+asc&per_page=20&id=neu%3Acj82mf17j&rows=20) collection is by "[de la Torre - Arenas, Irene](https://repository.library.northeastern.edu/files/neu:cj82qj439)". There are a few creator names that start with "Z", so this file shouldn't sort at the bottom of the collection.

I reindexed the record, but it still sorts at the end. Is it possible the "de la" and the "-" are throwing off the indexing?

**Comment by dgcliff** [comment]
that does seem odd. Will look into it

**Comment by dgcliff** [comment]
This seems to be a capitalization problem. Looking into seeing if Solr can be adjusted.

**Comment by dgcliff** [comment]
I'm going to look to see if I can include LowerCaseFilterFactory to resolve this issue

**Comment by dgcliff** [comment]
Fixed. Further noticed instances will need the specific item, and all of it's neighboring core files to be re-indexed (best just let me know the collection, and I can kick it off in the console)
