### ISSUE TITLE
XML loads not included in daily digest count?

### ISSUE THREAD

**Issue by sarahjeansweeney** [NEU-Libraries/cerberus#1155]
The "Daily Non-Featured Content and Collection Uploads and Updates" email that counted yesterday's activity counted only 67 items:

- 50 Marcom loads
- 13 user uploads
- 4 updated collections

I also loaded 189 files yesterday afternoon using the XML loader, so the actual count should be 252, not 67. 

FWIW, this number is correct on the stats page.

![2018-01-11_1007](https://user-images.githubusercontent.com/4663073/34832203-354aa5c0-f6b7-11e7-83d5-40fd652075cd.png)

Or maybe it's not? I only see 14 interface uploads from yesterday (featured and non-featured), not 15.

**Comment by dgcliff** [comment]
the 15th was a private test upload I did after deploying, which is why it wasn't in the email

sadow
Private Test
neu:cj82qt404

**Comment by sarahjeansweeney** [comment]
It looks like no loads or core file edits were counted in the "Daily Non-Featured" email. Only the 12 collection adds/edits were counted.

The stats page counts 87 uploads and 65 edit tab edits for core files:

![2018-01-23_1011](https://user-images.githubusercontent.com/4663073/35283415-34da4a5a-0026-11e8-8a4a-9f57cdf93f3e.png)

**Comment by dgcliff** [comment]
Fixed with 75853f0d2b7b5dea5295bcac4d63a27afee4b87c - should be in effect as of next email.
