### ISSUE TITLE
IPTC batch upload button disabled in Internet Explorer

### ISSUE THREAD

**Issue by sarahjeansweeney** [NEU-Libraries/cerberus#1157]
A user reported to me yesterday that the upload button on the D'Amore Mckim IPTC loader page was disabled, even after agreeing to the terms, etc...:

![image001](https://user-images.githubusercontent.com/4663073/35882878-8bcee87e-0b53-11e8-848b-9da765f42685.png)

She was using Internet Explorer. When she tried again in Chrome the button was enabled and she was able to load the files.

**Comment by dgcliff** [comment]
That's a javascript problem. May be hard to emulate internet explorer on a Mac, but I'll give it a shot.

**Comment by dgcliff** [comment]
I was able to utilize browser stack to emulate the latest version of IE, and the button was fine - this appears to be an environmental problem on this users computer.

I would suggest that they upgrade their internet explorer, disable any plugins that interact with Javascript, and ensure javascript isn't disabled.

But I'd really suggest just using Chrome.

I've attached the emulation showing no conflict between standard IE and the upload button

![screenshot 2018-02-06 15 46 06](https://user-images.githubusercontent.com/459084/35883398-22c07c6a-0b55-11e8-9c46-16c48707be1a.png)

**Comment by dgcliff** [comment]
And the screenshot to show (my bogus) file was rejected, indicating that I was able to press the button and progress in the process

![screenshot 2018-02-06 15 48 46](https://user-images.githubusercontent.com/459084/35883458-49a06318-0b55-11e8-8657-0639ea9b9ac2.png)
