### ISSUE TITLE
Title sort with numbers

### ISSUE THREAD

**Issue by sarahjeansweeney** [NEU-Libraries/cerberus#1159]
The What's New podcast now as more than 10 episodes: https://repository.library.northeastern.edu/collections/neu:cj82q862v

When sorted by title, the episodes sort in this order: 
1
10
11
2

Presumably this is because the number is treated as a string. Is it possible for numbers in a title field to be treated as integers to sort as the user would expect (1, 2 ... 10, 11)?

![2018-03-12_0958](https://user-images.githubusercontent.com/4663073/37288029-9c55c7c8-25dc-11e8-881d-277075df1f54.png)

**Comment by dgcliff** [comment]
Will take effect on deploy and reindex (later today)
