### ISSUE TITLE
Replacing thumbnails for collections

### ISSUE THREAD

**Issue by sarahjeansweeney** [NEU-Libraries/cerberus#1160]
This was reported to me by a user and I've experienced it myself. When replacing a thumbnail for a collection that already has a thumbnail, the old thumbnail image is not immediately replaced with the new thumbnail image. The replaced thumbnail displays instead of the new thumbnail. A hard refresh displays the new thumbnail. To replicate:

1. Go to any collection, add a new thumbnail, click "Submit"
2. Go back to manage that collection, select "Remove existing thumbnail?", click "Submit"
3. Go back to manage that collection again, add a new, different thumbnail, click "Submit"
4. On the saved collection page you'll see that the thumbnail is the first image, not the second, new image

In one instance, the thumbnail did eventually revert to the new file, but only after a few days: https://repository.library.northeastern.edu/collections/neu:cj82r2497

Here are a few collections where I know this has occurred:
Reported to me:
https://repository.library.northeastern.edu/collections/neu:cj82r176x
https://repository.library.northeastei rn.edu/collections/neu:cj82ng44t

Experienced myself:
https://repository.library.northeastern.edu/collections/neu:cj82r2497
https://repository.library.northeastern.edu/collections/neu:cj82qm68k

Not sure if it helps, but here are a few screenshots for https://repository.library.northeastern.edu/collections/neu:cj82qm68k

First thumbnail added: 
![2018-03-12_0939](https://user-images.githubusercontent.com/4663073/37287176-8b52caa4-25da-11e8-97f3-22ba9f192e1d.png)

First thumbnail removed:
![2018-03-12_0939-1](https://user-images.githubusercontent.com/4663073/37287185-9078caba-25da-11e8-853d-5de343598f1f.png)

Second, different thumbnail added:
![2018-03-12_0940](https://user-images.githubusercontent.com/4663073/37287193-9ac55fd8-25da-11e8-8b40-d999a68502d7.png)

**Comment by dgcliff** [comment]
Testing new github notifications on slack

**Comment by dgcliff** [comment]
Test notification
