### ISSUE TITLE
"Add to a Set." modal displays more Sets than user has access to

### ISSUE THREAD

**Issue by sarahjeansweeney** [NEU-Libraries/cerberus#1162]
I was working with a user this morning to go over how to add collections to a Set. While walking him through the process, I noticed the "Add to a Set" modal lists 110 Sets for him to choose from. 

<img width="1251" alt="screen shot 2018-03-16 at 11 07 34 am" src="https://user-images.githubusercontent.com/4663073/37541900-a1e3ea40-2932-11e8-8f89-3114fd1fe9c7.png">

His user only has 20 Sets in his list of personal and collaborative Sets:

![2018-03-16_1555](https://user-images.githubusercontent.com/4663073/37541906-a7692b92-2932-11e8-82de-ac8f17bcbc7c.png)

I'm nots sure what the other 90 Sets are. There are 301 Sets total, so it can't be all Sets. My best guess is that it's his Sets plus all public Sets.

Either way, this modal should display only the Sets that he has edit access to.

**Comment by sarahjeansweeney** [comment]
It seems now the modal displays fewer Sets than it should. I can edit 135 collaborative and personal Sets:

<img width="988" alt="2018-03-21_1637" src="https://user-images.githubusercontent.com/4663073/37736082-50e61288-2d26-11e8-8dc1-ce5a4ae7aa23.png">

When I click "Save for Later", only 123 Sets show up in the Add to Sets modal:
<img width="988" alt="2018-03-21_1638" src="https://user-images.githubusercontent.com/4663073/37736132-73fb1ff2-2d26-11e8-9d94-fc9c03f9376d.png">

I know that the "Associated Files" Set is missing from the modal - I haven't looked to see what the other missing Sets are.

**Comment by dgcliff** [comment]
Taking a look

**Comment by sarahjeansweeney** [comment]
Adding a file to a Set now brings up a modal with very few Sets. Of my 135 Sets, only 3 show up when I click "Add to Set":

![2018-03-26_1404](https://user-images.githubusercontent.com/4663073/37925094-b63fc762-3101-11e8-870f-6d155d873f26.png)

The other user from the first message in this ticket sees 0 Sets:

![2018-03-26_1419](https://user-images.githubusercontent.com/4663073/37925177-f1dfc7e0-3101-11e8-9dd3-0bf50b5c3892.png)

**Comment by sarahjeansweeney** [comment]
FWIW, I think the three Sets that I see were all created around the same time.

**Comment by dgcliff** [comment]
This has been fixed, but the numbers will not match collaborative + deposited/owned sets.

As per #1090 "Collaborative" is the list of items which are readable and/or editable as per the users grouper groups. This list includes sets to which a user will not be able to add items.

Therefore, the solr logic for this modal is going to be:

Owned/deposited by the user + editable according to the users grouper groups

**Comment by sarahjeansweeney** [comment]
This makes sense - the modal lists a more accurate number of sets now.
