### ISSUE TITLE
XML loader error: "Error - Namespace dc has not been defined"

### ISSUE THREAD

**Issue by sarahjeansweeney** [NEU-Libraries/cerberus#1163]
This morning I submitted a single page XML load for 20 files: https://repository.library.northeastern.edu/loaders/xml/report/3011

Each file failed with this error: 

> Error - Namespace dc has not been defined

None of the submitted XML files use the dc namespace and records created using the same method have successfully uploaded before. Perhaps this is related to the new Dublin Core transformation process?

**Comment by dgcliff** [comment]
Seems likely. Probably an ordering problem.
