### ISSUE TITLE
Incomplete records

### ISSUE THREAD

**Issue by sarahjeansweeney** [NEU-Libraries/cerberus#1164]
Two users have contacted us about incomplete records, both coming from Archives collections:

https://repository.library.northeastern.edu/files/neu:cj82n552n
https://repository.library.northeastern.edu/files/neu:138700

Both are missing their thumbnails and breadcrumbs, as well as the Manage File and Statistics tabs. The metadata and download options are still present. 

![2018-04-09_0925-1](https://user-images.githubusercontent.com/4663073/38500308-04db5b94-3bd8-11e8-9f34-9283b82ea6ed.png)

![2018-04-09_0925](https://user-images.githubusercontent.com/4663073/38500317-09497cce-3bd8-11e8-91e7-8f615eea44af.png)

It doesn't seem to be widespread, and it's possible only Archives records are impacted (so maybe related to re-indexing activity?).

**Comment by sarahjeansweeney** [comment]
It looks like CERES sites are impacted as well:
https://repository.library.northeastern.edu/files/neu:cj82m750b
![2018-04-09_0933](https://user-images.githubusercontent.com/4663073/38500673-1aa71854-3bd9-11e8-95e9-bfb476e54ed9.png)
![2018-04-09_0933-1](https://user-images.githubusercontent.com/4663073/38500691-243588a6-3bd9-11e8-965b-004dbed1382f.png)

**Comment by dgcliff** [comment]
"it's possible only Archives records are impacted (so maybe related to re-indexing activity?)" - seems like a reasonable chance. I'll take a look

**Comment by dgcliff** [comment]
Being fixed
