### ISSUE TITLE
Intermittent access issues ("Forbidden"/"PowerStack Test Page" messages)

### ISSUE THREAD

**Issue by sarahjeansweeney** [NEU-Libraries/cerberus#1166]
I've encountered a few DRS access issues this morning while performing a few small tasks. 
1) After I uploaded this video: https://repository.library.northeastern.edu/files/neu:cj82rf444

I verified that the video streamed, but on a second play I received the "this video could not be played message". I reloaded the page and got a "Forbidden" screen. I didn't capture the exact page, but here's a screenshot of the page when I encountered it again a few minutes later while looking at this file: https://repository.library.northeastern.edu/files/neu:cj82rf42k

<img width="1225" alt="2018-06-15_0936" src="https://user-images.githubusercontent.com/4663073/41471219-04dc7a96-7081-11e8-9cf8-10f657f44cf8.png">

2) After receiving the first "Forbidden" message, I went to the DRS homepage to make sure it wasn't down. That's when I encountered the "PowerStack Test Page":

<img width="1225" alt="2018-06-15_0933" src="https://user-images.githubusercontent.com/4663073/41471437-a48c55fc-7081-11e8-8781-ded1fd807835.png">

3) I also encountered the "Forbidden" message when trying to impersonate a user:

<img width="1225" alt="2018-06-15_0939" src="https://user-images.githubusercontent.com/4663073/41471366-70a70e12-7081-11e8-8f84-9f4161a4b161.png">

**Comment by dgcliff** [comment]
mod_evasive was re-enabled either by ITS or a system update. I've since moved this file out of the directory to avoid such a reoccurrence.
