### ISSUE TITLE
Adjustments for ETDs

### ISSUE THREAD

**Issue by PatrickYott** [NEU-Libraries/cerberus#1169]
For the campus-wide ETD service that HC is developing, we need to modify how we index the MODS records for ETDS:

- create a new field for advisor and index anybody with that roleTerm
- create a new field for committee_member and index anybody with that roleTerm
- create a new field for year_awarded and index year value from originInfo with appropriate displayLabel

Each of these new SOLR elements should be available as a facet from the API.

**Comment by dgcliff** [comment]
Should be visible on next deploy in the API results

**Comment by PatrickYott** [comment]
[image1.png]

Patrick Yott
Associate Dean for Digital Strategies and Services
Northeastern University Libraries
360 Huntington Ave, SL 327
Boston, MA 02115
617.373.4194
p.yott@neu.edu<mailto:p.yott@neu.edu>

Sent from my iPhone

On Sep 10, 2018, at 4:46 PM, David Cliff <notifications@github.com<mailto:notifications@github.com>> wrote:


Should be visible on next deploy in the API results

**Comment by PatrickYott** [comment]
David -- do you know when the next deploy will be?  And I forgot to mention that we will need to reindex the ETD collection...  not sure how difficult it is to reindex a virtual collection...

thanks
P

**Comment by dgcliff** [comment]
The deploy referenced in this ticket has been done - I can kick off a reindex of the relevant files today

**Comment by PatrickYott** [comment]
Thanks!!!



Patrick Yott
Associate Dean for Digital Strategies and Services
Northeastern University Libraries
360 Huntington Ave, SL 331
Boston, MA 02115
617.373.4194
p.yott@northeastern.edu<mailto:p.yott@northeastern.edu>

**Comment by PatrickYott** [comment]
One small change here, I think.  It looks like the advisors and committee members are still showing up as creators as well as in their newly created etd_advisor and etd_committee_member fields.  We’ll want to have them barred from being creators, or if easier, create an etd_author field that just lists the true author (role=”Author”).  Sorry, I fear I wasn’t clear on this one…
p

Patrick Yott
Associate Dean for Digital Strategies and Services
Northeastern University Libraries
360 Huntington Ave, SL 331
Boston, MA 02115
617.373.4194
p.yott@northeastern.edu<mailto:p.yott@northeastern.edu>


From: "Yott, Patrick" <P.Yott@northeastern.edu>
Date: Monday, September 24, 2018 at 9:58 AM
To: NEU-Libraries/cerberus <reply@reply.github.com>, NEU-Libraries/cerberus <cerberus@noreply.github.com>
Cc: State change <state_change@noreply.github.com>
Subject: Re: [NEU-Libraries/cerberus] Adjustments for ETDs (#1169)

Thanks!!!



Patrick Yott
Associate Dean for Digital Strategies and Services
Northeastern University Libraries
360 Huntington Ave, SL 331
Boston, MA 02115
617.373.4194
p.yott@northeastern.edu<mailto:p.yott@northeastern.edu>

**Comment by dgcliff** [comment]
First things first, the index isn't done.

Secondly, the ticket asked for creating three new fields. Which I did.

Thirdly, "We’ll want to have them barred from being creators" is destructive and would affect all items in the DRS and Toolkit.

Lastly - " if easier, create an etd_author field that just lists the true author (role=”Author”)" is this not already acheived? There is an author_tesi field....

**Comment by PatrickYott** [comment]
Yes, I know you did what I asked.  I was just clarifying my thinking.  I was assuming there was a way to selectively index ETDs as they are a clearly prescribed class of objects, but maybe we don’t need to -- I’ll double check after my current meeting as I didn’t see the author_tesi field available as a facet.
p

Patrick Yott
Associate Dean for Digital Strategies and Services
Northeastern University Libraries
360 Huntington Ave, SL 331
Boston, MA 02115
617.373.4194
p.yott@northeastern.edu<mailto:p.yott@northeastern.edu>

**Comment by dgcliff** [comment]
The ETDs are being selectively reindexed, it still takes time. There's 3482 of them, and that's 3482 actions in a loop.

**Comment by dgcliff** [comment]
author_tesi isn't a facet, but that's also not what was asked for. I will make a facet specifically for the etd author.

**Comment by PatrickYott** [comment]
Thanks.   Sorry for the shit-show of non-explicit thinking!
p

Patrick Yott
Associate Dean for Digital Strategies and Services
Northeastern University Libraries
360 Huntington Ave, SL 331
Boston, MA 02115
617.373.4194
p.yott@northeastern.edu<mailto:p.yott@northeastern.edu>

**Comment by dgcliff** [comment]
Patched for new facet. I will update this ticket when deployed, and ETDs reindexed.

**Comment by dgcliff** [comment]
Deployed and reindexed
