### ISSUE TITLE
Stats page file and core file count discrepancy

### ISSUE THREAD

**Issue by sarahjeansweeney** [NEU-Libraries/cerberus#1170]
While putting together a public stats report I realized that the DRS stats page file counts don't add up to the stats page core file count. I've been taking screenshots of the stats page on the first of each month to help me prep the stats reports, so I have a few data points to look at:

On July 1 the core file count was 152,209, while the sum of the file counts was 152,202 - a difference of 7.

<img width="1280" alt="2018-07-01_1333" src="https://user-images.githubusercontent.com/4663073/45178846-da6c7180-b1e4-11e8-90eb-00ad811f8dca.png">

On August 1 the core file count was 152,768, while the sum of the file counts was 152,771 - a difference of -3.

![overview_stats](https://user-images.githubusercontent.com/4663073/45178851-dfc9bc00-b1e4-11e8-83a6-906f1b134db5.png)

On September 1 the core file count was 154,022, while the sum of the file counts was 154,020 - a difference of 2 (the difference is the same as of today).

<img width="1200" alt="2018-09-01_1417" src="https://user-images.githubusercontent.com/4663073/45178860-e5bf9d00-b1e4-11e8-8b69-8899db22f433.png">

The counts aren't off by that much, so I'm not concerned, but these numbers should probably match. I was originally thinking maybe there was a file type missing from the file list, but the difference isn't consistent enough for that to be the cause, and it wouldn't explain why there were 3 fewer core files than files in August.

**Comment by dgcliff** [comment]
When you say sum of file counts, are we talking public + private or all of the file types added up (or both?)

**Comment by sarahjeansweeney** [comment]
All of the file types listed in the right column (image files, pdf files .... text files, excel files) added up, not the public/private counts.

**Comment by dgcliff** [comment]
One of the files is a core file with no canonical class - https://repository.library.northeastern.edu/files/neu:cj82p2348

**Comment by dgcliff** [comment]
This one I don't have permissions to see, but same problem - neu:cj82rm18j

**Comment by dgcliff** [comment]
I can do one of two things. I can adjust the core file count to include only core files with canonical types. Or make a count of broken files (but this will be nebulous and never quite perfect I imagine). That might just be annoying though - given the fluctuating count, it seems as though they're getting cleaned up via incomplete/in_progress purging anyway

**Comment by sarahjeansweeney** [comment]
I don't think a broken file count is necessary. It sounds like counting core files with canonical types only would be preferable.
