### ISSUE TITLE
Faceting behavior for Dublin Core type values

### ISSUE THREAD

**Issue by sarahjeansweeney** [NEU-Libraries/cerberus#1171]
The new MODS-to-Dublin Core stylesheet uses both the MODS type of resource and genre values to create the DC type values:

```
<mods:genre>articles</mods:genre>
<mods:typeOfResource>text</mods:typeOfResource>
```

becomes

```
<dc:type>articles</dc:type>
<dc:type>Text</dc:type>
```

Although this is technically fine, it causes some odd faceting behavior. I believe the older stylesheet mapped the MODS type of resource value to a prescribed list of values from the DCMI Type Vocabulary, which was used to populate the facet Type value. The new MODS stylesheet does not map to the DCMI vocabulary, so there are more type values than expected in the Type facet:

![2018-09-06_1504](https://user-images.githubusercontent.com/4663073/45181862-a0ec3400-b1ed-11e8-96fd-a5eddf227c6c.png)

Also, it looks like Blacklight only uses the first type value in the DC record to populate the Type facet, rather than all type values. For records with both genre and type of resource values, this means that an image may be given a type of "Image" rather than "StillImage". Again, this is technically fine, but it splits images into two different faceted categories. For example, if you wanted to limit these search results just to photographs, you'd have to limit by "Image" first, then go back and limit by "StillImage" to see all the photographs in the results:

![2018-09-06_1537](https://user-images.githubusercontent.com/4663073/45182066-46070c80-b1ee-11e8-9b2b-84450311c78f.png)

This is labeled as "needs discussion" because I think @dgcliff has a few thoughts about how this could be addressed and I'm open to updating how this facet uses the type values, rather than expecting the facet to behave as it did with the original stylesheet.

**Comment by dgcliff** [comment]
My instinct is just to impose the DC strict types again, and we can review faceting possibilities for v2

**Comment by dgcliff** [comment]
I should also add - keeping the duplicitous values from the MODS-to-DC automated script, but only picking the strict value for the facet (so no loss of background metadata)

**Comment by sarahjeansweeney** [comment]
Strict DC types works for me - I think that's preferred/expected.

**Comment by dgcliff** [comment]
Will be fixed on prod after a retroactive job run against a Solr Query. Shall do so after a deploy
