### ISSUE TITLE
New core file missing uploaded content object

### ISSUE THREAD

**Issue by sarahjeansweeney** [NEU-Libraries/cerberus#1172]
I'm uploading a few files on behalf of a faculty member to this collection: https://repository.library.northeastern.edu/collections/neu:cj82ss18r

All files uploaded so far are .bin files (they are valid, as far as I can tell). Most files have uploaded as expected, with the exception of this file: https://repository.library.northeastern.edu/files/neu:cj82ss27q

I submitted the 769MB bin file as usual, filled out the minimum metadata fields, and uploaded the file without any errors. After the file finished, I noticed there were no download options for the file, only a "Save for later" button: 

![2018-09-18_1042](https://user-images.githubusercontent.com/4663073/45695575-b3406900-bb2f-11e8-89a7-c3572f6027be.png)

The file doesn't seem to be incomplete or in progress, and I don't see any related activity in resque.

**Comment by dgcliff** [comment]
It's there now. The cache was visited  after the purge but before the item was finished. Could've been open in another tab perhaps.
