### ISSUE TITLE
"Add to set" is missing from Grid View for collections

### ISSUE THREAD

**Issue by sarahjeansweeney** [NEU-Libraries/cerberus#1175]
The "Add to set" option is not available for collection items in search and browse lists when the user is in Grid View:

![2018-12-14_0924-1](https://user-images.githubusercontent.com/4663073/50008446-341dce00-ff82-11e8-990f-dad172ec5130.png)

Only the Report a Problem button displays.

The "Add to set" option does display for the same collections in "List View":

![2018-12-14_0924](https://user-images.githubusercontent.com/4663073/50008473-4dbf1580-ff82-11e8-86ce-052354b3aac0.png)

The "Add to set" option should be present for both views

**Comment by dgcliff** [comment]
Unfortunately a conscious choice made back in #644 due to mobile layout concerns. Valid issue due to inconsistency, marking for V2 cosmetic fix.

**Comment by dgcliff** [comment]
Cleared up in chat - fixable due to collection scope in V1 - will make a patch
