### ISSUE TITLE
Download for streaming-only A/V file is triggered after logging in

### ISSUE THREAD

**Issue by sarahjeansweeney** [NEU-Libraries/cerberus#1178]
Here's an odd one: a user reported that signing in to the DRS while on the file page for a streaming-only file triggered a download for the A/V file, which should be streaming-only. This particular DRS item should not have been public, so I corrected the permissions and it's no longer a good option for testing. I was able to replicate it with a different file I uploaded as a test: https://repository.library.northeastern.edu/files/neu:f1881m477

![streamingonly](https://user-images.githubusercontent.com/4663073/52430229-a4088a80-2ad3-11e9-869c-e4d81d25d4f6.gif)

Steps to replicate:

1. Log out of the DRS or go incognito to make sure you're not signed in
2. Navigate to the [file information page](https://repository.library.northeastern.edu/files/neu:f1881m477)
3. Click the Login button to sign in
4. The browser with either prompt you where to download, automatically download, or start playing in the browser (I tried in 3 browsers and they each handled it differently, depending on my preferences)

**Comment by dgcliff** [comment]
All sorted
