### ISSUE TITLE
Failed multipage XML upload: "Missing required parameter :pid"

### ISSUE THREAD

**Issue by sarahjeansweeney** [NEU-Libraries/cerberus#1180]
I submitted this load with two multipage records this morning: https://repository.library.northeastern.edu/loaders/xml/report/3956

It was taking longer than I expected, so I checked resque, which showed one failed job with this error:

> Missing required parameter :pid

![2019-02-22_1050](https://user-images.githubusercontent.com/4663073/53253640-ba941180-368f-11e9-87c1-05055752413b.png)

I've loaded a few batches this morning that I had to retry because of various errors that were my fault, so it's not out of the question that this is the result of how I set up the package for loading, but PIDs aren't required for new loads so I'm not sure what happened.

**Comment by dgcliff** [comment]
Ok, I can reproduce this. It seems related to the MASTER and DERIVATIVE code. Digging into it.

**Comment by dgcliff** [comment]
Fixed with 3ba7c60d
