### ISSUE TITLE
"This site can’t be reached" message when accessing the DRS

### ISSUE THREAD

**Issue by sarahjeansweeney** [NEU-Libraries/cerberus#1184]
I get this message when I try to visit the DRS:

> This site can’t be reached The connection was reset.
> Try:
> 
> Checking the connection
> Checking the proxy and the firewall
> ERR_CONNECTION_RESET

![2019-04-17_1022](https://user-images.githubusercontent.com/4663073/56295402-c5e94380-60fa-11e9-86b2-1799cc1923af.png)

I had been able to access the site without issue until about 10 minutes ago.

**Comment by sarahjeansweeney** [comment]
Of course, the page loaded just after I hit submit. Though it's still loading rather slowly.

**Comment by dgcliff** [comment]
Looks like ITS is having some server issues with nb4404

**Comment by sarahjeansweeney** [comment]
I'm encountering this again. Access to the DRS has been intermittent for the last 15 minutes or so.

<img width="1225" alt="2019-05-07_1354" src="https://user-images.githubusercontent.com/4663073/57321589-a9c03d00-70cf-11e9-8871-782a3880fab6.png">
