### ISSUE TITLE
Updates to Marketing IPTC Loader

### ISSUE THREAD

**Issue by sarahjeansweeney** [NEU-Libraries/cerberus#1187]
The Marketing team has decided that they’d like the metadata, small, and large images to remain available faculty and staff, but they’d like to restrict the master file to just the marketing group (drs:marketing_and_communications:staff). They would also like to update their use and reproduction statement:

> The Northeastern External Affairs division manages the rights and usage of Marketing and Communications images. All rights are reserved, and no usage or reproduction of any type may be made of said images without the express permission of the Communications or Marketing departments. Please contact brand@northeastern.edu if you are interested in using one of these images. If appropriate, you will receive written approval for explicit use and will be provided the high resolution image. Images cannot be manipulated or altered in any way from the original. Image should be credited: “Photographer Name/Northeastern University.”
 
Four things will need to happen to implement this change:

1. The loader will need to be updated with the new permissions for master files and the new use and reproduction statement
2. A sentinel will need to be run to update permissions for all existing master files
3. The use and reproduction statement will need to be updated for all files in the collection
4. The marketing staff group will need to be updated with more staff: drs:marketing_and_communications:staff (list forthcoming from Matt)

**Comment by dgcliff** [comment]
Updated
