### ISSUE TITLE
Content objects still public after making core file private

### ISSUE THREAD

**Issue by sarahjeansweeney** [NEU-Libraries/cerberus#1193]
The subject of [these](https://repository.library.northeastern.edu/sets/neu:f18824335) photos has asked that they be removed from public view and from Google's index. The core files were made private by Archives staff and I submitted removal requests for two of them. According to Google's analysis, the other two are still "available" and must be removed from the site before they can be removed from the index.

The core files are private, but it looks like the content objects are still public. Copying the direct download URL for any of the content objects triggers a download. For example, when signed out:

https://repository.library.northeastern.edu/files/neu:m0419v19m --> prompts a login
https://repository.library.northeastern.edu/downloads/neu:m041j628v?datastream_id=content --> opens a file download dialog box.

I added these files to a set and ran a sentinel to force the content objects to private, but they are still public in Fedora:

![Screen Shot 2019-12-09 at 9 13 17 AM (2)](https://user-images.githubusercontent.com/4663073/70442381-3b2bcf00-1a64-11ea-868b-2dd2a690f7f7.png)

Here's a separate example. This core file was made private on Friday:
https://repository.library.northeastern.edu/files/neu:f18823860

The PDF download options are still public:
https://repository.library.northeastern.edu/downloads/neu:m044v826p?datastream_id=content

![Screen Shot 2019-12-09 at 9 20 29 AM (2)](https://user-images.githubusercontent.com/4663073/70443033-64992a80-1a65-11ea-826f-e0c30a2aac73.png)

For this example, the `northeastern:drs:sail:staff` was granted "edit" permissions for the core file. I don't see this reflected in the content object, just the core file. (Not that you can edit the content object, but that group should be explicitly listed as being able to read the file.)

I'm sure making edits to a core file's permissions has updated the content objects in the past, as did the sentinel content object changes. I'm not sure when these permission changes stopped syncing, but when a core file's permissions change, the content object permissions should change, as well.

**Comment by dgcliff** [comment]
That seems odd.

I tried to replicate your set steps. I added https://repository.library.northeastern.edu/files/neu:m0419v19m to a private set. I specifically chose ImageSmallFile to be private in the sentinel. I ran it, and it appears to have changed as expected?

```<rightsMetadata xmlns="http://hydra-collab.stanford.edu/schemas/rightsMetadata/v1" version="0.1">
<copyright>
<human type="title"/>
<human type="description"/>
<machine type="uri"/>
</copyright>
<access type="discover">
<human/>
<machine/>
</access>
<access type="read">
<human/>
<machine> </machine>
</access>
<access type="edit">
<human/>
<machine>
<person>000000000</person>
<group>northeastern:drs:repository:staff</group>
</machine>
</access>
<embargo>
<human/>
<machine/>
</embargo>
</rightsMetadata>```

**Comment by sarahjeansweeney** [comment]
Interesting. That one prompts a login for me now, too.

These two still trigger a download (as of this moment, anyway):
https://repository.library.northeastern.edu/downloads/neu:m041j6294?datastream_id=content
https://repository.library.northeastern.edu/downloads/neu:m0419v20c?datastream_id=content

Still the case for you? Maybe I just have a cached version of these?

**Comment by dgcliff** [comment]
I also was prompted with a login before I ran my set experiment. It doesn't appear to be a caching issue, so much as a Set/Sentinel interface/execution issue. I'm guessing because my attempt was hyper specific it didn't run into the issue you're facing.

Could you try the set approach for the https://repository.library.northeastern.edu/downloads/neu:m041j6294 binary object and document the steps involved?

**Comment by sarahjeansweeney** [comment]
I added [this](https://repository.library.northeastern.edu/files/neu:m0419v19m) core file to a set and updated the core file and content object permissions:
![Screen Shot 2019-12-09 at 10 11 18 AM (2)](https://user-images.githubusercontent.com/4663073/70447622-053f1880-1a6d-11ea-98a8-c515e3cdedcc.png)

All objects are now private.

I added two files to a set and ran the same process: https://repository.library.northeastern.edu/sets/neu:f1882435q

Some content objects are restricted, others are not, which makes me think that even though the sentinel is done running, the updates are still catching up.

**Comment by dgcliff** [comment]
Collection privatization had a logic error that privatized core files but not their content objects - https://github.com/NEU-Libraries/cerberus/commit/8fb9776baf83f6d1f0e8f0e94c2c3db03584dac2 should resolve it
