### ISSUE TITLE
CAMD IPTC Photo Loader

### ISSUE THREAD

**Issue by sarahjeansweeney** [NEU-Libraries/cerberus#1196]
The CAMD media group would like to start uploading their college's photographs using an IPTC photo loader.

Here are the basic details you'll need to create their loader:

- Loader name: College of Arts, Media and Design
- Base Collection: https://repository.library.northeastern.edu/collections/neu:f1882040r
- Derivative sizes: No derivatives.
- MODS default values:

> <mods:accessCondition type="use and reproduction">The College of Arts, Media and Design manages the rights and usage of CAMD Marketing and Communications images. All rights are reserved, and no usage or reproduction of any type may be made of said images without the express permission of the CAMD Communications or Marketing departments. Please contact camdcommunications@gmail.com if you are interested in using one of these images. If appropriate, you will receive written approval for explicit use and will be provided the high-resolution image. Images cannot be manipulated or altered in any way from the original. Image should be credited: "Photographer Name/Northeastern University."</mods:accessCondition>

Access rights:
I think this is handled by the sentinel or collection now? If not:
Mass Permissions: `Private`
Can read: `northeastern:drs:camd:photo_archive:users`
Can edit: `northeastern:drs:camd:photo_archive:staff`

**Comment by dgcliff** [comment]
Added with 253a7e587002ff9ed583fba6442cc7fcf7271db5 - will close once it's deployed and verified as working with a test zip
