### ISSUE TITLE
System error when accessing an employee's "communities" page

### ISSUE THREAD

**Issue by sarahjeansweeney** [NEU-Libraries/cerberus#1201]
I get a system error when I click on the "[Casper's communities](https://repository.library.northeastern.edu/employees/neu:m040cf16h/communities)" tab on this person's My DRS page: https://repository.library.northeastern.edu/employees/neu:m040cf16h/

![Screen Shot 2020-06-05 at 12 56 52 PM](https://user-images.githubusercontent.com/4663073/83903423-17ec8e80-a72c-11ea-8e07-f4f9de54b49a.png)

I also encounter a system error when I try to edit the employee's account from the "Manage Employees" admin page.

Edited to add that I don't encounter this with other employees.

**Comment by dgcliff** [comment]
taking a look

**Comment by dgcliff** [comment]
This user belongs to a community that doesn't exist. I'm guessing it got deleted/remade. As best as I can tell, they belong to https://repository.library.northeastern.edu/communities/neu:116. Happy to redo this connection if that's acceptable.

**Comment by sarahjeansweeney** [comment]
Yes, please! Thanks
