### ISSUE TITLE
Sentinel process will fail if EPUB content object is present

### ISSUE THREAD

**Issue by sarahjeansweeney** [NEU-Libraries/cerberus#1210]
I attempted to use the sentinel feature to update the content object permissions for this core file: https://repository.library.northeastern.edu/files/neu:m043j9070

The interface feature allowed me to select the appropriate permissions change and run the process, but looking in `/resque` reveals the sentinel process failed with the following error message:

```undefined method `epub' for #<Sentinel:0x00000008981ae0>``` 

![Screen Shot 2021-08-18 at 4 05 40 PM](https://user-images.githubusercontent.com/4663073/129964926-79b06761-1219-43ab-8190-8eb29b9f260a.png)

**Comment by dgcliff** [comment]
Should be fixed with https://github.com/NEU-Libraries/cerberus/commit/79adff60444483634bef87b69573aacd4a9fe68e#diff-895119acf1d3df898d1855e44c383ea2390ad9ed38541538a03e691dca094640

Will reopen if not
