### ISSUE TITLE
College of Science IPTC Photo Loader

### ISSUE THREAD

**Issue by sarahjeansweeney** [NEU-Libraries/cerberus#1211]
The College of Science media group would like to start uploading their college's photographs using an IPTC photo loader.

Here are the basic details you'll need to create their loader:

Loader name: College of Science Dean's Office
Base Collection: https://repository.library.northeastern.edu/collections/neu:ww72bs269
Derivative sizes: No derivatives.
MODS default values:

```
<mods:originInfo>
        <mods:place>
            <mods:placeTerm type="text">Boston MA</mods:placeTerm>
        </mods:place>
        <mods:dateCreated keyDate="yes" encoding="w3cdtf">[DATE FROM EXIF]</mods:dateCreated>
        <mods:copyrightDate encoding="w3cdtf">[DATE FROM EXIF]</mods:copyrightDate>
        <mods:publisher>Northeastern University</mods:publisher>
    </mods:originInfo>
<mods:publisher>Northeastern University</mods:publisher></mods:originInfo>
```

```
<mods:accessCondition type="use and reproduction">The Northeastern College of Science Marketing and Communications team manages the rights and usage of Marketing and Communications images. All rights are reserved. College of Science faculty and staff may use these images for college-related purposes only. Please contact. cosmarcom@northeastern.edu if you have any questions. Images cannot be manipulated or altered in any way from the original. Image should be credited: "Photographer Name/Northeastern University."</mods:accessCondition>
```

```
<mods:accessCondition type="use and reproduction">In Copyright: This Item is protected by copyright and/or related rights. You are free to use this Item in any way that is permitted by the copyright and related rights legislation that applies to your use. For other uses you need to obtain permission from the rights-holder(s). (http://rightsstatements.org/page/InC/1.0/?language=en)</mods:accessCondition>
```

Access is handled by the collection values, but those are incomplete for the time-being, since Grouper groups aren't syncing correctly. Once Grouper is syncing, I'll add the correct Grouper groups to the collection (it may not matter, but just in case it's important to know the permissions aren't yet set correctly).

**Comment by sarahjeansweeney** [comment]
Updating to add: 
1) Grouper is syncing properly again, and
2) this is the group that manages access to the loader itself `northeastern:drs:repository:loaders:cos_media`

**Comment by dgcliff** [comment]
I think this can be considered done! Happy for it to be reopened if it doesn't work as intended
