### ISSUE TITLE
Error loading certain files using IPTC loader because of array data

### ISSUE THREAD

**Issue by sarahjeansweeney** [NEU-Libraries/cerberus#1213]
The one of the Communications photographers reported that she regularly encountered an unexpected error when processing some files:

<img width="890" alt="Screen Shot 2021-12-14 at 11 11 45 AM" src="https://user-images.githubusercontent.com/4663073/146036071-3a5f8d8c-e257-4c39-a159-e9af67988058.png">

Taking a look at the images that triggered the error and the detailed IPTC report for those images (i.e. this page: https://repository.library.northeastern.edu/loaders/marcom/file/453060), it looks like there are some corrected values embedded in the images that are incorrect according to the tools the loader uses to process the images. The `PaintCorrectionRangeMaskColorAmount` and `GradientBasedCorrRangeMaskColorAmount` fields contain two values (i.e. `[0.5, 0.5]`) when the loader expects only one (`0.5`). I compared this to a few other files that loaded successfully but also had the color amount correction set to `0.5` (like [this](https://repository.library.northeastern.edu/files/neu:bz61fx07s) one) and these files did not have multiple values, just the `0.5`. Photoshop lets you look at the raw XML for the file, and there are two `CorrectionRangeMask ColorAmount` values for at least one of the errored images in different nodes.
 
The IPTC loader should probably ignore this error and allow the file to be processed.

**Comment by dgcliff** [comment]
Closed with a040f06
