### ISSUE TITLE
Update "Privacy" link in DRS footer

### ISSUE THREAD

**Issue by sarahjeansweeney** [NEU-Libraries/cerberus#1247]
The "Privacy" link in the DRS footer goes to the privacy page on the old library website. The privacy page on the new library website is located here: https://library.northeastern.edu/administration/privacy-policy/

Can the "Privacy" link in the DRS footer be updated to the new privacy policy URL?

**Comment by dgcliff** [comment]
Closed with 3eb3f4026fcd0e956bc710ede713a690dc358ad0
