### ISSUE TITLE
New text for the core file statistics page

### ISSUE THREAD

**Issue by sarahjeansweeney** [NEU-Libraries/cerberus#1288]
To help users understand the awesome new graphs on the core file statistics pages, I'd like the following text added to the bottom of the page:

> Usage statistics are updated weekly. A graph visualizing interactions with a file will display when a file has 10 or more views, downloads, or streams. Please visit the [DRS subject guide](https://subjectguides.lib.neu.edu/drs/statistics) for more information about DRS statistics.

And, while we're making changes to this page, can the number counts be updated to include a comma separator for numbers greater than 999? So `1,000` instead of `1000`?

**Comment by dgcliff** [comment]
Closed with 751871c
