### ISSUE TITLE
Audio and Video Models

### ISSUE THREAD

**Issue by PatrickYott** [NEU-Libraries/cerberus#198]
After several meetings with faculty with pending audio and/or video projects, I'm convinced that we need to have two object models for each:

audio_streaming_only
audio_all (stream and download)

video_streaming_only
video_all (stream and download)

Folks are going to be keen to control who can actually download at a tighter level than who can stream (generally the public), and I think having two separate models will make this easier.  

Furthermore, given how we need to feed information to the streaming server, we might actually have a pair of object models for each mime-type -- of course we can control which mime-types we accept.  As a starter, something like this:

Audio
     MP3
     AAC
Video
    MP4
    MOV

would do well to get us started..

Sarah and I can play with this in the spaghetti monster and report back to the group.

**Comment by elizoller** [comment]
I took a look at the issues with JWplayer and Wowza.
Regarding the audio files that having disappearing images/posters: I read around and discovered that on streaming audio-only files, JWplayer recommends placing the image on the page outside the player and attaching Javascript to trigger the play of the audio with click. This feels like a hack to me. I posted on JWplayer's support site to see if this was a known issue or if they have a real solution.
Regarding the need for symlinks to files with .mp4/.mp3 extensions- I am able to get RTMP streaming working without symlink. This will cover our bases in browsers. In JWplayer's documentation, you are supposed to be able to add type: 'mp4' to a file with an alternate ending to help it out. This doesn't seem to be working in our case for HLS streaming (for iOS devices). I'm still working on HLS streaming for mp4. For mp3 I can't seem to get HLS streaming to work at all (even for the symlink files)- I wonder if this is a Wowza config issue.
Also in the future, I think we should put in a configuration for Android.

**Comment by PatrickYott** [comment]
Brilliant - the library inherited this server and software, so I have no idea how it was originally configured.  Will you be able to do the same with the .mov extension?
p
Patrick Yott
Associate Dean for Digital Strategies and Services
Northeastern University Libraries
360 Huntington Ave, SL 327
Boston, MA 02117
p.yott@neu.edu
617.373.4194
617.373.5409 (fax)

**Comment by elizoller** [comment]
Status of finagling jwplayer + wowza as of 3/6 

File Type  | Device Type | Link Type | Status | Notes
 ------------ | ------------- | ------------ | ------------- | -------------
 MP4  | Computer- Full Browser  | rtmp | Working | no issues
 MP4  | iOS device  | http/hls | Working | requires uri encoding for file name, devices newer than iphone 3G
 MP4  | Android device | http | Working | requires fallback:false and androidhls:true will work on android 4.1+
 MOV  | Computer- Full Browser  | rtmp | -- | ??
 MOV  | iOS device  | http/hls | Working | requires uri encoding for file name
 MOV  | Android device | rtsp | Working | requires fallback:false and androidhls:true will work on android 4.1+
 MP3  | Computer- Full Browser  | rtmp | Working | image disappears on play
 MP3  | iOS device  | http/hls | -- | ??
 MP3  | Android device | rtsp | -- | ??

**Comment by dgcliff** [comment]
We've implemented (most) of this ticket. Will make a new ticket for making the distinction between steam-only, and stream and/or download
