### ISSUE TITLE
Public/private dropdown defaults to private as suggestion on new item. Should be public.

### ISSUE THREAD

**Issue by dgcliff** [NEU-Libraries/cerberus#320]
As per our meeting, we generally wish to encourage public object listings, so changing the default to public when creating something new would be preferred.

**Comment by dgcliff** [comment]
This didn't work properly.

**Comment by elizoller** [comment]
@dgcliff  I think I've got this working correctly. 
if parent is private then only display private as option for new/edited child.
if parent is public then display public and private as options for new/edited child. if new child, default to public. if edited child, default to pre-selected value.
but what about when a parent is edited and changed from public to private, can we put something to push that change out to it's children?
also sets/collections are different from core files- you want this parent/child behavior to pass from a collection parent to a child core file as well, right?
