### ISSUE TITLE
Character entities seem to be limiting search results

### ISSUE THREAD

**Issue by sarahjeansweeney** [NEU-Libraries/cerberus#439]
Searches for Bouve and Bouvé each retrieve 0 results, but a search for ```Bouv&#233```; retrieves several results. 
A search that includes e, é, or &#233 ; should all retrieve similar results.

**Comment by sarahjeansweeney** [comment]
I'm seeing this again, but now Bouvé brings up 0 results (Bouve has 2049).

**Comment by dgcliff** [comment]
Sigh. Ok. I'll patch it up more.

**Comment by dgcliff** [comment]
Pushed up another fix for this. It won't take effect until I deploy it, and we re-index everything, which may be a while.

**Comment by sarahjeansweeney** [comment]
Seeing this again. A search for Bouvé returns 0 results, Bouve 2377.

**Comment by dgcliff** [comment]
It looks like Tomcat at some point lost it's configuration - http://wiki.apache.org/solr/SolrTomcat#URI_Charset_Config

Will reapply tonight, to see if it fixes the issue

**Comment by dgcliff** [comment]
Yeah, that fixed it. I think the security updates may have updated tomcat, overriding the utf8 config setting.
