### ISSUE TITLE
Modal Styling

### ISSUE THREAD

**Issue by sarahjeansweeney** [NEU-Libraries/cerberus#484]
The following modal windows need styling:
-Edit Metadata page "Cancel" confirmation
 Change message to: Are you sure you want to cancel your changes?
-Edit Collection page "Cancel" confirmation
 Change message to: Are you sure you want to cancel your changes?
-Download Queue "remove" item confirmation
 Change message to: Are you sure you want to remove this file from your Download Queue?
-Download Queue "Destroy" confirmation 
 Change message to: Are you sure you want to clear your Download Queue?

**Comment by elizoller** [comment]
I'm going to reopen this and implement bootbox. It was included in the bower components but never implemented. Using bootbox can save us manually writing modals for simple confirm messages.

**Comment by elizoller** [comment]
I think this is best saved for when we update all the gems and move from Bootstrap 2->3 so I'm going to close it for now
