### ISSUE TITLE
OAI

### ISSUE THREAD

**Issue by PatrickYott** [NEU-Libraries/cerberus#506]
Damn, almost forgot.  It is highly desirable that we have an OAI provider in place when we launch.  There seem to be several gems out there, but this one is by the Hydra team: https://github.com/cbeer/blacklight_oai_provider -- we will want to limit OAI activity those records that offer public consumption...

**Comment by sarahjeansweeney** [comment]
Additions to the OAI feature:
We need to accommodate general consumers of OAI, and the controlled consumers, like Digital Commonwealth/DPLA. To do this we can create a general feed for all public, non-embargoed, etc, files, and a controlled feed for DC based on Sets (our Sets, not OAI Sets).
A button or check box mechanism can be added to Set options for users in the OAI Grouper group to request the items in that Set be exposed in the controlled OAI feed, which will be indicated in an OAI element in the properties datastream.

Also, all DRS items, old and new, will get a thumbnail inserted in the MODS. We'll probably need to think about what this means when users are allowed to replace thumbnails.

**Comment by PatrickYott** [comment]
How would that work?  How would we create a set, for example, of all archives materials?
P
Patrick Yott
Associate Dean for Digital Strategies and Services
Northeastern University Libraries
360 Huntington Ave, SL 327
Boston, MA 02115
617.373.4194
p.yott@neu.edu<mailto:p.yott@neu.edu>

Sent from my iPhone

On Dec 11, 2015, at 4:58 PM, Sarah S. <notifications@github.com<mailto:notifications@github.com>> wrote:


Additions to the OAI feature:
We need to accommodate general consumers of OAI, and the controlled consumers, like Digital Commonwealth/DPLA. To do this we can create a general feed for all public, non-embargoed, etc, files, and a controlled feed for DC based on Sets (our Sets, not OAI Sets).
A button or check box mechanism can be added to Set options for users in the OAI Grouper group to request the items in that Set be exposed in the controlled OAI feed, which will be indicated in an OAI element in the properties datastream.

Also, all DRS items, old and new, will get a thumbnail inserted in the MODS. We'll probably need to think about what this means when users are allowed to replace thumbnails.

-

**Comment by sarahjeansweeney** [comment]
@PatrickYott One of the new Sets enhancements is to be able to add collections to Sets, as well as whole pages of search and browse results. Archives will be able to create a Set for each collection they want to expose to DC/DPLA, or one Set for everything they want to expose.

**Comment by PatrickYott** [comment]
Freakin’ Brilliant!!
Patrick Yott
Associate Dean for Digital Strategies and Services
Northeastern University Libraries
360 Huntington Ave, SL 327
Boston, MA 02115
401.338.3787
p.yott@neu.edu<mailto:p.yott@neu.edu>

**Comment by dgcliff** [comment]
there is now the /oai_thumbnail path for DC to consume - until I get other direction on whether or not to implement either full OAI sets, or pseudo Cerberus sets linked to a custom route, going to mark this is as closed
