### ISSUE TITLE
Photograph Loader

### ISSUE THREAD

**Issue by PatrickYott** [NEU-Libraries/cerberus#592]
You can find the existing loaders at /var/www/html/functions/loaders on repository2

**Comment by sarahjeansweeney** [comment]
Following up on our discussion yesterday:

On the page where the user selects the zip file and the destination collection, can the text for the collection question be changed to:
"Where do you want to deposit these files?"

Here's the COE and CPS information you'll need:

COE photographs collection PID: neu:5m60qz05t
COE permissions: northeastern:drs:college_of_engineering:deans_office
COE username: (forthcoming) 

CPS photographs collection PID: neu:5m60qz16b
CPS permissions: northeastern:drs:college_of_professional_studies:media
CPS username: Julio Chuy

**Comment by elizoller** [comment]
What format are we storing the dates in for the mods? I'm getting a full time string from the images like down the second but I think before they were just saving the month-day-year?

**Comment by PatrickYott** [comment]
ISO Date — YYYY-MM-DD

p
Patrick Yott
Associate Dean for Digital Strategies and Services
Northeastern University Libraries
360 Huntington Ave, SL 327
Boston, MA 02117
p.yott@neu.edu
617.373.4194
617.373.5409 (fax)


From: Eli Zoller
Reply-To: NEU-Libraries/cerberus
Date: Friday, May 8, 2015 at 9:54 AM
To: NEU-Libraries/cerberus
Cc: Patrick Yott
Subject: Re: [cerberus] Photograph Loader (#592)


What format are we storing the dates in for the mods? I'm getting a full time string from the images like down the second but I think before they were just saving the month-day-year?

**Comment by elizoller** [comment]
Thanks!

**Comment by dgcliff** [comment]
I think this can be closed now.
