### ISSUE TITLE
Odd Blacklight Behavior when asking for 100 items at the end of a list of 93 items

### ISSUE THREAD

**Issue by PatrickYott** [NEU-Libraries/cerberus#611]
When I was browsing around the other day, I looped through the list of communities (93 in total) 10 at a time.  When I got to the last page, I asked it to show 100 items at a time, thinking it would give me all 93 in one screen, but it did something funky, and tried to display from item 901..

![error](https://cloud.githubusercontent.com/assets/4604086/5172296/9873fae4-73ec-11e4-972f-7c547e611977.jpg)

**Comment by sarahjeansweeney** [comment]
This happened today during the usability session. The user performed a search, then clicked "Last" to go to the last page, then used the Creator facet to limit by creator name:

<img width="1008" alt="2015-10-20_1622" src="https://cloud.githubusercontent.com/assets/4663073/10620483/5049730a-7749-11e5-9fb6-ce3b2345d3db.png">

**Comment by dgcliff** [comment]
This is the same old bug with Blacklight that they've solved upstream, and the backport hasn't worked properly. Not sure how much it's worth trying to fix with our older version.
