### ISSUE TITLE
Assigning upload privileges from the admin page

### ISSUE THREAD

**Issue by sarahjeansweeney** [NEU-Libraries/cerberus#612]
I'd like to be able to give upload privileges to a staff user from the admin/employees page (I'll also need to see the full list of faculty and staff on admin/employees, not just faculty with an employee page).

**Comment by elizoller** [comment]
I'm starting to work on this functionality and noticed the ticket is a bit old so I just wanted to verify what you're looking for. Currently, as you describe, the admin/employees page lists the employees. You want that page to list all the users and then have some sort of identifier that says if they're an employee and if they aren't then have a button or checkbox or something to make them an employee (giving them upload privileges)?

**Comment by sarahjeansweeney** [comment]
Actually, I haven't needed to give staff upload privileges to staff like I thought I would. We can close it.

**Comment by elizoller** [comment]
Ok. Thanks.
