### ISSUE TITLE
XML Editor save changes clarification

### ISSUE THREAD

**Issue by dgcliff** [NEU-Libraries/cerberus#629]
Sarah asked for some language on the XML Editor screen so that people know that until they hit "Save" they're work is not complete.

**Comment by elizoller** [comment]
@sarahjeansweeney where do you want the message?
Towards the top of the page? 
![screen shot 2015-01-21 at 8 16 56 am](https://cloud.githubusercontent.com/assets/5439169/5836638/fe3314b0-a145-11e4-9964-8067f2936c03.png)
or Down near the save/validate buttons?
![screen shot 2015-01-21 at 8 17 36 am](https://cloud.githubusercontent.com/assets/5439169/5836639/0080be70-a146-11e4-9821-8d8d25937b26.png)

**Comment by sarahjeansweeney** [comment]
@elizoller I think top of the page is best.
Thanks, Eli!

**Comment by elizoller** [comment]
Is that language ok?

**Comment by sarahjeansweeney** [comment]
Let's change it to:
This is just a preview. Click "Save" to apply your changes.
