### ISSUE TITLE
Breadcrumb titles with sub and superscripts display the <sub> and <sup> tags

### ISSUE THREAD

**Issue by sarahjeansweeney** [NEU-Libraries/cerberus#632]
Breadcrumb titles with sub and superscripts display the ```<sub>``` and ```<sup>``` tags:
![2015-01-16_0912](https://cloud.githubusercontent.com/assets/4663073/5777358/e0eef3e0-9d5f-11e4-91ee-bd8c5155039c.png)
(https://repository.lib.neu.edu/files/neu:331699)

Only the sub or superscript values should display, and they should be rendered above or below the line.

**Comment by dgcliff** [comment]
Pretty easy fix, they're just not being run through kramdown. Should be a one line change somewhere.
