### ISSUE TITLE
"more" facet option for Featured Content contains values from outside that featured content list

### ISSUE THREAD

**Issue by sarahjeansweeney** [NEU-Libraries/cerberus#633]
For both the Theses and Dissertations and Research Publications featured content lists, the "more" facet option is retrieving more values than should be in the list. For example:
The brief list of faceted creator names in the Research Publications featured content list is Vittoria, Nath, Bansil, Widom, and Vespignani. When I click "more Creators", other names from outside the Research Publications scope are listed, like Brooks Canaday from MarComm and the Chinese Progressive Association from Archives.

(This is very similar to issue #578)

**Comment by dgcliff** [comment]
Bleck. Ok, will look into it.

**Comment by dgcliff** [comment]
Not sure what to do with this. Pat is loading things without telling me, and for at least Research Publications there are now 1202 items, so not that short list your provided.

Going to close until Pat has an explanation for what he is doing.

**Comment by sarahjeansweeney** [comment]
Okay, so Research Publications is a bad example while he's actively loading, but this still applies to the ETDs:
The brief creator facet list is Gould, Ahern, Amiji, Ewell, and Jones:

![2015-01-16_1131](https://cloud.githubusercontent.com/assets/4663073/5779790/9f7bc820-9d73-11e4-8323-60eb80753464.png)
The full list includes more than just the ETD creator values, like Brooks and the Chinese Progressive Association:

![2015-01-16_1133](https://cloud.githubusercontent.com/assets/4663073/5779801/d4b75838-9d73-11e4-8d12-d3789885fedd.png)
