### ISSUE TITLE
Creating a new collection generated multiple collections

### ISSUE THREAD

**Issue by sarahjeansweeney** [NEU-Libraries/cerberus#634]
When Zohreh Firouzabadia (https://repository.lib.neu.edu/employees/neu:5m60qz551) created a new collection (https://repository.lib.neu.edu/collections/neu:rx913q03c), four collections were generated: https://repository.lib.neu.edu/collections/neu:rx913q01t

![2015-01-20_1158](https://cloud.githubusercontent.com/assets/4663073/5821648/b30766c6-a09b-11e4-93bb-96650b284ca8.png)

She reported this to me after the fact (this happened way back on January 9) and I haven't been able to replicate it.

**Comment by dgcliff** [comment]
So, the common convention seems to be use disable_with (which is javascript). I think coupling this with rejecting it on the back-end is the solution (by including unique id's generated for each form).

How bizarre.

**Comment by dgcliff** [comment]
This can be closed with eli's fix I think. I'll be doubling down on this at a later date with back-end code, but I'll make a separate ticket for that.

**Comment by sarahjeansweeney** [comment]
Surprisingly, this seems to be happening again! Drew just created a new "Legacy records" collection here: http://hdl.handle.net/2047/D20326841

She moved through the collection creation process and two collections were created:
<img width="1513" alt="Screenshot 2023-04-07 at 12 19 33 PM" src="https://user-images.githubusercontent.com/4663073/230642775-e4799635-f2b8-4aaa-884e-b60aedfeb831.png">

I remembered this ticket from ages ago and tried to replicate the duplication by creating a new "test" collection and double clicking the submit button here: https://repository.library.northeastern.edu/collections/neu:h989rv30w

Double clicking did create two new "test" collections:
<img width="1513" alt="Screenshot 2023-04-07 at 12 21 41 PM" src="https://user-images.githubusercontent.com/4663073/230642923-3a7bf508-bc0a-43a2-8d0f-b3a2902a6a99.png">

I also created a new collection by single clicking the submit button here: https://repository.library.northeastern.edu/collections/neu:h989rv358

This created a single collection, as expected.

**Comment by dgcliff** [comment]
Looking through the code, I re-broke this adding in the modal that informs users about how many files affected when they privatize collections, back in 2017 - https://github.com/NEU-Libraries/cerberus/commit/584e1b66f9c275fd4cd509887e7d335916c23b73

I'll look at making a patch

**Comment by dgcliff** [comment]
Should be fixed with c543e12 - will deploy and test tonight

**Comment by dgcliff** [comment]
Having done some testing, this appears it can be closed again
