### ISSUE TITLE
Pagination doesn't work for items sorted by date

### ISSUE THREAD

**Issue by sarahjeansweeney** [NEU-Libraries/cerberus#635]
From Brooks: "It occurred when I was searching through a single collection (campus) as well as the entire MarCom community. Just now I went into the alumni collection and was able to navigate between pages, but as soon as I sorted by date created it was stuck on the first page, so I imagine that’s where the issue lies."

This may just affect communities or collections.

**Comment by dgcliff** [comment]
This is related to the fix for #611 - looking into a workaround
