### ISSUE TITLE
Facet titles cover numbers

### ISSUE THREAD

**Issue by elizoller** [NEU-Libraries/cerberus#638]
![screen shot 2015-01-21 at 3 54 48 pm](https://cloud.githubusercontent.com/assets/5439169/5844926/db443af2-a185-11e4-9ec2-016589bb8df1.png)

**Comment by dgcliff** [comment]
Great - does that mean this can be closed then?

**Comment by elizoller** [comment]
I think I've got it right, I just want to test one more thing. Is there a way I can get department to show up as a facet in the local environmental?

**Comment by dgcliff** [comment]
Yeah, I think if you do a search for a community by name, you should be able to facet by that value

**Comment by sarahjeansweeney** [comment]
The values for the department facet come from the scholarly object metadata extension, so if the test records in the local environment don't have that, you won't be able to limit by department. To get one to show up you should just be able to add this to a MODS test record:
```
<mods:extension>
      <scholarly_object>
         <category>Theses and Dissertations</category>
         <department>Department of Communication Studies</department>
         <degree>M.A.</degree>
      </scholarly_object>
   </mods:extension>
```
