### ISSUE TITLE
Clicking on a research pub folder does nothing

### ISSUE THREAD

**Issue by sarahjeansweeney** [NEU-Libraries/cerberus#640]
Clicking on a faculty member's research pubs collection does nothing, just adds "research" to the facets/URL. Here's how to replicate:

From the homepage:
Click "Communities"
Click any community (Dept. of English)
Search at the community level ("language")
Limit by creator name
Click Research Publications for the creator
![2015-01-23_1600](https://cloud.githubusercontent.com/assets/4663073/5883162/e7d3f912-a31d-11e4-9456-5e7d90d27368.png)

(I'll put in more info on Monday, or as needed).

**Comment by dgcliff** [comment]
Yeah, this was a bad url construction at  https://github.com/NEU-Libraries/cerberus/blob/develop/app/views/shared/drs_item/_drs_item_smart_collection.haml#L2

Simple fix, should have it up soon.
