### ISSUE TITLE
Facet sort error

### ISSUE THREAD

**Issue by sarahjeansweeney** [NEU-Libraries/cerberus#641]
I encountered this error when I attempted to sort facet values alphabetically:

![2015-01-28_1605](https://cloud.githubusercontent.com/assets/4663073/5946963/9e8b37be-a707-11e4-84ad-b5c9523495f6.png)

Steps to replicate:

From the homepage I:
Clicked on Research Publications
Clicked "more Creators" from the Creator facet
Clicked "A-Z" in the full facet list of creators

This also happens when I click "Next" to see the second page of values.

**Comment by dgcliff** [comment]
3906f56 actually fixed a similar but different bug. Reopened, but should be easy to fix.
