### ISSUE TITLE
Research Publications search returns all research pubs

### ISSUE THREAD

**Issue by sarahjeansweeney** [NEU-Libraries/cerberus#642]
All of the research publications for a community are returned when I search a community's Research Publications folder, not just the items that should match my search.

Steps to replicate:
* Go to the Research Publications folder for the School of Law (https://repository.lib.neu.edu/communities/neu:417/research)
* Notice there are 43 items
* Search for anything (policy, biology, turnips) and you'll get the same 43 results.

Two other things I noticed, which may be other issues or intentional, I'm not sure:
* The Research Publications folders don't seem to have a Facet list, just the Sort By/Show options.
* After I execute the search, my search term (which I entered in the featured content search box) is also now in the default DRS search box.

![2015-01-28_1647](https://cloud.githubusercontent.com/assets/4663073/5947719/6bce2812-a70d-11e4-8362-3d740249012d.png)

**Comment by dgcliff** [comment]
Tried turnips, got the same result. (That's going to be my default search from now on :P) Will look into it.
