### ISSUE TITLE
Display for Associated Files

### ISSUE THREAD

**Issue by sarahjeansweeney** [NEU-Libraries/cerberus#645]
Now that Patrick has started ingesting associated files, we need to establish how those files are displayed to users:

- [ ] Associated and parent files should have a bidirectional tab to connect them
- [ ] The tab title should be "Supplemental Files"
- [ ] ~~Associated files shouldn't be discoverable in search~~

We also should discuss in our next meeting what happens when users try to access the associated file's core file

**Comment by sarahjeansweeney** [comment]
Instead of using "Supplemental Files" for the tab title, can we use the MODS title for that record?

**Comment by dgcliff** [comment]
@sarahjeansweeney  How does that work if there are multiple supplemental files? I figured it'd be one tab, with a corresponding list, not one tab per associated file

**Comment by sarahjeansweeney** [comment]
@dgcliff I not sure if we specifically talked about one tab vs. multiple tabs, but one tab for all files is certainly better than one tab for each file.
So how will that work when someone discovers an associated file through a search? Will they be taken to the core file for that file or the supplemental tab file list?

**Comment by dgcliff** [comment]
Hmm. I'll have a think - what was the pid/title for the one that's in the at the moment? I know it had "persist" or something

**Comment by sarahjeansweeney** [comment]
Parent file: https://repository.library.northeastern.edu/files/neu:603
Supplemental file: https://repository.library.northeastern.edu/files/neu:334062

**Comment by dgcliff** [comment]
Excellent, thanks

**Comment by dgcliff** [comment]
:thumbsup:

**Comment by dgcliff** [comment]
I'll deploy at 5sh to make sure I don't clash with Pat's work
