### ISSUE TITLE
Date facet sort should be chronological

### ISSUE THREAD

**Issue by sarahjeansweeney** [NEU-Libraries/cerberus#647]
If possible, the default date sort for the year facet (both the menu facet and the modal) should be chronological, not by quantity of results. 

![2015-02-06_1611](https://cloud.githubusercontent.com/assets/4663073/6087768/74fa4fb2-ae1d-11e4-9000-06293317b451.png)

**Comment by dgcliff** [comment]
Invert for newset -> oldest on the submenu
Look into if "more Years" can default to A-Z sort
