### ISSUE TITLE
Stats page for the admin

### ISSUE THREAD

**Issue by dgcliff** [NEU-Libraries/cerberus#649]
For now, a section listing numbers for things (Communities, Collections, Core Files, Employees and Users). Will take numbers from Solr. We can expand on it later - off the top of my head, listing the count of validated files would be nice, so we can keep an eye on the delta.

**Comment by dgcliff** [comment]
@elizoller hey eli, going to have a crack at this this morning - I'll commit to the same admin styling branch if that's cool?

**Comment by elizoller** [comment]
Sounds good

**Comment by dgcliff** [comment]
@eli pushed up to admin styling branch

**Comment by elizoller** [comment]
Are there thoughts in terms of how you guys want the data on the page?
I started with a table. Do you want to separate out the file types?

![screen shot 2015-02-24 at 2 48 08 pm](https://cloud.githubusercontent.com/assets/5439169/6357696/4f58ab62-bc34-11e4-82ca-324f6481b3ad.png)

**Comment by dgcliff** [comment]
Don't mind - @sarahjeansweeney ?

**Comment by elizoller** [comment]
Also going to see if we can order the file types most to least.

**Comment by sarahjeansweeney** [comment]
Looks good to me. Can we add the number of people, too?

**Comment by dgcliff** [comment]
Sure - we should add Users and Employees as seperate values, given that they aren't 1:1 anymore

**Comment by elizoller** [comment]
@dgcliff not sure how to do users though

**Comment by dgcliff** [comment]
No worries, I'll patch it in now

**Comment by elizoller** [comment]
![screen shot 2015-02-25 at 10 43 32 am](https://cloud.githubusercontent.com/assets/5439169/6373913/94deb666-bcdb-11e4-8ef3-1d73f385eee7.png)
I linked back to the admin pages for communities and employees- will that be helpful?

**Comment by sarahjeansweeney** [comment]
Yeah, links to the admin pages is definitely helpful.

**Comment by sarahjeansweeney** [comment]
Is it possible to have two sets of statistics for core files, one for all core files and one for public core files?

**Comment by dgcliff** [comment]
I think we can break it down like that with the existing Solr information
