### ISSUE TITLE
Pagination on the admin pages

### ISSUE THREAD

**Issue by elizoller** [NEU-Libraries/cerberus#653]
Using Blacklight to add pagination to the admin pages. Starting with 5430d2f6d374cba4db535949251eccb5d9bca2a8 
![screen shot 2015-02-24 at 7 44 05 am](https://cloud.githubusercontent.com/assets/5439169/6349494/f7ac6416-bbf8-11e4-9727-21491bc1ccf4.png)

This by default should sort the employees and communities into alpha by name also.

**Comment by elizoller** [comment]
@dgcliff can you remind me how to add employees via console so I can test locally? Thanks!

**Comment by dgcliff** [comment]
Cerberus::Application::Queue.push(EmployeeCreateJob.new("nuidhere", "Joe Blow"))

**Comment by dgcliff** [comment]
In the rails console

**Comment by elizoller** [comment]
Thanks!
