### ISSUE TITLE
My Communities to My DRS page

### ISSUE THREAD

**Issue by elizoller** [NEU-Libraries/cerberus#656]
Add a tab for My Communities on the My DRS Page
![screen shot 2015-02-24 at 8 09 41 am](https://cloud.githubusercontent.com/assets/5439169/6349844/84ab325e-bbfc-11e4-9974-7b664aa24652.png)

The view will contain a list of the communities the user belongs to.

**Comment by elizoller** [comment]
What do you want this page to look like?
Right now I just have a basic table. Do you want it like the my deposits page with the grid/list view?

**Comment by sarahjeansweeney** [comment]
I think the grid/list view like the My Deposits page would be great!

**Comment by elizoller** [comment]
Ok thanks!
