### ISSUE TITLE
Grouper id to admin/employees page communities list

### ISSUE THREAD

**Issue by elizoller** [NEU-Libraries/cerberus#658]
Add grouper id (ie. neu:drs:staff) to admin/employees page communities list
![screen shot 2015-02-24 at 8 12 17 am](https://cloud.githubusercontent.com/assets/5439169/6350049/53c04cfe-bbfe-11e4-93b8-b932dd66e270.png)

@sarahjeansweeney is that the right place?

**Comment by sarahjeansweeney** [comment]
Yes, the page is correct, but the grouper groups should be listed separately from the communities.

I vaguely remember a meeting not too long ago where we discussed adding the grouper groups to the admin page, and @dgcliff said it couldn't/shouldn't be done. Has something changed?

**Comment by elizoller** [comment]
I might not have explained it correctly.

**Comment by dgcliff** [comment]
Yeah, I'm vaguely recalling this conversation from a while back. I think we tabled it, just because grouper information is always going to be stale unless it directly comes from grouper itself.
