### ISSUE TITLE
Lowercase t in title for a user submitted item

### ISSUE THREAD

**Issue by PatrickYott** [NEU-Libraries/cerberus#662]
As discussed, this may be a historical relic, but the paper deposited by Denis Erdogmus, listed in thi search (https://repository.lib.neu.edu/?f%5Bcreator_sim%5D%5B%5D=Erdogmus%2C+Deniz&q=erdogmus&utf8=%E2%9C%93) - click on facet by type - and found at https://repository.lib.neu.edu/files/neu:rx913q26p has a lowercase t in its type value.  Should be an uppercase T

**Comment by dgcliff** [comment]
Ok, theres a capitalization fix that needs to go into cerberus code, plus some re-indexing, but the latter we'll be doing anyway after this weekends metadata batch fix

**Comment by dgcliff** [comment]
Sarah had a chat with Dan, and we cleared up some expectations. Currently Cerberus makes these fields lowercase. This will be changed to uppercase. There will be some very minor metadata cleanup for some already in the system.

**Comment by PatrickYott** [comment]
cool
Patrick Yott
Associate Dean for Digital Strategies and Services
Northeastern University Libraries
360 Huntington Ave, SL 327
Boston, MA 02115
401.338.3787
p.yott@neu.edu
