### ISSUE TITLE
New icon for zip files

### ISSUE THREAD

**Issue by sarahjeansweeney** [NEU-Libraries/cerberus#664]
Zip files should have their own icon. This one looks good: http://fortawesome.github.io/Font-Awesome/icon/file-archive-o

**Comment by dgcliff** [comment]
@elizoller I can leave this one alone right - you had a patch for the core_file model that allowed for a .zip? method, and an update to _media_display.haml partial? No rush, just didn't want to duplicate work

**Comment by elizoller** [comment]
I'll show you what I have. I think I only have part of it.

**Comment by elizoller** [comment]
I tried to create a zip file locally to test but it is giving me an error message: "[{"error":"Error occurred while creating core file."}]"

**Comment by dgcliff** [comment]
Eli's fixed this with aa061d5
