### ISSUE TITLE
Allow Solr to search for literal mods:subTitle interpretation (deal with the ":" char)

### ISSUE THREAD

**Issue by sarahjeansweeney** [NEU-Libraries/cerberus#667]
I don't think MODS subtitles are being indexed. Here are a few sample searches that bring up 0 results:
* Argentine intellectuals as harbingers of modernity : the democratization projects of Marcos Aguinis (https://repository.lib.neu.edu/files/neu:1469)
* Gay rights and lefts : rights critique and distributive analysis for real law reform (https://repository.lib.neu.edu/files/neu:332902)

Remove the subtitle, and the search is successful.

**Comment by dgcliff** [comment]
Definitely getting indexed - I think the : is what's messing up the query

http://solr.lib.neu.edu:8080/solr/development/select?q=id%3A%22neu%3A1469%22&wt=ruby&indent=true

**Comment by dgcliff** [comment]
I'm making this a bug, just because it's somewhat unexpected behavior when you have so many correct search terms, and it comes up with nothing. I'll look into what we can do with the query parser to be more resilient.

**Comment by dgcliff** [comment]
Actually, an enhancement. Because, technically, there is no ":" character stored in MODS, and Solr is doing the right thing. The ":" is introduced in the MODS display for convenience.

**Comment by dgcliff** [comment]
Open it up to OR search if there are no results (make the user click a link). This so that the user has a next step, and doesn't have to figure out what they misspelled, or errant characters like ":" etc.

**Comment by dgcliff** [comment]
We will attempt to refine this so it's not quite and either/or situation.
