### ISSUE TITLE
My DRS User Created Collection sort order

### ISSUE THREAD

**Issue by sarahjeansweeney** [NEU-Libraries/cerberus#670]
Can the personal collections sort alphabetically? Right now they seem to sort by the last time they were edited, with the most recent on the bottom.

![2015-02-27_1111](https://cloud.githubusercontent.com/assets/4663073/6416116/b7a3aaf2-be71-11e4-851e-9046742a133f.png)

**Comment by elizoller** [comment]
Do you want this on smart collections here too?

**Comment by sarahjeansweeney** [comment]
No, Smart Collections should stay in that prescribed order.

**Comment by elizoller** [comment]
Ok thanks
