### ISSUE TITLE
Sort order for Sets

### ISSUE THREAD

**Issue by sarahjeansweeney** [NEU-Libraries/cerberus#674]
Another alphabetical sort request:
Can the Sets lists be alphabetical, too? There are two lists for Sets (that I can think of):
The Sets page:
![2015-03-04_1614](https://cloud.githubusercontent.com/assets/4663073/6493603/c1dad9fc-c289-11e4-9122-5d2351116dc7.png)

And from the Save for Later button menu (the button looks great, btw)
![2015-03-04_1615](https://cloud.githubusercontent.com/assets/4663073/6493609/c6ce6e74-c289-11e4-9ad6-e1bb33611e0a.png)

(Please ignore my messy Sets...)

**Comment by elizoller** [comment]
@sarahjeansweeney and maybe we can clean up that add to your sets modal some?

**Comment by sarahjeansweeney** [comment]
Absolutely. Do you want me to start a new ticket with some suggestions?

**Comment by elizoller** [comment]
Sounds good to me. Thanks!
