### ISSUE TITLE
Faculty Communities NoMethodError

### ISSUE THREAD

**Issue by sarahjeansweeney** [NEU-Libraries/cerberus#676]
I encountered this error when I clicked the "My Communities" tab in Roger Abram's file list page:
![2015-03-05_1053](https://cloud.githubusercontent.com/assets/4663073/6508333/30fc108e-c326-11e4-8c3e-1ab278db25f7.png)

Steps to replicate:
Navigate to any faculty page (https://repository.library.northeastern.edu/employees/neu:29118)
Click his or her files tab ("Roger I. Abrams's files")
Click the My Communities tab

**Comment by elizoller** [comment]
Do you want to be able to access the communities through this way? If so, should this be an admin only thing?

**Comment by dgcliff** [comment]
Well there's a separate problem first - it's not "My Communities" if I'm on someone else page. Secondly, it's internally inconsistent in that it's on the "Roger I. Abrams's files" page, and not their first page.

If we do want that link when it's not one's own section, it'll have to take their name, and be on both.

**Comment by elizoller** [comment]
I should be able to fix it like the way "[Name] Collections" Vs. "My Collections" works

**Comment by dgcliff** [comment]
Sounds good.
