### ISSUE TITLE
Extension missing from downloads in Chrome

### ISSUE THREAD

**Issue by sarahjeansweeney** [NEU-Libraries/cerberus#680]
In Chrome, when I click on an image to download a file (any file - .jpg, .pdf) and select Save Image As, the file extension is missing from the filename:
![2015-03-09_1344](https://cloud.githubusercontent.com/assets/4663073/6560956/2a2ed2c8-c664-11e4-85d4-520c977a31d9.png)
Firefox and Safari don't have this problem

**Comment by dgcliff** [comment]
Thanks Sarah

**Comment by elizoller** [comment]
@dgcliff Is there a way to know what Content-type header is being passed back with the image? I don't see it when I inspect the source. I'm reading around that this is a known issue for Chrome when the source does not contain a file extension but that some people have fixed it by including the content-type header.

**Comment by dgcliff** [comment]
I think I have a fix for this, stay tuned

**Comment by dgcliff** [comment]
Ok, I think we can fix this with a url change for downloads

https://repository.lib.neu.edu/downloads/neu:37068?datastream_id=content <- doesn't work
http://nb4676.neu.edu:8080/fedora/objects/neu:37068/datastreams/content/content <- does work

**Comment by dgcliff** [comment]
Obviously we don't point the user at nb4676, but there must be something being lost in translation between servers

**Comment by dgcliff** [comment]
@elizoller I think we can put in a header fix by overriding something in here, which we include in our downloads controller

https://github.com/projecthydra/hydra-head/blob/6-4-stable/hydra-core/app/controllers/concerns/hydra/controller/download_behavior.rb

**Comment by dgcliff** [comment]
@elizoller Except I do get the mime type with curl?

curl -s -D - "https://repository.lib.neu.edu/downloads/neu:37068?datastream_id=content" -o /dev/null

```
HTTP/1.1 200 OK
Date: Tue, 10 Mar 2015 15:04:20 GMT
Server: Apache/2.2.15 (Red Hat)
Accept-Ranges: bytes
Content-Disposition: inline; filename="High Resolution Image for neu:37065"
Content-Transfer-Encoding: binary
Cache-Control: private
X-UA-Compatible: IE=Edge
ETag: "97ad744c56906c5479444d0d0a111c07"
X-Request-Id: 0feba4446930a006ed4fac99522b735d
X-Runtime: 0.110589
X-Rack-Cache: miss
X-Powered-By: Phusion Passenger 4.0.45
Status: 200 OK
Cache-Control: max-age=315360000
Expires: Fri, 07 Mar 2025 15:04:20 GMT
Connection: close
Transfer-Encoding: chunked
Content-Type: image/jpeg
```

**Comment by dgcliff** [comment]
Ok - simple fix, the hydra code allows for a filename parameter

https://repository.lib.neu.edu/downloads/neu:37068?datastream_id=content&filename=derp.jpg

**Comment by elizoller** [comment]
Nice! Yay!
