### ISSUE TITLE
A/V error in Firefox

### ISSUE THREAD

**Issue by sarahjeansweeney** [NEU-Libraries/cerberus#684]
For some reason I see this error when I try to play any of David's sample files in Firefox:

![2015-03-13_1200](https://cloud.githubusercontent.com/assets/4663073/6642128/b0489882-c978-11e4-8354-bbb5e0de8687.png)

They all work just fine Chrome and Safari. Admittedly, I rarely use Firefox, so it's possible it's just me.

**Comment by elizoller** [comment]
What version of Firefox are you using?

**Comment by sarahjeansweeney** [comment]
Version 36.0.1

**Comment by elizoller** [comment]
Are the other test files working at all?

**Comment by dgcliff** [comment]
That particular file never worked - Pat asked if it worked with MOV files, the answer is, "it depends"

This file doesn't. The converted version does.

**Comment by sarahjeansweeney** [comment]
@dgcliff Alright, so that file is a bad example. Which of your test files can I use as a better example?

@elizoller No, the other test files aren't working either, although now the error message is much more friendly.

**Comment by elizoller** [comment]
Did you do a hard refresh Cmd + Shift + R in Firefox?
mov: https://repository.library.northeastern.edu/files/neu:rx913r28f
mp4: https://repository.library.northeastern.edu/files/neu:rx913r15c
mp3: https://repository.library.northeastern.edu/files/neu:rx913r19g

I am still working on error messages some as well as Android.

**Comment by sarahjeansweeney** [comment]
I just did a hard refresh and I still see an error message for each of those files: "There was an error playing this file. Please try on a different device or download the file."

**Comment by elizoller** [comment]
Do you have flash enabled/installed for firefox?

**Comment by sarahjeansweeney** [comment]
It was installed but not enabled. I enabled it and they're all working now. Thanks, Eli!

**Comment by dgcliff** [comment]
Good to know - @elizoller maybe we can put in a notice informing people that flash has to be installed/working - I think theres some standard javascript that can detect this?

**Comment by elizoller** [comment]
I will look into it. Thanks

**Comment by elizoller** [comment]
Added check for Flash existing with  f6f60ade5663d1a30eb428e1b5a7bf032d9a71a4
The tool to do this - swfobject was already included with sufia.js
Note though that this doesn't distinguish between the player being installed and enabled. For me Firefox gives me lots of warnings that Flash player isn't enabled when I travel to a page that has Flash embedded in it.
@dgcliff do you know of something to detect Flash specifically being enabled?

**Comment by dgcliff** [comment]
Nope, was just hoping there was a standard library for it. Never done it before myself.
