### ISSUE TITLE
Error Pages on Production

### ISSUE THREAD

**Issue by elizoller** [NEU-Libraries/cerberus#685]
![screen shot 2015-03-13 at 2 19 29 pm](https://cloud.githubusercontent.com/assets/5439169/6644626/fe9fc13c-c98b-11e4-8de8-2c1e9a2b2c5c.png)
Error pages need configuration now that we moved to "production"

**Comment by dgcliff** [comment]
Something that keeps the general layout, but has a nice error on it

like what you get if you go to https://repository.library.northeastern.edu/collections/neu:flibbertygibbert but maybe more attractive?

I imagine theres probably a 404 default settings somewhere that needs to change

**Comment by elizoller** [comment]
Thoughts?
![screen shot 2015-03-18 at 10 54 03 am](https://cloud.githubusercontent.com/assets/5439169/6711385/200a8828-cd5d-11e4-8ce5-324e0c35d9b0.png)

**Comment by dgcliff** [comment]
Looks good to me!

**Comment by sarahjeansweeney** [comment]
Looks great!
What is "blah" a placeholder for? The URL?

**Comment by elizoller** [comment]
Yeah , so to generate the page i had gone to /blah. It also works on urls like files/blah, communities/blah, etc.

**Comment by dgcliff** [comment]
Should be fixed with Eli's recent pull request - 808ecb5ef5d85fa2dd39a6b92aad857c3979a501
