### ISSUE TITLE
drs:northeastern:all group

### ISSUE THREAD

**Issue by PatrickYott** [NEU-Libraries/cerberus#686]
We would like to create a "fake" grouper value for anybody who has logged in via shibboleth -- they should be given drs:northeastern:all - any object that is available to anybody at Northeastern will have this value encoded in its rightsMetadata datastream.

p

**Comment by dgcliff** [comment]
n.b. This is resurrecting the notion of a "registered" user, and is distinct from a public item (which you can view it logged in or not).

**Comment by dgcliff** [comment]
Shouldn't it be northeastern:drs:all?

**Comment by sarahjeansweeney** [comment]
Yes, northeastern:drs:all is the correct value.

**Comment by PatrickYott** [comment]
Yes,  I seem to have grouper dyslexia

Patrick Yott
Associate Dean for Digital Strategies and Services
Northeastern University Libraries
360 Huntington Ave, SL 327
Boston, MA 02117
p.yott@neu.edu
617.373.4194
617.373.5409 (fax)
