### ISSUE TITLE
My Communities error

### ISSUE THREAD

**Issue by sarahjeansweeney** [NEU-Libraries/cerberus#687]
When I click on my own "My Communities" from My DRS, I get this error:
![2015-03-16_1435](https://cloud.githubusercontent.com/assets/4663073/6673469/c28d03ac-cbe9-11e4-9153-5153644b239d.png)

I only see this on my My DRS page. When I visit another user's My Communities tab, I don't see the error.

**Comment by dgcliff** [comment]
Hm, I didn't get an email, and I can't repilcate it with my user.

**Comment by dgcliff** [comment]
Are you associated with any communities at the moment?

**Comment by sarahjeansweeney** [comment]
I am:
https://repository.library.northeastern.edu/communities/neu:5m60qz44h
https://repository.library.northeastern.edu/communities/neu:466

**Comment by dgcliff** [comment]
Hm. We also don't show error pages anymore...so you shouldn't be seeing that page, unless it was in your cache

**Comment by sarahjeansweeney** [comment]
Yup, that was it. Hard refresh and it disappeared. Thanks.
