### ISSUE TITLE
Formatting for 'Daily Featured Content Uploads and Updates' email

### ISSUE THREAD

**Issue by sarahjeansweeney** [NEU-Libraries/cerberus#691]
The information in the daily featured content emails is a bit hard to read:
![2015-03-19_0911](https://cloud.githubusercontent.com/assets/4663073/6731145/f8714826-ce18-11e4-915f-73c08e01ebdc.png)

Could the formatting be changed to clarify the collection, title, depositor, and PID information, maybe with the element name followed by a colon?:

Collection: Department of Electrical and Computer Engineering Master's Theses
Title: 0.18μm CMOS low power ADPLL with a novel local passive interpolation time-to-digital converter based on tri-state inverter User
Depositor: Temp (drsadmin@neu.edu)
PID: neu:1338

**Comment by dgcliff** [comment]
Sure

**Comment by sarahjeansweeney** [comment]
A few other changes to this notice:
 - [ ] Remove Learning Objects
 - [ ] Add Other Publications
 - [ ] Add the editor's name to the information about updated files
 - [ ] HTML...

**Comment by elizoller** [comment]
@dgcliff whats the best way to test the mailers in dev env?

**Comment by dgcliff** [comment]
Good question, not sure to be honest. I think there's a way to trigger them in rails console, I'll have a look.

**Comment by elizoller** [comment]
I tried doing MetadataMailer.daily_alert_email.deliver in the console but got an error. Probably I don't have dev setup to actually do mailing though.

**Comment by elizoller** [comment]
AH! Maybe its an issue with HAML http://guides.rubyonrails.org/v2.3.8/action_mailer_basics.html#configure-action-mailer-to-recognize-haml-templates

**Comment by dgcliff** [comment]
Nice catch, hopefully that's the issue

**Comment by elizoller** [comment]
Nevermind...doesn't exist in ActionMailer3+

**Comment by elizoller** [comment]
So the issue was actually with Outlook Desktop stripping out HTML tables. Just converted the one with a table with line breaks. Lists and paragraphs and links and such seem to work fine.

**Comment by dgcliff** [comment]
Huzzah - death to Outlook and its terrible ways

**Comment by dgcliff** [comment]
I think this is done now

**Comment by elizoller** [comment]
@dgcliff  I didn't do the Other Publications or the including the editor's name part. I tried doing the Other Publications but I think I'm missing the query somewhere along the way because it was failing. I also didn't see if we were storing the editor's info anywhere?

**Comment by dgcliff** [comment]
ah ok, I'll re-open

**Comment by elizoller** [comment]
I think the last piece (including editor info on updates) of this will require a db migrate in order to start storing the editors info?

**Comment by dgcliff** [comment]
We do a db:migrate as part of the production deploy so that should be fine

**Comment by elizoller** [comment]
Ok I'll take a stab at the last piece of this sometime soon then
