### ISSUE TITLE
500 Error When Uploading Large(ish) Video

### ISSUE THREAD

**Issue by PatrickYott** [NEU-Libraries/cerberus#692]
I just tried to load a 366 MB video file into the Library's media collection (https://repository.library.northeastern.edu/collections/neu:rx913s505), but got a 500 server error.

Do we have  a max upload size set? If so, how large can it go?

**Comment by dgcliff** [comment]
I can't see a 500 error in the logs. We don't have a max upload size that I'm aware of.

**Comment by dgcliff** [comment]
Can you remember the original filename of the file? Was it;

Digital Media Commons -  The Shape of Things to Come-JbpCUVRNYqc.mp4

?

**Comment by PatrickYott** [comment]
That was the reduced version that I was able to load.  The original file was the same name with the .mov extension.
Should I try again?
p
Patrick Yott
Associate Dean for Digital Strategies and Services
Northeastern University Libraries
360 Huntington Ave, SL 327
Boston, MA 02117
p.yott@neu.edu
617.373.4194
617.373.5409 (fax)

**Comment by dgcliff** [comment]
Sure, I guess.

**Comment by PatrickYott** [comment]
Will do.  If it loads I'll delete the lower resolution MP4 version.
p
Patrick Yott
Associate Dean for Digital Strategies and Services
Northeastern University Libraries
360 Huntington Ave, SL 327
Boston, MA 02117
p.yott@neu.edu
617.373.4194
617.373.5409 (fax)

**Comment by PatrickYott** [comment]
Same result.

p
Patrick Yott
Associate Dean for Digital Strategies and Services
Northeastern University Libraries
360 Huntington Ave, SL 327
Boston, MA 02117
p.yott@neu.edu
617.373.4194
617.373.5409 (fax)

**Comment by dgcliff** [comment]
Still nothing in the logs, and without further information, hard to determine what the issue is. I could try replicating it if you make the file available somewhere I suppose.

**Comment by dgcliff** [comment]
This is why we include screenshots!

![screenshot 2015-03-19 16 11 25](https://cloud.githubusercontent.com/assets/459084/6739933/b4211824-ce52-11e4-8fbc-10aa40d0df71.png)

It's an Apache 500, which means we need to alter the configuration to handle this arbitrarily large file.

**Comment by dgcliff** [comment]
the /tmp directory is running out of space - Ernesto is reorganizing spacing to fix the issue

**Comment by PatrickYott** [comment]
What's the reasonable size limit?  I think we will start seeing lots of video requests!

Thanks so much
P

Patrick Yott
Associate Dean for Digital Strategies and Services
Northeastern University Libraries
360 Huntington Ave, SL 327
Boston, MA 02115
617.373.4194
p.yott@neu.edu<mailto:p.yott@neu.edu>

Sent from my iPhone

On Mar 19, 2015, at 5:41 PM, David Cliff <notifications@github.com<mailto:notifications@github.com>> wrote:


Closed #692<https://github.com/NEU-Libraries/cerberus/issues/692> via 061b46c<https://github.com/NEU-Libraries/cerberus/commit/061b46cf8bc7596b0e40a0cf8d871d20bd5db63a>.

-

**Comment by dgcliff** [comment]
Hmm, not sure. Have a chat with @nestochan - the issue lies with the amount of space we can give to a /tmp or /var/tmp or similar, which is a money/ITS thing I think.

**Comment by PatrickYott** [comment]
Will do - stop working.  Good basketball on..

Patrick Yott
Associate Dean for Digital Strategies and Services
Northeastern University Libraries
360 Huntington Ave, SL 327
Boston, MA 02115
401.338.3787
p.yott@neu.edu

**Comment by elizoller** [comment]
Avalon sets their max upload size to 250MB right now. This is set in the master_file model and then checked in the create method in the controller and returns an error if over that size.
https://github.com/avalonmediasystem/avalon/search?utf8=%E2%9C%93&q=MAXIMUM_UPLOAD_SIZE

**Comment by PatrickYott** [comment]
Interesting.  I think we'll want ours larger as we are about to embark (I think) on converting some commercial VHS tapes in the collection.
p
Patrick Yott
Associate Dean for Digital Strategies and Services
Northeastern University Libraries
360 Huntington Ave, SL 327
Boston, MA 02117
p.yott@neu.edu
617.373.4194
617.373.5409 (fax)
