### ISSUE TITLE
Availability of Poster Images

### ISSUE THREAD

**Issue by PatrickYott** [NEU-Libraries/cerberus#693]
I've loaded 3 videos the the communications media collection (https://repository.library.northeastern.edu/collections/neu:rx913s505), all with their own poster file in jpg format.  If you look at the display, it seems that only one has treated the poster as a downloadable file.  It doesn't matter if its downloadable or not, but it should be consistent.

thanks
P
![videos](https://cloud.githubusercontent.com/assets/4604086/6739806/abfc7de2-ce51-11e4-8d41-ee023eecae27.jpg)

**Comment by dgcliff** [comment]
There was a bug where permissions weren't being applied to posters (the content object just wouldn't have a rightsmetadata)

I believe I have this code fixed, and will manually fix the one file I know is missing metadata, but if you see any others, let me know and I'll fix those too.

**Comment by PatrickYott** [comment]
Brilliant .  I'm going to call you "David the Closer" from now on!
Patrick Yott
Associate Dean for Digital Strategies and Services
Northeastern University Libraries
360 Huntington Ave, SL 327
Boston, MA 02117
p.yott@neu.edu
617.373.4194
617.373.5409 (fax)

**Comment by dgcliff** [comment]
I ended up just deleting neu:rx913s59n - it was broken in a very strange way

**Comment by PatrickYott** [comment]
I'll reload tomorrow to see what happens.

Patrick Yott
Associate Dean for Digital Strategies and Services
Northeastern University Libraries
360 Huntington Ave, SL 327
Boston, MA 02115
617.373.4194
p.yott@neu.edu<mailto:p.yott@neu.edu>

Sent from my iPhone

On Mar 24, 2015, at 4:59 PM, David Cliff <notifications@github.com<mailto:notifications@github.com>> wrote:


I ended up just deleting neu:rx913s59n - it was broken in a very strange way

-
