### ISSUE TITLE
Irregularity with Faculty - Department Connections

### ISSUE THREAD

**Issue by PatrickYott** [NEU-Libraries/cerberus#694]
In looking at the lists of faculty currently attached to departments, the largest number in any department is 10.  This is the case for Law.  Roger Abrams (loaded at the time all the other faculty were loaded and using the same loader) is a law faculty member, but doesn't appear in the law school faculty list.

I'm wondering if there is a hard-coded limit somewhere in the old sufia code?

![abrams](https://cloud.githubusercontent.com/assets/4604086/6740579/7776be9c-ce57-11e4-8a10-a65e7181ce8a.jpg)
![law](https://cloud.githubusercontent.com/assets/4604086/6740580/7776e462-ce57-11e4-9688-d17aa36ff132.jpg)

**Comment by dgcliff** [comment]
Yeah, 10 is the default Solr limit. We just need to adjust what the query is doing.

**Comment by PatrickYott** [comment]
Of course! I knew that.   Not sure why that escaped me.  I hate that limit...

Patrick Yott
Associate Dean for Digital Strategies and Services
Northeastern University Libraries
360 Huntington Ave, SL 327
Boston, MA 02117
p.yott@neu.edu
617.373.4194
617.373.5409 (fax)

**Comment by elizoller** [comment]
@dgcliff I went to convert the remaining methods in the communities controller (for research publications, presentations, etc) but they rely on some additional functions in the solr_queries that the find_employees didn't rely on. They're methods for find_all_files_by_type, find_smart_collections_by_type, and find_user_root_collections [(lines 94-122)](https://github.com/NEU-Libraries/cerberus/blob/develop/lib/cerberus/solr_queries.rb#L94). And those methods still rely on SolrService - is that ok for those functions? Or do they need to be converted too?

**Comment by dgcliff** [comment]
Hm, hold off then, when I'm next in we'll look at the best solution.

**Comment by elizoller** [comment]
Ok Sounds good
