### ISSUE TITLE
Notice for items removed from set

### ISSUE THREAD

**Issue by sarahjeansweeney** [NEU-Libraries/cerberus#696]
I happened to add the wonky video referenced in #693 to a Set. Since it was removed yesterday, I received this notice:

![2015-03-25_0938](https://cloud.githubusercontent.com/assets/4663073/6825863/dd3d99c8-d2d3-11e4-82b1-2fe45fa1f634.png)

This notice is great, but can the PID be replaced by the title with the PID in parentheses?:

"The following items no longer exist in the repository and have been removed from your set: Wonky DMC Video (neu:rx913s59n)"

**Comment by dgcliff** [comment]
Mmm, I'm not sure that's possible. Because it's removed, theres no title to be retrieved. But I agree the pid is jarring. Would a generic "A file in your set has been removed" etc. be better?

**Comment by sarahjeansweeney** [comment]
Sure, a generic note for truly deleted objects makes sense. 
In the future most objects won't be deleted, they'll be tombstoned. Could the Title (PID) format be applied for tombstoned records?

**Comment by dgcliff** [comment]
Sure

**Comment by elizoller** [comment]
Looking at this ticket again - Sets and Download Cart look for deleted items by checking for pids that doesn't exist but this doesn't check for tombstoned items because they technically still "exist". So there would be two scenarios - one for truly deleted items which we can't retrieve the title for and one for tombstoned items which we can retrieve the title for. Should it be one message? multiple messages?

**Comment by dgcliff** [comment]
I think the exiting setup can be left for truly deleted, with tombstoned showing the newer language

**Comment by elizoller** [comment]
I was thinking about the scenario where a set/download cart has truly deleted items and tombstoned items

**Comment by sarahjeansweeney** [comment]
Eli and I talked about this a little bit, and we decided it's better to start simple and just have one message for all items, deleted and tombstoned:

[x] files have been removed from the DRS and are no longer available in this Set."

If there's demand for more specific information about what files have been removed, we can add that later.

**Comment by sarahjeansweeney** [comment]
[x] being the number of files removed, not a PID or title.

**Comment by dgcliff** [comment]
ok, sounds good

**Comment by elizoller** [comment]
We want this message in the download carts and sets, right?

**Comment by sarahjeansweeney** [comment]
Definitely for Sets, and I suppose it's good to have this in the download queue, too. I'm tempted to say it's unlikely anyone would encounter a deleted file in an ephemeral download queue, but that we know that kind of logic doesn't really work.

**Comment by elizoller** [comment]
Logic is in place right now for deleted objects in download cards but doesn't account for tombstoned objects (like sets). I will update them both so they do the same thing.
