### ISSUE TITLE
Long Set Titles push content outside of container

### ISSUE THREAD

**Issue by elizoller** [NEU-Libraries/cerberus#697]
![screen shot 2015-03-26 at 7 53 14 am](https://cloud.githubusercontent.com/assets/5439169/6845660/41ae2eb8-d38d-11e4-9365-96a0f8078fb7.png)
Noticed this during the presentation at all staff yesterday because the screen resolution was all wonky and Sarah uses sets like we would expect a user to so we should accommodate for longer names + descriptions. We may want to consider even not showing the description at that tile view?

**Comment by sarahjeansweeney** [comment]
Not showing the description at the tile view makes a lot of sense. I've noticed some people are unsure where to click to open the set, so removing the description may help there. Maybe giving the text a little more weight might help, too?

**Comment by elizoller** [comment]
They're set on a ultra light font weight right now so I'll up that to regular.
I do get what you're saying though - since the Create a new set block is one giant link and it does the hover color change, it makes it clear that it's a button but on the existing sets, it isn't obvious that the title is the link to view the set itself and there isn't a view icon/button in the button set. 
What would you think about making it like the item blocks and the create a set button where the whole thing is a link to view the set?

**Comment by sarahjeansweeney** [comment]
Sounds good to me!
