### ISSUE TITLE
Inconsistent display of changes made to metadata through the Edit form

### ISSUE THREAD

**Issue by sarahjeansweeney** [NEU-Libraries/cerberus#699]
There's some inconsistent behavior for metadata display when changes are made through the edit form. 
For example, when a title is edited using the Edit tab the page title updates but the MODS display stays the same. I changed the title in this record https://repository.library.northeastern.edu/files/neu:rx913q47f from "Digital Scholarship Group Quick Facts Sheet" to "DSG Quick Facts Sheet":

![2015-04-06_1049](https://cloud.githubusercontent.com/assets/4663073/7006233/90d178c4-dc4d-11e4-82d7-675bfee66ea7.png)

I tried reloading the page and a hard refresh, and I also viewed the page in another browser. The MODS display section still showed the "Digital Scholarship Group Quick Facts Sheet" title, but it was correct everywhere else (the page title, the breadcrumbs, the Edit tab, and the XML editor).

I edited the record using the Edit tab again to test another field, and when I saved those changes the record did display the updated information, which you can see if you visit the record now.

**Comment by dgcliff** [comment]
I think this is a caching issue - will look into how we're invalidating, and shall fix it. Should be simple enough.

**Comment by sarahjeansweeney** [comment]
It looks like this is happening again. Hillary fixed the subjects in this record (combined the numbers to create a single "2.4.6.-trichlorophenol" heading), but the changes aren't reflected in the MODS display:
![2015-05-06_1701](https://cloud.githubusercontent.com/assets/4663073/7503557/c816639a-f411-11e4-9aeb-cfd2e80fc18f.png)

![2015-05-06_1702](https://cloud.githubusercontent.com/assets/4663073/7503558/cbea4a86-f411-11e4-83ff-14db67709a1a.png)

**Comment by elizoller** [comment]
Do you have the pid? Thanks

**Comment by sarahjeansweeney** [comment]
https://repository.library.northeastern.edu/files/neu:329995

**Comment by dgcliff** [comment]
It looks fine from here

**Comment by dgcliff** [comment]
I think you just need to refresh the page?

**Comment by sarahjeansweeney** [comment]
Yes, it does look fine now. Yesterday when she and I both refreshed the page (regular and hard refresh) and tried different browsers and the edits weren't reflected.

**Comment by dgcliff** [comment]
Next time it happens, let me know as soon as you can. If we can get this to be reproducible, there'll be something I can dig into.

**Comment by dgcliff** [comment]
I might trial implementing this - http://stackoverflow.com/questions/711418/how-to-prevent-browser-page-caching-in-rails on staging, and see what kind of performance hit we take
