### ISSUE TITLE
Missing space in Add to Set modal

### ISSUE THREAD

**Issue by sarahjeansweeney** [NEU-Libraries/cerberus#700]
When I add an item to an existing Set, the Set title text changes to "Remove from [Set Title]", but there's a space missing between "Remove from" and the Set title:
![2015-04-05_1827](https://cloud.githubusercontent.com/assets/4663073/7006351/7071342e-dc4e-11e4-847a-7b287c09d466.png)
This only appears to be true for newly added items. If I click "Save for later" again, the text is properly formatted with a space

**Comment by elizoller** [comment]
fixed with ece16410bcc79566b4ea6d52cfbac63c8720018f
