### ISSUE TITLE
Missing upload?

### ISSUE THREAD

**Issue by sarahjeansweeney** [NEU-Libraries/cerberus#704]
About 20 minutes ago I uploaded an MOV file to this collection: https://repository.library.northeastern.edu/collections/neu:5m60qx72g

As far as I could tell, the upload went smoothly. I added metadata, clicked upload, and the file was marked as processing. When I came back to the page 10 minutes later and refreshed, the file disappeared from the collection. 

I'm not sure what other information you'll need to investigate. If it helps, here are the file names for the MOV and poster image:

ymcaoh3.mov
2015-04-08_1145.png

**Comment by dgcliff** [comment]
Somebody or something deleted it...

INFO 2015-04-08 11:52:46.606 [http-8080-2] (DefaultDOManager) Committing removal of neu:rx913x34m
INFO 2015-04-08 11:52:46.606 [http-8080-2] (DefaultDOManager) Deleting neu:rx913x34m from ResourceIndex
INFO 2015-04-08 11:52:46.607 [http-8080-2] (DefaultDOManager) Deleting managed datastream: neu:rx913x34m+rightsMetadata+rightsMetadata.0 for neu:rx913x34m
INFO 2015-04-08 11:52:46.615 [http-8080-2] (DefaultDOManager) Deleting managed datastream: neu:rx913x34m+rightsMetadata+rightsMetadata.1 for neu:rx913x34m
INFO 2015-04-08 11:52:46.622 [http-8080-2] (DefaultDOManager) Deleting managed datastream: neu:rx913x34m+rightsMetadata+rightsMetadata.2 for neu:rx913x34m
INFO 2015-04-08 11:52:46.630 [http-8080-2] (DefaultDOManager) Deleting managed datastream: neu:rx913x34m+properties+properties.0 for neu:rx913x34m
INFO 2015-04-08 11:52:46.637 [http-8080-2] (DefaultDOManager) Deleting managed datastream: neu:rx913x34m+properties+properties.1 for neu:rx913x34m
INFO 2015-04-08 11:52:46.644 [http-8080-2] (DefaultDOManager) Deleting managed datastream: neu:rx913x34m+properties+properties.2 for neu:rx913x34m
INFO 2015-04-08 11:52:46.651 [http-8080-2] (DefaultDOManager) Deleting managed datastream: neu:rx913x34m+mods+mods.0 for neu:rx913x34m
INFO 2015-04-08 11:52:46.658 [http-8080-2] (DefaultDOManager) Deleting managed datastream: neu:rx913x34m+mods+mods.1 for neu:rx913x34m
INFO 2015-04-08 11:52:46.663 [http-8080-2] (DefaultDOManager) Deleting managed datastream: neu:rx913x34m+mods+mods.2 for neu:rx913x34m
INFO 2015-04-08 11:52:46.674 [http-8080-2] (DefaultDOManager) Deleting neu:rx913x34m from FieldSearch index

**Comment by dgcliff** [comment]
@PatrickYott deleting anything with scripts?

**Comment by PatrickYott** [comment]
Nope.  haven't touched system since last week.
Patrick Yott
Associate Dean for Digital Strategies and Services
Northeastern University Libraries
360 Huntington Ave, SL 327
Boston, MA 02117
p.yott@neu.edu
617.373.4194
617.373.5409 (fax)

**Comment by PatrickYott** [comment]
Trying to think of the last time I might have issued a delete call - probably over 2 months ago

Patrick Yott
Associate Dean for Digital Strategies and Services
Northeastern University Libraries
360 Huntington Ave, SL 327
Boston, MA 02117
p.yott@neu.edu
617.373.4194
617.373.5409 (fax)

**Comment by dgcliff** [comment]
Well then, I'm not sure.

The only other activity around that item was related to this https://repository.library.northeastern.edu/collections/neu:rx913v50k

**Comment by PatrickYott** [comment]
that's something that archives is creating as they scan, yes?

Patrick Yott
Associate Dean for Digital Strategies and Services
Northeastern University Libraries
360 Huntington Ave, SL 327
Boston, MA 02117
p.yott@neu.edu
617.373.4194
617.373.5409 (fax)

**Comment by dgcliff** [comment]
Actually, I think we can safely close this. There appears to have been a network error that caused your upload to have it's pipe (connection) broken, so the upload never finished, and I think fedora auto-cleaned it out

Worker
nb4404:4708 on CONTENT_CREATION at about 4 hours ago
Class
 Cerberus::Resque::MarshaledJob
Arguments
"BAhvOhdDb250ZW50Q3JlYXRpb25Kb2INOhNAY29yZV9maWxlX3BpZEkiEm5l\ndTpyeDkxM3gzNG0GOgZFVDoPQGZpbGVfcGF0aEkiQy9ob21lL2Rycy9hcHBz\nL2RldmVsb3AvcmVsZWFzZXMvMjAxNTA0MDcxNjA2NTAvdG1wL3ltY2FvaDMu\nbW92BjsHVDoPQGZpbGVfbmFtZUkiEHltY2FvaDMubW92BjsHVDoRQGRlbGV0\nZV9maWxlVDoRQHBvc3Rlcl9wYXRoSSJLL2hvbWUvZHJzL2FwcHMvZGV2ZWxv\ncC9yZWxlYXNlcy8yMDE1MDQwNzE2MDY1MC90bXAvMjAxNS0wNC0wOF8xMTQ1\nLnBuZwY7B0Y6EEBzbWFsbF9zaXplaQA6EUBtZWRpdW1fc2l6ZWkAOhBAbGFy\nZ2Vfc2l6ZWkA\n"
Exception
Errno::EPIPE
Error
Broken pipe

**Comment by dgcliff** [comment]
The timeline seems to correspond with your file going missing

**Comment by sarahjeansweeney** [comment]
@PatrickYott Yup, it looks like Audrey's just getting started on the Bouve collection.

@dgcliff I guess it's a good thing that there's nothing wrong with Ceberus. Is this kind of network interruption a fluke, or can we expect that users might experience this sort of phantom upload in the future?

**Comment by dgcliff** [comment]
No idea. It's the first time I've seen it, and I'm mostly inferring what occurred without knowing for certain. Wouldn't be able to predict how many occurrences there might be, if ever again. That being said, whatever the odds are, they will be higher with bigger files, like videos.

**Comment by elizoller** [comment]
do you think it could be because of file size?

**Comment by dgcliff** [comment]
I don't think it was *because* of the file size, but the longer something is being uploaded, the more susceptible it would be to a disconnection causing a broken pipe

**Comment by PatrickYott** [comment]
[cid:234687CF-26A9-494D-B2DF-9AD53D8FE9ED]
Patrick Yott
Associate Dean for Digital Strategies and Services
Northeastern University Libraries
360 Huntington Ave, SL 327
Boston, MA 02117
p.yott@neu.edu
617.373.4194
617.373.5409 (fax)

**Comment by dgcliff** [comment]
So, Sarah and I figured it out. She accidentally navigated back to the 2nd page of the upload process after having succesfully uploaded the item. The javascript prompt we have in place asked her then, if she wanted to leave without finishing the file (naive of the fact that she'd navigated backwards) and promptly deleted it.

I'll look into making this a safer process.

**Comment by PatrickYott** [comment]
![cerberus_logo](https://cloud.githubusercontent.com/assets/4604086/7054739/8697ff8e-de0c-11e4-9c04-670ed6a179fd.jpg)


Could not resist.  Drinks tomorrow.
