### ISSUE TITLE
File taking a long time to process

### ISSUE THREAD

**Issue by sarahjeansweeney** [NEU-Libraries/cerberus#707]
I loaded this file about an hour ago: https://repository.library.northeastern.edu/files/neu:rx913x56n
It's still processing. It's a huge file, so I'm not surprised it's taking a long time (forgive me if we set a limit on uploads and I just forgot).
Is it truly still processing, or has it failed?
FWIW, this is the same file I failed to upload yesterday in issue #704 (filename: ymcaoh3.mov).

**Comment by dgcliff** [comment]
I just pushed up some code which may have affected your upload. Do you mind trying again if I delete that file?

**Comment by sarahjeansweeney** [comment]
Not at all. Third time's a charm, right?

**Comment by dgcliff** [comment]
lol hopefully - ok, it's deleted. I'll keep an eye on the background queue too

**Comment by sarahjeansweeney** [comment]
Okay, uploading now.

**Comment by dgcliff** [comment]
Hm, I'm seeing

Rendering 404 page due to exception: #<ActiveFedora::ObjectNotFoundError: ActiveFedora::ObjectNotFoundError>

in the log

Could be an issue with our new tmp directory settings, in combination with a large file

**Comment by dgcliff** [comment]
And I'm seeing this in resque's failed jobs list

nb4404:18172 on CONTENT_CREATION at about a minute ago
Class
 Cerberus::Resque::MarshaledJob
Arguments
"BAhvOhdDb250ZW50Q3JlYXRpb25Kb2INOhNAY29yZV9maWxlX3BpZEkiEm5l\ndTpyeDkxM3g1ODYGOgZFVDoPQGZpbGVfcGF0aEkiQy9ob21lL2Rycy9hcHBz\nL2RldmVsb3AvcmVsZWFzZXMvMjAxNTA0MDkyMDM4NTgvdG1wL3ltY2FvaDMu\nbW92BjsHVDoPQGZpbGVfbmFtZUkiEHltY2FvaDMubW92BjsHVDoRQGRlbGV0\nZV9maWxlVDoRQHBvc3Rlcl9wYXRoSSJLL2hvbWUvZHJzL2FwcHMvZGV2ZWxv\ncC9yZWxlYXNlcy8yMDE1MDQwOTIwMzg1OC90bXAvMjAxNS0wNC0wOF8xMTQ1\nLnBuZwY7B0Y6EEBzbWFsbF9zaXplaQA6EUBtZWRpdW1fc2l6ZWkAOhBAbGFy\nZ2Vfc2l6ZWkA\n"
Exception
Errno::EPIPE
Error
Broken pipe

**Comment by dgcliff** [comment]
We'll have to put this on the back burner for the moment. Definitely related to the sheer size of the file.

**Comment by dgcliff** [comment]
I think this is for the most part sorted with the file size restriction, and reorganization of temp file locations, so I'm going to close.
