### ISSUE TITLE
Error Page when permissions fail

### ISSUE THREAD

**Issue by PatrickYott** [NEU-Libraries/cerberus#709]
I've received a cranky gram from one of my colleagues about this:

![screen](https://cloud.githubusercontent.com/assets/4604086/7091456/be6a404a-df77-11e4-8cce-91397db803ea.jpg)

Can you folks work on the working to make it less ominous (something like "sorry, you don't have permissions to access...") and indicated where the login button is (yes, this was a complaint). 

Thanks guys

**Comment by elizoller** [comment]
Something like this better? I can change the header as well.
![screen shot 2015-04-10 at 1 01 01 pm](https://cloud.githubusercontent.com/assets/5439169/7092653/b816fa08-df81-11e4-8570-82fa53e19008.png)

**Comment by PatrickYott** [comment]
I think the phrase "Permissions Error" was what sent Amira into a tailspin, especially the word "Error"
Patrick Yott
Associate Dean for Digital Strategies and Services
Northeastern University Libraries
360 Huntington Ave, SL 327
Boston, MA 02115
401.338.3787
p.yott@neu.edu

**Comment by sarahjeansweeney** [comment]
That sounds good, Eli. Maybe replace the "Permissions Error" header text with the "Sorry, you don't have permission to access this page." text?

**Comment by PatrickYott** [comment]
Bingo.
Patrick Yott
Associate Dean for Digital Strategies and Services
Northeastern University Libraries
360 Huntington Ave, SL 327
Boston, MA 02115
401.338.3787
p.yott@neu.edu

**Comment by dgcliff** [comment]
The things some people choose to care about...

**Comment by sarahjeansweeney** [comment]
That triangle(!) should probably be replaced, too. Maybe with one of these:
http://fortawesome.github.io/Font-Awesome/icon/shield
http://fortawesome.github.io/Font-Awesome/icon/asterisk/

**Comment by elizoller** [comment]
![screen shot 2015-04-10 at 1 48 29 pm](https://cloud.githubusercontent.com/assets/5439169/7093560/4ea8228e-df88-11e4-8e6e-4aa06a7698a3.png)
Thanks!
Is the login button overkill?

**Comment by dgcliff** [comment]
I'd say so, but I'm not sure I'm the correct demographic. The link would probably be fine on it's own.

**Comment by sarahjeansweeney** [comment]
I agree. The link should be enough.
