### ISSUE TITLE
Tab to request a file be deleted or moved

### ISSUE THREAD

**Issue by sarahjeansweeney** [NEU-Libraries/cerberus#710]
Right now users have to contact DRS staff in order to get a file moved or deleted. This works, but it could be improved by including a tab (or button, or a link, or whatever's feasible) to request that a file be moved or deleted.
Here are a few things to consider:
* The tab/button/link would only be visible to users who can edit the file.
* For move requests, there would need to be a space to enter the destination collection.
* There should be an optional "Please explain why you would like this file removed or deleted" field.
* The DRS staff email would need to be notified (Library-Repository-Team@neu.edu).

**Comment by dgcliff** [comment]
Do we really want to give them the option of requesting a file be moved? The code for that doesn't exist, and will need to be built.

Things that I don't think are easily answered in a generic way;

Do they have permissions in the location they want?
If not, do we change the depositor, if so, to who. If we do, and they now can't access their file, now what?
What permissions should be applied beyond the depositor? Assume the permissions of the parent? Ask them if they want it public or private?

That's just off the top of my head

**Comment by sarahjeansweeney** [comment]
Both the delete and move options would just be requests sent to the staff email, so I don't think any new code would be needed. For both requests I would just make the change using the Fedora admin interface.

**Comment by dgcliff** [comment]
So you'd be going into Fedora's admin interface and manually changing metadata to effect the move?

**Comment by sarahjeansweeney** [comment]
That would be great. 
And to be clear, I'm completely open to doing this through Cerberus, but for now I'm perfectly happy doing it manually through Fedora until we can find the time to build a more efficient move/delete process.

**Comment by dgcliff** [comment]
God that'd suck to do though. That interface is even worse than Groupers!

**Comment by sarahjeansweeney** [comment]
Yup, but it must be done...

**Comment by dgcliff** [comment]
This is mostly done, just need to put in the moving tab.

**Comment by elizoller** [comment]
Will that one just be an email request for now?

**Comment by dgcliff** [comment]
Yep, same as the tombstoning one (except, the admin won't have any cerberus alternative)

**Comment by elizoller** [comment]
Ok I can take care of that then

**Comment by elizoller** [comment]
How do you want users to indicate where they want the file moved? A field for collection url?

**Comment by sarahjeansweeney** [comment]
Yes, a field for the collection URL would be great.
This may be overly cautious, but is it possible to validate the URL to make sure it truly is a DRS collection URL?

**Comment by dgcliff** [comment]
Yeah, that's not too hard to do

**Comment by elizoller** [comment]
I think I've got it figured out

**Comment by sarahjeansweeney** [comment]
Text change:
The DRS is a permanent archive, but we recognize that occasionally it may be necessary to
remove files. Please review our policies [https://repository.library.northeastern.edu/terms] for more information about withdrawing DRS content.

Why would you like us to delete this file?

**Comment by elizoller** [comment]
![screen shot 2015-04-22 at 9 11 48 am](https://cloud.githubusercontent.com/assets/5439169/7275043/a82e6d04-e8cf-11e4-9501-3aab9b95248d.png)
Better?

**Comment by elizoller** [comment]
Also the move tab looks like this:
![screen shot 2015-04-22 at 9 12 38 am](https://cloud.githubusercontent.com/assets/5439169/7275068/c3714500-e8cf-11e4-98e2-c85820bbee5b.png)

**Comment by sarahjeansweeney** [comment]
The delete tab looks great.

Here's some new text for the move tab:
Where would you like this file to be moved?
(Please enter the URL for the destination collection.)

Why would you like us to move this file?

Also, the Request button for both tabs can just say "Request".

**Comment by sarahjeansweeney** [comment]
When the user clicks "Request move/delete" are they asked to confirm that they really want to move or delete the file?

**Comment by elizoller** [comment]
Want to click through it with me on my computer so you get the whole experience?

**Comment by elizoller** [comment]
Yes they are asked to confirm.

**Comment by elizoller** [comment]
![screen shot 2015-04-22 at 9 34 39 am](https://cloud.githubusercontent.com/assets/5439169/7275576/d9271a02-e8d2-11e4-871f-90d29f0e7f0f.png)

**Comment by elizoller** [comment]
![screen shot 2015-04-22 at 9 35 20 am](https://cloud.githubusercontent.com/assets/5439169/7275602/ec717346-e8d2-11e4-8cbf-2f0d2565bca8.png)

**Comment by sarahjeansweeney** [comment]
Yeah, I would like to see this in action.

For the Move tab: Can the "Please enter..." text be in () or italicized, or smaller? Something to indicate that it's helpful text.

Confirmation: I think we have standard styling for modals (see #484). The text for both can be:

Confirm Move/Delete Request
Are you sure you want us to move/delete this file?

**Comment by elizoller** [comment]
Thanks. Feel free to come by and I'll walk you though.
I'm working on standard styling now.

**Comment by sarahjeansweeney** [comment]
More confirmation text:

Invalid collection URL message: 
That collection does not exist. Please submit a new request and enter a valid collection URL.

Successful move/delete request message:
Your request has been received and will be processed soon.

**Comment by elizoller** [comment]
Thanks!
