### ISSUE TITLE
Spreadsheet loaders

### ISSUE THREAD

**Issue by sarahjeansweeney** [NEU-Libraries/cerberus#712]
Spreadsheet loader for just metadata:
Archives staff are digitizing materials and depositing directly into the DRS (see https://repository.library.northeastern.edu/collections/neu:rx913r06d and https://repository.library.northeastern.edu/collections/neu:rx913v50k). After they upload the file they enter metadata into a Google form, which populates a Google spreadsheet.
We will need a loader to process the spreadsheet, create metadata records, and replace the original stub records with the new metadata.

Spreadsheet loader for metadata and files:
Same as above, but the files will be loaded along with the metadata.

**Comment by elizoller** [comment]
![screen shot 2016-05-03 at 11 16 37 am](https://cloud.githubusercontent.com/assets/5439169/14988162/be065522-1120-11e6-8928-5b713bd04379.png)
^ what I've come up with so far for a "preview" page on the MODS loader

**Comment by sarahjeansweeney** [comment]
This looks great so far. I have a few questions/suggestions:

- Can the PID be included after the collection name? i.e. Collection: Random Objects (neu:cz30pv57c)
- What is the "created at" date? The date/time the load was started?
- The name in the "User" field will also be the depositor?

Is the XML editable? I think we talked about this yesterday but somehow my memory is fuzzy.

**Comment by elizoller** [comment]
- Yes, we can include the collection pid - I'll add that.
- The created at refers to the load start time - should I change the label on that to something like Load start time?
- Yes, the user refers to the depositor- should I change the label to depositor?

**Comment by elizoller** [comment]
Initial pass at mods diff
![screen shot 2016-05-03 at 3 35 26 pm](https://cloud.githubusercontent.com/assets/5439169/14995806/bb345104-1144-11e6-93dc-b619dcc84dd3.png)

**Comment by sarahjeansweeney** [comment]
Yes, the load start and depositor names changes are helpful.
Preview looks great!

**Comment by elizoller** [comment]
@sarahjeansweeney for fields with authorities - how do you want to handle those? will they be another field in the spreadsheet? then we can just assign them like we assign any other field value.

**Comment by elizoller** [comment]
@sarahjeansweeney for the "place of publication" field in the spreadsheet, we currently have two fields under place - one for city and one for state (both have the field name placeTerm but with different attributes)
```
t.place(path: 'place', namespace_prefix: 'mods'){
  t.city_term(path: 'placeTerm', namespace_prefix: 'mods', attributes: { type: 'text' })
  t.state_term(path: 'placeTerm', namespace_prefix: 'mods', attributes: { type: 'code', authority: 'marccountry' })
}
```
I am wondering if we "made up" this distinction with city and state with different attributes? Would you like to continue this method? If so, I would advocate for making city and state as separate fields in the spreadsheet. Parsing based on the comma would be unreliable in the case where there is no comma and how would we know if it is city or state.

**Comment by elizoller** [comment]
@sarahjeansweeney what does the "reformatting quality" field in the spreadsheet map to in mods?

**Comment by sarahjeansweeney** [comment]
re: authorities: This just came up the other day, and it was decided we would add a new column to the spreadsheet so the catalogers could explicitly state the value's authority.

re: place: As far as I can tell, the place of publication value shouldn't need to be split into city and state. It should map to the originInfo/place/placeTerm element, which doesn't have subelements. subject/hierarchicalGeographic terms do split into city, state, country, etc subelements.

**Comment by sarahjeansweeney** [comment]
@elizoller re: reformattingQuality is a subelement of physicalDescription, i.e.:
```
   <mods:physicalDescription>
      <mods:extent>1 postcard : 9 x 14.2 cm.</mods:extent>
      <mods:digitalOrigin>reformatted digital</mods:digitalOrigin>
      <mods:reformattingQuality>access</mods:reformattingQuality>
   </mods:physicalDescription>
```
It only has three allowed values: access, preservation, replacement

**Comment by elizoller** [comment]
Ok, thanks.
On further investigation of the city_term/state_term thing, the only place in the code that seems to be using this functionality is the iptc loaders which pass iptc city and state values (iptc stores them separately).
Should I merge those into a single string and store it as a single placeTerm in the mods?
(And keep the mods spreadsheet handling with a single place field)

**Comment by sarahjeansweeney** [comment]
@elizoller yes, for the originInfo placeTerm field they should be in a single string. the spreadsheet will stay the same.

**Comment by elizoller** [comment]
for table of contents are we just doing top level element like
```
<mods:tableOfContents>text goes here</mods:tableOfContents>
```

**Comment by sarahjeansweeney** [comment]
Yup, table of contents is pretty simple.

**Comment by sarahjeansweeney** [comment]
Thinking about user experience for all our new loaders, let's organize them based on what the user is doing, not by uploaded file type:

Metadata Overwrite Tool
- assumes core file exists
- Accepts either xslx or MODS XML
- User doesn't select a destination collection
- Requires a zip for MODS XML export/import process
- No permissions options

New File Loader

- Accepts any file + xslx
- Accepts any file + MODS XML
- Accepts any file + MODS XML + ordering spreadsheet for multipage
- User selects destination collection
- Requires zip
- Permission options

**Comment by sarahjeansweeney** [comment]
I'm running into a system error when I try to use the spreadsheet loader on staging:

![2016-05-26_1024](https://cloud.githubusercontent.com/assets/4663073/15577825/166a12b8-232c-11e6-807f-a11b68f6f470.png)

**Comment by dgcliff** [comment]
I'll bet a very large drink with a tiny umbrella in it, it's because it's Thursday. I'll restart some things.

**Comment by sarahjeansweeney** [comment]
FWIW it *was* working earlier.

**Comment by elizoller** [comment]
Staging should be fixed now.

**Comment by sarahjeansweeney** [comment]
Two spreadsheet fields aren't being processed into MODS: Supplied title ("Is this a supplied title?") and any of the name affiliation fields. I'll send the spreadsheet over slack, but the resulting record is here: http://cerberus.library.northeastern.edu/files/neu:nz806157s

**Comment by elizoller** [comment]
WHEN YOU DEPLOY: Run console loop to mark all preview load reports as completed = true (default value is false)

**Comment by sarahjeansweeney** [comment]
I tested the upload spreadsheet + file upload process this morning and there are a few issues with how the MODS is being generated.
- The valueURI attribute for the primary creator contains the name value.
- The date created was entered into MODS as "yyyy\-00\-dd"
- Subject heading one contains the value for subject heading two in the authority attribute.
- Name subject heading 1 is in a topic field and is missing the name type
- The name subject heading name type was processed as it's own subject term.
- The relatedItem fields for the original item, collection title, and series, are missing.
- The scholarly object extension field includes `<category>miscellany</category>`, which isn't a valid SO category.

I didn't test a full MODS spreadsheet, just what lives in the Board of Trustees spreadsheet, but I'll try that next to make sure it wasn't just how the spreadsheet was formatted. 
I'll also share the spreadsheet I used over slack.

**Comment by sarahjeansweeney** [comment]
Here are the records I created, if that helps: 
http://cerberus.library.northeastern.edu/files/neu:nz8062499
http://cerberus.library.northeastern.edu/files/neu:nz8062545
http://cerberus.library.northeastern.edu/files/neu:nz806252m

**Comment by dgcliff** [comment]
@elizoller do you mean all *previous* load reports?

**Comment by elizoller** [comment]
Yeah sorry

**Comment by sarahjeansweeney** [comment]
Just tried another load. The preview page displayed the metadata as expected, with relatedItems and good dates, etc:

![2016-05-27_1436](https://cloud.githubusercontent.com/assets/4663073/15617813/810eeaf2-2418-11e6-9d32-3621d477ab9b.png)

But when the record loaded, it loaded with the same MODS issues described above (http://cerberus.library.northeastern.edu/files/neu:nz806286f):
![2016-05-27_1436](https://cloud.githubusercontent.com/assets/4663073/15617829/93be22c6-2418-11e6-8e1f-59917770c755.png)

**Comment by dgcliff** [comment]
Probably caching Sarah, which will be a quick patch. I'll manually expunge it to see if it works

**Comment by sarahjeansweeney** [comment]
Getting this message now:
![2016-05-27_1514-1](https://cloud.githubusercontent.com/assets/4663073/15618739/c36068b8-241d-11e6-8301-1fd7fcb170d8.png)

**Comment by elizoller** [comment]
I think this is because there is an empty column header. I will do a better check for that.

**Comment by sarahjeansweeney** [comment]
Just tested again and noticed a few other things:
Personal name:
The given name for a personal name creator field was inserted in the MODS valueURI attribute:
![image](https://cloud.githubusercontent.com/assets/4663073/15678949/1876cf56-271e-11e6-82ca-622fb87e8658.png)
became
```
    <mods:name type="personal" valueURI="Sarah">
        <mods:namePart type="given">Sarah</mods:namePart>
        <mods:namePart type="family">Sweeney</mods:namePart>
        <mods:namePart/>
        <mods:role>
            <mods:roleTerm authority="marcrelator" authorityURI="http://id.loc.gov/vocabulary/relators" type="text">Creator</mods:roleTerm>
        </mods:role>
        <mods:namePart type="termsOfAddress">Ms.</mods:namePart>
        <mods:namePart type="date">1923 -</mods:namePart>
    </mods:name>
```

Corporate name:
I may not have formatted this correctly, but the URIs are missing from corporate name fields:
![image](https://cloud.githubusercontent.com/assets/4663073/15679118/b5dd8262-271e-11e6-9434-5547c4112a3b.png)
Became:
```
    <mods:name type="corporate" usage="primary">
        <mods:namePart>Northeastern University (Boston, Mass.). Board of Trustees</mods:namePart>
    </mods:name>
```
Subject Topic:
The authority value and URI were inserted in the same attribute:

![image](https://cloud.githubusercontent.com/assets/4663073/15679175/ea58fc2e-271e-11e6-8f82-15b8ce34c20d.png)


Became
```
 <mods:subject authority="lcsh | URI">
        <mods:topic>College trustees</mods:topic>
        <mods:topic>Massachusetts</mods:topic>
        <mods:topic>Boston</mods:topic>
    </mods:subject>
```

Subject Name:
The field value for subject name was inserted into the ValueURI attribute, with a \ to escape the apostrophe:

![image](https://cloud.githubusercontent.com/assets/4663073/15679019/5011cbb4-271e-11e6-8210-5c4c837939ff.png)

Became

```
<mods:subject>
        <mods:name type="corporate" authority="lcsh" valueURI="Boston Young Men\'s Christian Association">
            <mods:namePart>Boston Young Men's Christian Association</mods:namePart>
        </mods:name>
    </mods:subject>
```

**Comment by sarahjeansweeney** [comment]
Let's use "topical subject heading" and "name subject heading" for consistency in the subject column headers.

**Comment by elizoller** [comment]
Fixes are in for the above issues with URIs and deployed to staging (e04af55d5cf6425061bd30d650c1fc6cf030e10c)

**Comment by sarahjeansweeney** [comment]
Here's the grouper group for loaders: ```northeastern:drs:repository:loaders:spreadsheet```
We'll sort out the full permissions for all the loaders later.

**Comment by dgcliff** [comment]
Should be finished with ca6ca2a5fb66610f6c805b537d06d6b55d45fff2
