### ISSUE TITLE
Hanging files

### ISSUE THREAD

**Issue by sarahjeansweeney** [NEU-Libraries/cerberus#713]
There are at least two files that have been stuck in the processing stage since 4/9:
https://repository.library.northeastern.edu/files/neu:rx913x55c
https://repository.library.northeastern.edu/files/neu:rx913x586

**Comment by dgcliff** [comment]
@sarahjeansweeney both files have been deleted. Hopefully with your new admin panel addition we'll be able to keep an eye on these. At least with the giant file we have a pretty strong idea of what went wrong.
