### ISSUE TITLE
Powerpoint files are mischaracterized by FITS

### ISSUE THREAD

**Issue by sarahjeansweeney** [NEU-Libraries/cerberus#714]
FITS characterizes a Powerpoint's MIME type as "application/vnd.oasis.opendocument.text", and as a result they download as .odt files rather than .ppt/.pptx.

Pat's suggestion: "There isn’t a “creating application” value for this file that would help us clarify this. I think the only (and I’m doubtful if its a safe trigger to use) hint is the extension…"

Sarah's suggestion: I think powerpoint files have given us trouble in the past, so can we just zip them for now?

**Comment by dgcliff** [comment]
I could look into seeing if I can get a newer version of "NLNZ Metadata Extractor" which FITS seems to be using for it's mime extraction if it's worthwhile. It could be FITS is behind the times and there's a bugfix for this.

**Comment by dgcliff** [comment]
Hm. Doesn't look like it. Blech.

**Comment by dgcliff** [comment]
This is an interesting comment thread, there might be something of use I can get out of it to fix our issue

https://github.com/thoughtbot/paperclip/issues/1530

**Comment by dgcliff** [comment]
Woo!

I have a solution. 23 days ago, this particular gem solved this issue

https://github.com/minad/mimemagic/pull/20

By pulling it into our gemfile with 
```
gem 'mimemagic', git: 'git://github.com/minad/mimemagic.git'
```

I can then get results like this

```
MimeMagic.by_path('/home/vagrant/cerberus/spec/fixtures/files/pat.pptx')
 => #<MimeMagic:0x000000075d8980 @type="application/vnd.openxmlformats-officedocument.presentationml.presentation", @mediatype="application", @subtype="vnd.openxmlformats-officedocument.presentationml.presentation">
```

**Comment by dgcliff** [comment]
Hm. Maybe not. That seems to be doing it just from extension...

**Comment by dgcliff** [comment]
There's reference to using the extra magic, but it doesn't work in the console from what I can see

https://github.com/minad/mimemagic#extra-magic-overlay

```
2.0.0-p598 :002 > require 'mimemagic/overlay'
 => true
2.0.0-p598 :003 > MimeMagic.by_magic(File.open('/home/vagrant/cerberus/spec/fixtures/files/pat.pptx'))
 => #<MimeMagic:0x000000073dc870 @type="application/zip", @mediatype="application", @subtype="zip">
```

**Comment by PatrickYott** [comment]
If this is a problem that centers around the xml-enabled microsoft products, could we rely on the FITS characterization as open0ffice and then look at the extension of the submitted file (also in the FITS record) to make a "best guess".  Or is this a plain dumb idea?

**Comment by dgcliff** [comment]
extension isn't in the fits record for some/many of the batch ingested objects as far as I can tell?

First image I looked at - http://nb4676.neu.edu:8080/fedora/objects/neu:37069/datastreams/characterization/content

**Comment by PatrickYott** [comment]
This is one of the reasons I suggested we recreate FITS records for all records.  The version of FITS on the server is including those, as well as checksums.

**Comment by dgcliff** [comment]
I don't think FITS will be able to retroactively be able to get filenames and thus extensions? At this point, it's a long way removed from being run from it's source file.

**Comment by PatrickYott** [comment]
good point.  forgot that fedora uses extension-less storage.  Moving forward, in that sunny day when I'm not pushing files, we should have much more predictable FITS records.

**Comment by PatrickYott** [comment]
Fortunately, one of the bulk edits I did some time ago did add filenames to the properties data streams

Patrick Yott
Associate Dean for Digital Strategies and Services
Northeastern University Libraries
360 Huntington Ave, SL 327
Boston, MA 02115
401.338.3787
p.yott@neu.edu

**Comment by dgcliff** [comment]
I remember some of those missing extensions - https://github.com/NEU-Libraries/cerberus/issues/503

**Comment by PatrickYott** [comment]
lets table this, if you don't mind, until I'm back.  I can run some queries to make sure all the properties datastreams (#503 refers to rels-int, which we shelved, I think) have extensions.  I think they do..

**Comment by PatrickYott** [comment]
fortunately, the only file types I've migrated are TIFF, JPEG, and PDF

**Comment by dgcliff** [comment]
Not working on it, but putting this here for posterity

http://serverfault.com/questions/338087/making-libmagic-file-detect-docx-files

I amended /etc/magic to take those rules, and it worked. We're locked into using file-5.04 for operating system reasons, which means although the above works, it truncates the mime to 64 chars

That is enough chars though, for a unique string and positive match

**Comment by dgcliff** [comment]
It's possible to manually update to 5.22 which fixes the truncated issue

git clone https://github.com/file/file.git file
autoreconf -i
./configure
make
sudo make install

**Comment by dgcliff** [comment]
Very nearly there. Production now has file 5.22 - I manually recharacterized pats pptx file, and it worked perfectly. However, he way we infer extension from the mime type (drumroll) also is too old to accommodate for microsoft's mime type. Later versions of rack do the right thing https://github.com/rack/rack/commit/1aef6413d18750894ca25a798653f216bd0228f8 as of Feb 5, but I'm loathe to try and integrate such a core component out of step (rack does much more than mime conversion for us).

Sigh.

That being said, I can get the correct extension at the linux level, with something like

echo $(grep "application/vnd.openxmlformats-officedocument.presentationml.presentation" /etc/mime.types | awk '{print $2}')

I need to ruby-fy that and put it in the relevant places. But we're nearly there.

**Comment by dgcliff** [comment]
Fixed - I'm running the redo of FITS now, once it's complete, this issue should be completely done for
