### ISSUE TITLE
Empty MODS usage attribute causing validation error

### ISSUE THREAD

**Issue by sarahjeansweeney** [NEU-Libraries/cerberus#717]
The XML Editor can't validate MODS records for files uploaded through Cerberus because of an empty usage attribute:

"Invalid XML provided

Nokogiri::XML::SyntaxError: Element '{http://www.loc.gov/mods/v3}name', attribute 'usage': [facet 'enumeration'] The value '' is not an element of the set {'primary'}. 

Nokogiri::XML::SyntaxError: Element '{http://www.loc.gov/mods/v3}name', attribute 'usage': '' is not a valid value of the atomic type '{http://www.loc.gov/mods/v3}usageAttributeDefinition'. "

Examples:
https://repository.library.northeastern.edu/files/neu:rx913q26p
https://repository.library.northeastern.edu/files/neu:rx913q40h

**Comment by dgcliff** [comment]
Known fix, just have to work it into the timeline. At the moment, the attribute is set to empty by cerberus code, whereas the attribute should actually be deleted.

**Comment by dgcliff** [comment]
I'll push this up to production sometime today - it won't retroactively fix the ones that have already been afflicted (they can fixed with the XML editor), but it'll stop it from happening again
