### ISSUE TITLE
Thumbnails for PDFs with cropped first pages

### ISSUE THREAD

**Issue by sarahjeansweeney** [NEU-Libraries/cerberus#718]
Hillary uploaded this file yesterday and the thumbnail for the first page doesn't display as she expected: https://repository.library.northeastern.edu/files/neu:rx9143948

![2015-04-23_1137](https://cloud.githubusercontent.com/assets/4663073/7305659/92026806-e9cd-11e4-8bb8-0ef7720ce684.png)

The first page of the PDF is a cropped horizontal page (it's the front page - the other half of the cropped page was moved to the last page), so she expected the thumbnail to only display the cropped half of the page, but the thumbnail seems to use the dimensions from the full horizontal page.

**Comment by dgcliff** [comment]
This may not be something we can really do much about, other than put in an option to remove the thumbnail (which may or may not be an improvement...)

**Comment by dgcliff** [comment]
This can be dealt with by #727 when it's finished
