### ISSUE TITLE
Google optimization

### ISSUE THREAD

**Issue by sarahjeansweeney** [NEU-Libraries/cerberus#719]
Google search results for DRS content are not ideal. Searches either turn up non-DRS matches, repository.neu.edu content, or results that are just queries:

![2015-04-23_1541](https://cloud.githubusercontent.com/assets/4663073/7305905/7d96518c-e9cf-11e4-8140-6712d50ba3ad.png)

We should follow the steps recommended by Google to enhance DRS content in search results:
https://support.google.com/webmasters/answer/35769?hl=en

**Comment by dgcliff** [comment]
I think this will help Eli and I when we go to address this - http://blog.lebrijo.com/how-to-get-google-to-properly-index-your-rails-website/

The sitemap might have be a solr-generated dynamic thing, but I've got an idea how that might work

**Comment by elizoller** [comment]
For the header content we can pull in description and keywords on a core file page. Would you want other fields in the header keywords? On collections and communities we could add the description at least.
Where else could we plug in headers? Sets?
And we'll need generic headers for everywhere else so a description of the DRS and some keywords.

**Comment by sarahjeansweeney** [comment]
Core file pages should have title, creator, description, and keywords. Collections and communities should have title and description. 
Sets aren't discoverable in the DRS, so we should leave them alone, but I suppose the faculty pages could use headers.

**Comment by sarahjeansweeney** [comment]
Generic header stuff (if I've overlooked a useful keyword, feel free to add it):

DRS description: The Digital Repository Service is a secure repository system, designed to store and share scholarly, administrative, and archival materials from the Northeastern University community. The DRS was developed by the Northeastern University Library as a tool for University faculty and staff to protect the valuable information and data that has been created as part of the University’s research and instructional mission. It provides long-term security for the files it stores, as well as access management controls and support for various metadata standards to help ensure that data is as accessible and usable in the present and the future.

Keywords: Digital Repository Service, DRS, Northeastern University Libraries, Northeastern University Library, digital repository, digital repositories, faculty research, theses, dissertations, ETDs

**Comment by elizoller** [comment]
Thanks!

**Comment by elizoller** [comment]
I think the title is processed with the page title already. Is there other content we could populate for a faculty member?

**Comment by sarahjeansweeney** [comment]
I think the only meaningful information we have for faculty is their name.

**Comment by elizoller** [comment]
Ok, that is already covered in the title. Thanks.

**Comment by dgcliff** [comment]
This has been implemented, and is live in production.
