### ISSUE TITLE
Error accessing a community

### ISSUE THREAD

**Issue by sarahjeansweeney** [NEU-Libraries/cerberus#720]
I get a "System Error" page when I try to open the "Department of Languages, Literatures, and Cultures" community:

![2015-04-24_1147](https://cloud.githubusercontent.com/assets/4663073/7322752/17f874be-ea78-11e4-9c2f-becb28639e14.png)

It's a valid community (https://repository.library.northeastern.edu/communities/neu:191), and I can find it in search results and the admin panel:

![2015-04-24_1145](https://cloud.githubusercontent.com/assets/4663073/7322749/13c6cc1a-ea78-11e4-8be5-d47456f3a5a9.png)

**Comment by dgcliff** [comment]
I think it has an old smart collection type we don't use anymore "other" (we never used it maybe?)

I'll look into fixing it

**Comment by dgcliff** [comment]
I deleted the route, seemingly by accident https://github.com/NEU-Libraries/cerberus/commit/99e28b2b6982a9a773c495e469bc5090978dd1d6#diff-21497849d8f00507c9c8dcaf6288b136

**Comment by sarahjeansweeney** [comment]
Oh, that might help answer Eli's question in #691 : "I tried doing the Other Publications but I think I'm missing the query somewhere along the way because it was failing."
