### ISSUE TITLE
System Error page styling

### ISSUE THREAD

**Issue by sarahjeansweeney** [NEU-Libraries/cerberus#721]
Can the "System Error" page be updated to match the styling for the "Permissions Error" page (#709)? (Just the styling - the text is good.)

![2015-04-24_1147](https://cloud.githubusercontent.com/assets/4663073/7322837/9d659aaa-ea78-11e4-8ec9-cf687af8d8f7.png)

**Comment by elizoller** [comment]
Do you want the icon changed also?

**Comment by sarahjeansweeney** [comment]
Yeah ... since the text is good I guess the icon is the only real change. I should have just asked for that :)

**Comment by elizoller** [comment]
Ok. I'll make the icon the same size as the text as well so it's not as big.
