### ISSUE TITLE
PDF uploaded as a zip file

### ISSUE THREAD

**Issue by sarahjeansweeney** [NEU-Libraries/cerberus#724]
Hillary uploaded this PDF earlier today: 
https://repository.library.northeastern.edu/files/neu:rx914504h

I ran FITS on the file locally and it's clearly a PDF, but the MIME type in the characterization datastream is application/zip.

**Comment by dgcliff** [comment]
ok, I'll look into it

**Comment by dgcliff** [comment]
fits isn't wrong, it is a zip file. FITS has taking the mime type of the zip *cerberus* made. Cerberus decided it couldn't figure out what it was, and zipped it up (which is what we do with unknown content)

**Comment by dgcliff** [comment]
I have no idea - I downloaded the file from the url you provided, took it out of the zip file, and uploaded it to repository.library without any issues. You may have to ask Hilary what she did?

**Comment by sarahjeansweeney** [comment]
I'll asked her. I just did the same thing you did (download, unzip, upload, etc) and the file file got zipped: https://repository.library.northeastern.edu/files/neu:rx914541n

**Comment by dgcliff** [comment]
I'll come see you, and we can both do it. There must be something one of us is missing.

**Comment by dgcliff** [comment]
Fixed with 42e719939f368dd9cdcfad91f684086408c47d7f
