### ISSUE TITLE
Collaborative Sets

### ISSUE THREAD

**Issue by sarahjeansweeney** [NEU-Libraries/cerberus#726]
To make Sets more collaborative, permissions for sets should be expanded to allow Set creators to select "Edit" and allow a group of users to add to that Set. 

We'll have to talk about the user experience for collaborative Sets, particularly for the user who has the edit permission but did not create the Set. Perhaps a list on their My Sets page for "Sets shared with me", or something similar.

**Comment by dgcliff** [comment]
I think this can be closed - done in other tickets.
