### ISSUE TITLE
Creating personal collections for users

### ISSUE THREAD

**Issue by sarahjeansweeney** [NEU-Libraries/cerberus#728]
Right now a personal collection needs to exist before proxy staff can deposit a file in a user's person, so if proxy staff want to deposit in a user's account they either need to deposit in a smart collection or in an existing personal collection. Proxy staff should have the ability to create a personal collection for a user on his or her behalf.

**Comment by dgcliff** [comment]
I believe this has been fixed with the Impersonate User feature. Happy to re-open if this is not the case.

**Comment by sarahjeansweeney** [comment]
Yup. Definitely works: https://repository.library.northeastern.edu/collections/neu:rx918700h
