### ISSUE TITLE
Grouper Group List Display

### ISSUE THREAD

**Issue by sarahjeansweeney** [NEU-Libraries/cerberus#729]
When users are given the option to select a Grouper group, can the list of groups be sorted in alphabetical order?

![2015-03-24_0905](https://cloud.githubusercontent.com/assets/4663073/7421274/4558dd8a-ef51-11e4-8bb2-545742323ff7.png)

Also, the Grouper group string is pretty ugly (most people won't see the large list that I see, but the northeastern:drs:etc string isn't easy to read). When I create a group in Grouper I have to supply three pieces of information: path, name, and description. I believe what we're seeing in the list is the path. Does Grouper pass the Group description, too? If so, can the Group name display rather than the path?

**Comment by elizoller** [comment]
Fixed with https://github.com/NEU-Libraries/cerberus/commit/a31afc3d00dedba46b0281caa2c98a4b36dc84b2
Will refactor this later to use ActiveRecord and store the pretty values for grouper groups and create a component of the admin panel that will allow for adding/editing pretty values
