### ISSUE TITLE
Add multiple items to a Set

### ISSUE THREAD

**Issue by sarahjeansweeney** [NEU-Libraries/cerberus#730]
If possible, it would be great if users could add multiple items to a set. I can think of two ways users might want to do this: Add a page of search results or add an entire collection.

**Comment by elizoller** [comment]
What should happen when a user adds a collection to a set but some of the items in the collection already exist individually in the set?

**Comment by dgcliff** [comment]
Well one of two things I guess

We don't let them add the collection until they remove the individual items first (which is harsh)

Or, we add the collection, and remove the individual items ourselves, and tell them that's what we did (total count, list of pids/titles?)

There's a third way, which is to do the second, but after a warning, so they have to say, Yes, I'd like to replace in place, these x items

**Comment by sarahjeansweeney** [comment]
Of those three options, I think the third is the best.

Is nothing an option, or are there consequences to keeping the individual items and the full collection? Would those items show up as duplicates in Toolkit searches?

**Comment by dgcliff** [comment]
Yep, duplicates. Doing nothing is an option, but it does mean we'd have to do filtering at multiple end points (downloading, OAI, Toolkit, i.e. everywhere we'd want to use it)

Which would be a massive pain, instead of just preventing it in the first place

**Comment by dgcliff** [comment]
I think this can be closed.
