### ISSUE TITLE
Grouper changes not reflected in DRS?

### ISSUE THREAD

**Issue by sarahjeansweeney** [NEU-Libraries/cerberus#732]
I made some Grouper group changes this morning for the first time since Thursday's upgrade. I removed myself from the drs:library:dsg group and I created a new group (drs:drspt:arader_gallery), but neither of those changes are reflected in the DRS edit page for groups:

![2015-05-13_1407](https://cloud.githubusercontent.com/assets/4663073/7617549/dd5a3c78-f979-11e4-9de6-6bfd1a6d7582.png)

**Comment by dgcliff** [comment]
Presumably linked to the grouper update - I'll try and find out what may have gone awry

**Comment by dgcliff** [comment]
@sarahjeansweeney could you email the contents of what you see at https://repository.library.northeastern.edu/secure/ ? (as opposed to pasting it here, as it probably contains sensitive info)

**Comment by sarahjeansweeney** [comment]
@dgcliff Sure, no problem

**Comment by dgcliff** [comment]
This looks to be a grouper/IS issue, going to close, but if this does turn out to be something we can help fix, feel free to re-open it

**Comment by sarahjeansweeney** [comment]
Okay, I'll put in a ticket with IS.
