### ISSUE TITLE
Downloading a Large(ish) set failed

### ISSUE THREAD

**Issue by PatrickYott** [NEU-Libraries/cerberus#733]
I tried to download this set - https://repository.library.northeastern.edu/sets/neu:rx913r143 - but failed.  I wasn't logged in at the time.

Sarah created this set for me and was, I believe, able to download it to her desktop.  She emailed me the URL for the set (these are PDF files that need to have covers stripped), and I was unable to download it.  Received the following error.
![error](https://cloud.githubusercontent.com/assets/4604086/7632133/f7c280d6-fa17-11e4-8b20-ad0db6f6dfcc.jpg)

**Comment by dgcliff** [comment]
I just downloaded it myself, with no issue, but I was logged in. I have the corresponding error, I'll look into it.

**Comment by dgcliff** [comment]
Yeah, the zip compilation job expects a login user (to check against embargo), and doesn't have a rescue case if there isn't one. Should be an easy fix.
