### ISSUE TITLE
Zip loader errors in COE and CPS

### ISSUE THREAD

**Issue by sarahjeansweeney** [NEU-Libraries/cerberus#734]
The Marcom loader works perfectly, and I can upload files as expected using each of the loaders, but the COE and CPS loaders keep returning the same IPTC error ("Error - undefined method `gsub' for [year]:Fixnum"), even for files that didn't cause errors when loaded into the old repository:

![coe error](https://cloud.githubusercontent.com/assets/4663073/7654377/af72300a-faea-11e4-9fd6-63612a994758.png)

I tried with several different files with the same result:
http://cerberus.library.northeastern.edu/loaders/cps/report/14
http://cerberus.library.northeastern.edu/loaders/engineering/report/13
http://cerberus.library.northeastern.edu/loaders/cps/report/7 (these were just CPS files I had on my computer, so I can't say for sure that they would be successful in the old repository, either)
http://cerberus.library.northeastern.edu/loaders/engineering/report/6

The only successful COE or CPS load was when I tried loading Marcom photos to a COE collection:
http://cerberus.library.northeastern.edu/loaders/engineering/report/12

Let me know if you want the files I used.

**Comment by elizoller** [comment]
I'm fairly certain this error was because the keyword array contained a number and it was expecting a string. I've added checks for non-strings and converting expected non-string values to strings. 4d79c7ce160c55c22e9d51ef0a078817676b0cdb
I'll deploy to staging again shortly and then you can have another go at it.

**Comment by elizoller** [comment]
Ok give it another try when you have a chance.
I deployed to staging with the latest changes and cleared it back to the stock objects.

**Comment by dgcliff** [comment]
It looks like this is safe to be closed
