### ISSUE TITLE
Loader Reports and Emails

### ISSUE THREAD

**Issue by sarahjeansweeney** [NEU-Libraries/cerberus#735]
I have a three small suggestions for the loader reports and emails:
 - [x] Add a column to the "Past Loads" table for the destination collection name 
 - [x] Include the depositor name in the load email
 - [x] If possible, include a message in the load email when the load contains an error, something like "At least one error was detected in this upload. Please view the load report for more information."

**Comment by sarahjeansweeney** [comment]
Also, since these email will go to users they should probably look less like our internal messages. Is it possible to change [Cerberus] in the subject line to DRS?

**Comment by dgcliff** [comment]
I think all of the above can be done - thanks for the suggestions

**Comment by dgcliff** [comment]
Looks like this can be closed
