### ISSUE TITLE
Loader access for non-faculty users

### ISSUE THREAD

**Issue by sarahjeansweeney** [NEU-Libraries/cerberus#739]
I logged in as Matt to prepare for Tuesday's test run of the loaders, but I can't actually access the loaders as Matt. As regular staff he won't get a user page, so clicking his name does nothing (it's also permanently the lighter hover gray):

![2015-05-21_0850](https://cloud.githubusercontent.com/assets/4663073/7748939/2bb79316-ff97-11e4-964a-3ad9a3b1cf85.png)

Could "My Loaders" be added to the dropdown menu, above "Sets"?

**Comment by elizoller** [comment]
I'll look into why he doesn't have a my_drs page - he should because he's an employee.
In regards to the dropdown - we can add whatever would be valuable to that - My Loaders, My Collections, etc

**Comment by elizoller** [comment]
He should be have an employee record, right?

**Comment by elizoller** [comment]
Nevermind - I just reread your comment and see he shouldn't have a my_drs page.
I'll add My Loaders to the dropdown and deploy to staging shortly.

**Comment by elizoller** [comment]
This is deployed to staging.
