### ISSUE TITLE
mods:nonSort field doesn't display in Sets

### ISSUE THREAD

**Issue by sarahjeansweeney** [NEU-Libraries/cerberus#741]
The mods:nonSort field is missing from titles in a Set, which causes initial articles to be removed from the title:

![2015-05-22_1047](https://cloud.githubusercontent.com/assets/4663073/7773151/9fd5aba0-0070-11e5-9f1e-5074c61da254.png)

(Should be "A reproduction" and "A seated member"

**Comment by elizoller** [comment]
It was just missing the non-sort which we manually display for the core files in other places like the core file display. I also added the kramdown_parse function on the title to allow superscript and subscript in the Sets view.
