### ISSUE TITLE
current_user nil errors introduced with loader code

### ISSUE THREAD

**Issue by dgcliff** [NEU-Libraries/cerberus#743]
There are several places where current_user.loader? are called, but we don't check to see if current_user isn't nil. This causes 500 errors on several pages if you're not logged in.

https://github.com/NEU-Libraries/cerberus/blob/c556349fa84be7c8bc9895f6b96676ca6c514e36/app/views/employees/communities.html.haml#L11

https://github.com/NEU-Libraries/cerberus/blob/c556349fa84be7c8bc9895f6b96676ca6c514e36/app/views/employees/communities.html.haml#L22

https://github.com/NEU-Libraries/cerberus/blob/c556349fa84be7c8bc9895f6b96676ca6c514e36/app/views/employees/list_files.html.haml#L11

https://github.com/NEU-Libraries/cerberus/blob/c556349fa84be7c8bc9895f6b96676ca6c514e36/app/views/employees/list_files.html.haml#L22

https://github.com/NEU-Libraries/cerberus/blob/c556349fa84be7c8bc9895f6b96676ca6c514e36/app/views/employees/my_loaders.html.haml#L25

https://github.com/NEU-Libraries/cerberus/blob/c556349fa84be7c8bc9895f6b96676ca6c514e36/app/views/employees/my_loaders.html.haml#L29

https://github.com/NEU-Libraries/cerberus/blob/c556349fa84be7c8bc9895f6b96676ca6c514e36/app/views/employees/my_loaders.html.haml#L33

https://github.com/NEU-Libraries/cerberus/blob/c556349fa84be7c8bc9895f6b96676ca6c514e36/app/views/employees/personal_graph.html.haml#L17

**Comment by elizoller** [comment]
Ah.. Thanks!
