### ISSUE TITLE
Browsing recent deposits in a community

### ISSUE THREAD

**Issue by sarahjeansweeney** [NEU-Libraries/cerberus#745]
The browsability of communities could be improved with the ability to view recent deposits in the community's nested collections.

This is similar to the recent deposits list in repository.neu.edu:
![2015-05-26_1614](https://cloud.githubusercontent.com/assets/4663073/7822280/77f54104-03c2-11e5-9b0f-bccf7bf2d1bd.png)

**Comment by elizoller** [comment]
Visually are you thinking full item displays or a more minimal display without abstract/download buttons (for example)?
I'm thinking maybe have 5 or 10 displayed and that it could either fit under the facets/limiters in the left column or under the regular results. Do you have other thoughts on this?

**Comment by elizoller** [comment]
Just some preliminary ideas. 
<img width="1264" alt="screen shot 2015-10-07 at 2 39 07 pm" src="https://cloud.githubusercontent.com/assets/5439169/10347334/560958fc-6d01-11e5-8a21-7bf7a786bd02.png">
<img width="1281" alt="screen shot 2015-10-07 at 2 38 16 pm" src="https://cloud.githubusercontent.com/assets/5439169/10347339/583b8c3a-6d01-11e5-9ddb-0c30365546be.png">
<img width="1293" alt="screen shot 2015-10-07 at 2 37 10 pm" src="https://cloud.githubusercontent.com/assets/5439169/10347341/5a98bdcc-6d01-11e5-9409-9dd0def78e4f.png">

**Comment by dgcliff** [comment]
Won't all 3 get weird in grid view?

**Comment by elizoller** [comment]
Probably. Should we make it a separate page and then link to it from near the description?

**Comment by dgcliff** [comment]
That could work - a modal even, as a quick look in

**Comment by elizoller** [comment]
Ok will try that

**Comment by elizoller** [comment]
is this for collections and communities?

**Comment by dgcliff** [comment]
Just communities I think? For collections, a sort would suffice I think.

**Comment by elizoller** [comment]
Ok Thanks

**Comment by elizoller** [comment]
<img width="1227" alt="screen shot 2015-10-08 at 11 47 08 am" src="https://cloud.githubusercontent.com/assets/5439169/10371653/63d8f71a-6db2-11e5-9933-e6390c76e4fa.png">
<img width="1232" alt="screen shot 2015-10-08 at 11 47 17 am" src="https://cloud.githubusercontent.com/assets/5439169/10371654/654a378a-6db2-11e5-9ab2-6300e905ff23.png">
I took out the abstract on the files but its still a really busy modal. I could make it wider, that might help.

**Comment by dgcliff** [comment]
We could just drop everything but a link to the title? Depending on how much functionality replication we're trying to achieve versus just a quick information hit

**Comment by elizoller** [comment]
I'm game.

**Comment by elizoller** [comment]
<img width="1214" alt="screen shot 2015-10-08 at 12 04 27 pm" src="https://cloud.githubusercontent.com/assets/5439169/10372208/c06ac38a-6db4-11e5-8655-452f0e217c93.png">

**Comment by dgcliff** [comment]
Looks good to me - hopefully that meets what Sarah was after

**Comment by elizoller** [comment]
with deposit dates
<img width="1215" alt="screen shot 2015-10-08 at 12 20 50 pm" src="https://cloud.githubusercontent.com/assets/5439169/10372685/128f4f26-6db7-11e5-9e71-f30e1ad9e1c8.png">
Will wait to push anything up until Sarah can give feedback

**Comment by sarahjeansweeney** [comment]
A few things:
- This should be available for communities and collections (the sort option only works for collections without nested collections).
- Change "Recent Deposits" to "Recently Added"
- The simplified modal looks great, though users will want to see the thumbnail, too.
- Are we limited to just five items like we are with the facets, or can the modal display 10 at a time?

**Comment by elizoller** [comment]
We are not limited to 5.
If we do Recently Added, Author List, and Title List for communities and collections then I'm wondering if maybe they should all trigger the same type of action, ie. going to a new page. Or else similar looking/placed buttons would do different things (modal vs. new page)?

**Comment by sarahjeansweeney** [comment]
Good point, they should all go to a new page.

**Comment by elizoller** [comment]
So it will operate like a search with pagination, facets, list/grid view. It will have a separate route (including breadcrumb) and button. We will do a special visual queue that shows you've sorted/searched by recently uploaded (like the finder search).

**Comment by elizoller** [comment]
Hide this button if there are no items - this will take into account permissions.

**Comment by elizoller** [comment]
Merged with https://github.com/NEU-Libraries/cerberus/pull/887
