### ISSUE TITLE
Community object count

### ISSUE THREAD

**Issue by sarahjeansweeney** [NEU-Libraries/cerberus#746]
The count for objects contained in communities is incorrect:

![2015-05-28_0922](https://cloud.githubusercontent.com/assets/4663073/7860998/7fb616a2-051b-11e5-928d-6d09faed8b68.png)

Presumably this is because Research Publications and Faculty are queries, and therefore not really countable objects, correct? Since the typical user doesn't know this difference, the count looks like a mistake.

**Comment by dgcliff** [comment]
Yeah, faculty and research pub are throwing it off. I imagine this could be fixed.
