### ISSUE TITLE
mods:form element is empty in bulk loaded records

### ISSUE THREAD

**Issue by sarahjeansweeney** [NEU-Libraries/cerberus#747]
The form element in the MODS record created by the loader is missing its value:

![2015-05-29_1335](https://cloud.githubusercontent.com/assets/4663073/7888630/def13aa6-0607-11e5-8298-647c26400800.png)

The full element should be:

```
<mods:physicalDescription>
  <mods:form authority="marcform">electronic</mods:form>
  <mods:digitalOrigin>born digital</mods:digitalOrigin>
  <mods:extent>1 photograph</mods:extent>
</mods:physicalDescription>
```

(Sample record is here, but it's been tombstoned: https://repository.library.northeastern.edu/files/neu:rx9149741)

**Comment by elizoller** [comment]
They'll all have the same values, right?

**Comment by dgcliff** [comment]
Just to be clear, this is not Pat's loads, but Cerberus bulk loaders, presumably from Marcom?

**Comment by sarahjeansweeney** [comment]
Yes to both your questions:
The physicalDescription values are the same for every Marcom load.
The example above is from the test load I did this morning with Marcom's Cerberus loader.

**Comment by dgcliff** [comment]
Ok, cool, thanks

**Comment by dgcliff** [comment]
Are there any records that need these values retroactively, or was this just your test file?

**Comment by sarahjeansweeney** [comment]
Nope, it was just the test file.

**Comment by dgcliff** [comment]
Huzzah, well that helps. I'll be pushing up Eli's fixes shortly after 5
