### ISSUE TITLE
XML Editor fails to validate MODS records with only non-topical headings

### ISSUE THREAD

**Issue by sarahjeansweeney** [NEU-Libraries/cerberus#748]
The XML editor fails validation when the user tries to save a record that has only non-topical headings:

![2015-05-26_1558](https://cloud.githubusercontent.com/assets/4663073/7919703/27445448-0868-11e5-818e-d96b03c7649a.png)

One keyword is required, but we don't mandate that the keyword be a topical term.

Here's the list of MODS non-topical headings:
geographic
temporal
titleInfo
name
geographicCode
genre
hierarchicalGeographic
cartographics
occupation

**Comment by dgcliff** [comment]
Yeah, definitely don't want to try and handle all those in cerberus code, I'll just let mods_display do the work for me. Thanks for the ticket.
