### ISSUE TITLE
Access rights for photo loaders

### ISSUE THREAD

**Issue by sarahjeansweeney** [NEU-Libraries/cerberus#749]
The photo loaders need to give read access to the following groups:

Marcom loader:
```
<access type="read">
  <machine>
    <group>northeastern:drs:faculty</group>
    <group>northeastern:drs:staff</group>
    <group>northeastern:drs:repository:staff</group>
    <group>northeastern:drs:marketing_and_communications:staff</group>
    <person>000000000</person>
  </machine>
</access>

```
Engineering loader:
```
<access type="read">
  <machine>
    <group>northeastern:drs:college_of_engineering:deans_office</group>
    <group>northeastern:drs:repository:staff</group>
    <person>000000000</person>
  </machine>
</access>
```
College of Professional Studies loader:
```
<access type="read">
  <machine>
    <group>northeastern:drs:college_of_professional_studies:media</group>
    <group>northeastern:drs:repository:staff</group>
    <person>000000000</person>
  </machine>
</access>
```

**Comment by sarahjeansweeney** [comment]
I'm sorry - I should have looked at the edit rights, too.

Right now it seems that only the depositor has edit rights for photos deposited using the loaders. At the very least DRS staff needs edit rights, too, as well as the loading group:

Marcom:
```
<access type="edit">
  <machine>
    <person>000000000</person>
    <group>northeastern:drs:repository:staff</group>
    <group>northeastern:drs:marketing_and_communications:staff</group>
  </machine>
</access>
```

Engineering:
```
<access type="edit">
  <machine>
    <person>000000000</person>
    <group>northeastern:drs:repository:staff</group>
    <group>northeastern:drs:college_of_engineering:deans_office</group>
  </machine>
</access>
```

College of Professional Studies:
Marcom:
```
<access type="edit">
  <machine>
    <person>000000000</person>
    <group>northeastern:drs:repository:staff</group>
    <group>northeastern:drs:college_of_professional_studies:media</group>
  </machine>
</access>
```

**Comment by elizoller** [comment]
Oops. I didn't think of that either.

**Comment by elizoller** [comment]
If  you give a group edit access, does it automatically give them read access or do I need to specify both?

**Comment by sarahjeansweeney** [comment]
I asked @dgcliff that same question earlier this week! Edit does grant read access, but David brought up a good point that if a group is given edit access, and edit access is removed, then they won't be able to read the file anymore. So it's best to explicitly grant both edit and read.

**Comment by elizoller** [comment]
Thanks @sarahjeansweeney

**Comment by sarahjeansweeney** [comment]
I just tested another upload (see: https://repository.library.northeastern.edu/files/neu:rx914b88k), and only the depositor has edit access on the file.

**Comment by elizoller** [comment]
I pushed it up on github but I didn't deploy.

**Comment by sarahjeansweeney** [comment]
Okay. Can you let me know when it's deployed?

**Comment by dgcliff** [comment]
Given that Pat's not loading, I'll do it today ~5sh

**Comment by sarahjeansweeney** [comment]
Thanks!

**Comment by dgcliff** [comment]
This is now up on production.

**Comment by sarahjeansweeney** [comment]
I just tested uploaded another file, and this is what I see:
```
<access type="read">
  <human/>
  <machine>
    <group>northeastern:drs:faculty</group>
    <group>northeastern:drs:staff</group>
  </machine>
</access>

<access type="edit">
  <human/>
  <machine>
    <person>000000000</person>
    <group>northeastern:drs:repository:staff</group>
    <group>northeastern:drs:marketing_and_communications:staff</group>
  </machine>
</access>
```
I thought we were explicitly giving groups read and edit access, not just relying on the edit privledges, or did I misunderstand?

**Comment by elizoller** [comment]
If I give them both read and edit, it doesn't actually give them both. It only gives them edit. I tried both programmatically and through the front end.

**Comment by dgcliff** [comment]
@sarahjeansweeney turns out the code doesn't allow for that (ours and Hydra's).

**Comment by sarahjeansweeney** [comment]
Okay, thanks.
