### ISSUE TITLE
Can't update title field text using the edit form

### ISSUE THREAD

**Issue by sarahjeansweeney** [NEU-Libraries/cerberus#750]
Jim uploaded this file earlier today:
https://repository.library.northeastern.edu/files/neu:rx914b53g

As he described it to me, he removed the filename from the title field on the upload form and hand-typed the title of his poster into the field, with capitalization.
After he saved and viewed his file, he noticed the capitalized letters had been reverted to lowercase.
He edited the metadata to capitalize the title and saved again, but the title remained uncapitalized.

![drspt](https://cloud.githubusercontent.com/assets/4663073/7993016/2b314d48-0ad1-11e5-9c6b-1c67ad25d140.png)

I tried editing his title, and I had success adding and removing words, but the title refuses to be capitalized.

I'm not sure what's different about Jim's file. I uploaded an hour earlier, and my file is properly capitalized, and I can edit the capitalization (https://repository.library.northeastern.edu/files/neu:rx914b41p).

Other fields in his record don't seem to be affected.

**Comment by dgcliff** [comment]
No idea - You can use the XML editor to save the changes though. I just did it successfully, than unfortunately unwound my changes by trying the form again.

**Comment by dgcliff** [comment]
I think it's probably related to the non-sort of The at the start, and some logic attached to that.

**Comment by dgcliff** [comment]
Yeah, it is. I've got a fix, will push it up soon.

**Comment by sarahjeansweeney** [comment]
Awesome, thanks!

**Comment by dgcliff** [comment]
@sarahjeansweeney Feel free to edit the title as needed now, it's up on production
