### ISSUE TITLE
Move and Delete requests for collections

### ISSUE THREAD

**Issue by sarahjeansweeney** [NEU-Libraries/cerberus#751]
Users should be able to request collections be moved or deleted, just like files. The Move and Delete tabs could live on the edit collection page:
![2015-06-15_1016](https://cloud.githubusercontent.com/assets/4663073/8161907/11b3b2fa-1348-11e5-95cc-94d1581fe52a.png)

**Comment by elizoller** [comment]
Will users be able to delete collections or tombstone them?
Interestingly enough there is actually a delete modal being formed on the collection pages but nothing ever triggers it.

**Comment by dgcliff** [comment]
Everything used to be delete-able, but that wasn't something that made it to production for obvious reasons ;)

I imagine it'll be request for tombstone, same as core file?

**Comment by elizoller** [comment]
Ok, thanks

**Comment by sarahjeansweeney** [comment]
Yes, now that we'll be adding handles to collections, I'll want the option to tombstone collections.

**Comment by elizoller** [comment]
Makes sense. So we'll want a warning about if you tombstone/move a collection, it tombstones/moves all of the items within that collection also?
In the admin panel, will we want a 'Manage Collections' section to show all the tombstoned collections, so you can actually delete theme from there?

**Comment by sarahjeansweeney** [comment]
Yes to both ... though would tombstoning a collection with files actually tombstone all the files it contains, as well?

**Comment by elizoller** [comment]
I would think so? But I don't know

**Comment by dgcliff** [comment]
Not entirely...A topic for the next meeting I think.

**Comment by elizoller** [comment]
Ok. I'll hold off then

**Comment by elizoller** [comment]
I think I've got most of the main functionality working on this but I ran into a question.
If you tombstone a collection and then revive a file from the collection without reviving the whole collection, where does that file live? It shows up in search again but you can't browse to it. Same goes for if you tombstone a collection with sub-collections and then revive a sub-collection or a file within the sub-collection.

**Comment by dgcliff** [comment]
I think the answer is - you can't. If it's possible, we put in some code to make sure the parent has to be live, first.

**Comment by elizoller** [comment]
Ok that makes sense. Thanks

**Comment by elizoller** [comment]
As far as I know this was closed with https://github.com/NEU-Libraries/cerberus/pull/768
