### ISSUE TITLE
Handles for Collections

### ISSUE THREAD

**Issue by sarahjeansweeney** [NEU-Libraries/cerberus#752]
A faculty member has requested that we create permanent URLs for collections. How feasible is it to create and display handles for new collections?

**Comment by dgcliff** [comment]
Not hard at all.

**Comment by sarahjeansweeney** [comment]
Excellent!
In that case, let's start generating handles for DRS collections. They URL can display below the collection title:
![2015-06-15_1110](https://cloud.githubusercontent.com/assets/4663073/8163316/554e6930-1350-11e5-9851-9ec98a84d820.png)

**Comment by dgcliff** [comment]
Will be created and displayed for future collections that are created - will need to run a job to retroactively give handles to existing collections
