### ISSUE TITLE
Collection "Edit" Link

### ISSUE THREAD

**Issue by sarahjeansweeney** [NEU-Libraries/cerberus#753]
I've noticed users have a hard time locating the "Edit" link for a collection:
![2015-06-15_1018](https://cloud.githubusercontent.com/assets/4663073/8162327/86a817f2-134a-11e5-8555-dd6e41ad2b4b.png)

1. Can this link be styled to make it more visible? Perhaps make it a button, similar to the "+Add" button?
2. Can the label be changed from "Edit" to "Manage Collection"

**Comment by elizoller** [comment]
@sarahjeansweeney  Do you want an icon?

**Comment by elizoller** [comment]
without icon?
![screen shot 2015-06-15 at 2 22 30 pm](https://cloud.githubusercontent.com/assets/5439169/8167093/fcf19d7e-1369-11e5-96c6-2af4e24c8c9f.png)

**Comment by sarahjeansweeney** [comment]
Sure. How about the pencil icon we use for the Edit tab on the metadata page?

**Comment by elizoller** [comment]
Do you want it the clear button like 'Add' button at the bottom of the collection page?
With Pencil:
![screen shot 2015-06-16 at 7 42 55 am](https://cloud.githubusercontent.com/assets/5439169/8182265/c666f5a0-13fb-11e5-9ead-19e23eec5ab6.png)
On hover:
![screen shot 2015-06-16 at 7 43 02 am](https://cloud.githubusercontent.com/assets/5439169/8182266/c66da922-13fb-11e5-8b68-b062140890e6.png)

**Comment by sarahjeansweeney** [comment]
Yes, the clear looks great!
