### ISSUE TITLE
Confirmation Modal

### ISSUE THREAD

**Issue by sarahjeansweeney** [NEU-Libraries/cerberus#754]
When a confirmation modal appears on a long page (say, an edit page for an item with a lot of subjects or groups), the user typically needs to scroll up the page to see modal. If the user doesn't know to scroll to the top of the page, the page just appears to have grayed out:

http://www.screencast.com/t/29iw7c40f1g

To replicate, try editing the metadata for this file on a typical screen (like a laptop): https://repository.library.northeastern.edu/files/neu:212654

Click "Cancel" at the bottom of the page
Notice the page appears to gray out and you need to scroll up to see the confirmation modal.

It's preferable that the modal display closer to where the user is on the page, or somehow bring the user to the modal.

**Comment by elizoller** [comment]
Blacklight comes with an add-on to Bootstrap called Improved Modals that overrides some of Bootstrap's base styling. This ended up causing some issues. Let me know if this doesn't seem to fix the issues. As far as I could tell with all the modals I tested, it resolves the issue. I'm still not entirely satisfied with the way modals are working but it makes more sense to overhaul them once we move to Bootstrap 3.

**Comment by sarahjeansweeney** [comment]
Thanks, Eli. I'll let you know if I see this again.
