### ISSUE TITLE
Display for long facet values

### ISSUE THREAD

**Issue by sarahjeansweeney** [NEU-Libraries/cerberus#755]
Very long facet values run out of the box:
![2015-06-15_1407](https://cloud.githubusercontent.com/assets/4663073/8169136/89835c68-1375-11e5-9752-3ec7a55173ff.png)

If possible, they should wrap around to the next line, preferably with an indent.

To replicate:
Click "Theses and Dissertations" from the homepage
Click "more Departments" under the Departments facet
Click "A-Z Sort"

**Comment by elizoller** [comment]
I have a fix for this. Will push it up in the a.m.
