### ISSUE TITLE
Depositor Info for Incomplete and In Progress Files

### ISSUE THREAD

**Issue by elizoller** [NEU-Libraries/cerberus#758]
Request to have depositor name and email for incomplete and in progress in the admin panel

**Comment by elizoller** [comment]
Is this what you're looking for?
![screen shot 2015-06-24 at 4 04 30 pm](https://cloud.githubusercontent.com/assets/5439169/8340204/fe62b710-1a8a-11e5-8085-6b6ddb4dae09.png)

**Comment by sarahjeansweeney** [comment]
Yes! I think we also talked about the time and date the upload started.

**Comment by elizoller** [comment]
Will do
