### ISSUE TITLE
XML editor swapping names when validated (and saved)

### ISSUE THREAD

**Issue by sarahjeansweeney** [NEU-Libraries/cerberus#760]
Kevin just reported this to me:

"After I validate an ETD’s XML  that contains a personal name in <mods:subject>, the DRS does the following 3 things:
 
1.     It strips the personal name from the subject node
2.     It does not display personal name subject
3.     It replaces the personal name in <mods:name> with the name from the subject node"

He also sent me two screenshots, but they're a little unclear. I was able to replicate the issue:

I edited a record (https://repository.library.northeastern.edu/files/neu:rx914b41p) that originally just had my name in the creator field to include one other name, and to add Kevin as a subject:
  ```
<mods:name type="personal" usage="primary">
      <mods:namePart type="given">Sarah</mods:namePart>
      <mods:namePart type="family">Sweeney</mods:namePart>
  </mods:name>
  <mods:name type="personal">
      <mods:namePart type="given">Matt</mods:namePart>
      <mods:namePart type="family">Berninger</mods:namePart>
  </mods:name>

  <mods:subject>
      <mods:name type="personal" authority="local">
            <mods:namePart>Grant, Kevin</mods:namePart>
      </mods:name>
  </mods:subject>
```

When I validated (not just saved, validated) my name was stripped out, Kevin's name replaced my own, and now the subject field is empty:

```
<mods:name type="personal" usage="primary">
      <mods:namePart type="given">Kevin</mods:namePart>
      <mods:namePart type="family">Grant</mods:namePart>
  </mods:name>
  <mods:name type="personal">
      <mods:namePart type="given">Matt</mods:namePart>
      <mods:namePart type="family">Berninger</mods:namePart>
  </mods:name>

  <mods:subject>
      <mods:name type="personal" authority="local">
          <mods:namePart/>
      </mods:name>
  </mods:subject>
```

Let me know if I can clarify anything.

**Comment by dgcliff** [comment]
This has got to do with how we process things so we can have first name and last name on the edit form. I'll look into it, but I imagine we'll end up with some kind of compromise.

**Comment by sarahjeansweeney** [comment]
This may be completely unrelated, but I might as well mention it here just in case it is. We noticed a batch of records with bizarre MODS records that don't match the records that were ingested. In these records the creator names and the titles are affected.

Here are the pertinent fields, as they were originally ingested:
```

    <mods:titleInfo usage="primary">
        <mods:title>Corn Poppy</mods:title>
    </mods:titleInfo>
    
    <mods:name authority="lcnaf" authorityURI="http://id.loc.gov/authorities/names" valueURI="http://id.loc.gov/authorities/names/n80161602" type="personal">
        <mods:namePart>Le Moyne de Morgues, Jacques</mods:namePart>
        <mods:namePart type="date">1533?-1588</mods:namePart>
        <mods:role>
            <mods:roleTerm authority="marcrelator" authorityURI="http://id.loc.gov/vocabulary/relators" valueURI="http://id.loc.gov/vocabulary/relators/art" type="text">Artist</mods:roleTerm>
        </mods:role>
    </mods:name> 
```

This is what the MODS looks like in the DRS:

```
    <mods:titleInfo usage="primary">
        
    <mods:nonSort/></mods:titleInfo>
    
    <mods:name authority="lcnaf" authorityURI="http://id.loc.gov/authorities/names" valueURI="http://id.loc.gov/authorities/names/n80161602" type="personal" usage="primary">
        <mods:namePart/>
        <mods:namePart type="date">1533?-1588</mods:namePart>
        <mods:role>
            <mods:roleTerm authority="marcrelator" authorityURI="http://id.loc.gov/vocabulary/relators" valueURI="http://id.loc.gov/vocabulary/relators/art" type="text">Artist</mods:roleTerm>
        </mods:role>
    <mods:namePart type="given">Jacques</mods:namePart><mods:namePart type="family">Morgues</mods:namePart></mods:name> 
    
<mods:relatedItem type="series"> <mods:titleInfo> <mods:title>Corn Poppy</mods:title> </mods:titleInfo> </mods:relatedItem>
```

Again, this may not be related, but I suppose it's worth noting here. 
Here's an example: https://repository.library.northeastern.edu/files/neu:344110

**Comment by dgcliff** [comment]
Moved the name extraction logic to the edit action with 8c9e44f920bf8683cf201dd6ce6ef00a7d02f5e8

This doesn't solve the intractable problem of the edit from mangling hand-made XML, but it does mean it can always be fixed with the XML editor. The edit action is rarely used, and almost never for records created/edited by hand (XML editor or Fedora direct ingestion).

So, in short, this reduces the problem, and allows for the XML editor to be a way for all issues with metadata to be fixed if need be.

**Comment by dgcliff** [comment]
This has been merged in, but isn't up on production yet. @sarahjeansweeney I'll let you know when that occurs.

**Comment by dgcliff** [comment]
This is now up on production.
