### ISSUE TITLE
Clicking the Edit tab causes an error

### ISSUE THREAD

**Issue by sarahjeansweeney** [NEU-Libraries/cerberus#761]
I received an error when I clicked the Edit tab for this file: https://repository.library.northeastern.edu/files/neu:rx914p75k

![2015-06-30_0905](https://cloud.githubusercontent.com/assets/4663073/8431388/1ebc7b7e-1f07-11e5-8039-8c3b0caaddd8.png)

I've tried a opening the edit page for a few other files, all with the same error, so this seems to be widespread.

**Comment by elizoller** [comment]
I think it's related to the fix David put in for #760

**Comment by dgcliff** [comment]
Fixed with e5b3114b1a610c8d0d76e6796bed7e95ca16ff1a
