### ISSUE TITLE
Minor change for Edit button on Collections

### ISSUE THREAD

**Issue by dgcliff** [NEU-Libraries/cerberus#762]
I rarely care about this kind of things, and am happy to be talked out of it, but would anyone mind if they looked solid instead of clear, with a bit of spacing bump at the top, like so?

![screenshot 2015-07-02 09 55 12](https://cloud.githubusercontent.com/assets/459084/8478668/defcc98a-20a0-11e5-9e27-8cfd504e661a.png)

The current clear on grey seems a bit weird to me.

**Comment by sarahjeansweeney** [comment]
Looks good to me!
