### ISSUE TITLE
Changes to sort menu

### ISSUE THREAD

**Issue by sarahjeansweeney** [NEU-Libraries/cerberus#763]
After discussing the sort dropdown menu for the Toolkit sites, I think we should simplify the DRS sort dropdown menu a bit. I think it's safe to assume that users don't often sort by oldest, so let's remove the oldest to newest sort options for date. The labels should be changed, as well (with capitalization):

Title
Creator, A-Z
Creator, Z-A
Recently created
Recently added
Relevance

**Comment by dgcliff** [comment]
Sounds good

**Comment by elizoller** [comment]
Like this? Or remove the arrows?
![screen shot 2015-07-06 at 1 38 30 pm](https://cloud.githubusercontent.com/assets/5439169/8528903/5e1eda28-23e4-11e5-940d-32d8879c59c9.png)

**Comment by sarahjeansweeney** [comment]
I think the arrows can be removed.

**Comment by elizoller** [comment]
![screen shot 2015-07-06 at 1 42 03 pm](https://cloud.githubusercontent.com/assets/5439169/8528968/db847e32-23e4-11e5-8336-5ce7c0e38de4.png)

**Comment by sarahjeansweeney** [comment]
Can Recently created and Recently added be swapped? Otherwise, perfect!
