### ISSUE TITLE
Static page for IRis handles

### ISSUE THREAD

**Issue by sarahjeansweeney** [NEU-Libraries/cerberus#764]
Not all of the IRis content is being migrated to the DRS, so we'll need a static DRS page to use as a destination for the handles without DRS content. That page will contain this text:

"The file you are trying to reach is currently unavailable.

In July 2015 Northeastern University Libraries transitioned from IRis, our previous repository platform, to the newly redesigned Digital Repository Service (DRS) and we are in the process of reviewing some IRis content to determine its suitability for permanent preservation.

If you feel this file should be permanently preserved, please contact Library-Repository-Team@neu.edu

For more information about the DRS and the transition from IRis, please visit the Library's DRS resource page [http://library.northeastern.edu/services/drs-digital-repository-service]."

This text may change, so could it be added to the yaml file?

**Comment by dgcliff** [comment]
That would be a good place to put it I think. Given that it's mild complexity (links, line breaks) we might need to do that together to make sure it parses correctly

**Comment by sarahjeansweeney** [comment]
If it's complex enough to require two people to make edits, maybe it belongs somewhere else?

**Comment by dgcliff** [comment]
It'll be fine, but I just know that Steven had put one in there that required a bit of code syntax is all. A good thing for us to both learn.

**Comment by elizoller** [comment]
Is this still needing to happen? If so, I can probably help with yaml file syntax.

**Comment by sarahjeansweeney** [comment]
Yes, this definitely still needs to happen.

**Comment by elizoller** [comment]
How would a user land on this page?

**Comment by sarahjeansweeney** [comment]
For items we are not migrating from IRis, we will replace its specific IRis URL on the handle server with the URL for this page. That way, if the user follows the handle for an item that was not migrated, they would end up on this static but informative page rather than just the generic redirect error for IRis URLs.

**Comment by elizoller** [comment]
Ah ok. I don't really know what's involved in the replacing of URLs on the handle server but I will look into the static page component.

**Comment by sarahjeansweeney** [comment]
Patrick will take care of the handle replacement. We just need a page URL to point to.

**Comment by elizoller** [comment]
Preferences for path and page title?

**Comment by sarahjeansweeney** [comment]
Path: /iris

Title: "IRis content in the DRS"

I tweaked the text in my original comment a bit:

"The file you are trying to reach is currently unavailable.

In July 2015 Northeastern University Libraries transitioned from IRis, our previous repository platform, to the newly redesigned Digital Repository Service (DRS) and we are in the process of reviewing some IRis content to determine its suitability for permanent preservation.

If you feel this file should be permanently preserved, please contact Library-Repository-Team@neu.edu

For more information about the DRS and the transition from IRis, please visit the Library's DRS resource page [http://library.northeastern.edu/services/drs-digital-repository-service]."

**Comment by elizoller** [comment]
http://cerberus.library.northeastern.edu/iris

**Comment by sarahjeansweeney** [comment]
Excellent - thank you!

**Comment by dgcliff** [comment]
We can close this now right?
