### ISSUE TITLE
Marketing uploader won't accept valid JPG

### ISSUE THREAD

**Issue by sarahjeansweeney** [NEU-Libraries/cerberus#765]
It seems Matt is having trouble using the Marketing loader. This morning he tried to upload 12 files (I'll email two sample files separately), all of which failed: https://repository.library.northeastern.edu/loaders/marcom/report/7

The error is "File is not a JPG image", but the files are indeed JPGs according to FITS.

**Comment by dgcliff** [comment]
I can reproduce this on staging, so I'll look into it

**Comment by dgcliff** [comment]
This seems to be as a result of the "&" character in the file names. Matt can rename them, or wait until we have a fix in place.

**Comment by sarahjeansweeney** [comment]
Okay, I'll let him know. Thanks!
