### ISSUE TITLE
Title sort & nonSort

### ISSUE THREAD

**Issue by sarahjeansweeney** [NEU-Libraries/cerberus#766]
When files are sorted by title, the records that use the MODS nonSort field to isolate the initial article are bumped to the bottom of the sort, rather than being interfiled as they should. The best example of this is the ETD collection. If you choose to show 100 per page and skip to page 16, you'll see "The academic and social impact..." follows "Zero tolerance policing":

![2015-07-06_1040](https://cloud.githubusercontent.com/assets/4663073/8525023/857df7f6-23cc-11e5-8e4c-b41194c8f7e3.png)

To complicate things, there are some collections where the sort does seem to respect nonSort (the Honors Junior/Senior Projects collection [https://repository.library.northeastern.edu/collections/neu:rx914k236], for example). The default sort is by title, and you'll see the first item in the list starts with "The", which is stored in nonSort, and a few others, as well ("The Cambridge Ring"). If you skip to the end of the list, though, you'll see 11 records with nonSort fields forced to the bottom of the list.

**Comment by sarahjeansweeney** [comment]
Looking at the examples again, I think this is caused by capitalization. If that's true, is it possible for sorting to ignore capitalization?

**Comment by dgcliff** [comment]
Probably, though I think that'll involve some investigation in how Blacklight and Solr co-operate

**Comment by dgcliff** [comment]
I  believe I have a solution for this (and it is related to the capitalization). Testing it out at the moment.
