### ISSUE TITLE
New loader for EMSA/EMC

### ISSUE THREAD

**Issue by sarahjeansweeney** [NEU-Libraries/cerberus#767]
Julio Chuy, who loads files for CPS, is now also working with Enrollment Management and Student Affairs (EMSA), and he'd like a loader for the EMSA marketing group (EMC), too. 

Here are the basic details you'll need to customize the loader:
*Collection PID: neu:5m60qx99w

*Access rights:
They want to allow the full NU community to discover just the metadata and thumbnails for each file, a group of EMSA staff to be able to download the files, and a smaller group of EMC staff to be able to edit metadata for the files.
Core files/thumbnails:
```
<rightsMetadata xmlns="http://hydra-collab.stanford.edu/schemas/rightsMetadata/v1" version="0.1">
  <access type="read">
    <machine>
      <group>northeastern:drs:all</group>
    </machine>
  </access>
  <access type="edit">
    <machine>
      <group>northeastern:drs:enrollment_management:emc:emc_admin</group>
      <group>northeastern:drs:repository:staff</group>
      <person>000000000</person>
    </machine>
  </access>
</rightsMetadata>
```
Master and derivatives:
```
<rightsMetadata xmlns="http://hydra-collab.stanford.edu/schemas/rightsMetadata/v1" version="0.1">
  <access type="read">
    <machine>
      <group>northeastern:drs:enrollment_management:emc:emc_admin</group>
      <group>northeastern:drs:enrollment_management:emc:emc_staff</group>
      <group>northeastern:drs:repository:staff</group>
      <person>000000000</person>
    </machine>
  </access>
  <access type="edit">
    <machine>
      <group>northeastern:drs:enrollment_management:emc:emc_admin</group>
      <group>northeastern:drs:repository:staff</group>
      <person>000000000</person>
    </machine>
  </access>
</rightsMetadata>
```
*Derivative sizes:
Small: 600
Large: 1400

*Standard statement for mods/accessCondition: 
```<mods:accessCondition type="use and reproduction">Enrollment Marketing and Communications images are for use only within the context of Northeastern University. Appropriate uses include: Northeastern University-related websites, Northeastern University-based print/web publications and for speaking appearances when acting as a representative of Northeastern University. Images should be credited: "(Insert Photographer's Name)/Northeastern University.” Images are not to be used for self-promotional purposes outside of Northeastern University or in commercial/external publications such as advertisements, books or magazines without written permission from Northeastern Enrollment Marketing and Communications. Full size downloads are restricted to Enrollment Management and Student Affairs staff. For more information, please email Enrollment Marketing and Communications at Gnphotorequest@neu.edu.</mods:accessCondition>```

Let me know if I'm missing something.

**Comment by sarahjeansweeney** [comment]
I just added the rights statement and root collection PID. Let me know if there's anything else you need to create the loader.

**Comment by elizoller** [comment]
@sarahjeansweeney will there be an northeastern:drs:repository:loaders:emsa group for drs users who have access to the loaders?

**Comment by sarahjeansweeney** [comment]
Yes, sorry about that. The loader group is northeastern:drs:repository:loaders:emsa_emc

**Comment by elizoller** [comment]
Ok. thanks!

**Comment by elizoller** [comment]
@sarahjeansweeney Will EMSA/EMC want sub-collections under "Enrollment Marketing and Communications Media" or will it all go into that collection? Up until now, the loaders have had a parent collection and then sub-collections which a load goes into so if they don't want sub-collections, I'd probably just go up a level to "Enrollment Marketing and Communications" - though that is a community.

**Comment by sarahjeansweeney** [comment]
I just uploaded a file using the new loader (http://cerberus.library.northeastern.edu/files/neu:hx11xh41m). The load was successful, but it looks like the permissions need to be tweaked. The core file and thumbnails are good, but the master file and the derivatives shouldn't be available to all, just to emc admins and staff:
```
<rightsMetadata xmlns="http://hydra-collab.stanford.edu/schemas/rightsMetadata/v1" version="0.1">
  <access type="read">
    <machine>
      <group>northeastern:drs:enrollment_management:emc:emc_admin</group>
      <group>northeastern:drs:enrollment_management:emc:emc_staff</group>
      <group>northeastern:drs:repository:staff</group>
      <person>000000000</person>
    </machine>
  </access>
  <access type="edit">
    <machine>
      <group>northeastern:drs:enrollment_management:emc:emc_admin</group>
      <group>northeastern:drs:repository:staff</group>
      <person>000000000</person>
    </machine>
  </access>
</rightsMetadata>
```

**Comment by elizoller** [comment]
I'm looking into it. Thanks

**Comment by elizoller** [comment]
fixed with #808

**Comment by sarahjeansweeney** [comment]
The rights look great for the new EMSA loader. I tried it out on staging using Julio's test account (which I want him to try first), but he doesn't have permission to view the file once it's been uploaded:

http://cerberus.library.northeastern.edu/files/neu:hx11xj22m

![2015-08-28_1015](https://cloud.githubusercontent.com/assets/4663073/9548301/d6965c94-4d6d-11e5-996b-0a6307cbab54.png)

**Comment by dgcliff** [comment]
Probably just a matter of fake grouper values, I'll adjust them

**Comment by dgcliff** [comment]
@sarahjeansweeney adjusted, and data has been reset. Have another go, let me know if it's fixed

**Comment by sarahjeansweeney** [comment]
I just tried another load and everything looks good - thanks!
