### ISSUE TITLE
Marcom Loader "contains NilClass data" error

### ISSUE THREAD

**Issue by sarahjeansweeney** [NEU-Libraries/cerberus#769]
Matt encountered two errors this morning when he tried to load a few files:
1) All files returned an "Error - contains NilClass data" error message
2) When he clicked "View IPTC" he encountered a system error.

Here are the screenshots he sent me:

![screen shot 2015-07-07 at 11 37 09 am 2](https://cloud.githubusercontent.com/assets/4663073/8551178/0647aaf4-24a3-11e5-8435-81c3a6727259.png)

![screen shot 2015-07-07 at 12 05 06 pm 2](https://cloud.githubusercontent.com/assets/4663073/8551181/0949d01a-24a3-11e5-9699-76fe9ac57a8d.png)

**Comment by elizoller** [comment]
Any chance you have one of those files? The fix I made yesterday shouldn't have affected the fixes we had in there for invalid characters but I'm wondering if it encountered invalid characters that weren't already on the list?

**Comment by dgcliff** [comment]
Looking at the code, the error is complaining that there are Nil values in the IPTC. If we could have a look at one of the example files, it'll help determine whether it did the right thing or not.

**Comment by sarahjeansweeney** [comment]
I've asked him for a sample file. While we're waiting, he did send me another screenshot of one file's IPTC, which may or may not be helpful: 
![screen shot 2015-07-07 at 11 47 27 am](https://cloud.githubusercontent.com/assets/4663073/8551746/7007d4c0-24a6-11e5-9628-4239b0769acf.png)

**Comment by dgcliff** [comment]
Hm, can't see anything obvious from that
