### ISSUE TITLE
Single upload error

### ISSUE THREAD

**Issue by sarahjeansweeney** [NEU-Libraries/cerberus#770]
An Archives student had trouble uploading a single file this morning. Here's what she described:

"The page stalled when I attempted to upload my first file (hence, the three uploads of A030193). Now, I cannot continue uploading until the "incomplete records" have been addressed. Perhaps this is a normal function of the DRS, but when I attempt to delete the record on the "Rescue Incomplete Files" page, I get a message stating that the parent is either not specified or invalid."

I asked her to explain what she meant by "the page stalled":

"I'm guessing the process stalled between the initial upload page and the metadata page since the file did upload. When I went to complete the metadata, I encountered a blank screen (on each occasion) instead of the metadata page. Eventually, I exited out of the Boston-Bouve collection, re-entered, and then accessed one of the A030193 records to complete the metadata.'

**Comment by dgcliff** [comment]
They couldn't delete because of a bug, which I fixed with 80c29677b357a62f400ddcec85eafe9b2e48bd11

It didn't stall, it was processing. I'm not sure what we can do beyond what we've already done (progress bar, the please wait button). @elizoller could you add a spining icon maybe? It was still working, and they navigated away. They need to wait.

**Comment by dgcliff** [comment]
I've added the same spinning icon as the XML editor has, but I'm not sure that'l do anything to change their actions.

**Comment by elizoller** [comment]
Spinner looks good to me. Should we fade the rest of the page out like when you open a modal?

**Comment by sarahjeansweeney** [comment]
Oddly enough, I was able to replicate the blank page on staging. I clicked upload and this page appeared with this URL:
http://cerberus.library.northeastern.edu/files
![2015-07-09_0913](https://cloud.githubusercontent.com/assets/4663073/8596008/ca0a70a2-261a-11e5-8d5e-b69ee8ef9df4.png)
The file did upload, it's just stuck in "Incomplete".

I'm able to upload in production just fine.

**Comment by sarahjeansweeney** [comment]
Also, yes @elizoller, I think fading the page is a good idea, too.

**Comment by elizoller** [comment]
Deployed David's most recent fixes to staging and upload is working again
