### ISSUE TITLE
Clear Loader History

### ISSUE THREAD

**Issue by sarahjeansweeney** [NEU-Libraries/cerberus#771]
Is it possible to add a "Clear History" button to the Loader page?

**Comment by elizoller** [comment]
Maybe just show the last 10 loads or something?

**Comment by elizoller** [comment]
So I had the sort backwards on the loaders until https://github.com/NEU-Libraries/cerberus/commit/084bb1b2156dd516e635440c40a3109146514693 I am wondering if you'd still like to be able to clear the history or the fact that the most recent loads are first is sufficient?
If you still want to clear, will probably do something like tombstoning, where the actual reports will still exist in the system but they will be hidden from view.

**Comment by sarahjeansweeney** [comment]
I think the most recent loads is sufficient. We'll see how EMSA feels about the load history once they're ready to start loading.
