### ISSUE TITLE
Creator facet includes subject names

### ISSUE THREAD

**Issue by sarahjeansweeney** [NEU-Libraries/cerberus#775]
The Creator facet is pulling in both creator names and subject names, when it should just be pulling in the creator names:

![2015-07-09_1440](https://cloud.githubusercontent.com/assets/4663073/8604981/f35ad37c-264f-11e5-8220-26c5d6fdbda3.png)

The best example of this is the Archive's Hall of Fame collection (https://repository.library.northeastern.edu/collections/neu:rx9149830). The whole collection has a single creator value (Northeastern University (Boston, Mass.). Dept. of Athletics.), but the creator facet for the collection lists the names of all the hall of fame honorees, which are stored in MODS subject fields:
```
    <mods:subject>
        <mods:name type="personal" authority="local">
            <mods:namePart/>     
            <mods:namePart type="given">Daniel R.</mods:namePart>
            <mods:namePart type="family">Ross</mods:namePart>
        </mods:name>
    </mods:subject>
```

**Comment by dgcliff** [comment]
This is fixed in code, but will need a solr reindex to clear up the symptom
