### ISSUE TITLE
Dates in creator facet

### ISSUE THREAD

**Issue by sarahjeansweeney** [NEU-Libraries/cerberus#776]
The creator facet is adding separate creator entries for the dates in names:

![2015-07-09_1549](https://cloud.githubusercontent.com/assets/4663073/8605345/b7add632-2652-11e5-8686-892101c6049f.png)

So in the example above, Marjorie Bouve is the creator of the items, but the dates below her name are her birth and death dates:

```
  <mods:name usage="primary" authority="local">
    <mods:namePart>Bouv&#xE9;, Marjorie</mods:namePart>
    <mods:namePart type="date">1879-1970</mods:namePart>
  </mods:name>
```

The dates should appear at the end of her name ("Bouve, Marjorie (1879-1970)"). If that's not feasible, the date should be ignored in the facet display.

**Comment by elizoller** [comment]
do you know if this and #775 happening prior to yesterday?

**Comment by sarahjeansweeney** [comment]
I can't say for sure about either, though #775 was reported to me by Daniel in Archives, and he seemed to think that "More" was available earlier in the week.

**Comment by elizoller** [comment]
Ok I'll look into them. I'm pretty sure the 'more' was because of the facet limit changes for the API. Not sure about these other issues though.

**Comment by sarahjeansweeney** [comment]
Sorry, I confused issues. Daniel didn't mention when he noticed that subjects were showing up in the creator facet.

**Comment by dgcliff** [comment]
Fixed in code (date will no longer show as part of name facets), but will need a solr reindex to clear up the symptom
