### ISSUE TITLE
Can't edit ETD collections?

### ISSUE THREAD

**Issue by sarahjeansweeney** [NEU-Libraries/cerberus#777]
I can't edit ETD collections through the interface. The rights metadata grants edit permissions to DRS staff, but I don't see the "Manage Collection" button. Is this because these are technically smart collections? This isn't a high priority (I can make the changes in Fedora), I just want to make sure I'm not missing something.

Example: https://repository.library.northeastern.edu/collections/neu:44

**Comment by dgcliff** [comment]
Just because it's a smart collection. Putting in a patch so that the admin user can still do it (caveat emptor)

**Comment by sarahjeansweeney** [comment]
Not sure if this is related (if not, I'll open a separate ticket), but when I click the "Manage Collection" button for any ETD collection (https://repository.library.northeastern.edu/collections/neu:182 , https://repository.library.northeastern.edu/collections/neu:42) for example, I get a permissions error ("Sorry, you don't have permission to access this page.")

**Comment by dgcliff** [comment]
Yeah, this is because we have old code that sits in between rights metadata. Can see where it is, and do a similar patch
