### ISSUE TITLE
Can Created At/Updated At Time in the admin panel Manage Files table have eastern time zone?

### ISSUE THREAD

**Issue by sarahjeansweeney** [NEU-Libraries/cerberus#780]
The admin panel's Manage Files table displays the correct date for an upload, but the wrong time. In the example below the files were uploaded around 2:40pm, so the time should be 14:39, not 18:39:
![2015-07-22_1445](https://cloud.githubusercontent.com/assets/4663073/8834453/488f855e-3082-11e5-9486-dcee9354bfe6.png)

**Comment by dgcliff** [comment]
I imagine this is a timezone thing. UTC instead of EST, etc.

**Comment by dgcliff** [comment]
https://www.google.com/webhp?sourceid=chrome-instant&ion=1&espv=2&ie=UTF-8#q=18%3A39+UTC+in+EST

**Comment by elizoller** [comment]
Since this is low priority, I won't deploy to production. I will deploy to staging though.
