### ISSUE TITLE
MODS attributes for handles

### ISSUE THREAD

**Issue by sarahjeansweeney** [NEU-Libraries/cerberus#782]
When MODS records are created through the loader or the interface the mods:identifier field for handles only includes a type="uri" attribute:
```
<mods:identifier type="uri">http://hdl.handle.net/2047/D20128439</mods:identifier>
```

The mods:identifier field for handles should use the type="handle" attribute and also include a displayLabel attribute:

```
<mods:identifier displayLabel="Permanent URL" type="handle">http://hdl.handle.net/2047/d20181287</mods:identifier>
```

**Comment by elizoller** [comment]
d087157817b39e3bacf3daa95884e51f38b4dd15 fixes this for items uploaded in the future. We'll probably need to write a job to fix the previous uploaded ones which is best left in the hands of David.
