### ISSUE TITLE
Author and Title Browse

### ISSUE THREAD

**Issue by sarahjeansweeney** [NEU-Libraries/cerberus#784]
We need to give users the option to browse by unique names (personal and corporate) and unique titles. We can discuss where/how in our meeting tomorrow.

**Comment by sarahjeansweeney** [comment]
Here's the example from BC: http://lawdigitalcommons.bc.edu/authors.html

**Comment by elizoller** [comment]
Is the browse by author and title at the collection level or system level?

**Comment by elizoller** [comment]
Is this creator/author and title or subject?

**Comment by elizoller** [comment]
Collection page:
<img width="1215" alt="screen shot 2015-10-08 at 11 34 55 am" src="https://cloud.githubusercontent.com/assets/5439169/10371320/c679a1a0-6db0-11e5-85ac-d09e75566cb5.png">
Author list page:
<img width="1216" alt="screen shot 2015-10-08 at 11 35 02 am" src="https://cloud.githubusercontent.com/assets/5439169/10371322/c7d0da0a-6db0-11e5-9731-88129b47ff9f.png">

**Comment by sarahjeansweeney** [comment]
The browse lists should be at the community and collection level. Just author and title are lists fine. The mockup for author looks great. Will the title list also have a count? If so, that's probably not necessary (most title will just have a count of 1).

**Comment by elizoller** [comment]
No pagination, have an A-Z anchor nav at the top. 
Author list requires count (title list does not). Author list will basically use the facet values where as title list will be a search that only returns titles. 
Hide these buttons if there are no items - this will take into account permissions.

**Comment by sarahjeansweeney** [comment]
Two things I noticed testing out this feature in the test EMSA collection (http://cerberus.library.northeastern.edu/communities/neu:rx915867k):
* Author browse: Clicking on the author's name in the browse list brings me to an empty page of results
![2015-12-11_1413](https://cloud.githubusercontent.com/assets/4663073/11753684/91db4a34-a014-11e5-80c5-8f230164b53d.png)

* Title browse: There should be 45 files in the title list, but I only see 10. I think we talked about all files displaying on the same page (hence the A-Z list).
![2015-12-11_1436](https://cloud.githubusercontent.com/assets/4663073/11753689/98473d10-a014-11e5-9d4a-6acf0b785b93.png)

**Comment by elizoller** [comment]
Ah thanks!
I have to add scope on the author links since the authors could be in nested collections.
And I'll fix the number visible on the title list.

**Comment by elizoller** [comment]
Do you want the author list default sorted by author name or default sorted by count? Also do you want that called creator or author because I realized I was inconsistent?

**Comment by sarahjeansweeney** [comment]
Author/creator list should be sorted by name, and let's use Creator instead of Author. Thanks!

**Comment by elizoller** [comment]
Is this supposed to be disabled for neu:1?

**Comment by elizoller** [comment]
e41ca8cb248b7dd45fb9089d55cad44c160753a5 fixes the creator links
322a496358b5a47ba55a91ed7cf6c71785cdc4e7 fixes creator count
2949ffa5355cee2e54390f33ded96bf0fed8e375 fixes title count

**Comment by elizoller** [comment]
merged with https://github.com/NEU-Libraries/cerberus/pull/887

**Comment by dgcliff** [comment]
I've commented out this functionality for now, as per this commit message 5384ab2d2ea554fa81f89df1ab41ae7247c39c95

```Disabling browse lists - theres a hard cap at 100 for title list I can't fix, and even with improvements, neu:466 Uni Libraries community takes 15 seconds to load. Not really acceptable. We'll need to rearchitect if we want to keep this feature```

Some communities/partials were taking so long as to time out.

**Comment by dgcliff** [comment]
I think this can be closed now.
