### ISSUE TITLE
API Item Response Creator combines with Contributor

### ISSUE THREAD

**Issue by elizoller** [NEU-Libraries/cerberus#787]
In the front end the creator and contributor are separate MODS displays
ie. https://repository.library.northeastern.edu/files/neu:344505
![screen shot 2015-08-11 at 2 56 07 pm](https://cloud.githubusercontent.com/assets/5439169/9207044/2f74d7d8-4039-11e5-82dd-ecd47851222d.png)
but the API returns both the creator and contributor as contributors
ie. https://repository.library.northeastern.edu/api/v1/files/neu:344505
![screen shot 2015-08-11 at 2 57 25 pm](https://cloud.githubusercontent.com/assets/5439169/9207064/4c310662-4039-11e5-808c-93bcb3286d66.png)

**Comment by sarahjeansweeney** [comment]
I think when the MODS display gem generates the Creator display it only uses personal names that have the "Author" attribute. All other role terms are considered "Contributors", which isn't ideal (many other roles can be creators).

**Comment by dgcliff** [comment]
Eli and I had a look at this, I think the discrepancy might be due to how the API generates the JSON (missing some mods_display logic). Shouldn't be too hard to fix.

**Comment by dgcliff** [comment]
@elizoller appears to be fixed - I stole the metadata form your example and put it on handsome squidward on staging

http://cerberus.library.northeastern.edu/files/neu:hx11xg294
http://cerberus.library.northeastern.edu/api/v1/files/neu:hx11xg294
