### ISSUE TITLE
Missing thumbnails for embargoed files

### ISSUE THREAD

**Issue by sarahjeansweeney** [NEU-Libraries/cerberus#788]
The thumbnails for recently uploaded files with an embargo are displaying as broken images for logged out users:

![2015-08-14_1212](https://cloud.githubusercontent.com/assets/4663073/9278276/c7c15cfa-427d-11e5-9086-8c6dda152028.png)

I can see the thumbnails, but only when I'm logged in, and I'm not sure what non-DRS staff see.

Here are two examples:
https://repository.library.northeastern.edu/files/neu:rx915q09c
https://repository.library.northeastern.edu/files/neu:rx915q24g

The rightsMetadata record for the core file looks fine, and the thumbnails are accessible through the back end: http://nb4676.neu.edu:8080/fedora/objects/neu:rx915q11d/datastreams

Older files don't seem to have this problem:
https://repository.library.northeastern.edu/files/neu:336784

Some background:
When Kevin uploads new ETDs that are embargoed, I add the embargo date to the core file's rightsMetadata record, but just the core file, not the thumbnails' rightsMetadata record.

**Comment by dgcliff** [comment]
Something or someone has set the content objects rights permissions incorrectly

http://nb4676.neu.edu:8080/fedora/objects/neu:rx915q11d/datastreams/rightsMetadata/content

```
<rightsMetadata xmlns="http://hydra-collab.stanford.edu/schemas/rightsMetadata/v1" version="0.1">
<copyright>
<human type="title"/>
<human type="description"/>
<machine type="uri"/>
</copyright>
<access type="discover">
<human/>
<machine/>
</access>
<access type="read">
<human/>
<machine/>
</access>
<access type="edit">
<human/>
<machine>
<person>000000000</person>
<group>northeastern:drs:repository:staff</group>
</machine>
</access>
<embargo>
<human/>
<machine/>
</embargo>
</rightsMetadata>
```

**Comment by dgcliff** [comment]
Is he making private files, that you're making public manually?

**Comment by sarahjeansweeney** [comment]
Yes, he sets them to private, I add the embargo date, then make them public. Up until recently I was doing it in the Edit form, though this week I've been doing it through the admin tool.

**Comment by dgcliff** [comment]
So, the problem with that it's stranding the content objects - if you don't use the edit form (and I understand why), you'll have to make sure to go to each of the main objects (pdf, word, image etc.) *and* the thumbnail file and make sure they all have the right permissions

**Comment by sarahjeansweeney** [comment]
Okay, so to fix the two existing files with mismatched metadata, I'll need to correct the object and thumbnail records so they match the core file, correct? Would a reindex be needed for the thumbnail to display, or would clearing the browser cache be enough?

**Comment by dgcliff** [comment]
Clearing the cache should be enough (if even that). Just to be clear, the content objects don't need the embargo value, but just the public value. So the above one I quoted would be changed to

```
<rightsMetadata xmlns="http://hydra-collab.stanford.edu/schemas/rightsMetadata/v1" version="0.1">
<copyright>
<human type="title"/>
<human type="description"/>
<machine type="uri"/>
</copyright>
<access type="discover">
<human/>
<machine/>
</access>
<access type="read">
<human/>
<machine>
<group>public</group>
<machine/>
</access>
<access type="edit">
<human/>
<machine>
<person>000000000</person>
<group>northeastern:drs:repository:staff</group>
</machine>
</access>
<embargo>
<human/>
<machine/>
</embargo>
</rightsMetadata>
```

**Comment by dgcliff** [comment]
Editing the rightsMetadata should trigger a reindex via the Solrizer daemon anyhow

**Comment by sarahjeansweeney** [comment]
Oh, of course! Thanks for clarifying.
