### ISSUE TITLE
Titles missing from Admin Panel/Manage Files page

### ISSUE THREAD

**Issue by sarahjeansweeney** [NEU-Libraries/cerberus#792]
There are currently eight tombstoned items: https://repository.library.northeastern.edu/admin/files
For some reason the list only displays the title for the most recently tombstoned file:

![2015-08-20_1404](https://cloud.githubusercontent.com/assets/4663073/9391385/75fa0838-4744-11e5-936c-994039c60e3b.png)

The tombstoned files do have titles, they just seem to be missing from the table.

**Comment by dgcliff** [comment]
That'll be as a result of my changes I think - probably pointing to a solr field that no longer exists. I'll look into it.

**Comment by sarahjeansweeney** [comment]
We should have a label that falls below "low", maybe something like "Only affects Sarah".

**Comment by dgcliff** [comment]
lol - Well Sarah is just as important as anyone

**Comment by sarahjeansweeney** [comment]
Perhaps, but more importantly I can be pretty patient :)

**Comment by dgcliff** [comment]
so, this is a quirk of tombstoned files, they just need to be reindexed - doing so now (campus feature should be visible if you do a hard refresh)

**Comment by dgcliff** [comment]
all future tombstoned files should be fine

**Comment by dgcliff** [comment]
All sorted
