### ISSUE TITLE
Admin panel community search isn't retrieving communities

### ISSUE THREAD

**Issue by sarahjeansweeney** [NEU-Libraries/cerberus#795]
I'm trying to add a new faculty user (https://repository.library.northeastern.edu/admin/employees/neu:rx915x82m/edit) to a community that I know already exists in the DRS (https://repository.library.northeastern.edu/communities/neu:77).

A search for "business" retrieves nothing:

![2015-08-21_1540-1](https://cloud.githubusercontent.com/assets/4663073/9417667/377db6c6-481c-11e5-94fc-27b1e2797106.png)

When I search for the PID (which I've never tried before today, so I'm not sure if this ever worked) I get a "null" result:

![2015-08-21_1546](https://cloud.githubusercontent.com/assets/4663073/9417672/3ca24fb8-481c-11e5-9f0e-31f70848ef6a.png)

I attached two other users to communities Tuesday and Thursday of this week without a problem.

**Comment by dgcliff** [comment]
I think this is the same problem we were just talking about. neu:77 doesn't have usage primary in it's mods title_info

**Comment by dgcliff** [comment]
@sarahjeansweeney should we walk away from usage="primary" as the differentiator? I was going to start a job to fix collections missing it - I can include communities too, but I think there may be some core_files missing it too, as https://github.com/NEU-Libraries/cerberus/commit/490630fdc478448f84831157a99eef94827288f1 and issue #606 weren't that long ago

**Comment by sarahjeansweeney** [comment]
@dgcliff Are there better alternatives to using the usage attribute as the differentiator?

**Comment by dgcliff** [comment]
Not sure about better. But, theoretically, there shouldn't ever be more than one title_info off the main node, that *doesn't* have a type? (The reason we went with usage primary, was because of translated titles being title_info off the main node)

By looking for an absence of something,  it absolves the communities and collections missing usage primary, but protects the existing files with translated titles.

**Comment by sarahjeansweeney** [comment]
It would be unlikely to have more than one titleInfo without a type, and if a record like that does exist, it should be fixed.

Just for the record, in addition to the translated titles, there can also be abbreviated, alternative, and uniform titles, all off the main node (though more than two together is rare).

**Comment by dgcliff** [comment]
And they'd all specify themselves (in correct mods) with a type?

If that's cool, I'll implement that change and push it up tonight
