### ISSUE TITLE
Collection proxying

### ISSUE THREAD

**Issue by sarahjeansweeney** [NEU-Libraries/cerberus#806]
Because I work with a lot of users to set up collections, I've created a lot of collections in the DRS, and therefore I'm the "depositor" for several collections. Proxying for files is set up so that the person proxying chooses to proxy for the depositor of a collection, not a specific individual. This means that when someone proxy uploads to a collection I created for another person or department, that person is proxying as me, not as the actual owner/depositor of the collection. (I've only uploaded 2 files in this list as myself, the rest were from proxy uploads to collections I created: https://repository.library.northeastern.edu/employees/neu:5m60qx563/files)
The collection creation process should be updated to include a proxy mechanism, so when I or other staff create collections for others, we don't become the "depositor" of that collection.

**Comment by dgcliff** [comment]
I believe this has been fixed with the Impersonate User feature. Happy to re-open if this is not the case.

**Comment by sarahjeansweeney** [comment]
In order for the impersonate feature to fix this I'll need to be able to impersonate the admin user, which is still forthcoming, yes?

**Comment by dgcliff** [comment]
Yep, a little minor work on that front, and will let you know when it's done
