### ISSUE TITLE
Title sort when browsing is not sorting by title

### ISSUE THREAD

**Issue by sarahjeansweeney** [NEU-Libraries/cerberus#810]
Title sort is not sorting by title when browsing (it seems to be fine for search results). 
Two examples are the Monographs and Faculty featured content collections on the homepage:

<img width="659" alt="2015-09-02_1323" src="https://cloud.githubusercontent.com/assets/4663073/9638794/7e5ed3f0-5176-11e5-815d-d63ad1977633.png">

<img width="579" alt="2015-09-02_1324" src="https://cloud.githubusercontent.com/assets/4663073/9638802/86aea2a6-5176-11e5-91f2-7cfde0f68870.png">

**Comment by dgcliff** [comment]
It is, actually. The problem is that things need to be reindexed so that the fix for #766 can take effect.

For example, in your above example, Kiss of Death is out of order as it's been recently indexed.
I'll look into the Faculty, but I think it'll be the same thing.

**Comment by dgcliff** [comment]
Employees apparently never had the solr field title_ssi - patched with 86a5a39. I'll manually reindex the monographs and the faculty, as they're aren't that many objects, but until a full reindex happens, new items will appear out of order.

**Comment by dgcliff** [comment]
@sarahjeansweeney Kicking off a full reindex tonight, hopefully with the long weekend, and the fixes and tweaks for performance we've made recently will mean it'll finally get a chance to complete

**Comment by sarahjeansweeney** [comment]
@dgcliff Excellent, thank you!
