### ISSUE TITLE
Add subtitle to brief display

### ISSUE THREAD

**Issue by sarahjeansweeney** [NEU-Libraries/cerberus#812]
MODS subtitles don't display in search results or browse lists, which makes it hard for users to scan for the correct file. The PONS test is one example:
https://repository.library.northeastern.edu/collections/neu:rx9144872
![2015-09-03_0953](https://cloud.githubusercontent.com/assets/4663073/9660056/ae809f7c-5221-11e5-9b60-8e7563779344.png)

And the Spectrum magazine:
![2015-09-03_0950](https://cloud.githubusercontent.com/assets/4663073/9660088/e5bae27c-5221-11e5-9284-a3551c3d83cf.png)

Can mods:subtitle be added to the brief display for titles in search and browse?

**Comment by dgcliff** [comment]
Sure, that shouldn't be too hard. Just needs to create a mapping into the MODS datastream and modify a couple of view partials.

**Comment by elizoller** [comment]
Do you have thoughts on how you want this to look? Ie. do you want a colon between title and subtitle? Do you want the sub title part of the clickable link?
Some ideas:
<img width="1206" alt="screen shot 2015-09-18 at 2 11 39 pm" src="https://cloud.githubusercontent.com/assets/5439169/9967316/0992e4e8-5e10-11e5-86c1-b7270ba6b304.png">
<img width="933" alt="screen shot 2015-09-18 at 2 15 05 pm" src="https://cloud.githubusercontent.com/assets/5439169/9967314/09927a9e-5e10-11e5-9e5d-cd9f257fcb70.png">
<img width="914" alt="screen shot 2015-09-18 at 2 17 00 pm" src="https://cloud.githubusercontent.com/assets/5439169/9967313/09917d7e-5e10-11e5-8fc9-54368753e8aa.png">
<img width="903" alt="screen shot 2015-09-18 at 2 18 35 pm" src="https://cloud.githubusercontent.com/assets/5439169/9967344/2ecc7dd2-5e10-11e5-8849-ce8c095bf81e.png">

**Comment by dgcliff** [comment]
Another option is to put it down similar to abstract. What happens if it's long enough to wrap?

**Comment by elizoller** [comment]
We could force it to do a ... if its too long or it can proceed to a second line like regular titles do
<img width="928" alt="screen shot 2015-09-18 at 2 29 10 pm" src="https://cloud.githubusercontent.com/assets/5439169/9967617/a871cd8a-5e11-11e5-8d8b-c584e70f6b69.png">

**Comment by dgcliff** [comment]
I like that last image. But up to @sarahjeansweeney

**Comment by sarahjeansweeney** [comment]
Title and subtitle are meant to be together, so I prefer the second-to-last image with the smaller subtitle on the same line (https://cloud.githubusercontent.com/assets/5439169/9967344/2ecc7dd2-5e10-11e5-8849-ce8c095bf81e.png) and the ellipsis for long titles.

**Comment by elizoller** [comment]
Just for clarification, subtitle will not be present in grid view, correct?

**Comment by sarahjeansweeney** [comment]
I always forget about grid view! No, I suppose they shouldn't be. There's no way they'd fit.

**Comment by elizoller** [comment]
Correction to my earlier statement. Grid view forces ellipsis. List view allows a title to flow to multiple lines. Do you want the subtitle to flow to multiple lines for list view?

**Comment by sarahjeansweeney** [comment]
Multiple lines for list view sounds good.
