### ISSUE TITLE
Support for multipage objects

### ISSUE THREAD

**Issue by sarahjeansweeney** [NEU-Libraries/cerberus#813]
Possible metadata options:
Properties:
```
To represent page number: <ordinalValue>[1, 2, etc]</ordinalValue>
To represent the last page (only present if true): <ordinalLast>true</ordinalLast>
```

RELS-EXT (if necessary):
```
<ns:isConstituentOf>[core file PID]</ns:isConstituentOf>
```

Display:
Eli will look into the Bootstrap options for displaying multiple pages as a gallery.

**Comment by elizoller** [comment]
Core File view with gallery slider and dropdowns for each page's download options
![screen shot 2015-09-01 at 2 54 39 pm](https://cloud.githubusercontent.com/assets/5439169/9668609/7e223ac8-5250-11e5-8166-828b05732295.png)

**Comment by elizoller** [comment]
https://repository.library.brown.edu/studio/item/bdr:45266/

**Comment by elizoller** [comment]
I will work on updated mockups regarding gallery (able to accommodate 100+) and adding a paginated list of thumbnails for each page image to the Associated Files tab.

**Comment by dgcliff** [comment]
Thanks Eli!

**Comment by elizoller** [comment]
![screen shot 2015-09-08 at 8 41 25 am](https://cloud.githubusercontent.com/assets/5439169/9734986/645e3098-5605-11e5-8baa-f9a61b8ce69e.png)
![screen shot 2015-09-08 at 8 41 00 am](https://cloud.githubusercontent.com/assets/5439169/9734987/64655ca6-5605-11e5-9af0-e287b1d03728.png)

**Comment by elizoller** [comment]
example with pagination (Probably 5 pages looks like a good max number if we want to use the default list view for the images) (also minor note the thumbnails are just manually put in for this mockup and they'll be uniform size when cerberus processes them)
![screen shot 2015-09-08 at 9 30 27 am](https://cloud.githubusercontent.com/assets/5439169/9736001/ac106562-560c-11e5-96ee-a70c3d6e44be.png)

**Comment by elizoller** [comment]
Page image view
![screen shot 2015-09-08 at 9 37 31 am](https://cloud.githubusercontent.com/assets/5439169/9736094/39fc355e-560d-11e5-8323-de86ea814ca2.png)
has breadcrumb back to corefile and page number next to header title
do you still want metadata preview on right?

**Comment by elizoller** [comment]
with metadata on right:
![screen shot 2015-09-08 at 9 41 29 am](https://cloud.githubusercontent.com/assets/5439169/9736221/f33769ee-560d-11e5-9638-6fa3c6cfb0b8.png)

no metadata, centered image:
![screen shot 2015-09-08 at 9 41 45 am](https://cloud.githubusercontent.com/assets/5439169/9736230/f98318d4-560d-11e5-99fd-ace5cc7e639e.png)

**Comment by sarahjeansweeney** [comment]
These look great. I think centered without metadata is best (it's like a focused view).
Would it be possible to include buttons for the previous and next files?

**Comment by elizoller** [comment]
Yes. Some options:
![screen shot 2015-09-08 at 11 00 16 am](https://cloud.githubusercontent.com/assets/5439169/9738333/f0af427c-5618-11e5-9192-1528d163c20f.png)
![screen shot 2015-09-08 at 11 00 04 am](https://cloud.githubusercontent.com/assets/5439169/9738335/f0b2efe4-5618-11e5-9722-805fa6f44eda.png)
![screen shot 2015-09-08 at 10 59 57 am](https://cloud.githubusercontent.com/assets/5439169/9738334/f0b239f0-5618-11e5-91e0-85740a750b25.png)

**Comment by sarahjeansweeney** [comment]
I like the centered blue link buttons.

**Comment by elizoller** [comment]
Ok sounds good. Thanks

**Comment by dgcliff** [comment]
I had a question about example spreadsheet given. Some of the TIFFs have different title's to the core_file. But if they don't have mods, that title won't display anywhere?

**Comment by sarahjeansweeney** [comment]
I generated the spreadsheet after a lot of work was done to edit the MODS harvested from Brown. Since I knew we wouldn't be using the MODS records for the individual TIFFs, I only had David edit the titles in the core file. So, the TIFF titles are the old titles, which we don't care about, and the core file title is the correct title.

**Comment by dgcliff** [comment]
Ok, sounds good.

**Comment by dgcliff** [comment]
Merged in multipage branch
