### ISSUE TITLE
System error when trying to create a collection 

### ISSUE THREAD

**Issue by sarahjeansweeney** [NEU-Libraries/cerberus#815]
I just received a "Sorry, you encountered a system error." message when trying to create a collection. 

I tried creating a collection in a community: https://repository.library.northeastern.edu/communities/neu:466
and in my personal space: https://repository.library.northeastern.edu/collections/neu:rx913q58z

Let me know if you need any other information.

**Comment by dgcliff** [comment]
Hm, I get that too. I'll try and see if I can reproduce it in development.

**Comment by dgcliff** [comment]
Blech. This is related to #752 

I'll make a patch, but won't be able to deploy until the index is done. The upside is that should be sometime tomorrow it looks like.

**Comment by sarahjeansweeney** [comment]
No worries, tomorrow should be fine!

**Comment by dgcliff** [comment]
@sarahjeansweeney if you want them for today, I could make them in the console. Let me know by email the details if you do

**Comment by sarahjeansweeney** [comment]
@dgcliff Thanks, but I can wait until after reindexing is finished. 
If you notice anyone else trying and failing to make a collection, let me know. We should probably reach out to them.

**Comment by dgcliff** [comment]
Will do.
