### ISSUE TITLE
Clickable links in file, collection, and community records

### ISSUE THREAD

**Issue by sarahjeansweeney** [NEU-Libraries/cerberus#816]
The details pages for individual files allows for basic markup, like bold, italics, and links (see Kiss of Death for a good example: https://repository.library.northeastern.edu/files/neu:rx916007n)

Collection and community descriptions don't seem to have the same support. Can collection and community descriptions be updated to include support for the same markup available for files?

**Comment by dgcliff** [comment]
My instinct is the opposite. Why would we encourage visual markup in metadata?

Already, in your above example, someones used &#x2019; for the right single quotation mark. Which is awful.

**Comment by sarahjeansweeney** [comment]
I'll concede that bold, italics, and other visual markup isn't necessary, but links should be hyperlinked. 

Also, if we don't want users to use visual markup in metadata (and I get why we wouldn't), why is it currently allowed for files?

**Comment by dgcliff** [comment]
By accident. We use markdown to parse <sup> and <sub> for legitimate presentation reasons. (Math equations). I didn't expect people to use utf8 to craft html in metadata, as I wouldn't expect any reasonable person would.

**Comment by dgcliff** [comment]
We deliberately scrub all html tags except those two, just for this very reason. Someone did an end run around that processing.

Let me give you the main reason why this is terribly idea. If you put in the utf8 for a ```</div>``` you'd kill the entire visual aspect of that page.

**Comment by sarahjeansweeney** [comment]
Fair enough. IRis allowed it, and some other online tools allow it, as well, so I can see why it's been done, especially since most users don't see the XML metadata, they only see the form.

That being said, forget the HTML suggestion. The heart of this ticket is really links. Visually and functionally, un-hyperlinked links are worthless and it would be nice if the collection and community descriptions, which often contain URLs for finding aids, NU departments, etc, had actual, functional links.

**Comment by dgcliff** [comment]
That's fine, and fairly easy to implement.

**Comment by dgcliff** [comment]
Do we have any idea of how prevalent this presentation utf8 is in metadata currently? I find it worrying.

**Comment by sarahjeansweeney** [comment]
I would say it's not very prevalent, but that's just a guess based on how rarely I've seen it used.

**Comment by dgcliff** [comment]
I'll be patching to prevent this from occurring, if I can. Do we know who added in this particular set?

**Comment by elizoller** [comment]
This is deployed to staging for collections, communities, and sets.
<img width="1201" alt="screen shot 2015-09-18 at 1 48 38 pm" src="https://cloud.githubusercontent.com/assets/5439169/9966640/07b30c74-5e0c-11e5-9434-c19dedc7af0f.png">
