### ISSUE TITLE
Black thumbnails

### ISSUE THREAD

**Issue by sarahjeansweeney** [NEU-Libraries/cerberus#818]
Kevin uploaded three ETDs yesterday afternoon and the thumbnails for two items uploaded as completely black boxes:

https://repository.library.northeastern.edu/files/neu:rx917b34s

https://repository.library.northeastern.edu/files/neu:rx917b36b

A third uploaded with a black frame: https://repository.library.northeastern.edu/files/neu:rx917b327 

I tested neu:rx917b36b in staging and production this morning. The file uploads normally in staging (http://cerberus.library.northeastern.edu/files/neu:p8418n95n), but not in production (it's private, so you'll have to sign in to see it): https://repository.library.northeastern.edu/files/neu:rx917b484). 

Other PDFs seem to upload just fine: https://repository.library.northeastern.edu/files/neu:rx917b505

**Comment by dgcliff** [comment]
Eh, I think this is just a rehash of the ongoing issue of bad input. Thankfully, it looks like for this set of dodgy pdfs, I can just update ghostscript on production to match staging (something I tried to help Joey with this same problem a while back).

Will close once I've done so.

**Comment by dgcliff** [comment]
Blah. This is appears to be the more modern version of libreoffice installed (extremely poorly) on repo2. Will try and wind it back to 4.0.4.2-9

**Comment by dgcliff** [comment]
ImageMagick was similarly the wrong version. I've reinstalled both to the versions we know work best, and tested the upload.
