### ISSUE TITLE
Accurate descriptive labels for files in the download queue

### ISSUE THREAD

**Issue by sarahjeansweeney** [NEU-Libraries/cerberus#819]
Hillary pointed this out to me yesterday:

<img width="799" alt="2015-09-16_1222" src="https://cloud.githubusercontent.com/assets/4663073/9936372/a60b7200-5d29-11e5-8707-d9ab7023b3dc.png">

The descriptive label in parentheses that follow the mods title is a mix of filename, content type, and others ("Content Datastream").

It would be great the labels we choose to display after the title were descriptive and consistent (filename or content type should be fine).

**Comment by dgcliff** [comment]
<img width="1092" alt="screenshot 2015-09-17 11 18 40" src="https://cloud.githubusercontent.com/assets/459084/9937257/ebe15566-5d2d-11e5-8d67-9e9443193a97.png">

Using same labels as the derivative buttons now (on staging, will put it on production after regular work hours)
