### ISSUE TITLE
Inactive links

### ISSUE THREAD

**Issue by sarahjeansweeney** [NEU-Libraries/cerberus#820]
It seems that links stored in metadata, either as a URL in the description field or in the URL field, are inactive. They appear to be clickable, but are not.

Two examples:

https://repository.library.northeastern.edu/files/neu:rx916007n
https://repository.library.northeastern.edu/files/neu:m039kb14h

**Comment by dgcliff** [comment]
Related to 6e4255e0755cfd394bc5190ca38759d775bf11dc

It's scrubbing out the href attribute - will add it to the whitelist
