### ISSUE TITLE
Marcom loader error: "Undefined method `strip' for nil:NilClas"

### ISSUE THREAD

**Issue by sarahjeansweeney** [NEU-Libraries/cerberus#823]
Matt just reported a problem with his most recent load: https://repository.library.northeastern.edu/loaders/marcom/report/154

"Error - undefined method `strip' for nil:NilClas"

He sent me the file, so let me know if you need it.

**Comment by dgcliff** [comment]
@sarahjeansweeney something seems to have been malformed or missing in the "By-line" tag

Could you send us the file?

**Comment by elizoller** [comment]
I think I have a fix. Will test it with the file.

**Comment by dgcliff** [comment]
Given it's relation to the use of a name in "Firstname Lastname" format, which is a first from  Marcom, I gave it the metadata tag.

Job shouldn't have died, so that'll be fixed - still mulling over whether we should just make them do "Lastname, Firstname" for consistency, or incorporating Namae

**Comment by sarahjeansweeney** [comment]
We can ask them to stick to the lastName, firstName format. Since that's been the practice for years now, it was probably just a mistake.

**Comment by elizoller** [comment]
I've got it working with a check to make sure its a string. If its a string and contains a comma then it parses it into the first name, last name hash. If it doesn't contain a comma it uses Namae to parse it into the first name, last name hash. If Namae fails, it creates a special error (like iptc errors) that says incorrectly formatted by-line.

**Comment by dgcliff** [comment]
A mistake that'll probably happen again :) I, for one, find lastname, firstname weird, but that's because I'm not a metadata person I suppose. @elizoller has a patch with Namae, so it can be a catch-all for future forgetfulness ;)

On a related note (EMSA and smart quotes) this is an example of where we might want to have a middle ground between pass/fail.

If we have a yellow warning on the report indicating that we've modified their input for the sake of the system (Name parsing, Punctuation modification) - so that they're aware that it's happened, and can keep an eye on workflow if it became an issue.

**Comment by sarahjeansweeney** [comment]
@dgcliff A middle ground between pass and fail is a great idea.

**Comment by elizoller** [comment]
Ok. I will patch this ticket up now without the special yellow warning and create a feature branch to add the special yellow warning so it can be used for other purposes (like EMSA and smart quotes).

**Comment by dgcliff** [comment]
:+1:

**Comment by sarahjeansweeney** [comment]
Is it safe for Matt to start uploading again?

**Comment by dgcliff** [comment]
We haven't deployed this change to production yet, but if they stick with "Lastname, Firstname" I think they'll be fine

**Comment by sarahjeansweeney** [comment]
Okay, thanks!

**Comment by elizoller** [comment]
https://github.com/NEU-Libraries/cerberus/commit/81c8c2ef89d4e76a23bd753a735234aa2ab6ecc1 adds warning message for modified. still valid corefile but counts as 'modified' not success or fail

**Comment by dgcliff** [comment]
Great - will deploy tonight
