### ISSUE TITLE
Updates to the edit form insert dateCreated

### ISSUE THREAD

**Issue by sarahjeansweeney** [NEU-Libraries/cerberus#825]
When an edit is made to the update form (keyword, public/private, etc), and the record does not contain dateCreated, one gets inserted into the record.

**Comment by dgcliff** [comment]
Blank values no longer are saving, and if the XML has been removed in the editor preventing things like Date being saved, we no longer crash, but present the user with a message, and Eli and I will get an exception email

e.g.

![screenshot 2015-10-02 16 29 43](https://cloud.githubusercontent.com/assets/459084/10257007/d89ed554-6922-11e5-9765-49797de5996d.png)

**Comment by sarahjeansweeney** [comment]
This is great - thanks!
