### ISSUE TITLE
Recently uploaded videos missing audio

### ISSUE THREAD

**Issue by sarahjeansweeney** [NEU-Libraries/cerberus#826]
I uploaded two videos recently, one last week (https://repository.library.northeastern.edu/files/neu:rx917f555) and another this morning (https://repository.library.northeastern.edu/files/neu:rx917f619). I tested the files locally and the audio track plays, but the uploaded files are missing the audio. Joey cleared these files to be uploaded, and I can't see anything wrong with them.

**Comment by dgcliff** [comment]
Given we have videos that do play audio, and the downloaded video plays with audio, I'm guessing it's however the video was encoded not playing well with Wowza? Not sure we'll have to much we can fix with that.

**Comment by sarahjeansweeney** [comment]
Okay, I'll talk with Joey to see what we can do about the files.

**Comment by elizoller** [comment]
Do they have the same encoding as previously uploaded files that do work?

**Comment by sarahjeansweeney** [comment]
It appears they don't. From Joey: "Looking under the hood at these, things look pretty normal except for the fact that they use PCM audio with AVC video…typically AVC/H.264 video is paired with AAC audio."

He's going to try to transcode them with AAC audio.

Related note: only the MOV is needed for streaming, correct?

**Comment by elizoller** [comment]
As far as I know, HLS streaming only accepts AAC audio not PCM.
Yes, just the MOV should allow streaming.

**Comment by sarahjeansweeney** [comment]
Can other formats be streamed, or is MOV just the recommended format?

**Comment by elizoller** [comment]
MP4 can also be streamed

**Comment by sarahjeansweeney** [comment]
Joey adjusted the files, but I won't get a chance to test them out until next Wednesday.
