### ISSUE TITLE
Community scoped search error ("Sorry, I don't understand your search.")

### ISSUE THREAD

**Issue by sarahjeansweeney** [NEU-Libraries/cerberus#827]
I tried doing a search in the Bouve community scoped search box (https://repository.library.northeastern.edu/communities/neu:38), but the search drops me back to the DRS homepage with the message "Sorry, I don't understand your search."

Other community and collection searches appear to work just fine.

**Comment by dgcliff** [comment]
I think this is due to the way we put together a nested search, and how many faculty Bouvé has. Looking into a fix.

**Comment by dgcliff** [comment]
Functioning now, found another limit to bump up in solrconfig (maxBooleanClauses in config - query)

Will close, but we'll be looking to streamlining the scoped query so it's not so onerous.
