### ISSUE TITLE
Edit form: non-topical subjects are being stripped from MODS

### ISSUE THREAD

**Issue by sarahjeansweeney** [NEU-Libraries/cerberus#828]
Dan reported to me today that some geographical MODS subject terms were moved to another subject field. These were embargoed, so we assume this happened when I made the items public using the edit form.
Here are his examples: 
https://repository.library.northeastern.edu/files/neu:rx915f28x
https://repository.library.northeastern.edu/files/neu:rx914p75k
https://repository.library.northeastern.edu/files/neu:rx914p04m

From Dan:

```
In the first example from above, Kevin originally created two headings as:
 
<mods:subject>
     <mods:geographic>Qatar</mods:geographic>
</mods:subject>
 
<mods:subject>
     <mods:topic>undergraduate leadership</mods:topic>
</mods:subject>
 
However, at some point (quite possibly after the embargo was set), the subject nodes were combined into one:

<mods:subject>
    <mods:geographic>Qatar</mods:geographic>
    <mods:topic>undergraduate leadership</mods:topic>
</mods:subject>
```
I can't replicate that particular problem, but when I tested it out (on this record http://cerberus.library.northeastern.edu/files/neu:p8418n95n) the geographic heading was stripped out entirely.

I added the sample MODS from Dan in the XML editor, which validated just fine:
![2015-10-15_1557](https://cloud.githubusercontent.com/assets/4663073/10526177/478ea960-7357-11e5-998c-6744334d3d3f.png)
When I opened the edit form the geographic term was missing entirely from the form, and saving it stripped it from the record:

![2015-10-15_1557-2](https://cloud.githubusercontent.com/assets/4663073/10526223/8d2b398e-7357-11e5-9b1a-62db0c703456.png)

Same for other non-topical terms, like temporal and name/namePart.

**Comment by dgcliff** [comment]
I think I need some educating - why were they separate in the first place? What purpose does that serve?

**Comment by sarahjeansweeney** [comment]
The MODS subject field is discrete, and each individual subject heading gets its own subject field. 
It is possible to combine terms, but that makes a subject string, which takes on a different meaning than the two separate terms.

In other words, the string "undergraduate leadership -- Qatar" has a different meaning than having two separate terms, "undergraduate leadership" and "Qatar". In proper subject cataloging, the first means the paper is about undergraduate leadership IN Qatar, whereas the the second means it's about undergraduate leadership AND Qatar. If you're interested, I bet the "Undergraduate leadership -- Qatar" string isn't even allowed in LCSH, though it's been along time since I consulted the LCSH schedules.

Both are allowable, and local practice here is to use both, depending on what's being described and what LCSH allows.

**Comment by dgcliff** [comment]
This should fix all of the above issues, even if the edit form is used to change keywords.

**Comment by sarahjeansweeney** [comment]
Simmons testing is tomorrow. Tonight is safe :)
