### ISSUE TITLE
Empty Set Download

### ISSUE THREAD

**Issue by sarahjeansweeney** [NEU-Libraries/cerberus#831]
Similar to what Tom Petrini reported earlier this week, a user reported to me today that her Set download zip file is empty, except for a unix file. I can replicate. You guys may already be aware of this, but I wanted to record her issue. Let me know if you want more information.

**Comment by dgcliff** [comment]
I can't replicate this? Could you provide steps and PIDs

**Comment by dgcliff** [comment]
Never mind - I'm pretty sure I figured it out. It's a regression from the fix for sets being loaded into memory, due to timing and naming. Will push up a fix tonight.

**Comment by sarahjeansweeney** [comment]
Sure. Here's what she reported to me:

She added files to her set and clicked the Set's "Download" tab.
When she unzipped the downloaded file, the only file that's unzipped is an executable file.

I can replicate it:

![2015-10-22_1544](https://cloud.githubusercontent.com/assets/4663073/10676385/c39d83ce-78d3-11e5-9edf-588e77b3f856.png)

**Comment by dgcliff** [comment]
Did you just do those two tests? Theres a seperate bug I'm seeing in hydra code related to embargo, where theres a nil date - if you could provide a PID to those set's it might help figure out why theres a nil date being compared

**Comment by sarahjeansweeney** [comment]
I did just download these this afternoon. If it matters, "Set" was created today, but "Remove First Page" is pretty old:

https://repository.library.northeastern.edu/sets/neu:rx915b87g

https://repository.library.northeastern.edu/sets/neu:rx917m96f

**Comment by dgcliff** [comment]
Do you know if any of the files in those two sets went through a manual embargo process?

**Comment by sarahjeansweeney** [comment]
None of them were involved in the embargo process.

**Comment by dgcliff** [comment]
Hm...ok. Will keep looking.

**Comment by sarahjeansweeney** [comment]
If it helps, the "Remove first page" set contains files migrated from IRis, "Set" contains a file that was uploaded recently.
