### ISSUE TITLE
Search is returning only text documents

### ISSUE THREAD

**Issue by sarahjeansweeney** [NEU-Libraries/cerberus#832]
Matt reported to me this morning that he couldn't search for photos. Digging a little deeper, it seems that searches are only returning items with full text (so no photos, collections, communities, etc.). Searching for a known file, community, or collection using its metadata returns less than it should:

Examples:
"Adelaide Cromwell" - should return a few recently deposited images, including one that was just on the homepage, but nothing at all is returned.
"Marketing" - should return a ton of stuff, including the marketing community, collections, and files, but only text documents are returned
"arader" - just brings up text documents, no images or collections.

Let me know if you want/need more info.

**Comment by dgcliff** [comment]
This appears to be happening at the solr end of things, not in cerberus. Looking into it.

**Comment by dgcliff** [comment]
Should be fixed. Not entirely sure how it was working before hand, but I explicitly added title, asbtract, keywords and creators to solrconfig (which weren't in there to begin with).

The solr server has had those old settings since day 1....

**Comment by sarahjeansweeney** [comment]
That's really strange. Things are looking much better now - thanks.

So do you want a list of MODS fields to turn on in Solr?

**Comment by dgcliff** [comment]
Those fields are the ones we've used historically. Were there others that should be included?

**Comment by sarahjeansweeney** [comment]
I think subject is the only field missing there.

**Comment by dgcliff** [comment]
subjects == keywords?

**Comment by sarahjeansweeney** [comment]
Yup, anything in the MODS subject field.

**Comment by dgcliff** [comment]
Yes, those should be in there.

**Comment by sarahjeansweeney** [comment]
Thanks! Matt's happy again.
