### ISSUE TITLE
Student employee?

### ISSUE THREAD

**Issue by sarahjeansweeney** [NEU-Libraries/cerberus#833]
I just received a new employee notification for this user: https://repository.library.northeastern.edu/employees/neu:m039q160f

I looked him up, and it appears he signed in using a student account (his NUID is linked to a Husky account, not a staff or faculty account). Why did he get a faculty/employee account in the DRS?

**Comment by dgcliff** [comment]
We only create employees with faculty in their shib details

```if(auth.info.employee == "faculty")
        Cerberus::Application::Queue.push(EmployeeCreateJob.new(auth.info.nuid, emp_name))
      end```

My guess someone screwed up on the shib side of things

**Comment by dgcliff** [comment]
His LinkedIn says "Full-Time Graduate Faculty"

If you want me to delete his employee node, send me an email

**Comment by dgcliff** [comment]
Also - http://www.northeastern.edu/cpsfacultycentral/wp-content/uploads/2013/08/Faculty-Newsletter-September-2013.pdf

```In one workshop, faculty member Art LaMan demonstrates
the challenges of in-class lectures within a multi-cultural
learning environment.```

**Comment by sarahjeansweeney** [comment]
Yes, I'm aware Art LaMan is a faculty member. He appears to have two accounts, his faculty account (a.laman) and his Husky account (laman.a). The NUID for the LaMan employee we created in the DRS is associated with his laman.a student Husky account, not his faculty a.laman account. 

If Shib says the account he used to login is for a faculty member, even though the staff directory says otherwise, then there's no problem.

**Comment by dgcliff** [comment]
The email associated with his user in the system is a.laman@neu.edu (the faculty one) - so it appears it was created as expected

**Comment by sarahjeansweeney** [comment]
What record are you looking at? The properties datastream for neu:m039q160f doesn't have an email, so where are you seeing that email address?

```
<fields>
<nuid>000572976</nuid>
<name>LaMan, Arthur Eldridge</name>
<status>COMPLETE</status>
</fields>
```

**Comment by dgcliff** [comment]
The rails user object that we store in MySQL

**Comment by sarahjeansweeney** [comment]
Can we add that value to the properties datastream, or somewhere I can see it?

**Comment by dgcliff** [comment]
Sure - we can look into adding it somewhere/displaying it somewhere, in the refactor we do to allow users to be made without email
