### ISSUE TITLE
Improved page titles for search results

### ISSUE THREAD

**Issue by sarahjeansweeney** [NEU-Libraries/cerberus#835]
The page titles for search results contain the search string plus the text "Remove constraint" followed by a string of search terms and facets:

![2015-11-06_1625](https://cloud.githubusercontent.com/assets/4663073/11009252/9ef1930e-84a3-11e5-9d32-1ec5d07aedae.png)

Is it possible to keep the first set of search terms in the page title, but remove "Remove constraint" and everything else that follows up to " - DRS"?

**Comment by dgcliff** [comment]
Sure, shouldn't be too hard

**Comment by sarahjeansweeney** [comment]
Awesome. Of our open tickets, this might actually have the lowest priority, so don't sweat it.

**Comment by elizoller** [comment]
@sarahjeansweeney so you just want the search query not any facet values?

**Comment by sarahjeansweeney** [comment]
Yes, exactly.
