### ISSUE TITLE
Some MODS subject fields are not being indexed?

### ISSUE THREAD

**Issue by sarahjeansweeney** [NEU-Libraries/cerberus#836]
Michelle reported to me that a search for "Melnea Cass" in the Freedom House collection (https://repository.library.northeastern.edu/collections/neu:6008) was returning fewer records than she expected. Looking at the records that were excluded (https://repository.library.northeastern.edu/files/neu:129400, https://repository.library.northeastern.edu/files/neu:129585) it looks like Melnea Cass was added as a name subject, and not in the title or description fields, which I think is why some records are not showing up in search.

I tested one of my own records to see if any other non-topic fields were being indexed, and I don't think they are. In this record https://repository.library.northeastern.edu/files/neu:rx914b41p I added three additional subjects, one for name (kites), title (running), and geographic location (Afghanistan). 

```
<mods:subject>
        <mods:name authority="local" type="personal">
            <mods:namePart>kites</mods:namePart>
        </mods:name>
    </mods:subject>
    <mods:subject>
        <mods:titleInfo>
            <mods:title>running</mods:title>
        </mods:titleInfo>
    </mods:subject>
    <mods:subject>
        <mods:hierarchicalGeographic>
            <mods:country>Afghanistan</mods:country>
        </mods:hierarchicalGeographic>
    </mods:subject>
    <mods:subject>
        <mods:topic>Hydra</mods:topic>
    </mods:subject>
    <mods:subject>
        <mods:topic>communities</mods:topic>
    </mods:subject>
    <mods:subject>
        <mods:topic>collections</mods:topic>
    </mods:subject>
```

Searching the DSG community for those new subjects returns nothing. Only the terms in the mods:topic fields return the record. Each of these fields, plus a few more, should be indexed

**Comment by dgcliff** [comment]
Will look into it

**Comment by dgcliff** [comment]
Reindexed your demo obj, seems to have worked

https://repository.library.northeastern.edu/collections/neu:rx914b40d?utf8=%E2%9C%93&utf8=%E2%9C%93&id=neu%3Arx914b40d&sort=score+desc%2C+system_create_dtsi+desc&q=Afghanistan

We can schedule a full reindex soon
