### ISSUE TITLE
Admin Panel Changes

### ISSUE THREAD

**Issue by sarahjeansweeney** [NEU-Libraries/cerberus#837]
I've made a few changes to various datastreams in a couple records using the Fedora admin interface today, but I haven't seen any of those changes reflected in the DRS itself. Just as an example, I changed the title for this record from "Salem Parsonage Site" to "Salem Parsonage" about 10 minutes ago:

https://repository.library.northeastern.edu/files/neu:rx917m688

Even after a hard refresh, the title is still "Salem Parsonage Site":

![2015-11-13_1530](https://cloud.githubusercontent.com/assets/4663073/11156720/97019d42-8a1b-11e5-94f0-2a355ce74f87.png)

I have a few other examples if you need them.

**Comment by dgcliff** [comment]
Solrizerd needs to catch up. It's running, it'll just take some time. In the mean time, I'll reindex that particular item in a moment

**Comment by dgcliff** [comment]
Why aren't these changes being made in the front-end? That would reflect the changes instantly...

**Comment by sarahjeansweeney** [comment]
Most of the changes I've made today are to the RELS-EXT to associate files (like this one https://repository.library.northeastern.edu/files/neu:rx918060h), which can't be done in the front end. To make sure I wasn't just doing something wrong I tested a change on the title for the Salem record, and just decided to use that as an easy example.

**Comment by dgcliff** [comment]
Fair enough. If theres a list of pids that you'd like to be manually updated while we wait for solrizerd to catch up, lemme know

**Comment by sarahjeansweeney** [comment]
Thanks, but they can all wait until Monday.

Why is Solrizer so far behind?

**Comment by dgcliff** [comment]
Deploying restarts the daemon, and I guess it starts from the beginning of the ActiveMQ queue.
