### ISSUE TITLE
Associating Instructional Materials

### ISSUE THREAD

**Issue by sarahjeansweeney** [NEU-Libraries/cerberus#838]
Associating files by adding  in the RELS-EXT works just fine, but I can't seem to associate files using the isInstructionalMaterialFor relationship.

https://repository.library.northeastern.edu/files/neu:379201 has a supplemental file relationship, which works:
```
<rdf:RDF xmlns:ns0="info:fedora/fedora-system:def/model#" xmlns:drs="http://repository.neu.edu/ns/relations#" xmlns:rdf="http://www.w3.org/1999/02/22-rdf-syntax-ns#">
	<rdf:Description rdf:about="info:fedora/neu:379201">
		<ns0:hasModel rdf:resource="info:fedora/afmodel:CoreFile"></ns0:hasModel>
		<drs:isSupplementalMaterialFor rdf:resource="info:fedora/neu:378444"></drs:isSupplementalMaterialFor>
	</rdf:Description>
</rdf:RDF>
```

https://repository.library.northeastern.edu/files/neu:rx918060h has an instructional material relationship, which doesn't:
```
<rdf:RDF xmlns:drs="http://repository.neu.edu/ns/relations#" xmlns:ns0="info:fedora/fedora-system:def/model#" xmlns:ns1="info:fedora/fedora-system:def/relations-external#" xmlns:rdf="http://www.w3.org/1999/02/22-rdf-syntax-ns#">
  <rdf:Description rdf:about="info:fedora/neu:rx918060h">
    <ns0:hasModel rdf:resource="info:fedora/afmodel:CoreFile"></ns0:hasModel>
    <ns1:isMemberOf rdf:resource="info:fedora/neu:rx914499v"></ns1:isMemberOf>
    <drs:isInstructionalMaterialFor rdf:resource="info:fedora/neu:rx917x48n"></drs:isInstructionalMaterialFor>
  </rdf:Description>
</rdf:RDF>
```
What am I missing?

**Comment by dgcliff** [comment]
Appears we're not currently looking for those in the interface, just supplemental

https://github.com/NEU-Libraries/cerberus/blob/master/app/views/core_files/_actions_nav.haml#L6

Easy enough fix, will patch today

**Comment by dgcliff** [comment]
Eli's fixed it https://repository.library.northeastern.edu/files/neu:rx918060h

**Comment by sarahjeansweeney** [comment]
Excellent, thanks!
