### ISSUE TITLE
Faculty missing from search

### ISSUE THREAD

**Issue by sarahjeansweeney** [NEU-Libraries/cerberus#839]
Searching the Featured Content area for Faculty doesn't return any results. I tried a few known names (Abrams, Sweeney, Corbett, etc) all with no results:

![2015-11-16_1600](https://cloud.githubusercontent.com/assets/4663073/11194641/344dc196-8c7b-11e5-8414-27c32386fcaa.png)

I tried doing a general search for those faculty names. The faculty collections were retrieved, but not the faculty objects themselves. "Faculty" doesn't show up in the Type facet, either:

![2015-11-16_1558](https://cloud.githubusercontent.com/assets/4663073/11194603/fc034ebe-8c7a-11e5-93f8-4c3e2be4158e.png)

Though it does show up in the Faculty Featured Content area:

![2015-11-16_1600-1](https://cloud.githubusercontent.com/assets/4663073/11194647/3edb6e9c-8c7b-11e5-85d3-9bef8619a1a8.png)

**Comment by dgcliff** [comment]
Will require a reindex of faculty, after being pushed up later today

**Comment by dgcliff** [comment]
https://repository.library.northeastern.edu/?f%5Btype_sim%5D%5B%5D=Faculty&q=abrams&sort=score+desc%2C+system_create_dtsi+desc&utf8=%E2%9C%93

Reindexing happening now

**Comment by sarahjeansweeney** [comment]
:+1:
