### ISSUE TITLE
Streaming MP3s

### ISSUE THREAD

**Issue by sarahjeansweeney** [NEU-Libraries/cerberus#840]
We're getting errors when we try to stream recently uploaded MP3s ("There was an error playing this file. Please try on a different device, verify Flash is enabled, or download the file."). The files were uploaded as MP3s, and are stored in Fedora as MP3s, but for some reason they download as MPGA.

I have two examples:
DMC Studios: https://repository.library.northeastern.edu/files/neu:rx918154k
Archives: https://repository.library.northeastern.edu/files/neu:rx918155v

The Archives file has been reviewed and approved by Joey, but I'm not sure about the origin of the Studios' file.

**Comment by elizoller** [comment]
dumb mistake on my part.

**Comment by sarahjeansweeney** [comment]
Should we delete and reload the files?

**Comment by elizoller** [comment]
Nope. Should be good once we deploy the code.

**Comment by dgcliff** [comment]
should be fine as is, just need to push up the changes later today

**Comment by sarahjeansweeney** [comment]
Thanks!
