### ISSUE TITLE
Files for poster uploads

### ISSUE THREAD

**Issue by sarahjeansweeney** [NEU-Libraries/cerberus#841]
Joey was able to upload this video file yesterday without a poster: https://repository.library.northeastern.edu/files/neu:rx918173s

Looking at the files, it seems that he uploaded an MOV file instead of the poster image file. Can we limit poster uploads to just image files?

**Comment by dgcliff** [comment]
haha, yeah. I'll look into scrubbing out that "poster"

**Comment by sarahjeansweeney** [comment]
Cool - can I send you a replacement poster?

**Comment by dgcliff** [comment]
Sure

**Comment by sarahjeansweeney** [comment]
Can the poster for this file be replaced with:
![266691_poster](https://cloud.githubusercontent.com/assets/4663073/11842913/a8c6ca84-a3d4-11e5-8b2b-46420e785f41.jpeg)

**Comment by dgcliff** [comment]
Sure

**Comment by dgcliff** [comment]
Done

**Comment by sarahjeansweeney** [comment]
Thanks! Once Joey replaces the metadata for this file, the NIEC video migration will be done :)
