### ISSUE TITLE
Files downloading with different extensions

### ISSUE THREAD

**Issue by sarahjeansweeney** [NEU-Libraries/cerberus#842]
After talking with Eli I'm afraid this is a browser problem and not a DRS problem, but I'll log it here just in case it's not just me and my browser settings.

When entering issue #840 I noticed that the mp3 file downloads as mpga. Looking a bit deeper, this extension change happens for a lot of files:

jpg --> downloads as --> jpeg
tif --> tiff
mov --> qt
mp3 --> mpga

I'm seeing this in Firefox, Safari, and Chrome, and it happens when I click the download button or right click to save the file.

MOV example:
https://repository.library.northeastern.edu/files/neu:rx918120r
Firefox:
<img width="1225" alt="2015-11-19_1104" src="https://cloud.githubusercontent.com/assets/4663073/11278441/f453dc70-8eb8-11e5-9b8c-2a824ad260e4.png">

Safari:
<img width="1225" alt="2015-11-19_1105" src="https://cloud.githubusercontent.com/assets/4663073/11278444/f795db18-8eb8-11e5-9e93-b60c9d123a60.png">

MP3 example:
https://repository.library.northeastern.edu/files/neu:rx918154k
Firefox:
<img width="1225" alt="2015-11-19_1159" src="https://cloud.githubusercontent.com/assets/4663073/11278447/fd197b76-8eb8-11e5-9c49-724f6ad79c07.png">

This doesn't happen for me elsewhere. For example, I can download the DRS image on the DSG website  (http://dsg.neu.edu/resources/drs/) as a .jpg, which is the original file extension.

**Comment by dgcliff** [comment]
Theres no good solution for this, as far as I know. We create the extension based on the mime type of the file - as far as I'm aware, those are all correct for those files. The original_filename field would be the solution, which we have, but if I recall, this wasn't done correctly for many IRis migrated files (the tiff/jpg debacle being prime candidate one)

**Comment by dgcliff** [comment]
Bleh - I have a potential solution, that will user original_filename when it's not obviously wrong (a paper over hack, but I guess we already have plenty of those for bad input files already...)
