### ISSUE TITLE
Change to EMSA Loader and Files

### ISSUE THREAD

**Issue by sarahjeansweeney** [NEU-Libraries/cerberus#844]
EMSA has decided to change who can view and download their photos. They currently allow northeastern-all to view metadata, but only certain groups can actually download files. They would like to expand permissions so northeastern-all can view metadata and download their photos.
So, two things:
1) The EMSA loader should be updated so that all core files and objects have the same permissions (below).
2) There are currently 409 existing EMSA files, each with a small, large, and master file that will need to be updated with the new permissions. Is there a way we can update the rights records for all their files programmatically? I'd really like to avoid updating 1200+ rights records using Fedora Admin.

```
<rightsMetadata xmlns="http://hydra-collab.stanford.edu/schemas/rightsMetadata/v1" version="0.1">
  <access type="read">
    <machine>
      <group>northeastern:drs:all</group>
    </machine>
  </access>
  <access type="edit">
    <machine>
      <group>northeastern:drs:enrollment_management:emc:emc_admin</group>
      <group>northeastern:drs:repository:staff</group>
      <person>000000000</person>
    </machine>
  </access>
</rightsMetadata>
```

**Comment by dgcliff** [comment]
Yeah there's a way, I'll look into writing it up.

**Comment by sarahjeansweeney** [comment]
Can I raise the priority for number 1 above? EMSA has decided to hold off on loading any new files until the loader matches their new standard.

**Comment by dgcliff** [comment]
Sure - Eli's code is in, we just need to retroactively apply those permissions to previously loaded files.

**Comment by dgcliff** [comment]
This is processing in the background now, will close this ticket when it's done.

**Comment by sarahjeansweeney** [comment]
Thanks!
