### ISSUE TITLE
Streaming Only Option for A/V

### ISSUE THREAD

**Issue by sarahjeansweeney** [NEU-Libraries/cerberus#846]
From Patrick:
"RADS has started working with vendors on licensing streaming content that can go into the DRS, and one of the requests we are getting is that the videos not be (easily) downloadable by end users, and that the wowza stream be the only asset they see.  Would it be possible to:

A)  Create a new video object model that doesn’t provide for a download link for the file.  I was thinking a clone of the current model and upload workflow would work here, with the addition of a button on the upload form that, when checked, would chose a model that doesn’t allow direct download."

**Comment by elizoller** [comment]
If we wrap this in with the thumbnail for audio/video, it will only be available at upload not on editing, is that ok?

**Comment by dgcliff** [comment]
Yeah, we can retrofit on editing if we need to, but I don't think it's something we need to worry about right now
