### ISSUE TITLE
Replacement Thumbnail for neu:379116

### ISSUE THREAD

**Issue by sarahjeansweeney** [NEU-Libraries/cerberus#847]
Can the thumbnail for https://repository.library.northeastern.edu/files/neu:379116 be replaced with this file?: 
![neu_379118](https://cloud.githubusercontent.com/assets/4663073/11506163/fb90bb68-981b-11e5-8b20-18a54dc5a27f.jpg)

**Comment by dgcliff** [comment]
Sure, will do

**Comment by dgcliff** [comment]
Done - https://repository.library.northeastern.edu/files/neu:379116

Not straightforward with current code. I uploaded the image to my account, changed it's wiring to belong to neu:379116 in fedora Admin tool, ran the derivative generator, than destroyed the master image

**Comment by sarahjeansweeney** [comment]
Yikes. That does not sound like a healthy way to replace thumbnails.

**Comment by dgcliff** [comment]
It's not. But with how the system is currently setup, it's the only way. When multipage comes in, there's been some refactoring to make it a little easier, but it's still not regulated.

Thumbnail workflow expects core_file -> object relationships, as we copy permissions, create urls etc.

So retroactively changing thumbnails to be of something that doesn't exist (i.e. not the PDF that is the canonical object) is very much against the grain of how everything else works.

**Comment by sarahjeansweeney** [comment]
Fair enough. Though it just occurred to me that the thumbnails live as their own datastreams. In the future could I just purge and replace the old thumbnails with the new thumbnails files?

**Comment by dgcliff** [comment]
You could, but you'd have to manually do each of it's different scaled content datastreams. That's a lot more work (and introduces uncertainty of process, i.e. are they all jpg, what happens if they're not etc.)
