### ISSUE TITLE
Failed Upload neu:rx918356j

### ISSUE THREAD

**Issue by sarahjeansweeney** [NEU-Libraries/cerberus#848]
I just uploaded this file: https://repository.library.northeastern.edu/files/neu:rx918356j#stay

According to resque it failed: No such file or directory - /tmp/DRStmp/1448987329-7864308-63

**Comment by dgcliff** [comment]
Fixed and recovered

The DRStmp mount wasn't mounted - seems someone (me?...I truly hope not) commented out the bind in fstab, and when I restarted last night to do security updates, it picked up the commented out line and didn't mount as it should've

**Comment by sarahjeansweeney** [comment]
Thanks
