### ISSUE TITLE
DRS Homepage Link

### ISSUE THREAD

**Issue by sarahjeansweeney** [NEU-Libraries/cerberus#851]
Users have a hard time navigating back to the homepage. Let's update the tiny "DRS" link to include the File box icon and "DRS Digital Repository Service", just like on the homepage.
![2015-12-11_1042-1](https://cloud.githubusercontent.com/assets/4663073/11748179/0b0929e6-9ff5-11e5-8595-01a8d7c3346c.png)

Only the "Digital Repository Service" text would need to be hyperlinked, I think.

If we do end up doing this, it will make the current icon/DRS text on the homepage redundant, so I think we can remove that header.

Here are two other options I thought of, but I like the option above the best:

![2015-12-11_1041-1](https://cloud.githubusercontent.com/assets/4663073/11748187/13ac5ba4-9ff5-11e5-9905-fef89187ed0f.png)

![2015-12-11_1043](https://cloud.githubusercontent.com/assets/4663073/11748190/162a7eba-9ff5-11e5-890a-0ee9055df1d8.png)

**Comment by elizoller** [comment]
Some variations on color/font/icon.
<img width="1202" alt="screen shot 2015-12-16 at 3 04 13 pm" src="https://cloud.githubusercontent.com/assets/5439169/11878750/9c0872b0-a4c5-11e5-8b72-0790d00758d8.png">
<img width="1204" alt="screen shot 2015-12-16 at 3 03 57 pm" src="https://cloud.githubusercontent.com/assets/5439169/11878753/9c096f62-a4c5-11e5-801a-fe5ea59cdcb5.png">
<img width="941" alt="screen shot 2015-12-16 at 3 03 51 pm" src="https://cloud.githubusercontent.com/assets/5439169/11878748/9c05c934-a4c5-11e5-8e24-b60843c53270.png">
<img width="1205" alt="screen shot 2015-12-16 at 3 01 46 pm" src="https://cloud.githubusercontent.com/assets/5439169/11878752/9c094c8a-a4c5-11e5-81d8-16b0f61f483a.png">
<img width="1213" alt="screen shot 2015-12-16 at 3 01 35 pm" src="https://cloud.githubusercontent.com/assets/5439169/11878749/9c06e8f0-a4c5-11e5-9473-09d40c7101ee.png">
<img width="1206" alt="screen shot 2015-12-16 at 3 00 47 pm" src="https://cloud.githubusercontent.com/assets/5439169/11878751/9c08acbc-a4c5-11e5-9a8b-b7b61b1ad9fb.png">
<img width="1203" alt="screen shot 2015-12-16 at 2 59 19 pm" src="https://cloud.githubusercontent.com/assets/5439169/11878754/9c0e9460-a4c5-11e5-9b52-291f4187d42a.png">
<img width="1214" alt="screen shot 2015-12-16 at 2 59 01 pm" src="https://cloud.githubusercontent.com/assets/5439169/11878755/9c10f746-a4c5-11e5-8c74-5e0f1569b5e9.png">
<img width="1212" alt="screen shot 2015-12-17 at 1 53 06 pm" src="https://cloud.githubusercontent.com/assets/5439169/11878757/a0040f64-a4c5-11e5-8391-915bdafd7a30.png">
<img width="1220" alt="screen shot 2015-12-17 at 1 47 14 pm" src="https://cloud.githubusercontent.com/assets/5439169/11878758/a0053024-a4c5-11e5-96c7-40cd65b3c278.png">

**Comment by sarahjeansweeney** [comment]
I prefer the mockups with the icon, dark font color, and less spacing between letters:
https://cloud.githubusercontent.com/assets/5439169/11878751/9c08acbc-a4c5-11e5-9a8b-b7b61b1ad9fb.png
https://cloud.githubusercontent.com/assets/5439169/11878758/a0053024-a4c5-11e5-96c7-40cd65b3c278.png
https://cloud.githubusercontent.com/assets/5439169/11878754/9c0e9460-a4c5-11e5-9b52-291f4187d42a.png

**Comment by sarahjeansweeney** [comment]
@PatrickYott Do you have any thoughts about this change?

**Comment by sarahjeansweeney** [comment]
In the initial ticket I said that only the "Digital Repository Service" text should be hyperlinked, but I think the whole thing should be, actually, as long as it stays the darker text color.
