### ISSUE TITLE
New DRS Footer

### ISSUE THREAD

**Issue by sarahjeansweeney** [NEU-Libraries/cerberus#852]
Users have a hard time finding help and contact information. Let's add a second footer for more information about the DRS that includes links to (in this order):

* About the DRS (http://dsg.neu.edu/resources/drs)
* Contact Us (Library-Repository-Team@neu.edu)
* Terms of Service (https://repository.library.northeastern.edu/terms)
* IRis and the DRS (https://repository.library.northeastern.edu/iris)
* Help (http://dsg.neu.edu/wiki/DRS_User_Guide)
* Report a Problem (http://library.northeastern.edu/get-help/tech-support/report-a-problem)

If possible, can you add a visual cue to indicate links that take users out of the DRS?

**Comment by elizoller** [comment]
What are you thinking as far as visuals for the second footer?
I think one option could be to mimic the styling of the DRS header. Another option would be to mimic the styling of the NU footer. 

mimic DRS styling:
<img width="1335" alt="screen shot 2016-08-04 at 1 03 47 pm" src="https://cloud.githubusercontent.com/assets/5439169/17411066/8bf60d76-5a44-11e6-98f5-b9c835e9caf7.png">

mimic NU styling:
<img width="1341" alt="screen shot 2016-08-04 at 1 06 50 pm" src="https://cloud.githubusercontent.com/assets/5439169/17411065/8bf4ddf2-5a44-11e6-9019-78d6edb34227.png">

**Comment by sarahjeansweeney** [comment]
I prefer the footer that mimics the NU styling. I think the DRS styling would stick out too much on pages that aren't the homepage.

**Comment by elizoller** [comment]
I was thinking that too. My only hesitation with the NU styling is that we reserve that styling (colors and font) to only the NU footer and NU logo in the header right now. And I wasn't sure if putting the DRS stuff in NU styling would be confusing. But if I'm the only one that thinks that, that's ok.

**Comment by elizoller** [comment]
We could put a DRS logo on the left?

**Comment by sarahjeansweeney** [comment]
I don't think it would be confusing (it is a NU service after all), but it blends in really well so it may be overlooked. 

I like the idea of adding the logo on the left. Maybe we can mimic the choice in #851?
(Since Patrick doesn't seem to have an opinion, I should just choose one)

**Comment by elizoller** [comment]
Sounds good. I think it'd be good to roll that out at the same time too

**Comment by elizoller** [comment]
Thoughts?

![screen shot 2016-08-04 at 2 30 00 pm](https://cloud.githubusercontent.com/assets/5439169/17413646/087fd2cc-5a50-11e6-83f2-1578e67b2e87.png)


![screen shot 2016-08-04 at 2 29 47 pm](https://cloud.githubusercontent.com/assets/5439169/17413648/08844fbe-5a50-11e6-8019-a3a905579067.png)


![screen shot 2016-08-04 at 2 29 15 pm](https://cloud.githubusercontent.com/assets/5439169/17413647/08804766-5a50-11e6-8c3e-ac11fe49cc22.png)


![screen shot 2016-08-04 at 2 28 58 pm](https://cloud.githubusercontent.com/assets/5439169/17413649/0886ef8a-5a50-11e6-9ac8-f0c69e96afae.png)

**Comment by sarahjeansweeney** [comment]
These all look good. Although I like the spacing between our menu options better, I think the spacing should probably be closer together like the NU spacing. Or, even better, can we changing the spacing in the NU footer to match the spacing in the DRS footer?

This is nit-picky, but the DRS logo looks much darker than the other footer text. What would it look like if the color matched the rest of the footer text?

**Comment by elizoller** [comment]
Fixed spacing in NU footer to match spacing in DRS footer
changed DRS logo to same color as rest of footer links
<img width="1344" alt="screen shot 2016-08-04 at 2 56 42 pm" src="https://cloud.githubusercontent.com/assets/5439169/17414501/ae9c83be-5a53-11e6-993a-613117f7de73.png">

**Comment by sarahjeansweeney** [comment]
Beautiful!

**Comment by elizoller** [comment]
🎉

**Comment by sarahjeansweeney** [comment]
This looks good in staging! I have a few suggestions for small screens/mobile:

For screens smaller than 1200, the "Digital Repository Service" text starts to drop to the next line:

![2016-08-05_1446](https://cloud.githubusercontent.com/assets/4663073/17447252/6743556a-5b1b-11e6-8b24-28d363fa9b70.png)

Can the full "Digital Repository Service" move together as one to the next line as the screen gets smaller?

Also, when the screen gets below 765ish, a white space appears on either side of the DRS footer:

![2016-08-05_1448](https://cloud.githubusercontent.com/assets/4663073/17447306/b4a264d6-5b1b-11e6-8363-7265b3ddad07.png)

It should probably fill the full screen, like the university footer.

**Comment by elizoller** [comment]
Agh thanks!

**Comment by elizoller** [comment]
Like this?
<img width="496" alt="screen shot 2016-08-05 at 2 56 20 pm" src="https://cloud.githubusercontent.com/assets/5439169/17447517/d20f8c00-5b1c-11e6-8cd6-2499fc22fd23.png">

**Comment by sarahjeansweeney** [comment]
Yes, I think that looks better - thanks!

**Comment by sarahjeansweeney** [comment]
Can the "Help" URL be changed to : http://hdl.handle.net/2047/D20213468
Thanks!

**Comment by elizoller** [comment]
Closed with https://github.com/NEU-Libraries/cerberus/pull/1002 and 	6af4fb7
