### ISSUE TITLE
500 Server Error for IRis Page

### ISSUE THREAD

**Issue by sarahjeansweeney** [NEU-Libraries/cerberus#853]
For some reason I'm getting a server error when I try to connect to the DRS IRis page: https://repository.library.northeastern.edu/iris
I know some changes were made recently with how we use this URL, but shouldn't this still be a working URL?

**Comment by dgcliff** [comment]
Could you try a hard refresh? Worked for me.

**Comment by sarahjeansweeney** [comment]
A hard refresh worked...
