### ISSUE TITLE
Move for files and collections

### ISSUE THREAD

**Issue by sarahjeansweeney** [NEU-Libraries/cerberus#854]
Similar to the tombstoning procedure, there needs to be a process for me to move files and collections within Cerberus, without using the Fedora Admin.
A simple box for me to enter the PID or the URL for the destination collection should work.

**Comment by sarahjeansweeney** [comment]
To move a file or a collection now I update the collection PID in the file/collection's RELS-EXT (```<ns1:isMemberOf rdf:resource="info:fedora/neu:rx9160028"/>```) and properties (```<parent_id>neu:rx9160028</parent_id>```) datastreams.

**Comment by dgcliff** [comment]
Ah, that's right. Simple enough. We'll do the same we do for tombstone, just give you a privileged view (instead of the request) on each individual item's move tab, where you can put in the destination parent pid

**Comment by sarahjeansweeney** [comment]
Perfect, thanks :)
