### ISSUE TITLE
Downloads for zipped files

### ISSUE THREAD

**Issue by sarahjeansweeney** [NEU-Libraries/cerberus#860]
* Cumulative download size for zip files should be limited to 5GB
* If a user tries to download a Set or a Download Queue larger than 5GB, they should be presented with a modal informing them the file is too large:
"Sorry, this [Set/Download Queue] is too large to download at this time. Please contact DRS staff (Library-Repository-Team@neu.edu) for help downloading this file."

**Comment by dgcliff** [comment]
Closed with eaa850c
