### ISSUE TITLE
Adding files to a Set

### ISSUE THREAD

**Issue by sarahjeansweeney** [NEU-Libraries/cerberus#861]
Users are not confident in the "Save for later" function (it's too slow and it doesn't give them feedback about what's happening). To improve the "Save for later" function:

For existing Sets:
* Change the button color to yellow while the file is being added to the Set.

For new Sets:
* When users clicked "Save for later" and created a new set from the "Add to a Set." modal, they were unsure whether or not their Set was created and the file was added. When users create a new Set from the modal they should stay within the modal, where they'll see the new Set in the list, which will be red because the file was added. If that's not feasible, they should see another modal confirming that the set has been created and the file has been added.

Adding multiple items:
* Add a single page of results to a Set button, like SOS

**Comment by dgcliff** [comment]
Maybe a little spinner or something along with the yellow to indicate progress?

**Comment by sarahjeansweeney** [comment]
Sure! Moving things always help.

**Comment by dgcliff** [comment]
I think this can be closed.
