### ISSUE TITLE
Sort by and Relevance 

### ISSUE THREAD

**Issue by sarahjeansweeney** [NEU-Libraries/cerberus#863]
Users are very interested knowing how their results are sorted. To make the sorting more clear:
* the "Recently Added" sort option should be changed to "Recently Uploaded"
* the styling for "Sort by" and "Show" options could be restyled to match the facet styling (I'm not sure how to accomplish this, so this is the one that needs discussion)
* change the "Sort by" label to "Sorted by"

**Comment by dgcliff** [comment]
I think this can be closed.
