### ISSUE TITLE
Sort for core files in Admin Panel / Manage Files

### ISSUE THREAD

**Issue by sarahjeansweeney** [NEU-Libraries/cerberus#868]
Right now the sort for the Admin Panel Manage Files page appears to be either oldest --> newest (or maybe by most recently updated). Can sort order be changed to newest --> oldest

**Comment by elizoller** [comment]
This can be fixed no problem. For the tombstoned items, we don't store a date right now. I am changing that so we do store a date but basically the sort won't be that helpful on previously tombstoned things.

**Comment by sarahjeansweeney** [comment]
That's fine. Where will the new date be stored?

**Comment by elizoller** [comment]
In the solr doc for the tombstoned record as tombstone_date_ssi

**Comment by elizoller** [comment]
Just remembered about collections - will add this date and sort to tombstoned collections as well.
