### ISSUE TITLE
Reloading a page seems to strip styling

### ISSUE THREAD

**Issue by sarahjeansweeney** [NEU-Libraries/cerberus#869]
I noticed this late last week and assumed it was my browser, but I suspect it might be something else. When I reload a page in the DRS, the page styling is stripped:
![2015-12-15_0919](https://cloud.githubusercontent.com/assets/4663073/11812998/f8b874e8-a30c-11e5-8c75-d6bde8588717.png)

Reloading the page again returns it to normal. I've seen this in Chrome (regular and incognito) and Firefox.

Here's a video, if it helps: https://www.dropbox.com/s/6vgb8qyeny0hwf6/reload.mov?dl=0

**Comment by dgcliff** [comment]
Was able to reproduce this. Seems Apache started aggressively using its DefaultType text/plain directive (not sure why, perhaps a bug in an updated version). Changing it to None appears to have solved the issue. You may need to do a hard refresh before regular refreshes work as intended. 

http://stackoverflow.com/questions/5034131/mod-proxy-ajp-error-renders-html-as-text-plain-prompts-user-to-save-as was my source (similar but different issue it seems)

**Comment by sarahjeansweeney** [comment]
Great, thanks!
