### ISSUE TITLE
Multipage destination collection

### ISSUE THREAD

**Issue by sarahjeansweeney** [NEU-Libraries/cerberus#870]
Since this is going to be an administrative feature, can the destination collection be selected by entering a specific PID rather than by searching by collection name?

**Comment by dgcliff** [comment]
Will it always be admin only?

**Comment by sarahjeansweeney** [comment]
Probably not, but it will be for the foreseable future. If if we do open it up to general users, we would definitely want to make sure they enter the precise collection PID rather than search by name, which may not be unique.

**Comment by dgcliff** [comment]
That's true. Though I truly hope we don't get collections with same names being a regular occurrence.

**Comment by elizoller** [comment]
Could we do title and pid?

**Comment by dgcliff** [comment]
I think it already does that, in reverse. Pid off the to the side (in an unstyled way) Flipping it so you look for pid, and display the title in an attached label would suit our needs?

**Comment by elizoller** [comment]
Yeah it uses the pid as the value that gets passed through for the collection. Should be pretty simple to include the pid in the display.

**Comment by sarahjeansweeney** [comment]
That sounds great.

**Comment by elizoller** [comment]
pid or title first and how do you want them sorted?

**Comment by elizoller** [comment]
<img width="1212" alt="screen shot 2015-12-16 at 2 31 41 pm" src="https://cloud.githubusercontent.com/assets/5439169/11851729/2321f5a6-a402-11e5-93d5-8c7a4b4a0405.png">

**Comment by sarahjeansweeney** [comment]
Display and sort by the PID, since that's what I'll be searching on. Can you put a hyphen between the PID and the collection title?

**Comment by elizoller** [comment]
<img width="1226" alt="screen shot 2015-12-16 at 2 48 20 pm" src="https://cloud.githubusercontent.com/assets/5439169/11852083/13ce490e-a404-11e5-8dbc-0d85ddcd26b2.png">

**Comment by sarahjeansweeney** [comment]
Awesome - can you add a space between the pid and the hyphen so it's "PID - Collection Title"? Nit picky, I know, but it's easier to scan.
