### ISSUE TITLE
Display order for multipage items

### ISSUE THREAD

**Issue by sarahjeansweeney** [NEU-Libraries/cerberus#872]
I haven't been able to break anything so far, which is great.
One thing I have noticed is that the display order is inconsistent. I just upload the same file in two different loads:
http://cerberus.library.northeastern.edu/files/neu:5425kb035
http://cerberus.library.northeastern.edu/files/neu:5425kb078

It looks like the files uploaded correctly, and were assigned the correct order, but the files are being displayed in the wrong order. 
The thumbnail was created from the first page, so that's good, but page two is first to display on the metadata page, and it's the first page in the Associated Files list:
![2015-12-16_1516](https://cloud.githubusercontent.com/assets/4663073/11853055/b91531a2-a409-11e5-97b0-fb639d1ae524.png)

This file, on the other hand, is displaying in the correct order: http://cerberus.library.northeastern.edu/files/neu:5425kb10k

**Comment by dgcliff** [comment]
Quirky - probably an easy fix with a sort

**Comment by sarahjeansweeney** [comment]
New sort is better, though now it sorts as 1, 10, 11, 2, 3, 4...

![2015-12-17_1517](https://cloud.githubusercontent.com/assets/4663073/11880904/753341f4-a4d1-11e5-8afe-5cb7c2ac07a9.png)


would it be better if I entered 001, 002, 003 in the spreadsheet?

**Comment by elizoller** [comment]
fixed with 7219e13f3b5e2e8835297396d8297a282713077f - 15c8d334cc8ef7c8e6efd05a76a58f708b950841
