### ISSUE TITLE
Clickthrough for multipage thumbnail display

### ISSUE THREAD

**Issue by sarahjeansweeney** [NEU-Libraries/cerberus#873]
For the most part, the clickthrough for the multipage thumbnail display looks great. The experience is a little awkward when clicking through pages that are varying sizes. This [brochure] (http://cerberus.library.northeastern.edu/files/neu:5425kb192), for example, has 3 pages, one of which is vastly different from the other. When you click through the pages, the forward and back button realign to the center of the image, which looks nice, but when you click through too quickly and the button moves up or down, you end up clicking the image and being taken to the full page view (here's a video, if it helps: https://www.dropbox.com/s/ivkg4hvmoi8ombg/Multipage%20Sample.mov?dl=0)
Two possible ways to make the clickthrough smoother is to align the buttons to the top, or make the full right and left borders clickable to move forward or backward, rather than just the moving button.

**Comment by elizoller** [comment]
Ok. I can fix the arrows to a certain height so that no matter how tall the image is, the arrow will remain in the same place. Does that sound like it'd fix the issue?

**Comment by sarahjeansweeney** [comment]
That sounds great - thanks!

**Comment by elizoller** [comment]
Fixed with 46e8e67bbe05c56afc26848291668e31b6c36d63
