### ISSUE TITLE
Replacement thumbnails for engineering reports

### ISSUE THREAD

**Issue by sarahjeansweeney** [NEU-Libraries/cerberus#874]
Hillary needs the thumbnails replaced for these files:

https://repository.library.northeastern.edu/files/neu:376268
https://repository.library.northeastern.edu/files/neu:376262
https://repository.library.northeastern.edu/files/neu:376274
https://repository.library.northeastern.edu/files/neu:376265
https://repository.library.northeastern.edu/files/neu:376271

**Comment by dgcliff** [comment]
All regenerated
