### ISSUE TITLE
Migrated items with missing metadata

### ISSUE THREAD

**Issue by dgcliff** [NEU-Libraries/cerberus#879]
Both neu:206674 and neu:203914 are fundamentally broken - it appears they have no MODS content. They should either be fixed, or deleted.

**Comment by sarahjeansweeney** [comment]
Both MODS records have a few issues, but I removed the stray text ("  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0") that caused the records to be malformed.
