### ISSUE TITLE
Two hyphens display as "[nil]"

### ISSUE THREAD

**Issue by sarahjeansweeney** [NEU-Libraries/cerberus#880]
When two hyphens (--) exist in a MODS record, they display in the DRS as "[nil]".

Hillary pointed it out to me in this record: https://repository.library.northeastern.edu/files/neu:963

The MODS display on the item page presents the two hyphens correctly, but when you look at the abstract for the item in the collection display, you see the [nil] value:
![2016-01-04_1128](https://cloud.githubusercontent.com/assets/4663073/12094489/ecb98a86-b2d6-11e5-97b2-15d1062a3389.png)

I tested it out in Cerberus (http://cerberus.library.northeastern.edu/files/neu:p8418n86p), and the [nil] value shows up in the abstract, title, facets, and breadcrumbs
![2016-01-04_1124](https://cloud.githubusercontent.com/assets/4663073/12094496/f2b2da28-b2d6-11e5-9c49-09387e85253d.png)

**Comment by dgcliff** [comment]
This is a result of unicode parsing and multiple dash types. Working on a fix.

**Comment by dgcliff** [comment]
Affected items will require a reindex (I manually did neu:963)
