### ISSUE TITLE
Title sort

### ISSUE THREAD

**Issue by sarahjeansweeney** [NEU-Libraries/cerberus#883]
Hillary pointed out to me that the title sort does not take mods:subtitle into account. The Spectrum magazine collection is a good example: https://repository.library.northeastern.edu/collections/neu:rx9143905

(Adding mods:subtitle to sort will not fix all the sorting issues with this collection, but it will bring the sort more in line with what users would expect.)
When users are browsing or choose to sort by title, the title sort should include mods:subtitle. 

There are two other mods:titleInfo elements that I didn't mention yesterday that we don't display: partNumber and partName. Would it be possible to add those fields to the display and the sort title, as well?

**Comment by dgcliff** [comment]
I suppose we might as well while we're at it

**Comment by dgcliff** [comment]
Do any existing records use partNumber and/or partName?

**Comment by sarahjeansweeney** [comment]
I can't think of any that use partName, but many of the Lower Roxbury records use partNumber: https://repository.library.northeastern.edu/files/neu:rx9187200
https://repository.library.northeastern.edu/files/neu:rx918695v

**Comment by dgcliff** [comment]
Could you give an example of an arbitrary full title? (Non-sort, title, subtitle, partnumber and partname)

So we can get idea of visually how it should be put together (i.e. the : seperator, etc.)

**Comment by sarahjeansweeney** [comment]
Sure. In fact, I'd suggest just replicating what the MODS display gem does:

nonSort title : subTitle. partNumber, partName

See: http://cerberus.library.northeastern.edu/files/neu:5425kc54v
