### ISSUE TITLE
Video records that need the download option removed

### ISSUE THREAD

**Issue by sarahjeansweeney** [NEU-Libraries/cerberus#884]
Here's a list of the records that will need the download version removed once #846 is in place:

https://repository.library.northeastern.edu/files/neu:rx917x56b
https://repository.library.northeastern.edu/files/neu:rx918002m
https://repository.library.northeastern.edu/files/neu:rx918938v
https://repository.library.northeastern.edu/files/neu:rx917z94z
https://repository.library.northeastern.edu/files/neu:rx918937k
https://repository.library.northeastern.edu/files/neu:rx918001b
https://repository.library.northeastern.edu/files/neu:rx917z99b
https://repository.library.northeastern.edu/files/neu:rx9189394
https://repository.library.northeastern.edu/files/neu:rx9189369
https://repository.library.northeastern.edu/files/neu:rx918943q
https://repository.library.northeastern.edu/files/neu:rx918942f
https://repository.library.northeastern.edu/files/neu:rx9189415
https://repository.library.northeastern.edu/files/neu:rx918940w
https://repository.library.northeastern.edu/files/neu:rx9189440
https://repository.library.northeastern.edu/files/neu:rx9189458
https://repository.library.northeastern.edu/files/neu:rx918946j

**Comment by dgcliff** [comment]
Ok, will loop through and retroactively apply, hopefully later today

**Comment by dgcliff** [comment]
Should be good to go

**Comment by sarahjeansweeney** [comment]
Looks good - thanks!
