### ISSUE TITLE
Collection not displaying on Faculty page

### ISSUE THREAD

**Issue by sarahjeansweeney** [NEU-Libraries/cerberus#891]
I created this collection a few days ago: https://repository.library.northeastern.edu/collections/neu:cj82k8561
I created the collection for Phil Brown (https://repository.library.northeastern.edu/employees/neu:m039tg163), a faculty user David created for me the other day, by impersonating him and adding a new personal collection.

Patrick pointed out to me that the Catskills collection does not display on his faculty page:

<img width="1225" alt="2016-01-14_1027" src="https://cloud.githubusercontent.com/assets/4663073/12328540/c822cf54-baa9-11e5-89e1-6321ed55675f.png">

It doesn't seem to be a permissions issue, since it's discoverable even when I'm logged out, but I can't figure out why no one can see the Catskills collection on his public page. I can see the collection when I impersonate him:

<img width="1225" alt="2016-01-14_1029" src="https://cloud.githubusercontent.com/assets/4663073/12328546/cb30cf70-baa9-11e5-9aad-f80607a770ca.png">

I originally assumed this was a metadata problem, so I did update the collection's RELS-EXT, which was slightly different than other personal collections for other faculty. The collection had two parent collections, so I removed the relationship that didn't match other faculty personal collections:

```
<rdf:RDF xmlns:ns0="info:fedora/fedora-system:def/model#" xmlns:ns1="info:fedora/fedora-system:def/relations-external#" xmlns:rdf="http://www.w3.org/1999/02/22-rdf-syntax-ns#">
  <rdf:Description rdf:about="info:fedora/neu:cj82k8561">
    <ns0:hasModel rdf:resource="info:fedora/afmodel:Collection"></ns0:hasModel>
    <!-- Removed --><ns1:isMemberOf rdf:resource="info:fedora/neu:m039tg163"></ns1:isMemberOf>
    <ns1:isMemberOf rdf:resource="info:fedora/neu:m039tg17c"></ns1:isMemberOf>
  </rdf:Description>
</rdf:RDF>
```

**Comment by dgcliff** [comment]
Ack, that may have not been the right thing to do. We have a root collection that's almost never seen to allow for things to work. I'll take a look and see if I can repair it.

Worth noting that I made that Philip Brown node, so something might be missing.

**Comment by dgcliff** [comment]
Wait...this is an empty collection. By design, (and request, if I remember), we don't show empty collections at the employee level.

**Comment by dgcliff** [comment]
I've restored the RELS-EXT to what it was before. If you upload a file to that collection, it'll show as expected.

**Comment by sarahjeansweeney** [comment]
Oh right, that was something we requested. So if that's why it's not displaying, why can I see the smart collections, which are also all empty?

**Comment by dgcliff** [comment]
Because you have proxy, I believe. I don't and can't.

**Comment by sarahjeansweeney** [comment]
So proxy users can see empty smart collections, but they can't see empty user-created collections?

**Comment by dgcliff** [comment]
That's how it's currently built. I imagine we didn't expect proxy users to have a need to upload to collections that weren't either in one of the smart categories, or directly on the main graph (and were empty). It's a fairly narrow corner case.

**Comment by dgcliff** [comment]
Happy to figure out how to amend that if you want.

**Comment by sarahjeansweeney** [comment]
I would prefer them to behave similarly, but as you say, this case is an outlier (and will most likely only affect me), it's fine to leave as is.

**Comment by dgcliff** [comment]
one line fix, will make a hotfix
