### ISSUE TITLE
A/V Closed Captioning Support

### ISSUE THREAD

**Issue by sarahjeansweeney** [NEU-Libraries/cerberus#894]
Patrick has requested support for A/V with closed captioning. 
The plain text caption file (.vtt) would be supplied at the time of upload and would be stored as an additional derivative file, possibly indexed.

**Comment by elizoller** [comment]
From the jwplayer perspective, this looks relatively simple: https://support.jwplayer.com/customer/portal/articles/1407438-adding-closed-captions

**Comment by elizoller** [comment]
- [ ] add a text datastream to a core file
- [ ] interface for uploading the closed captioning file
- [ ] reconfigure jwplayer to handle the file if its present

**Comment by elizoller** [comment]
Progress on https://github.com/NEU-Libraries/cerberus/tree/feature/av_captions

**Comment by elizoller** [comment]
As far as permissions go - this should inherit from the core_file, right? and/or be determined by sentinels?

**Comment by dgcliff** [comment]
Yeah - inherit from the core_file, then apply a sentinel if it exists is the safest way. It does do some redundant things (you don't need edit, or depositor on a content object for example) but it covers all bases

**Comment by dgcliff** [comment]
Fixed with f09221f9ef43b3f0a35d996d6e534d15a5c6f821
