### ISSUE TITLE
New Featured Content/Scholarly Object Collection: Technical Reports

### ISSUE THREAD

**Issue by sarahjeansweeney** [NEU-Libraries/cerberus#897]
A new Scholarly Object collection needs to be created for "Technical Reports".
Each faculty member will need a new "Technical Reports" smart collection, and it will need to be added to the featured content area of the homepage, too. Icon suggestions are welcome, but I think this one works well: http://fortawesome.github.io/Font-Awesome/icon/bar-chart/

The "Technical Reports" designation will live in the scholarly_object MODS extension:

```
<mods:extension displayLabel="scholarly_object">
    <scholarly_object>
      <category>Technical Reports</category>
      <department/>
      <degree/>
      <course_info>
        <course_number/>
        <course_title/>
      </course_info>
    </scholarly_object>
  </mods:extension>
```

Technical Reports can live in between Monographs and Communities (the same space currently held by Datasets)

**Comment by sarahjeansweeney** [comment]
The char will be used for statistics. Use this instead: http://fortawesome.github.io/Font-Awesome/icon/university/

**Comment by elizoller** [comment]
What will the description be for this?

**Comment by elizoller** [comment]
Last time we added a new one (monographs i think), @dgcliff had to run something to give all the existing employee objects a technical reports smart collection

**Comment by sarahjeansweeney** [comment]
@elizoller Here's the description:
Documents describing research conducted by Northeastern faculty and staff.

**Comment by elizoller** [comment]
Decided to push this fix to a feature branch since the front end fixes won't completely close the ticket.

**Comment by elizoller** [comment]
fixed with https://github.com/NEU-Libraries/cerberus/commit/4f9b54d6244836f192d36ddafaa27a72f840e6f9
