### ISSUE TITLE
Moving files can create duplicates in a Set

### ISSUE THREAD

**Issue by sarahjeansweeney** [NEU-Libraries/cerberus#899]
Vicki did some testing on the new Sets features yesterday and discovered a way to have duplicate files within the Set: if a Set contains a single file and a collection, and that single file is moved to that collection, the file continues to exist as a single file and is now also a member of the collection. Here's an example: http://cerberus.library.northeastern.edu/sets/neu:cz30pv431

This set contains Random Objects and "Youngs Gap Casino". After the "Youngs Gap Casino" file was added to the Random Set, the file itself was moved to Random Objects. Now "Youngs Gap Casino" lives in the Set as an individual file and in the Random Objects collection.

This doesn't cause any issues from the user's perspective, but if I remember correctly from our Sets discussions, duplicate files is something we want to avoid.

**Comment by dgcliff** [comment]
Yep. And why I wanted to never allow moving lol

Ok, we can figure out a way to ensure after an item is moved, that Sets, and whatever else, is reconciled to match.

**Comment by dgcliff** [comment]
Fixed with 8a8cc2d6cc27251757821b6dbd6296dcb9e07226
