### ISSUE TITLE
Daily report statistics for Admin panel

### ISSUE THREAD

**Issue by sarahjeansweeney** [NEU-Libraries/cerberus#900]
Here are the daily report statistics that should be added to the Admin panel:
- Core file views
- Core file downloads
- Unique users
- New users?
- Uploads (count and file size?)
  - Interface uploads?
  - Loader uploads?
  - Total uploads 
- Core file edits
  - Edit tab edits?
  - XML tab edits?
  - Total core file edits

The admin panel statistics page already includes a count for files by file type; could a third column be added to include the total size for that file type?

**Comment by elizoller** [comment]
Fixed with https://github.com/NEU-Libraries/cerberus/commit/4f9b54d6244836f192d36ddafaa27a72f840e6f9
