### ISSUE TITLE
Users can't log out, view thumbnails

### ISSUE THREAD

**Issue by sarahjeansweeney** [NEU-Libraries/cerberus#901]
Both Kristen and Dan reported to me that they can't click the down arrow next to their name to logout, nor can they add new items or view any thumbnails. 
I can't replicate this problem on my machine in any browser, but I did watch over their shoulder and it's definitely happening for them.
They're both on PCs, and we tried in a few different browsers, including Chrome, Firefox, and IE (Dan's versions are: Chrome, Version 48.0.2564.97 m, Firefox: 44). I had Dan send me these screenshots, which may be helpful:

Chrome:

![chrome](https://cloud.githubusercontent.com/assets/4663073/12677386/a24c64f2-c666-11e5-8dc0-4641eeeaebc0.png)

Firefox:

![image003 jpg](https://cloud.githubusercontent.com/assets/4663073/12677387/a4521b0c-c666-11e5-843e-870e2e857dd4.jpeg)

Let me know if you need any more info.

**Comment by dgcliff** [comment]
I can't reproduce in any browser.

**Comment by dgcliff** [comment]
Frustrating as it is, the only thing I can suggest is a hard refresh. It's not something related  to their account, or as far as I can tell anything related to the site itself, in so much as their javascript loaded weird on their computer...

**Comment by dgcliff** [comment]
I did do a deploy earlier this morning (before 9am) - I'm going to bet they were on early, and caught the server before it was fully ready.

**Comment by sarahjeansweeney** [comment]
Dan just let me know that he's not experiencing the problem anymore, so you're probably right.
