### ISSUE TITLE
All DRS objects added to a Set

### ISSUE THREAD

**Issue by sarahjeansweeney** [NEU-Libraries/cerberus#902]
Since staging had been cleaned out, I created a whole new Set for testing. After I added the Set details (title, permissions, etc) I clicked Submit. The Set was created successfully, but it seems all DRS collections and communities were added to the Set:

![2016-02-01_0850](https://cloud.githubusercontent.com/assets/4663073/12719233/d766cbfc-c8c1-11e5-97ff-ad24786806d3.png)

I tried again as the Admin user with the same result (http://cerberus.library.northeastern.edu/sets/neu:cz30pw26k).
The file count is 0, though I have the option to limit by "text" (doing so causes a system error - even selecting "more" in the facet menu causes an error).

Adding a file to the Set works as expected, and that seems to remove all the collections and communities (see: http://cerberus.library.northeastern.edu/sets/neu:cz30pw259).

**Comment by elizoller** [comment]
fixed with 5975893f9636ca85cbf1282f53eb4288fa97a81f

**Comment by elizoller** [comment]
Deploying to staging now. They weren't "in the set" the query was just pulling back everything since there was nothing in the set.
