### ISSUE TITLE
"Save files for later" doesn't appear for collection or community searches

### ISSUE THREAD

**Issue by sarahjeansweeney** [NEU-Libraries/cerberus#904]
The ability to add search results to a Set only appears on search results pages from searches performed using the full DRS search box:

![2016-02-01_1021](https://cloud.githubusercontent.com/assets/4663073/12721405/b1bc9b5a-c8cd-11e5-97bb-e28f489df81a.png)

The button does not appear on results pages for scoped community or collection searches:

![2016-02-01_1027](https://cloud.githubusercontent.com/assets/4663073/12721547/6cd69490-c8ce-11e5-955c-6da8f517e997.png)

**Comment by elizoller** [comment]
Do you want it there on all browse pages or just when a search has been run?

**Comment by sarahjeansweeney** [comment]
All pages would be preferable. It should probably be considered part of the facet and sort options.

**Comment by dgcliff** [comment]
If current_user isn't nil (i.e. they're logged in and thus have the capacity for sets)

**Comment by elizoller** [comment]
Right. Moving the button into a partial so it can be easily shared across the different views.
