### ISSUE TITLE
Add search results modal

### ISSUE THREAD

**Issue by sarahjeansweeney** [NEU-Libraries/cerberus#906]
The functionality works just fine for the "Save files for later" search results button. This isn't a high priority, but when a user adds a list of results to a set that already contains some of those files (so, adding core files a & b, but b already exists in the set), the message only mentions the files it will add (i.e. "Are you sure you want to add 1 files to "Catskills"?"). 

![2016-02-01_1051](https://cloud.githubusercontent.com/assets/4663073/12722375/af2161c8-c8d2-11e5-9041-253e9189de42.png)

Can the number of items already in the Set (which will not be added) also be included in the modal?:
"Catskills" already contains X files. Are you sure you want to add 1 files to "Catskills"?

**Comment by elizoller** [comment]
<img width="498" alt="screen shot 2016-02-01 at 11 22 28 am" src="https://cloud.githubusercontent.com/assets/5439169/12723161/42784b5a-c8d6-11e5-8261-d1e53330351d.png">

**Comment by dgcliff** [comment]
Super picky - could we do 

> file(s) (to account for 1..n)

**Comment by elizoller** [comment]
yeah do you want it to check for > 1 before adding the s? or just use file(s) in the sentence?

**Comment by dgcliff** [comment]
Both works, one's much easier (and I'm lazy, so if it were me :stuck_out_tongue:)
