### ISSUE TITLE
"Creators List" names redirect to the communities list

### ISSUE THREAD

**Issue by sarahjeansweeney** [NEU-Libraries/cerberus#910]
When I click on any of the creator names in the "Creators List" for ETDs or Research Publications I'm taken to the communities list instead of a list of files created by that person. This doesn't seem to happen to communities or collections.

**Comment by elizoller** [comment]
Can you give me examples of where this happens? 
I tried from home page ETDs and from a faculty > ETD and from a community > ETD

**Comment by sarahjeansweeney** [comment]
Sure, try this:
Go to https://repository.library.northeastern.edu/theses_and_dissertations
Click on the "Creator List" button
Click any of the names in the list

http://screencast.com/t/2oauPstMp

**Comment by elizoller** [comment]
Oh I see. I was missing the part about clicking on the name.
