### ISSUE TITLE
Replacement thumbnail not displaying on zip core file page

### ISSUE THREAD

**Issue by sarahjeansweeney** [NEU-Libraries/cerberus#912]
I uploaded a replacement thumbnail for this file last week: https://repository.library.northeastern.edu/files/neu:rx918190f

The replacement file displays in browse and search, but not on the core file page:

<img width="669" alt="2016-02-08_1609-1" src="https://cloud.githubusercontent.com/assets/4663073/12899240/5674989a-ce7e-11e5-8f1e-56d9503891aa.png">

<img width="759" alt="2016-02-08_1609" src="https://cloud.githubusercontent.com/assets/4663073/12899246/5e057bc4-ce7e-11e5-8384-7ba0a01a9809.png">

**Comment by dgcliff** [comment]
Pretty sure this is due to how we handle zip files and is a bug (sort of). I think, logically, we didn't expect any thumbnails for a zip file. Will look into patching.
