### ISSUE TITLE
Increase handle visibility

### ISSUE THREAD

**Issue by sarahjeansweeney** [NEU-Libraries/cerberus#913]
I think users would use/share the handles more often if they were more visible on the page. Since handles are stored in the identifier field, MODS display pushes handles to the bottom of the core file page. Can the handle display also be included closer to the top of the page? I'm open to suggestions for where they'd fit (between the page title and thumbnail? Underneath the thumbnail? Between the metadata tab and MODS display?)

**Comment by elizoller** [comment]
I will do some screenshots of different variations on this.

**Comment by elizoller** [comment]
<img width="1222" alt="screen shot 2016-02-18 at 12 49 36 pm" src="https://cloud.githubusercontent.com/assets/5439169/13152634/1f292d3e-d63e-11e5-9b17-90a1cc82107a.png">
<img width="1213" alt="screen shot 2016-02-18 at 12 49 11 pm" src="https://cloud.githubusercontent.com/assets/5439169/13152633/1f2914d4-d63e-11e5-9ec6-4c84cb46f58c.png">
<img width="1233" alt="screen shot 2016-02-18 at 12 48 58 pm" src="https://cloud.githubusercontent.com/assets/5439169/13152635/1f298d1a-d63e-11e5-93cd-0b1ed4fd7a91.png">
<img width="1195" alt="screen shot 2016-02-18 at 12 42 02 pm" src="https://cloud.githubusercontent.com/assets/5439169/13152636/1f298f18-d63e-11e5-864b-1148c8e7765d.png">
<img width="1230" alt="screen shot 2016-02-18 at 12 41 46 pm" src="https://cloud.githubusercontent.com/assets/5439169/13152637/1f2a0970-d63e-11e5-9146-42eb322e90ec.png">
<img width="1216" alt="screen shot 2016-02-18 at 12 41 31 pm" src="https://cloud.githubusercontent.com/assets/5439169/13152638/1f3532b4-d63e-11e5-943b-00bb6d2f361e.png">
<img width="1216" alt="screen shot 2016-02-18 at 12 39 50 pm" src="https://cloud.githubusercontent.com/assets/5439169/13152640/1f3a3a8e-d63e-11e5-9b5a-6b89875bca9b.png">
<img width="1238" alt="screen shot 2016-02-18 at 12 39 35 pm" src="https://cloud.githubusercontent.com/assets/5439169/13152642/1f3d3e1e-d63e-11e5-824c-702e1b38c539.png">
<img width="1228" alt="screen shot 2016-02-18 at 12 38 47 pm" src="https://cloud.githubusercontent.com/assets/5439169/13152643/1f3d2ffa-d63e-11e5-9ec0-afe760fe4c59.png">
<img width="1240" alt="screen shot 2016-02-18 at 12 36 20 pm" src="https://cloud.githubusercontent.com/assets/5439169/13152641/1f3d2334-d63e-11e5-8bde-f03f02ce43dc.png">
<img width="1239" alt="screen shot 2016-02-18 at 12 35 55 pm" src="https://cloud.githubusercontent.com/assets/5439169/13152639/1f3a0e42-d63e-11e5-9719-001e65f344a4.png">
<img width="1258" alt="screen shot 2016-02-18 at 12 35 33 pm" src="https://cloud.githubusercontent.com/assets/5439169/13152644/1f4423f0-d63e-11e5-903e-2007d5b46b44.png">

**Comment by sarahjeansweeney** [comment]
I prefer the "[link icon] Permanent URL:" format. As for placement, visually I prefer the URL to the right above the metadata 
(https://cloud.githubusercontent.com/assets/5439169/13152635/1f298d1a-d63e-11e5-93cd-0b1ed4fd7a91.png), but the URL above the thumbnail would compete less with long titles ((https://cloud.githubusercontent.com/assets/5439169/13152641/1f3d2334-d63e-11e5-8bde-f03f02ce43dc.png), so let's go with that.
