### ISSUE TITLE
Empty faculty lists

### ISSUE THREAD

**Issue by sarahjeansweeney** [NEU-Libraries/cerberus#914]
Community faculty lists don't contain any faculty at the moment:

<img width="1018" alt="2016-02-08_1625" src="https://cloud.githubusercontent.com/assets/4663073/12899715/b0fcf9a4-ce80-11e5-9f61-db6b14e4e9b0.png">
I tried a few, including https://repository.library.northeastern.edu/communities/neu:417/employees, https://repository.library.northeastern.edu/communities/neu:175/employees, and https://repository.library.northeastern.edu/communities/neu:38/employees)

The community's smart collections contain files, and the homepage Faculty collections displays the full list of faculty. They only appear to be missing from the community faculty lists.

**Comment by dgcliff** [comment]
Have a fix for this, just doing some testing before I apply it.
