### ISSUE TITLE
Randomly bolded text

### ISSUE THREAD

**Issue by sarahjeansweeney** [NEU-Libraries/cerberus#915]
This isn't terribly important, but I've noticed today that some page text is randomly bolded:

<img width="751" alt="2016-02-08_1621" src="https://cloud.githubusercontent.com/assets/4663073/12899930/b44abd48-ce81-11e5-9d33-d73e9b6d1df2.png">

It's sometimes just one word (like above), and other times is most of the text on the page:

<img width="1225" alt="2016-02-08_1621-1" src="https://cloud.githubusercontent.com/assets/4663073/12899951/ccd0932e-ce81-11e5-8a59-eb173fdb25f9.png">

Reloading the page returns the text back to its normal weight:

<img width="1225" alt="2016-02-08_1622" src="https://cloud.githubusercontent.com/assets/4663073/12899966/df9a100c-ce81-11e5-9d0d-433828047940.png">

**Comment by dgcliff** [comment]
I think that is a result of the CSS loading imperfectly, and was as a result of a server issue (I was trying to make GZIP work again.) When the page loads as it should, I can't reproduce the issue. Will close for now, but will reopen if we see it in the wild again.

**Comment by sarahjeansweeney** [comment]
Not sure if this counts, but I just noticed this in staging:
![2016-02-09_1338](https://cloud.githubusercontent.com/assets/4663073/12926683/972bd4a2-cf32-11e5-8485-ed9067fcc4b9.png)

I haven't seen it in production, though.
