### ISSUE TITLE
Expand "employee" to include staff

### ISSUE THREAD

**Issue by sarahjeansweeney** [NEU-Libraries/cerberus#917]
Right now only faculty are designated as "employees" and given access to My DRS and the ability to upload. We'd like to expand that to include staff, as well.

The "Faculty" label in the "Featured Content" area will need to be changed to "Faculty and Staff". I'll update the hover over descriptions in the YAML when we're ready.

We should wait to implement this change until after storage has been increased.

**Comment by sarahjeansweeney** [comment]
This can move forward now that storage has been resolved.

**Comment by elizoller** [comment]
I think this can be closed with pull request #929 , e143131d22914271541085af13a53736cef9976d, cb817c3d19e795eadc74d5e79cfb3fd283580ee7, 7655474f886f22244317d94e9116210d1fb507ec, 694db89ec6a6c0b55dfd47b8061442aa91916a5e, 55e387c5cec7267d46b7705f94874cf1bd01f953, 5fc97ac85f3b12342163ed18e4d469a4ed54ca68
