### ISSUE TITLE
Permanent URL displays identifier, not handle

### ISSUE THREAD

**Issue by sarahjeansweeney** [NEU-Libraries/cerberus#918]
I found this record that has an identifier in the Permanent URL display: https://repository.library.northeastern.edu/files/neu:131795

![2016-02-26_0858](https://cloud.githubusercontent.com/assets/4663073/13354194/80f7bf92-dc67-11e5-94c2-698c31a04060.png)

Since the handle is stored in an identifier field, it's probably just selecting the first identifier. It should only select the identifier field with the "handle" type attribute:

`<mods:identifier displayLabel="Permanent URL" type="handle">`

**Comment by elizoller** [comment]
Ok i'll check it out

**Comment by dgcliff** [comment]
These items just need to be re-indexed - I did so with neu:131795 and it solved the issue. If you could come up with a rough list of items (or their collections) where items with multiple identifiers are, and I'll script to re-index them

**Comment by sarahjeansweeney** [comment]
Okay - almost all of the Archives records have additional identifiers: https://repository.library.northeastern.edu/collections/neu:6002

**Comment by dgcliff** [comment]
I'm running a loop to re-index the affected files right now. Hopefully won't take too long
