### ISSUE TITLE
Facet box covers the "more" modal in grid view

### ISSUE THREAD

**Issue by sarahjeansweeney** [NEU-Libraries/cerberus#919]
When in grid view, the facet box covers the modal when you select "more" from "Limit your search":

![2016-02-26_0854](https://cloud.githubusercontent.com/assets/4663073/13354296/015ccc4a-dc68-11e5-82f8-82f23e7da5cd.png)

To replicate:
Do a search
Display results in grid view
Click "Limit your search"
Hover over subjects and click "more subjects"
The subjects modal will appear and the facet options will remain and cover the modal. 

Clicking "Next" or "A-Z Sort" seems to make the box disappear.

**Comment by elizoller** [comment]
Probably a z-index issue

**Comment by elizoller** [comment]
Fixing the z-index will mean the dropdown menu will be behind the modal but I think the real issue is that the dropdown doesn't close after you click a more link. Would that be what you would expect to happen?

**Comment by sarahjeansweeney** [comment]
Yes, exactly - the box should close completely, which is what I think it does in list view (they should do the same thing anyway).

**Comment by elizoller** [comment]
It doesn't do it in list or grid but I can make it.

**Comment by sarahjeansweeney** [comment]
yes, please!
