### ISSUE TITLE
Collection title URLs in the daily "Non-Featured Content and Collection Uploads and Update" emails

### ISSUE THREAD

**Issue by sarahjeansweeney** [NEU-Libraries/cerberus#921]
The title URL in the Updated and New Collections section of the "Non-Featured Content and Collection Uploads and Update" emails use the "files" route instead of the "collections" route, so they cause an error. Example below, but I'll forward one along as a better example:

Updated Collections
Collection: Brown, Philip (https://repository.library.northeastern.edu/collections/neu:m039tg17c)
**Title: The Catskills Institute (https://repository.library.northeastern.edu/files/neu:cj82k8561)**

Depositor: Brown, Philip (p.brown@neu.edu) 

Editor: Sweeney, Sarah Jean (sj.sweeney@neu.edu) 

PID: neu:cj82k8561

**Comment by elizoller** [comment]
Oops. 
Also I realize now that Collection for the parent and title for the collection update/edited looks confusing. Do you want that changed?

**Comment by sarahjeansweeney** [comment]
Nah, it's fine for now.
