### ISSUE TITLE
mp3 file zipped at upload

### ISSUE THREAD

**Issue by sarahjeansweeney** [NEU-Libraries/cerberus#922]
An mp3 file that Joey uploaded earlier today (https://repository.library.northeastern.edu/files/neu:cj82ks85k) was zipped instead of treated as an mp3 file. We both checked the file (FITS and MedaiInfo) and we can't see anything about the file that would cause the DRS to zip it at upload. Is there a way to find out why the file was zipped?

**Comment by dgcliff** [comment]
Looking into it

**Comment by dgcliff** [comment]
```➜  cerberus git:(master) ✗ file --mime-type /home/vagrant/cerberus/AV-1028-1.mp3
/home/vagrant/cerberus/AV-1028-1.mp3: application/octet-stream```

File thinks it's octet-stream. Given that it hasn't done this to other MP3's, I would have to assume something is indeed different about this file.

**Comment by sarahjeansweeney** [comment]
http://stackoverflow.com/questions/2754713/why-some-mp3s-on-mime-content-type-return-application-octet-stream
This seems to say that MP3s are special snowflakes and the "something different" might just be that whatever identifies it as an MP3 is buried.

**Comment by dgcliff** [comment]
Hm...ok. I'll put in a catch clause for octet-stream where if the extension provided is one we support, to then default to that, instead of zipping. But if we ever get a "this file is the wrong type" as a result of this ticket, I reserve the right to rub it in someones face (the uploaders, not yours :P)

**Comment by sarahjeansweeney** [comment]
Before you do that, Joey just called me to let me know the file actually has the wrong codec. The file uploaded as expected when he changed it. So...yeah.

**Comment by dgcliff** [comment]
Haha, ok. Then I'll close, and we can do it if it happens with a genuine case :+1:
