### ISSUE TITLE
Add niec_lends_itself_to_use_of_space_ssim and niec_lends_itself_to_classifiers_ssim to facets

### ISSUE THREAD

**Issue by elizoller** [NEU-Libraries/cerberus#924]
Damon has reported that there are two values which they use as facets which are not facets in the DRS.
niec_lends_itself_to_classifiers_ssim and niec_lends_itself_to_use_of_space_ssim

I'm fairly certain adding them to catalog controller won't be a problem but then the NIEC items will need to be reindexed for them to show up as facets- is that correct?

**Comment by dgcliff** [comment]
Yep - we'll have to check our mods extension for niec has those starting values too
