### ISSUE TITLE
EMSA Zip Loader Error

### ISSUE THREAD

**Issue by sarahjeansweeney** [NEU-Libraries/cerberus#925]
I noticed this morning that the EMSA loader encountered this error for one of the files Julio tried to upload (https://repository.library.northeastern.edu/loaders/emsa/report/458):

Error - Can't connect to MySQL server on 'librarystaff.neu.edu' (111)

13 of the 14 files in the zip seem to have been processed as expected, just not that one file.

**Comment by dgcliff** [comment]
That's it trying to make a handle. I'm hoping it was just a network hiccup - will talk with Ernesto to check on it's health

**Comment by dgcliff** [comment]
Looks like it was an ITS thursday reboot...will look into what we can do
