### ISSUE TITLE
Collection handles and identifiers

### ISSUE THREAD

**Issue by sarahjeansweeney** [NEU-Libraries/cerberus#926]
David pointed out two things about collection handles:
- Collections that were created before we started creating handles for every DRS collection will need to have handles generated and inserted into their MODS records
- Some collections that were migrated from the old DRS have hyperlinked PIDs for other DRS collections in place of a handle. This will probably disappear from the display when they have a proper handle?

**Comment by dgcliff** [comment]
We should still scrub that bad pid/handle info anyway. Do you mind putting up one of the examples we found?

**Comment by sarahjeansweeney** [comment]
Nope - should have added this originally! : https://repository.library.northeastern.edu/collections/neu:6004

![2016-03-18_1558](https://cloud.githubusercontent.com/assets/4663073/13890837/f22ea834-ed23-11e5-945e-fae20875b5b4.png)

**Comment by dgcliff** [comment]
Should be finished now
