### ISSUE TITLE
Smart Collection Statistics

### ISSUE THREAD

**Issue by sarahjeansweeney** [NEU-Libraries/cerberus#930]
Since the collection statistics tab is behind the "Manage Collection" button, there's no way for faculty/staff users to see the statistics for their smart collections:

![2016-03-21_0923](https://cloud.githubusercontent.com/assets/4663073/13919964/c7608260-ef46-11e5-82c1-074fc1df5874.png)

We still don't want users to edit their Smart Collections, but can we add a way for users to view their statistics? I can think of two ways to do this:

1. Add the "Manage Collection" button to Smart Collections that contains a tab that describes how Smart Collections work and why they can't be edited and the statistics tab.
2. Add a plain "Statistics" button in place of the "Manage Collection" button that works like the statistics tab.

**Comment by elizoller** [comment]
Will this be determined based on user edit permissions like the manage buttons on the regular collections?

**Comment by sarahjeansweeney** [comment]
Yeah, I think that makes sense.

**Comment by elizoller** [comment]
This will only be for smart collections which are attached to users?
What about the ones at the community level?
And at the system level?
How will the permissions be determined for those or will they not have statistics?

**Comment by sarahjeansweeney** [comment]
Just users' smart collections should be fine.

**Comment by elizoller** [comment]
The partial shared/sets/edit is used for editing compilations(sets) and collections (including smart collections).
There are four scenarios that determine the tabs which show up on that page.

1. Type == Compilation -> User (with edit permissions) can edit, delete, statistics (not move)
2. Type == Collection, is_smart_collection? == false (aka regular collection) -> User (with edit permissions) can edit, move (request), delete (request), statistics (not move)
3. Type == Collection, is_smart_collection? == true, smart_collection_type == miscellany (aka regular user collection) -> User (with edit permissions) can edit, move, delete, statistics
4. Type == Collection, is_smart_collection? == true, smart_collection_type != miscellany (aka true smart collection like research publications) -> User (with edit permissions) can statistics (not edit, move, or delete)

**Comment by elizoller** [comment]
Do you have text in mind for the explanation of smart collection not being edit-able?

**Comment by sarahjeansweeney** [comment]
This should do for now:

This Smart Collection is designed to help you easily share your scholarly work with the Northeastern University community. The files you upload to this collection will be displayed as part of your communities' collections, as well.

This collection cannot be edited because it was automatically generated by the system and is connected to other collections in the DRS. If you want to create a new collection, you can do so by clicking "Create a new collection" under "User Created Collections" on your My DRS page.

**Comment by elizoller** [comment]
Sounds good. Thanks

**Comment by elizoller** [comment]
<img width="1217" alt="screen shot 2016-04-04 at 7 29 39 am" src="https://cloud.githubusercontent.com/assets/5439169/14246723/03fb6ffa-fa37-11e5-9e8c-7003d176ae93.png">

**Comment by sarahjeansweeney** [comment]
Looks good - thanks.
