### ISSUE TITLE
Faculty and staff in the type facet

### ISSUE THREAD

**Issue by sarahjeansweeney** [NEU-Libraries/cerberus#931]
Now that we have staff users, the "Faculty" facet label should be updated to "Faculty and Staff":

<img width="498" alt="2016-03-21_1410" src="https://cloud.githubusercontent.com/assets/4663073/13929374/39befe80-ef70-11e5-92d3-541706472f63.png">

**Comment by elizoller** [comment]
<img width="466" alt="screen shot 2016-04-01 at 12 00 06 pm" src="https://cloud.githubusercontent.com/assets/5439169/14212520/4f0a0a98-f801-11e5-9d36-11e1589e66dc.png">

**Comment by elizoller** [comment]
Just need to reindex employee objects and the label should change.

**Comment by dgcliff** [comment]
cool, I'll try and kick that off sometime today

**Comment by elizoller** [comment]
:+1: thanks

**Comment by elizoller** [comment]
@dgcliff finished reindex so label is up to date
<img width="458" alt="screen shot 2016-04-08 at 8 13 21 am" src="https://cloud.githubusercontent.com/assets/5439169/14383243/d4c980c2-fd61-11e5-8217-677b39f1b89b.png">
