### ISSUE TITLE
RSS feeds for communities and collections

### ISSUE THREAD

**Issue by sarahjeansweeney** [NEU-Libraries/cerberus#932]
A feed to see and share most recently deposited items at the collection and community level has been requested twice now. Not sure if we want to do this using RSS or the API.

**Comment by elizoller** [comment]
Would this be nested? Just thought I'd take a look at this real quick and it turns out blacklight gives us RSS out of the box. I just wired in the few fields (RSS specification is NOTHING compared to OAI...) and it works for translating what is directly off a specific collection/community. If it's nested you want, it'd probably take a little bit more work but maybe not that much.

**Comment by sarahjeansweeney** [comment]
I think nested RSS would be preferable (we already know this is what users want, since RSS is essentially equal to the "Recently Deposited" button).
For communities it would have to be nested, right? Otherwise community rss would just be for newly added collections, which would be fairly boring.

**Comment by elizoller** [comment]
Actually I should just be able to wire it in with recent deposits then. So it'd be like the recent deposit url with ?format=rss on the end.

**Comment by dgcliff** [comment]
Seems ideal

**Comment by elizoller** [comment]
May end up only being like 10-20 lines of code

**Comment by sarahjeansweeney** [comment]
:smiley:

**Comment by elizoller** [comment]
Ok I have this working for communites, collections, and smart collections all based off the recent_deposits. So basically if you add on .rss to the url it works. (note that this already worked for the search url but I never knew hah)
path examples:
- /communities/[pid]/recent.rss or /communities/[pid]/recent?format=rss
- /collections/[pid]/recent.rss or /collections/[pid]/recent?format=rss
- /technical_reports/recent.rss or /technical_reports/recent?format=rss
- /communities/[pid]/technical_reports/recent.rss or /communities/[pid]/technical_reports/recent?format=rss

Are you looking to have links to this in the interface somewhere?

**Comment by sarahjeansweeney** [comment]
Yeah, links for users would be useful. If rss is available for communities, collections, and search, I think the link (using an rss icon [either font awesome version is fine, but i like this one: http://fortawesome.github.io/Font-Awesome/icon/rss/]) should fit at the end of the facet area, near the Refresh button. I think there's plenty of space in list view, but grid view may be a bit tighter.

**Comment by elizoller** [comment]
Like down near 'Save files for later'?

**Comment by sarahjeansweeney** [comment]
Yup, that works.

**Comment by elizoller** [comment]
I pushed this staging to look at

**Comment by dgcliff** [comment]
Petty difference, but can the button be btn-clear?

**Comment by elizoller** [comment]
<img width="722" alt="screen shot 2016-04-11 at 12 02 50 pm" src="https://cloud.githubusercontent.com/assets/5439169/14433705/6a8cc664-ffdd-11e5-85b6-07d0fe38e8b0.png">
<img width="1232" alt="screen shot 2016-04-11 at 12 02 57 pm" src="https://cloud.githubusercontent.com/assets/5439169/14433711/6dc2d648-ffdd-11e5-86bc-9096ca7bf654.png">

**Comment by sarahjeansweeney** [comment]
Looks good - I like the clear background.

I was only able to see the button after I signed in, presumably because the RSS button is tied to "Save file for later", or is there logic behind restricting RSS to logged in users? I hadn't considered how RSS handles restricted content.

**Comment by elizoller** [comment]
That was going to be my next question - whether you want it to be available to all users or just logged in users? At this point it works like recent deposits so it determines permissions based on what the user can see. So if the user isn't logged in they will only get public items when they call the feed.

**Comment by sarahjeansweeney** [comment]
The more I think about this, the more I think that only public content should show up in the feed.
I think most people use a separate service for displaying rss feeds, like Feedly or a Wordpress widget, that can't be logged in.

**Comment by elizoller** [comment]
Makes sense. I'll do that and modify the button so you can see logged in or not.

**Comment by elizoller** [comment]
Do you want this for `neu:1`?

**Comment by sarahjeansweeney** [comment]
Unless it causes problems, yes! I know we're protective of neu:1, but rss seems fairly safe, right?

**Comment by dgcliff** [comment]
It's an expensive query off of neu:1, and really the rss should only have merit for vertical slices of the system (which is why it aligns well with the /recent path)

So my vote is no

**Comment by sarahjeansweeney** [comment]
What are the consequences of including a feed for neu:1?

**Comment by dgcliff** [comment]
You have to touch every single community/collection to get a true "recent" list. Even with pure solr, that's slow.

**Comment by dgcliff** [comment]
You could a totally different query, where you ignore the nested element and say "I want the last 10 core_files that were updated" - but that isn't done anywhere else, and isn't as cheap a win as the current rss implementation is elsewhere

**Comment by sarahjeansweeney** [comment]
Fair enough, we can move forward without it. If it seems worth having a neu:1 level query, we can revisit later.

**Comment by dgcliff** [comment]
Sounds good

**Comment by elizoller** [comment]
Fixed with https://github.com/NEU-Libraries/cerberus/pull/940
