### ISSUE TITLE
Store user's last "Show per page" choice

### ISSUE THREAD

**Issue by sarahjeansweeney** [NEU-Libraries/cerberus#935]
A few users have requested that we increase the number of results that display by default from 10 to 50 or 100. We probably don't want to do this globally for a few reasons, but if possible, can the user's last selection for the "Show per page" option be stored like we do for the List and Grid view choice?

**Comment by dgcliff** [comment]
Yep, I think that's definitely do-able

**Comment by elizoller** [comment]
Fixed with https://github.com/NEU-Libraries/cerberus/pull/938
