### ISSUE TITLE
Label for "Faculty and Staff" Featured Content

### ISSUE THREAD

**Issue by elizoller** [NEU-Libraries/cerberus#936]
The Featured Content/Smart Collections have labels on them for search and browse. They say "featured" except for the "Faculty and Staff" which doesn't have a label at all. 
When you search/browse and return single employee objects, they have the label "Person."
The "Faculty and Staff" featured content should probably have a label - perhaps "Faculty and Staff." We may also consider that the label should match/correlate with the single employee object?
One difficulty with using the "Faculty and Staff" label is that it is too long. Here are some proposed variations in CSS to make it work:
Let the label hang over the edges with a negative margin:
<img width="954" alt="screen shot 2016-04-04 at 7 46 00 am" src="https://cloud.githubusercontent.com/assets/5439169/14247119/e36adf66-fa39-11e5-854a-22beec066164.png">

Reduce the left/right padding:
<img width="955" alt="screen shot 2016-04-04 at 7 45 45 am" src="https://cloud.githubusercontent.com/assets/5439169/14247121/e372e74c-fa39-11e5-8fc9-e39aa9067af4.png">

Let the label wrap to two lines:
<img width="910" alt="screen shot 2016-04-04 at 7 45 31 am" src="https://cloud.githubusercontent.com/assets/5439169/14247120/e370f356-fa39-11e5-90f2-258f10e75706.png">

**Comment by sarahjeansweeney** [comment]
None of those options are ideal. I agree that they single employee should probably match the featured content object for faculty and staff, so maybe we should use "People" instead of "Faculty & Staff". "People" will fit, and it will match "Person" for the individual object.

**Comment by elizoller** [comment]
Ok will do
