### ISSUE TITLE
Error accessing the statistics daily report

### ISSUE THREAD

**Issue by sarahjeansweeney** [NEU-Libraries/cerberus#937]
This morning I received an DRS System Error when I tried to visit the daily report from the Admin statistics page: https://repository.library.northeastern.edu/admin/statistics/daily_report

**Comment by dgcliff** [comment]
So I was doing the multipage loading/deleting which has unearthed that a piece of that report doesn't handle deleted items. Easy fix, will patch today

**Comment by sarahjeansweeney** [comment]
This happened again this morning.
