### ISSUE TITLE
"Manage Collection" button not displaying in all expected collections

### ISSUE THREAD

**Issue by sarahjeansweeney** [NEU-Libraries/cerberus#939]
I'm not seeing the "Manage Collection" button in two places where I expect to see it:

1. Related to issue #930, when I impersonate a user I still don't see the "Manage Collection" option in his/her Smart Collections:
![2016-04-08_1011](https://cloud.githubusercontent.com/assets/4663073/14386341/4bcc78ea-fd72-11e5-963c-57fab1c7dabe.png)

2. I just created a series of collections as the Admin user (restricted, so you'll need to login to see it: https://repository.library.northeastern.edu/collections/neu:cj82m199j). When I'm logged in as myself, I see the "Manage Collection" option:

![2016-04-08_1013](https://cloud.githubusercontent.com/assets/4663073/14386400/94df18da-fd72-11e5-8050-8e3a4f7704bf.png)

But when I impersonate the Admin user (the creator of the collections), I can create new collections, but I don't have the "Manage Collection" option:

![2016-04-08_1003](https://cloud.githubusercontent.com/assets/4663073/14386413/a7f16cc0-fd72-11e5-8320-51d3f64ab317.png)

The Admin user and I share permissions, so we should have the same experience.

**Comment by elizoller** [comment]
Looking into it. I'm seeing now the can_edit method has logic to exclude smart collections, so removing that and fixing the button logic should fix this.
