### ISSUE TITLE
Download queue file extensions

### ISSUE THREAD

**Issue by sarahjeansweeney** [NEU-Libraries/cerberus#944]
I just downloaded a few videos using the Download Queue (see files in this Set: https://repository.library.northeastern.edu/sets/neu:cj82m953k)

The four files downloaded successfully, but the MP4 file extensions contain a comma, which should be removed: 

![2016-04-29_1057](https://cloud.githubusercontent.com/assets/4663073/14920086/cb9a9ba0-0df9-11e6-9ab6-d191e296ddbf.png)

Also, the files with the .qt file extension were uploaded with a .mov extension, not .qt. They're fine, I can play them, but how can these files be uploaded with one extension and then downloaded with another?

**Comment by dgcliff** [comment]
Hm. Odd that it's only for the mp4s. Will look into it.

**Comment by dgcliff** [comment]
The answer to the different extensions is that we don't trust user extensions - the linux file utility identified these files as qt, so that's what they were provided as.

**Comment by dgcliff** [comment]
In the event that multiple equivalent extension types are available, and one of them was the user supplied one, we can proactively choose that. Will make a patch for the MimeHelper module.

**Comment by dgcliff** [comment]
Turns out I already did the code for this, I just didn't apply it everywhere. Putting in a patch for the comma, will be up shortly.

**Comment by dgcliff** [comment]
fixed with 3ff3fb065f13a3293968edfa9af41e364228db0a
