### ISSUE TITLE
Staging system error

### ISSUE THREAD

**Issue by sarahjeansweeney** [NEU-Libraries/cerberus#945]
In an effort to help Daniel figure out if there's something wrong with the files he uploaded earlier today, I tried to upload one of his files to staging. I was able to get through the whole upload process, but when I reloaded the page to see if the file completed, I got a system error. Now every single page I go to on staging returns a system error. 

![2016-04-29_1658](https://cloud.githubusercontent.com/assets/4663073/14929495/b191b694-0e2b-11e6-981d-b9830abf231c.png)

![2016-04-29_1659](https://cloud.githubusercontent.com/assets/4663073/14929498/b39eff6e-0e2b-11e6-936e-c50f290dff19.png)

It's Friday afternoon and it's just staging, so this one can wait until next week.

**Comment by dgcliff** [comment]
Tomcat was down, brought it back up
