### ISSUE TITLE
MODS "keywords" field

### ISSUE THREAD

**Issue by sarahjeansweeney** [NEU-Libraries/cerberus#946]
When a file is uploaded through the interface, a
An empty "keyword" field is included in the MODS record for files uploaded through the interface:

```
<mods:subject>
    <mods:keyword/>
    <mods:topic>test</mods:topic>
</mods:subject>
```

When someone uses the XML editor to edit the metadata for these records the validation fails because "keyword" isn't a valid MODS field.

"Invalid XML provided: Nokogiri::XML::SyntaxError: Element '{http://www.loc.gov/mods/v3}keyword': This element is not expected. Expected is one of ( {http://www.loc.gov/mods/v3}topic, {http://www.loc.gov/mods/v3}geographic, {http://www.loc.gov/mods/v3}temporal, {http://www.loc.gov/mods/v3}titleInfo, {http://www.loc.gov/mods/v3}name, {http://www.loc.gov/mods/v3}geographicCode, {http://www.loc.gov/mods/v3}hierarchicalGeographic, {http://www.loc.gov/mods/v3}cartographics, {http://www.loc.gov/mods/v3}occupation, {http://www.loc.gov/mods/v3}genre )."

![2016-05-02_1701](https://cloud.githubusercontent.com/assets/4663073/14984488/fd24ddec-1110-11e6-97f8-584a4b89a60c.png)

I understand a blank keyword element is needed to create the record initially, but the MODS should at least validate. Can a MODS topic field be used instead of the general "keyword" field?:
```
<mods:subject>
    <mods:topic/>
    <mods:topic>test</mods:topic>
</mods:subject>

**Comment by dgcliff** [comment]
Yeah, the more I look at this, the more it seems like a (very) old vestigial mistake. Should be able to prevent it from happening, and delete it for existing items when they go to use the editor

**Comment by elizoller** [comment]
This is fixed in 3b16432b061c971f1f3cfa9a5067e3e721fc57b3 which will be merged in with the spreadsheet loader.

**Comment by elizoller** [comment]
Reopening - the commit above refers to newly created records. Not sure about cleaning up old records when users use the editor.

**Comment by dgcliff** [comment]
Probably a hand-done nokogiri xpath search and node deletion on preview/save
