### ISSUE TITLE
Attaching new files to an existing core file

### ISSUE THREAD

**Issue by sarahjeansweeney** [NEU-Libraries/cerberus#949]
In support of our forthcoming preservation work, there needs to be a mechanism for advanced users (primarily Joey) to upload additional preservation master or access copies of a file and attach them to an existing core file. 

- [x] - The add feature will be limited to just the members of the 'admin' group (northeastern:drs:repository:admin)
- [x] - The button to add a new file could live in the breadcrumbs, just like to add a file or collection.
- [x] - The user will need to be prompted to determine the permissions for the new file, since it may not share the permissions of the core file or the other sibling files.
- [x] - The uploaded file type must match the core file's canonical type.
- [x] - Once the file has been uploaded the uploader will be presented with the MD5 generated at ingestion for comparison.

Additional information from Joey: "We would like to add functionality to file uploads in the DRS such that a file can be linked within an existing files/record, connecting the new file to the same core file as the existing file in the DRS that is being linked to. These files are intended to be versions of one another (the new file to be considered a child file, generally serving as a preservation master that does not need to be available for download). This functionality need only be added to those with unlimited upload capabilities within the DRS. Upon completion of the upload, the generated md5 value should be made visible such that it can be compared against the md5 that was generated pre-ingest."

**Comment by elizoller** [comment]
Will preservation masters and access copies have different content types? (Like right now we have ImageMasterFile - It would be simple to add VideoMasterFile and AudioMasterFile and then automatically have any new files be assigned the "master" class but I don't know if this fits what you're describing with preservation masters vs access copies ) 

If the core file's canonical type/class is ZipFile then what will we accept for additional files? Or are we limiting this to Image, Audio, and Video?

**Comment by dgcliff** [comment]
It should just be for Audio and Video for now, I think. And my vote is for the new models (video master, and audio master)

**Comment by elizoller** [comment]
Ok, that simplifies this

**Comment by sarahjeansweeney** [comment]
👍  what David said

**Comment by elizoller** [comment]
should the depositor be the one depositing the added file or the core_record depositor?

**Comment by sarahjeansweeney** [comment]
The depositor.

**Comment by elizoller** [comment]
This is up on staging

**Comment by sarahjeansweeney** [comment]
Thanks, Eli. Do any of the staging accounts belong to the northeastern:drs:repository:admin group? I don't see any options to add additional files here: http://cerberus.library.northeastern.edu/files/neu:nz8061778

**Comment by elizoller** [comment]
I added you and David and I to the drs:admin grouper group on staging

**Comment by sarahjeansweeney** [comment]
Thanks! I can see the add button now.
So far the process seems to work, though I get a system error when I try to download the videos: http://cerberus.library.northeastern.edu/files/neu:nz8061778

I'm not sure if that's related to the feature or staging is just having a difficult time with video files.

**Comment by elizoller** [comment]
I think this might be a staging issue (I'm not seeing the issue locally and I'm seeing it on the other video that is staging). I'll take a look

**Comment by sarahjeansweeney** [comment]
Great, thanks.

Can some of the text be updated?

Change: "Your file is being added. Please check back soon."
To: Your file is being processed.

Change: "The type of file uploaded doesn't match the type of the existing file, which is a video"
To: You must upload an audio file. [for audio]
To: You must upload a video file. [for video]

**Comment by dgcliff** [comment]
I think the staging issue is related to it's large file upload process, and where the tmp storage has been configured (or not). Will take a look.

**Comment by elizoller** [comment]
On the "Your file is being processed" flash - do you want the md5 there also?
Also do you want the ability to provide an md5 on upload?

**Comment by dgcliff** [comment]
That would allow us to compare hashes, and notify them that they don't match, rather than relying on them to self compare/police

**Comment by sarahjeansweeney** [comment]
Submitting a hash to be compared is a good idea. It shouldn't be required, though.

**Comment by elizoller** [comment]
do you have helper text in mind for around the checksum field?
what do you want the field to be called?

**Comment by elizoller** [comment]
what do you want it to say if the checksum provided doesn't match the checksum we generate?

**Comment by dgcliff** [comment]
![Image of csn](http://i.imgur.com/XkU4Ajf.png)

**Comment by sarahjeansweeney** [comment]
We're only validating MD5 hashes, right? If so:
Field name: MD5 Hash Value
Helper text: Enter MD5 for hash validation
If the MD5 doesn't validate: The submitted MD5 hash value does not match the MD5 generated during ingest.

**Comment by sarahjeansweeney** [comment]
I was able to add multiple master files to the core file I tested on staging, but we should only allow one master file per core file (I confirmed with Joey that this fits his expectations).

**Comment by elizoller** [comment]
Thanks. Will fix up language, md5 field, and single master object in the morning and then merge it in.

**Comment by elizoller** [comment]
For ensuring single master object, I can do a front end check that will show/hide the upload button and a back end check in case someone tries to manually form the url. Does that sound ok?

**Comment by elizoller** [comment]
Also when do you want md5 doesn't validate message to show up - on the provide metadata screen or after the upload with the "Your file is being processed" message?

**Comment by sarahjeansweeney** [comment]
Front and back end checks sound good.

The provide metadata screen for this feature is where the uploader selects who can view the master, right? If so, then let's put it on that page. That will give them the option to back out of the process if the numbers don't match.

**Comment by elizoller** [comment]
Ok thanks

**Comment by elizoller** [comment]
<img width="1271" alt="screen shot 2016-05-13 at 9 24 11 am" src="https://cloud.githubusercontent.com/assets/5439169/15249220/7bb4969c-18ec-11e6-8647-c3c1bb194775.png">

**Comment by elizoller** [comment]
<img width="1239" alt="screen shot 2016-05-13 at 9 25 28 am" src="https://cloud.githubusercontent.com/assets/5439169/15249260/a6ce2302-18ec-11e6-9b9d-ca5cccef5b70.png">

**Comment by sarahjeansweeney** [comment]
These look good to me.
