### ISSUE TITLE
Daily report count for Uploaded files

### ISSUE THREAD

**Issue by sarahjeansweeney** [NEU-Libraries/cerberus#951]
I think the Daily Report count for uploads is counting Loader files twice. There appeared to be 1507 uploads in the Daily Report page for Monday, 768 of which were uploaded through the interface:

<img width="1225" alt="2016-05-10_0850" src="https://cloud.githubusercontent.com/assets/4663073/15182630/913bb6ea-175b-11e6-867a-91b87b807510.png">

It seems more likely that 739 files were uploaded using the Marcom loader and 29 files were uploaded through the interface, especially since there were only 700ish new files reported in the "Daily Non-Featured Content and Collection Uploads and Updates" email.

**Comment by elizoller** [comment]
Yes, you're correct. I'll push up a patch.
