### ISSUE TITLE
Associate files through the interface

### ISSUE THREAD

**Issue by sarahjeansweeney** [NEU-Libraries/cerberus#953]
Associated files are currently connected through the Fedora Admin interface by updated the RELS-EXT. As we start to take on more and more projects with related materials, we need to give users the ability to connect related files on their own.

- This feature would live in the "Manage File" area as a separate "Associate" tab.
- Users should be able to connect a file to any other file they have access to edit.
- Allow users to search for the file to be associated by text or by PID
- They should also be able to remove an association

In the future we may want to allow users to select the type of association (i.e. instructional material), but for now the default can be drs:isSupplementalMaterialFor

**Comment by elizoller** [comment]
As I was working on this I realized it might be helpful to show the relationship type in the already associated files area. What do you think?
<img width="1253" alt="screen shot 2016-08-30 at 9 26 34 am" src="https://cloud.githubusercontent.com/assets/5439169/18090706/039d2dc4-6e94-11e6-924d-36bc40afe9d9.png">

**Comment by sarahjeansweeney** [comment]
That is great! 👍

**Comment by dgcliff** [comment]
if we're going one direction, can we drop the for?

**Comment by elizoller** [comment]
Closed with https://github.com/NEU-Libraries/cerberus/pull/1038
