### ISSUE TITLE
Custom error page for SOS and Blackboard traffic

### ISSUE THREAD

**Issue by sarahjeansweeney** [NEU-Libraries/cerberus#955]
When students try to access restricted content from either Scholar OneSearch or Blackboard they encounter the generic DRS restricted access page:

<img width="1224" alt="2016-05-12_1435" src="https://cloud.githubusercontent.com/assets/4663073/15230187/6fda2b8c-1862-11e6-98d3-7f3b9b3b2eb0.png">

Since we know a lot of students are going to hit this page when clicking on links for restricted videos from SOS and Blackboard, can we create a customized error page with this language?:

This item is restricted to members of the Northeastern community - please sign in to continue.

"sign in" should be linked to the Shib login page

Base URL for SOS: http://alma.exlibrisgroup.com/view/action/uresolver.do?operation=resolveService&package_service_id=5269314510001401&institutionId=1401&customerId=1390
Base URL for Blackboard: https://blackboard.neu.edu

**Comment by dgcliff** [comment]
Yeah, I think we get enough environmental information that we can discern when this happens and present a different information page.

We could just take them straight to the shib page? Or without context do you think they wouldn't know why they were seeing that, and bail.

**Comment by sarahjeansweeney** [comment]
Straight to Shib is even better, as long as it takes them straight to the resource once they log in.

**Comment by dgcliff** [comment]
Yep, that's how it'll work

**Comment by dgcliff** [comment]
Bonus: If they've recently logged into Shib (i.e. shib hasn't timed out), it'll take them straight to the file.

**Comment by sarahjeansweeney** [comment]
Works beautifully - thanks!
