### ISSUE TITLE
Add button for attaching new files to an existing core file

### ISSUE THREAD

**Issue by sarahjeansweeney** [NEU-Libraries/cerberus#957]
The "+Add" button in the breadcrumbs used to add a master file to an existing core file appears clickable, but clicking on "+Add" doesn't do anything.

![2016-05-16_1348](https://cloud.githubusercontent.com/assets/4663073/15298377/ef7a8fb4-1b6c-11e6-9997-ee50fad594a4.png)

**Comment by elizoller** [comment]
Cached javascript - hard refresh should do the trick.
