### ISSUE TITLE
New zip loader: D’Amore-McKim

### ISSUE THREAD

**Issue by sarahjeansweeney** [NEU-Libraries/cerberus#958]
The D'Amore-Mckim Marcom group would like a photo loader for their media. This is not a high priority, but they would like their loader soon (next week, if possible).

Here are the basic details you'll need to create their loader:

**Community PID**: https://repository.library.northeastern.edu/communities/neu:rx913r53s

**Derivative sizes**:
No derivatives.

**Standard statement for mods/accessCondition**:

<mods:accessCondition type="use and reproduction">D’Amore-McKim School of Business Marketing & Communications images are for use only within the context of the marketing and promotion of the D’Amore-McKim School of Business at Northeastern University. Use and reproduction of these images is restricted to D’Amore-McKim School of Business Marketing and Communications employees only. All other uses require written permission from the D’Amore-McKim School of Business Marketing and Communications department. Appropriate uses include placement in D’Amore-McKim-related websites and insertion into D’Amore-McKim print and presentation materials. D’Amore-McKim faculty and staff are generally granted permission to reuse images for D’Amore-McKim-related marketing and communications efforts; however, the D’Amore-McKim Marketing and Communications team reserves the right to restrict use for brand consistency and to avoid overuse. Images must be credited: "Photographer Name/Northeastern University." If faculty, students, or other persons are easily identifiable in the photo, exercise discretion when using their likeness. Requesting permission from the individual(s) photographed is strongly encouraged. Images may be used for self-promotional purposes outside of Northeastern University such as on LinkedIn or Facebook, but usage must be in good faith and approved with written permission from D’Amore-McKim School of Business. For more information, please contact the D’Amore-McKim Marketing and Communications team at dmsbnews@neu.edu.</mods:accessCondition>

**Access rights**:

This one may need discussion. They would like to upload files with varying permissions. The good news is they want permissions to be sorted by collection. For example, in this collection they want "2016 Photos" to be available to the public with edit access for the DM group, but they want "Private and Sensitive Photography" to be restricted to just the DM group: https://repository.library.northeastern.edu/collections/neu:rx913r57w

This seems reasonable to me, though I'm not sure how to accommodate this at the loader stage. Would it make more sense for mixed collections like these to add an additional step to the upload phase to ask what permissions should be applied to the files being uploaded?

**Comment by sarahjeansweeney** [comment]
Grouper group for the loader: ```northeastern:drs:repository:loaders:damore_mckim```

**Comment by sarahjeansweeney** [comment]
This mostly worked as expected. I noticed that the collection creator/depositor's NUID was added to the group list, and it's being inserted in the rights record as a group:

![2016-06-06_1205](https://cloud.githubusercontent.com/assets/4663073/15828929/5c9e6afc-2bdf-11e6-8e03-5ee7f52b3eea.png)

```
<rightsMetadata xmlns="http://hydra-collab.stanford.edu/schemas/rightsMetadata/v1" version="0.1">
<copyright>
<human type="title"/>
<human type="description"/>
<machine type="uri"/>
</copyright>
<access type="discover">
<human/>
<machine/>
</access>
<access type="read">
<human/>
<machine/>
</access>
<access type="edit">
<human/>
<machine>
<person>000000000</person>
<group>northeastern:drs:damore_mckim:marcom</group>
<group>northeastern:drs:repository:staff</group>
<group>000574273</group>
</machine>
</access>
<embargo>
<human/>
<machine/>
</embargo>
</rightsMetadata>
```

The depositor value is being recorded correctly in the properties datastream.

**Comment by elizoller** [comment]
I'll put in a patch for this shortly.

**Comment by dgcliff** [comment]
Are there items we need to retroactively fix as result?

**Comment by sarahjeansweeney** [comment]
No, I only tested two files, which I'll delete soon.
