### ISSUE TITLE
Title validation for MODS History feature/XML editor

### ISSUE THREAD

**Issue by sarahjeansweeney** [NEU-Libraries/cerberus#961]
I think the validation is working as expected for the MODS History feature, but I noticed that when I revert to the original system-created record, the record validates even though it doesn't have a title:

![2016-06-06_1106](https://cloud.githubusercontent.com/assets/4663073/15826819/0821e7f4-2bd7-11e6-80c5-5110a3e9071c.png)

Technically it has a titleInfo element, which is why I imagine it's validating, but the element has no value, so the record could still be saved even though it doesn't have a title. See example: https://repository.library.northeastern.edu/files/neu:m0407n340

**Comment by dgcliff** [comment]
Yeah, I need to put in stricter title and keyword validation. Patch incoming.
