### ISSUE TITLE
One failed file in spreadsheet load

### ISSUE THREAD

**Issue by sarahjeansweeney** [NEU-Libraries/cerberus#962]
I just tried to upload a few more files using the spreadsheet loader (https://repository.library.northeastern.edu/loaders/mods_spreadsheet/report/743). It was mostly successful, but one file failed completely with this error:

```
No such file or directory - /tmp/DRStmp/1465240569-9871929-df/Academic_Affairs_19730427.pdf
/home/drs/cerberus/releases/20160606032334/app/jobs/content_creation_job.rb:75:in `size'
/home/drs/cerberus/releases/20160606032334/app/jobs/content_creation_job.rb:75:in `run'
/home/drs/cerberus/releases/20160606032334/lib/cerberus/resque/queue.rb:24:in `perform'
```

**Comment by sarahjeansweeney** [comment]
Tried again with fewer files (https://repository.library.northeastern.edu/loaders/mods_spreadsheet/report/744), got a different error:

```
undefined local variable or method `request' for #<ContentCreationJob:0x00000006bf1e08>
/home/drs/cerberus/releases/20160606032334/app/jobs/content_creation_job.rb:30:in `run'
/home/drs/cerberus/releases/20160606032334/lib/cerberus/resque/queue.rb:24:in `perform'
```

**Comment by elizoller** [comment]
Yeah I think thats actually a manifestation of the same issue

**Comment by elizoller** [comment]
should be fixed with https://github.com/NEU-Libraries/cerberus/commit/ce7f2a31223ad0dfc6b67cbd90a44d6943699f30
