### ISSUE TITLE
Another Shib login error

### ISSUE THREAD

**Issue by sarahjeansweeney** [NEU-Libraries/cerberus#964]
Abbie encountered the same error I experienced this morning: "I tried to login to the DRS today to do some metadata entry and I can't seem to get in. I keep getting told there's a Shibboleth error. I thought it was a cookie issue or something but I still can't get it to work in an incognito window."

![screenshot 2016-06-07 at 10 20 54 am](https://cloud.githubusercontent.com/assets/4663073/15861479/785af01a-2c9a-11e6-8092-8d4b4247b623.png)

**Comment by dgcliff** [comment]
Same error as you and I saw - Abbie does have two different nuids, but not sure if that's cause or just coincidence. I can manually fix her account. We do see emails when this occurs, so it's not widespread

**Comment by dgcliff** [comment]
If she logs in again, it should resolve itself now.

**Comment by sarahjeansweeney** [comment]
Yup, it worked. Thanks!
