### ISSUE TITLE
Corefile as Collection

### ISSUE THREAD

**Issue by sarahjeansweeney** [NEU-Libraries/cerberus#966]
While uploading presentations and accidentally triggering errors, I noticed that our Toolkit presentation that I uploaded last October is a "collection" for some reason

![2016-06-07_1139](https://cloud.githubusercontent.com/assets/4663073/15864346/c1b0d28e-2ca4-11e6-8f59-35778de86c8b.png)

The type value is coming from the Dublin Core, so I imagine our MODS to DC mapping is turning
```<mods:typeOfResource>software, multimedia</mods:typeOfResource>``` into ```<dc:type>Collection</dc:type>```?

**Comment by dgcliff** [comment]
Yep.

It means collection in terms of generic grouping (in this case, a zip file I believe)

Obviously can be confused for Collection in the other sense

relevant code

```
def assign_obj_type
          if self.canonical_class.constantize == VideoFile
            self.dc_type = "Moving Image"
            self.mods_type = "moving image"
          elsif self.canonical_class.constantize == ImageMasterFile
            self.dc_type = "Image"
            self.mods_type = "still image"
          elsif [TextFile, PdfFile, MswordFile].include? self.canonical_class.constantize
            self.dc_type = "Text"
            self.mods_type = "text"
          elsif self.canonical_class.constantize == AudioFile
            self.dc_type = "Audio"
            self.mods_type = "sound recording"
          elsif self.canonical_class.constantize == MsexcelFile
            self.dc_type = "Dataset"
            self.mods_type = "software, multimedia"
          elsif self.canonical_class.constantize == MspowerpointFile
            self.dc_type = "Interactive Resource"
            self.mods_type = "software, multimedia"
          elsif self.canonical_class.constantize == ZipFile
            self.dc_type = "Collection"
            self.mods_type = "software, multimedia"
          end
```

**Comment by sarahjeansweeney** [comment]
Since both terms are used correctly, I guess I'll have to live with it. We have very few real zip files, so it shouldn't cause too much confusion.
