### ISSUE TITLE
Set list scrolling on mobile

### ISSUE THREAD

**Issue by sarahjeansweeney** [NEU-Libraries/cerberus#969]
When I try to add a core file to a Set on my mobile device, I can't scroll down to get to the bottom of my Sets list. My list happens to be very long, so it extends farther than the screen. Attempting to scroll down scrolls the full page underneath the popup menu, but not the menu itself.
I was using Chrome, and I was able to replicate it using the Chrome inspect tool.

**Comment by sarahjeansweeney** [comment]
Forgot to add screenshots:

Here's the Set list:

![screenshot_2016-06-08-18-22-19](https://cloud.githubusercontent.com/assets/4663073/15978225/c5e9a10e-2f2a-11e6-8a09-bed6786ff158.png)

And here's the Create a new Set menu, which is also too long on mobile:

![screenshot_2016-06-08-18-22-48](https://cloud.githubusercontent.com/assets/4663073/15978228/c910ff44-2f2a-11e6-9321-d72663726a75.png)

**Comment by elizoller** [comment]
Ah ok. I'll check it out on Monday.
