### ISSUE TITLE
New employee issues: duplicates and missing notifications

### ISSUE THREAD

**Issue by sarahjeansweeney** [NEU-Libraries/cerberus#970]
I'm woefully behind on connecting new employees to communities and I only just started catching up now. I put together a list of all the new employees from the notifications I've been receiving and there are a lot of duplicates. For example, I've received 17 notifications about Alexandra Wallace Berleus. I've received 9 notifications for Lauren Dibble, 5 of which all came in on April 25. Not sure if this is a notification quirk or if an indication of somethings else. Let me know if you want me to forward any of the notifications.

**Comment by sarahjeansweeney** [comment]
I should also add that I haven't received any new employee notifications since June 9. The Daily Report statistics page indicates that were six new users yesterday.

**Comment by dgcliff** [comment]
I'm pretty sure this was a result of the northeastern/neu issue, and that duplicates aren't relevant. New users aren't necessarily new employees. Will look into it.

**Comment by dgcliff** [comment]
I think this can be closed? Feel free to re-open if it wasn't fully resolved.
