### ISSUE TITLE
Improve User Experience for Buffering Videos

### ISSUE THREAD

**Issue by elizoller** [NEU-Libraries/cerberus#973]
Currently when a video buffers for more than five seconds, a generic error message appears and the video player is removed.
Proposed solution:
When a video buffers for more than X seconds, an alternate error message appears above the video but the video player is not disturbed.

Preferences for how long we allow it buffer?
Language preferences for the alternate error message?

**Comment by sarahjeansweeney** [comment]
**How long**: I just found this [paper](https://www.akamai.com/kr/ko/multimedia/documents/technical-publication/video-stream-quality-impacts-viewer-behavior-inferring-causality-using-quasi-experimental-designs-technical-publication.pdf) from Akamai, which makes me think that 5 seconds is a good number.

> We show that viewers start to abandon a video if it takes more than 2 seconds to start up, with each incremental delay of 1 second resulting in a 5.8% increase in the abandonment rate.

**Language**: "This video is taking longer than expected to play. You may need to download the file to view it."

**Comment by elizoller** [comment]
Went to go fix the messages on this and I realized I already rolled it in.
https://github.com/NEU-Libraries/cerberus/commit/a74ab03adec09fcd197b5e55c8df48da7486fd74
