### ISSUE TITLE
Spreadsheet loader: Subject value URIs

### ISSUE THREAD

**Issue by sarahjeansweeney** [NEU-Libraries/cerberus#974]
RADS and Archives would like support for subject value URIs to be added to the spreadsheet loader. The value URI would live at the subject level, not the topic level:

```
<mods:subject authority="lcsh" authorityURI="http://id.loc.gov/authorities/subjects"
valueURI="http://id.loc.gov/authorities/subjects/sh2010109730">
```

**Comment by elizoller** [comment]
will this be in the `Topical Subject Heading X` field with a value like `African American students -- Massachusetts -- Boston | Value URI`

**Comment by sarahjeansweeney** [comment]
yes, exactly
