### ISSUE TITLE
Error trying to add a new collection as the admin user

### ISSUE THREAD

**Issue by sarahjeansweeney** [NEU-Libraries/cerberus#976]
I want to create subcollection for masters theses and dissertations in this ETD smart collection: https://repository.library.northeastern.edu/collections/neu:rx914r11f

I don't want to be the depositor for these collections, so I impersonated the admin user. I received the "Sorry, you don't have permission to access this page." error when I clicked tried to add a collection from the breadcrumbs. I don't receive this error when I'm logged in as myself.

![2016-06-21_1138](https://cloud.githubusercontent.com/assets/4663073/16235986/b22ee07a-37a4-11e6-9600-b0c3cc628704.png)

**Comment by dgcliff** [comment]
Hm, ok - I might be able to manually fix the permissions

**Comment by dgcliff** [comment]
Looks like neu:rx914r11f's depositor is 000000000, but not it's edit rights. Should be fixed now.
