### ISSUE TITLE
Spreadsheet Loader: Master file and access copies

### ISSUE THREAD

**Issue by sarahjeansweeney** [NEU-Libraries/cerberus#978]
Archives reminded me that they have more nuanced restrictions on their image files than other groups: the access/derivative files are public, but the master image is restricted to just Archives staff.

There are two pieces to this:
- Uploading or generating access copies as part of the bulk upload process
- Setting access rights for those copies that deviates from the collection rights

I think we talked about future workflows that accommodate determining rights at upload, but we didn't discuss it as part of the current spreadsheet workflow, which is an oversight on my part. This probably needs discussion, so we can talk about it next week's Cerberus meeting.

**Comment by dgcliff** [comment]
I think this can be closed as part of the sentinel branch
