### ISSUE TITLE
Spreadsheet Loader: changes to subjects, alternative title, access condition, corporate names

### ISSUE THREAD

**Issue by sarahjeansweeney** [NEU-Libraries/cerberus#979]
Here are the requested changes from Archives and RADS: 

**Alternate Title**
Accommodate multiple entries, update column header to include numbers:
- Alternate Title 1 Initial Article
- Alternate Title 1
- Alternate Title 1 Subtitle

 
**Access Condition : Restriction on access**
Accommodate multiple entries, update column header to include numbers:

- Access Condition : Restriction on access 1
- Access Condition : Restriction on access 2

**Corporate creator and subject names**
Needs to be updated to accommodate multiple namePart values
Field value will be formatted using ```--``` to separate different namePart entries. ```|``` will be used to separate nameParts from the value URI.
 
Sample spreadsheet entry: ```United States -- Court of Appeals (2nd Circuit) | valueURI```
Sample MODS:
```
<mods:name type="corporate" valueURI="valueURI" authority="authority" authorityURI="authorityURI">
     <mods:namePart>United States</mods:namePart>
     <mods:namePart>Court of Appeals (2nd Circuit)</mods:namePart>
</mods:name>
```
 
**_Subjects_** 
_(all subjects are repeatable and will require support for multiple entries)_
 
**Geographic**
Spreadsheet Column Headings:

- Geographic Subject Heading 1 (entered as: ```Term -- Term | valueURI```)
- Geographic Subject Heading Authority 1 (entered as: ```authority | authority URI```)
 

Sample MODS:
```
<mods:subject valueURI="valueURI" authority="authority" authorityURI="authorityURI">
     <mods:geographic>Massachusetts</mods:geographic>
     <mods:geographic>Springfield</mods:geographic>
</mods:subject>
```
 
**Temporal**
Works similarly to originInfo dates.

Spreadsheet column headings:
- Temporal Subject Heading 1 (entered as: ```1987```)
- Temporal Subject Heading End Date 1 (entered as: ```1990```)
- Temporal Subject Heading Qualifier 1 (entered as: ```approximate```)
 

Sample MODS:
```
    <mods:subject>
        <mods:temporal point="start" encoding="w3cdtf" qualifier="approximate">1987</mods:temporal>
        <mods:temporal point="end" encoding="w3cdtf" qualifier="approximate">1990</mods:temporal>
    </mods:subject>
```
 
**Title Info**
Spreadsheet column heading:

- Title Subject Initial Article 1
- Title Subject 1
- Title Subject Subtitle 1
- Title Subject Alternate Title Initial Article 1
- Title Subject Alternate Title 1
- Title Subject Alternate Title Subtitle 1

 
Sample MODS:
```
    <mods:subject>
        <mods:titleInfo>
            <mods:nonSort>The</mods:nonSort>
            <mods:title>title</mods:title>
            <mods:subTitle>subtitle</mods:subTitle>
        </mods:titleInfo>
    </mods:subject>
    <mods:subject>
        <mods:titleInfo type="alternative">
            <mods:nonSort>The</mods:nonSort>
            <mods:title>alternative</mods:title>
            <mods:subTitle>subtitle</mods:subTitle>
        </mods:titleInfo>
    </mods:subject>

```

**Geographic Code**
Spreadsheet column headings:

- Geographic Code Subject Heading 1 (entered as: ```code | valueURI```)
- Geographic Code Subject Heading Authority 1 (entered as: ```authority | authority URI```)

Sample MODS:

```

    <mods:subject authority="authority" authorityURI="authorityURI" valueURI="valueURI">
        <mods:geographicCode>code</mods:geographicCode>
    </mods:subject>

```

**Genre**
Spreadsheet column headings:

- Genre Subject 1 (entered as: ```genre | value URI```)
- Genre Subject Authority 1 (entered as: ```authority | authority URI```)
 

Sample MODS:

```
    <mods:subject  authority="authority" authorityURI="authorityURI" valueURI="valueURI">
        <mods:genre>Fiction</mods:genre>
    </mods:subject>
```
 

**Cartographic**
_n.b.: The order of the cartographic subfields must be maintained in order for the record to validate_

Spreadsheet column headings:

- Cartographics Subject Scale 1
- Cartographics Subject Projection 1
- Cartographics Subject Coordinates 1 (entered as: ```coordinates | valueURI```)
- Cartographics Subject Authority 1 (entered as: ```authority | authority URI```)

Sample MODS:

```
    <mods:subject authority="authority" authorityURI="authorityURI" valueURI="valueURI">
        <mods:cartographics>
            <mods:scale>1:22,000,000</mods:scale>
            <mods:projection>Conic proj</mods:projection>
            <mods:coordinates>E 72°--E 148°/N 13°--N 18°</mods:coordinates>
        </mods:cartographics>
    </mods:subject>
```

**Comment by sarahjeansweeney** [comment]
Correction: I mixed up two types of access conditions. "Use and Reproduction" should be repeatable, not "Restriction on Access" (though it's not a problem of "Restriction on Access" is also repeatable).

**Access Condition : Use and Reproduction**
Accommodate multiple entries, update column header to include numbers:

- Access Condition : Use and Reproduction 1
- Access Condition : Use and Reproduction 2

**Comment by sarahjeansweeney** [comment]
After some testing, almost all these changes look good. Here are a few things that may need adjustments (I'll send the spreadsheet I used over Slack):

**Alternate title**
The alternate title field seems to be ignored (though not the subject alternate title - that seems to be handled correctly). I tried formatting the column headings with and without the "1", but no luck generating the alternate title field in MODS.

**Access condition**
Similar to alternate title, the access condition: restriction on access column isn't being turned into MODS. I also tried variations on the column header, but no luck.

**Cartographic Subject Coordinates**
It seems the cartographic coordinates field needs support for authorities, which I was not aware of. It can follow the same pattern as the other authority and value URIs

- Cartographics Subject Coordinates 1: N 42° 20' 0'', W 71° 2' 58'' | http://www.geonames.org/maps/google_42.333_-71.049.html
- Cartographics Subject Authority 1: http://www.geonames.org

   ```
 <mods:subject>
        <mods:cartographics authority="http://www.geonames.org/" valueURI="http://www.geonames.org/maps/google_42.333_-71.049.html">
            <mods:scale>1:22,000,000</mods:scale>
            <mods:projection>Conic proj</mods:projection>
            <mods:coordinates>N 42° 20' 0'', W 71° 2' 58''</mods:coordinates>
        </mods:cartographics>
    </mods:subject>
```

**Comment by dgcliff** [comment]
If I'm reading things correctly (including the other tickets), if I can sort out the above three things, then this will be ready to merged into master?

**Comment by sarahjeansweeney** [comment]
yes, once alternate title, access condition, and the coordinates fields are done, it should be ready to go.

**Comment by dgcliff** [comment]
Ok, cool. I'll put it up on staging when it's ready to be tested, and if it gets the go-ahead, I'll merge, then rebase the XML loader branch so it's up to date, then put it up on staging for testing
