### ISSUE TITLE
Spreadsheet loader: changes to notes

### ISSUE THREAD

**Issue by sarahjeansweeney** [NEU-Libraries/cerberus#982]
Instead of specifying the note in the column header, RADS and Archives (RArchives?) would like to be able to define their own note type for each note added to the spreadsheet. This can be done by replacing the current note field columns (Provenance note and Other notes 1) with two new columns. Empty or missing Notes Attribute columns is valid, the note would just not have an attribute.

Example:

- Note 1: Gift of Susan Smith, 2007.
- Note 1 Attribute: acquisition

```<mods:note type="acquisition">Gift of Susan Smith, 2007.</mods:note>```

**Comment by elizoller** [comment]
haha RArchives

**Comment by sarahjeansweeney** [comment]
This looks good.
