### ISSUE TITLE
A/V out of sync

### ISSUE THREAD

**Issue by sarahjeansweeney** [NEU-Libraries/cerberus#983]
I have a small set of videos that meet the requirements for Wowza streaming (MP4, H.264, ACC), but the audio and video are out of sync when uploaded to the DRS and streamed:

https://repository.library.northeastern.edu/collections/neu:cj82n904t

Joey and I have tweaked the videos in a few different ways (changed to ACC passthru, basic transform using ffmpeg, change the frame rater from 30 to 29.97), but the audio and video stay out of sync when uploaded.

Are there clues in our Wowza or JWPlayer configurations that might help us investigate this issue?

**Comment by dgcliff** [comment]
I'm getting a different issue looking at https://repository.library.northeastern.edu/files/neu:cj82n908x

```There was an error playing this file. Please try on a different device, verify Flash is enabled, or download the file.```

combined with 

```[.PPAPIContext]GL ERROR :GL_INVALID_ENUM : glTexImage2D: target was GL_TEXTURE_RECTANGLE_ARB``` in the Javascript console.

Will look into it.

**Comment by dgcliff** [comment]
Ok, fixed my own problem (related to my specific Chrome settings it seems). Trying to reproduce the sync issue.

**Comment by sarahjeansweeney** [comment]
Let me know if you need more sample videos!

**Comment by dgcliff** [comment]
Hm, not sure how much we can do about this. General search queries for this kind of issue with Wowza tends to turn up posts suggesting to look at the encoding (which I know you and Joey have done)

There is this - https://www.wowza.com/forums/content.php?356-How-to-debug-AAC-or-MP3-timecode-issues-with-Apple-HLS-packetization - which we can try sometime, but all it might do is highlight what we can see/hear, without giving cause

**Comment by dgcliff** [comment]
I'm seeing artifacts and delays offline, as well?

**Comment by sarahjeansweeney** [comment]
The videos aren't high quality to begin with, but none of the original videos i was given seem to be out of sync

**Comment by dgcliff** [comment]
Hard to tell with the quality. I'll try and get some logging occurring, either with with master file offline or with Wowza

**Comment by sarahjeansweeney** [comment]
I'm pretty sure I've fixed the videos.
