### ISSUE TITLE
Spreadsheet Loader Error Handling

### ISSUE THREAD

**Issue by sarahjeansweeney** [NEU-Libraries/cerberus#985]
I encountered a few errors while doing some purposefully dumb things with the spreadsheet loader:

**Generic Error:**

![empty sheet](https://cloud.githubusercontent.com/assets/4663073/16779297/a150bc0a-483f-11e6-9a42-4ce2c01513b8.png)

Received when loading:
- A zip with files and an empty spreadsheet
- A zip with only files, no spreadsheet

**Pop up error:**
<img width="1225" alt="no filename" src="https://cloud.githubusercontent.com/assets/4663073/16779316/b1e1de00-483f-11e6-8c5e-f4ae264c8833.png">

Received when loading a zipped spreadsheet without a filename column

**No error, just a spinning page:**

![unzipped](https://cloud.githubusercontent.com/assets/4663073/16779331/c4098c9a-483f-11e6-9fee-901bb4eecb8b.png)

Received when loading an unzipped spreadsheet. I don't see this message until I return to the My Loaders page:

![2016-07-12_1450](https://cloud.githubusercontent.com/assets/4663073/16779435/39627466-4840-11e6-85fb-7b83ffa75fc3.png)

I suspect these could all be handled similarly? Perhaps with a generic pop up message:
Your file could not be processed. Please make sure the zip file contains the correct files and metadata.

Since it'll be just me loading for the next month or so, there's no rush to implement these. I know how to figure out what I did wrong.

**Comment by dgcliff** [comment]
Yeah - all of these I think are handled, but just poorly - they don't redirect when they should. But should be easy to fix.

**Comment by sarahjeansweeney** [comment]
Looks good to me. I have a few text changes, which I'll add to #993 with the other error messages.

**Comment by dgcliff** [comment]
Fixed with 77479a544b43a8763ac0c451ef7e9d7ed33e7c25
