### ISSUE TITLE
Spreadsheet Loader Error on Staging

### ISSUE THREAD

**Issue by sarahjeansweeney** [NEU-Libraries/cerberus#987]
I tested the spreadsheet loader after the XML loader was added to staging. After a lot of false starts, I finally submitted a correctly formatted spreadsheet, which made it through the preview stage. The [loader report](http://cerberus.library.northeastern.edu/loaders/spreadsheet/report/160) revealed that the metadata was not updated due to this error:

`File Status: Error - Unable to find "" in fedora.`

I had successfully uploaded a set of new files with spreadsheet metadata (http://cerberus.library.northeastern.edu/loaders/spreadsheet/report/150), so the loader certainly still functional.

**Comment by dgcliff** [comment]
This particular error should be fixed
