### ISSUE TITLE
Spreadsheet loader time out error

### ISSUE THREAD

**Issue by sarahjeansweeney** [NEU-Libraries/cerberus#988]
I used the spreadsheet loader to load a video this morning. It made it further than the other video loads, but it ultimately failed: https://repository.library.northeastern.edu/loaders/spreadsheet/report/871

The error for this particular load is "Error - Connection timed out - connect(2)". The file itself is no more than 200MB, so file size shouldn't be a factor.

**Comment by dgcliff** [comment]
Fixed with ee12b505c5c4cf7f11760d053c933daca18f0c9a
