### ISSUE TITLE
Error when retrieving MODS export

### ISSUE THREAD

**Issue by sarahjeansweeney** [NEU-Libraries/cerberus#989]
The MODS export that I started yesterday afternoon didn't finish until after 6pm. I clicked the link in the email around 7:50am and received a DRS system error. 

I can't remember how long the window is supposed to be, so I suppose it's possible the export had expired, and if it did, I think there should be a more specific error message.

**Comment by sarahjeansweeney** [comment]
Just in case a screenshot would help:
![2016-07-20_0804](https://cloud.githubusercontent.com/assets/4663073/16985767/b4481f12-4e50-11e6-8fd1-ad4243e33708.png)

**Comment by dgcliff** [comment]
Just the 6 hour window - will change to longer today
