### ISSUE TITLE
"Sign in" message in Firefox is yellow

### ISSUE THREAD

**Issue by sarahjeansweeney** [NEU-Libraries/cerberus#991]
This is extremely minor, but for some reason the "Sign in with your myNEU username..." banner message is yellow in Firefox instead of blue, like it is in Chrome and Safari:

<img width="1225" alt="2016-07-20_1619" src="https://cloud.githubusercontent.com/assets/4663073/17001654/e5a0df82-4e95-11e6-87d9-68402e211b2e.png">

**Comment by dgcliff** [comment]
Try hard refresh - some css changed for the blue

**Comment by sarahjeansweeney** [comment]
That worked - thanks!
