### ISSUE TITLE
Spreadsheet 2x2 changes

### ISSUE THREAD

**Issue by sarahjeansweeney** [NEU-Libraries/cerberus#993]
This looks really good to me. I only have a few suggestions for small text and cosmetic changes:

**Text**

- Change the prompt from"What type of files are you uploading?" to "What are you uploading?"
- Change "New files" button to "New files + metadata"
- Change "Existing Files" button to "Metadata only"

**Buttons**
When the user clicks on one of the upload options, the button color or shading should change to indicate that it has been selected, similar to the Recent Deposit / Creator List button behavior.

**Spacing and Alignment**
I could be swayed about this, but I think there should be more space between the prompt, the buttons, and the file selection options. I also think the buttons should be centered rather than left justified, and a little closer together.

**Comment by sarahjeansweeney** [comment]
Here's the error text I promised:

- "Your file could not be processed. Please make sure the zip file contains the correct files and metadata. The error received was: Wrong type - trying to add new files with an existing files load"
 - Please change to: Your upload could not be processed because the submitted .zip file contains new files. Please update the .zip file or select the "New Files + Metadata" option.

- "Your file could not be processed. Please make sure the zip file contains the correct files and metadata. The error received was: Wrong type - trying to edit existing files with a new files load"
 - Please change to: Your upload could not be processed because the submitted .zip file does not contain any files. Please update the .zip file or select the "Metadata Only" upload option.

- "Your file could not be processed. Please make sure the zip file contains the correct files and metadata. The error received was: No file name or PID provided"
 - Please change to: Your upload could not be processed because the spreadsheet is missing file names or PIDs. Please update the spreadsheet and try again.

**Comment by sarahjeansweeney** [comment]
Two more:

- "Your file could not be processed. Please make sure the zip file contains the correct files and metadata. The error received was: No spreadsheet files found in zip file"
 - Please change to: Your upload could not be processed because the submitted .zip file does not contain a spreadsheet.
- "Your file could not be processed. Please make sure the zip file contains the correct files and metadata. The error received was: Empty spreadsheet"
 - Please change to: Your upload could not be processed because the submitted .zip file contains an empty spreadsheet.

**Comment by dgcliff** [comment]
Fixed with 1f063fa7f80c58c13c04b7816635d397fa8b54ee
