### ISSUE TITLE
Sets download zip missing files

### ISSUE THREAD

**Issue by sarahjeansweeney** [NEU-Libraries/cerberus#996]
While helping a user with the difference between Sets and the Download Queue, I notice that her Set had 27 core files in it, but the download of the Set had only 19 files. Her Set is private, but I was able to replicate this with two of my Sets (the other 13 seem fine).

This Set contains 7 files: https://repository.library.northeastern.edu/sets/neu:rx915b87g
These two files weren't included in the zip file generated when I clicked the Set "Download" button:
https://repository.library.northeastern.edu/files/neu:329725
https://repository.library.northeastern.edu/files/neu:332794

This Set contains 23 files: https://repository.library.northeastern.edu/sets/neu:rx913r08z
This file wasn't included in the zip: https://repository.library.northeastern.edu/files/neu:341342

(I've shared these with DRS staff, so let me know if you can't see them for some reason.

**Comment by dgcliff** [comment]
Will look into it

**Comment by dgcliff** [comment]
For the sake of history and memory - this was caused by items not having Canonical Object set, usually this was a result of poorly migrated items.
