### ISSUE TITLE
Update Upload Alerts to handle Spreadsheet and XML Loaders

### ISSUE THREAD

**Issue by elizoller** [NEU-Libraries/cerberus#997]
- [x] add a 'type' field to the upload alert model that will record the type of load (ie. interface, loader name)
- [x] rename image_report to item_report since not all things uploaded using the loaders are images
- [x] modify upload alert so it does not send an email for spreadsheet or xml loaders (but still records it as an active record object)
- [x] update daily report and aggregated statistics job so that interface uploads and loader uploads are being calculated correctly (all items get upload alerts, only loader items will have image reports so total uploaded items = upload alerts, interface uploads = upload alerts - image reports, loader uploads = image reports)

**Comment by elizoller** [comment]
Do you want adding content objects to an existing core file to generate a value in the daily uploads email?
Do you want loaders to be part of the non-featured daily uploads email? Or not included at all? Or their own category?

**Comment by elizoller** [comment]
For spreadsheet and xml loaders that are updating metadata, we would want these to count as edits rather than uploads, right?
If that is the case, should edits be expanded to tab edits, xml edits, and loader edits?

**Comment by dgcliff** [comment]
I think in essence, yes. But, I would add one caveat. Currently, I'm pretty sure we assume that pressing submit on the Edit form or the XML edit form, and edit actually took place (a reasonable assumption).

With the loaders, I think it'd be prudent to actually measure if an edit took place or not. Take for example, your recent fix of the creator thing. Now, by far, the easiest thing to do was just re-run the whole spreadsheet...but only a few of the files were actually affected, right?

We could measure each core file after saving with the XML History distance metric (i.e. if > 0, an actual edit took place)

That way, we don't just have egregious inflated numbers, but an actual edit count. Thoughts?

**Comment by elizoller** [comment]
In the case of fixing the creator list, I actually created a new spreadsheet by filter down the original spreadsheets so that I wouldn't be wasting server energy rerunning thousands of records. But I definitely see your point. I'll see if I can copy over that distance metric and give it a shot.

**Comment by dgcliff** [comment]
Ah, I just assume people are as lazy as I am hahaha. Sounds good 👍

**Comment by sarahjeansweeney** [comment]
I've been needlessly angsting over this one, but the solution to that angst is in #864. For now:

- Yes, adding content objects to an existing core file should be included in "updates" section of the daily uploads email.
- Loaders should be included in the featured/nonfeatured notifications: metadata only would be included in "updates", metadata + files in "new". These don't need to display as itemized lists, just as summaries (similar to the completed load notification), otherwise these notifications could have thousands of files.

**Comment by elizoller** [comment]
Sounds good.
How about for the daily report in the admin panel - should edits be expanded to tab edits, xml edits, and loader edits? Or would you want loader edits to become part of one of the other categories?

**Comment by sarahjeansweeney** [comment]
Even though they're technically uploading something, they're not really adding anything new, just changing the core file, so adding loader edits to the 'core file edits' area of the daily report sounds good to me.

**Comment by dgcliff** [comment]
I'll be really interested to see how much uptake it has. I get the feeling it'll be used a fair bit, at least initially, especially paired with the new export functionality.

**Comment by elizoller** [comment]
Sounds right. 
Its like this now:
<img width="542" alt="screen shot 2016-08-12 at 11 51 28 am" src="https://cloud.githubusercontent.com/assets/5439169/17628401/26873222-6083-11e6-80cd-0060a9b04fc3.png">
Do you want a third row 'loader edits' (or some wording) or lump it in with one of the other?

**Comment by dgcliff** [comment]
Ah, yeah, splitting out xml vs spreadsheet will be good.

**Comment by elizoller** [comment]
👍

**Comment by sarahjeansweeney** [comment]
Cool - can we use this text then, so the edit sources are clear? I think you can remove "Edits", too:

Edit Tab
XML Tab
Spreadsheet Loader
XML Loader

**Comment by elizoller** [comment]
Yup

**Comment by elizoller** [comment]
Fixed with https://github.com/NEU-Libraries/cerberus/commit/19f88941e98810814c0dcbe1f4dd26357270c97d
