### ISSUE TITLE
Collection thumbnails don't display after saving

### ISSUE THREAD

**Issue by sarahjeansweeney** [NEU-Libraries/cerberus#998]
This was reported to me earlier today during this morning's interruption:  

> When I am adding thumbnail pictures, the system isn't attaching them the 1st, or 2nd, or even sometimes even the 3rd time I try to upload them to the collections page. And unfortunately this time, when it didn't catch, it made three collections instead of attaching the jpeg.

I was able to replicate all of this. When you upload a thumbnail, either to a new or existing collection, the thumbnail doesn't display right away after you save. It shows up if you reload the page, but not when the page loads after saving. I was able to make multiple collections by going back after the new collection was made, adding the thumbnail again, and saving. 

For existing collections, the thumbnail did show up after a few tries (I don't know why I tried with different images with each try, but I did):

- First try with one image, didn't show up after saving
- Second try with another image, the first image showed, not the second image
- Reloaded the page, second image showed

If possible, the thumbnail should display right away.
Another thing that might be throwing off her and other users is that the saved thumbnail doesn't show on the Manage Collection page after it's been uploaded. Can this be updated so that the selected image displays, either as the image or the file name? And a "Remove thumbnail" option would be good, too. (If these should be separate tickets, please let me know).

**Comment by dgcliff** [comment]
@sarahjeansweeney could you explicate this section a bit?

```I was able to replicate all of this. When you upload a thumbnail, either to a new or existing collection, the thumbnail doesn't display right away after you save. It shows up if you reload the page, but not when the page loads after saving. I was able to make multiple collections by going back after the new collection was made, adding the thumbnail again, and saving.```

I'm not entirely sure what you mean by going back

**Comment by sarahjeansweeney** [comment]
By going back I mean I:

- clicked Submit after creating a new collection
- saw the thumbnail didn't display even though I received "Collection Test Files (Public) was updated successfully." message
- used the back button to go back to the submission page to try adding the thumbnail again

**Comment by dgcliff** [comment]
Ok. Yeah, the back button is just as bad for Collection creation as it is Core File creation. It's not a duplicate collection being made, the user has essentially explicitly asked the system to make another one, even if they're unaware of it.

We'll have to introduce the #stay mechanism to prevent that occurring - to help alleviate the desire to do this, we can generate the thumbnail inline, which will make things slower, but won't give the user the concept that it's not being worked on.

**Comment by dgcliff** [comment]
Remove thumbnail should be a different ticket - pushing a patch to prevent back button, and inline thumbnail creation
